### ISSUE TITLE
docs: make `callback.apiResponse` argument a link to the upstream docs

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1007]
_continuing from https://github.com/GoogleCloudPlatform/gcloud-node/issues/990#issuecomment-162869090_

Anywhere we document an `apiResponse` argument, we should be able to link it to the API docs that show what the user can expect from that object.

Tip: for most of the API docs I've seen, you can append a fragment `#response` to the URL to deep link to the relevant section.

**Comment by callmehiphop** [comment]
Perhaps this would be better placed in gcloud-common?

**Comment by stephenplusplus** [comment]
Possibly, but the task will be actually writing link tags in the JSDocs. Unless you can think of an automated way to do this with metadata from the big JSON doc?

**Comment by callmehiphop** [comment]
Good point, it should probably just be in both.

**Comment by stephenplusplus** [comment]
We are probably not going to make any changes to our GitHub hosted docs, as our repos start to migrate out onto cloud.google.com.
