### ISSUE TITLE
[Docs] External links should open in a new tab

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/google-cloud-node#1094]
Most of the links in the documentation are going to the API docs on [cloud.google.com](https://cloud.google.com) or in general out of the gcloud-node docs website. Its always a better choice to open all such external links in a new tab.

Even the icon next to such link indicates to open in new tab.
![screen shot 2016-01-28 at 11 40 41 am](https://cloud.githubusercontent.com/assets/1330677/12656617/1942561a-c5b4-11e5-8847-307144a8d307.png)

Material Design Ref:
![screen shot 2016-01-28 at 11 40 28 am](https://cloud.githubusercontent.com/assets/1330677/12656614/1796533e-c5b4-11e5-9756-d089f41f611e.png)

**Comment by stephenplusplus** [comment]
I think the steps to complete this are:

- [ ] Overload `<a>` from `gcloud-common`. It should look for links that begin with `http` and assign a `target="_blank"`.
- [ ] Search for links in this repo that are external, and manually add `target="_blank"`

@callmehiphop does that sound correct? Do we still need to do no. 2 if no. 1 is implemented?

**Comment by callmehiphop** [comment]
I don't think so, but it should be mentioned that overloading <a> is slightly more complicated than it sounds. I tried this and ran into some issues where anchors dropped into the page via `bind-html` wouldn't get overloaded. My guess had something to do with the compiling phase ending and not traversing HTML appended in that fashion

**Comment by stephenplusplus** [comment]
Makes sense. Do we get any events when compiling is done that we can hook onto and re-compile? And if a loop is unavoidable there, maybe we can use that same event to just run some raw JS that assigns the target onto links with a shared class, e.g. `ext`.

**Comment by callmehiphop** [comment]
I don't believe there is an event for that.

Not a very graceful solution, but maybe we should just make a service and pass it to resource links, descriptions and markdown files.

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by eoogbe** [comment]
I am no longer on the team
