### ISSUE TITLE
"Available methods" section lists the constructor method

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1175]
I notice our method listings show the constructor method. How can we leave that out?

Example:

http://stephenplusplus.github.io/gcloud-node/#/docs/master/compute
<img width="767" alt="screen shot 2016-03-21 at 12 43 24 pm" src="https://cloud.githubusercontent.com/assets/723048/13926398/85c2a0b0-ef62-11e5-8b83-2103c8a5b6f6.png">

**Comment by callmehiphop** [comment]
I think we're going to need to add an option to the `manifest.json` that tells the docs app to ignore constructors. Both PHP and Ruby are going to want the constructor to display in the methods list.

**Comment by stephenplusplus** [comment]
How about we just leave this in.
