### ISSUE TITLE
Test docs for dead links

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1203]
On http://googlecloudplatform.github.io/gcloud-node/#/docs/v0.30.1/datastore/query

Looks like we moved these up a level (to the datastore instance) rather than defining datasets on their own. 

Can we do two things:
1. ~~Fix the dead links?~~
2. Make sure that dead links are caught in the build?

**Comment by richardkazuomiller** [comment]
This is in reference to the fact that we used to do it like this right?

````
var gcloud = require('gcloud');

var dataset = gcloud.datastore.dataset({
  projectId: <my project id>
  keyFilename: <my key filename>
});
```

This broke all of my things ｡･ﾟ･(ﾉД`)･ﾟ･｡

**Comment by stephenplusplus** [comment]
Catching dead links would be awesome. I'll fix the Datastore links and switch the focus of this issue to creating a step in our build task that catches these for us.

@richardkazuomiller - it was indeed a breaking change: https://github.com/GoogleCloudPlatform/gcloud-node/releases/tag/v0.30.0, but this issue is just about fixing the links in our docs that point to the old `dataset` object.

**Comment by richardkazuomiller** [comment]
Ah, I didn't see that. OK, looks like I have some refactoring to do lol

**Comment by stephenplusplus** [comment]
Sorry about that :disappointed: Feel free to tag us if we can help!

**Comment by jgeewax** [comment]
Sorry @richardkazuomiller :( Definitely feel the pain. We're still in the 0.x phase, so things are much more volatile than they otherwise would be.

**Comment by richardkazuomiller** [comment]
@jgeewax No worries. I'll remember to check the releases page from now on (^^ゞ

**Comment by stephenplusplus** [comment]
@richardkazuomiller make sure your package.json has gcloud saved as a safe range. For example, if you have gcloud saved as "^0.29.0", only 0.29.y releases will be pulled down automatically, which won't contain any breaking changes. You'll have to manually install new 0.x releases, and the release notes will call out the breaking changes so you can be prepared.

**Comment by richardkazuomiller** [comment]
@stephenplusplus Thanks for the tip. I always set the exact version number I use without a `^` or `~` and don't change it until I know it won't break in production, so go ahead and break all you like (^_-)-☆

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by eoogbe** [comment]
I am no longer on the team
