### ISSUE TITLE
Allow specifying access_token to use

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-node#1346]
There are situations where you can end up with just the access_token.  (eg. non-refereshable token for an endusers via oauth webflow).

There doesn't seem to be any way to place that raw token and initialize gcloud node. (gcloud-java recently added it in:
https://github.com/GoogleCloudPlatform/gcloud-java/issues/1029 

here are some references for the older googleapis node client:
https://github.com/google/google-api-nodejs-client#making-authenticated-requests

and a citation about overriding the config
https://github.com/GoogleCloudPlatform/gcloud-node/issues/678#issuecomment-131238194

**Comment by mbleigh** [comment]
+1 to the issue. I've issued a pull request against `google-auto-auth` that would allow for:

```js
var gcloud = require('gcloud')({
  credentials: {accessToken: 'ACCESS_TOKEN_HERE'}
});
```

**Comment by stephenplusplus** [comment]
Thank you for the PR over there, @mbleigh! What do you think about just not using `google-auto-auth` if a user provides a token?

**Comment by stephenplusplus** [comment]
*continuing from https://github.com/GoogleCloudPlatform/gcloud-node/pull/1410#issuecomment-230762662*

There are a couple edge cases:

  1. Calls made with gRPC APIs won't use the token (Datastore, Logging, Pub/Sub for now)
  1. There are other libraries we use-- [gce-images](http://gitnpm.com/gce-images) & [gcs-resumable-upload](https://github.com/stephenplusplus/gcs-resumable-upload)-- that would need to be updated to accept just an access token (and we would have to provide the access token the user give us to those libraries)

@murgatroid99 is there a way to provide gRPC with just an access token?

**Comment by murgatroid99** [comment]
The simplest way to use a plain access token would be to add it to the call's metadata, the same way you would add it to headers for an HTTP request. If you don't want to deal with adding it to every call, you can also create a `CallCredentials` object, similarly to how you would create one for GoogleAuth credentials:

```js
var creds = grpc.credentials.createFromMetadataGenerator(function(args, callback) {
  var metadata = new Metadata();
  metadata.add('authorization', 'Bearer: '+ access_token);
  return metadata;
});
```

Then you can pass it to a call in the options field, or compose it with SSL credentials using `grpc.credentials.combineChannelCredentials` and then using the resulting object to create a channel.

**Comment by stephenplusplus** [comment]
Awesome, thanks!

**Comment by sedouard** [comment]
Hey there. We're planning on adding GCE support to our cloud management platform. Through we're planning on getting an auth token from our users with permission scopes into GCP. Today can we pass access_token directly to this client?

**Comment by jmuk** [comment]
@stephenplusplus -- is there anything to do more?

**Comment by diiiego83** [comment]
any update? i really need to set my access token  but i can't find a solution.

**Comment by kwent** [comment]
+1 for this feature

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-common/issues/11.
