### ISSUE TITLE
logging: Public API for setting timestamp, severity, etc. on Entry

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/google-cloud-node#1348]
I can't find a public API for setting the [metadata fields](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/logging/entry.js#L124-L133) like timestamp and severity on a log entry.

It works to do `var entry = log.entry(...); entry.severity = "INFO";`, which is similar to what's done internally in [`Log.assignSeverityToEntries_`](https://github.com/GoogleCloudPlatform/gcloud-node/blob/master/lib/logging/log.js#L113), but I think there should be an options object argument in the Entry constructor.

**Comment by stephenplusplus** [comment]
An Entry already takes two objects, the first for the resource details, the second for the data.

We can change the `resource` argument to `metadata`:

```js
// before
var entry = log.entry({
  type: 'gce_instance',
  labels: {
    zone: 'global',
    instance_id: '3'
  }
}, {
  delegate: 'my_username'
});

entry.httpRequest = {...};

// after
var entry = log.entry({
  httpRequest: {...},
  resource: {
    type: 'gce_instance',
    labels: {
      zone: 'global',
      instance_id: '3'
    }
  }
}, {
  delegate: 'my_username'
});
```

Which do you prefer?

// @callmehiphop for thoughts

**Comment by callmehiphop** [comment]
Could we just add an optional `metadata` field to the resource itself?

```js
var entry = log.entry({
  type: 'gce_instance',
  labels: {
    zone: 'global',
    instance_id: '3'
  },
  metadata: {
    httpRequest: {},
    timestamp: Date.now()
  }
}, {
  delegate: 'my_username'
});
```

Or is that too weird?

**Comment by zbjornson** [comment]
Of the two, I think I like @stephenplusplus's proposal. The "resource" is already a bit confusing in nature, so it's nice to keep it explicitly separated. @stephenplusplus's is a breaking change though unless it's decided to keep supporting `(resource, payload)` in addition to the new `({resource, metadata}, payload)`.

**Comment by zbjornson** [comment]
I was also thinking `(resource, options, payload)`, like

```js
entry(
  {type: type, labels: {}},
  {severity: severity},
  {message: "server up"}
)
```

**Comment by stephenplusplus** [comment]
The only downside of the three arguments is that both `resource`* and `options`  are optional, so if we only receive 2 arguments, we couldn't safely detect which kind it is. Breaking change is unfortunate, but not a deal breaker.

\*`resource` is optional because it can be specified at the time of the call to `entry.write` to apply to all of the entries given.

**Comment by zbjornson** [comment]
Good point! Then my vote stays with `({resource, metadata}, payload)`. :)
