### ISSUE TITLE
Unable to get entity by key id (int64) from Datastore

### ISSUE THREAD

**Issue by gromtech** [GoogleCloudPlatform/google-cloud-node#1412]
For example, datastore already contains an entity with id = 100000000000001234 (18 digits). The integers in JavaScript (numbers without a period or exponent notation) are considered accurate up to 15 digits. 100000000000001234 will be 100000000000001000. Maybe the [Long type](https://www.npmjs.com/package/long) support (in the cloud.datastore.key method) is a way how to resolve this issue.

**Comment by stephenplusplus** [comment]
@pcostell does Datastore generate 18 digit IDs?

**Comment by gromtech** [comment]
Datastore allows us to save entities with 18 digit IDs (generated in our Java app). But it is impossible to get those entities in another services (written on NodeJS). Is there a some way to do this? I did not found it...

**Comment by stephenplusplus** [comment]
Ah, okay. Thanks for the info. I sent a PR to fix this in #1413.

If you'd like to test it out:

```sh
$ npm install --save stephenplusplus/gcloud-node#spp--1412
```
```js
var id = gcloud.datastore.int('100000000000001234');
var key = datastore.key(['Kind', id]);

// everything from this point should work normally.
```

**Comment by gromtech** [comment]
It works. Thank you.

**Comment by bjwatson** [comment]
Sounds related to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1681
