### ISSUE TITLE
API key auth with Bigtable doesn't work

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1424]
RE: https://github.com/GoogleCloudPlatform/gcloud-node/pull/1420#issuecomment-231924256

It looks like auth can be done by Default Application Credentials, service account credentials, or an API key. We support the first two currently, but I'm not sure @callmehiphop knows where to use an API key when making a Bigtable API request through gRPC. Any ideas, @lesv @sduskis?

**Comment by stephenplusplus** [comment]
I'm guessing this isn't a big priority. Feel free to re-open if this is something we need to support.

**Comment by anotheri** [comment]
It looks like API key auth doesn't work for `@google-cloud/language` as well.
could you fix it please?
