### ISSUE TITLE
Decoupling packages

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1467]
RE: https://github.com/GoogleCloudPlatform/gcloud-node/pull/1440/files#r73738579

There are a number of instances within our code where we (sort of) couple packages together. For example, in the NL package we offer optional support for annotating GCS objects. I think it would be great if we could remove the actual storage module dependency while still supporting this feature.

Possible solutions could include:

* Using [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies)
* Check for inheritance of `ServiceObject`
* Check the constructor name

**Comment by stephenplusplus** [comment]
This will fix issues like #1516.
