### ISSUE TITLE
Upgrade to Compute Engine Beta API

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1478]
It looks like a new GCE API is coming to town: https://cloud.google.com/compute/docs/reference/beta/

@jgeewax should we move our support from `v1` to `beta`?

**Comment by stephenplusplus** [comment]
// @omaray

**Comment by jgeewax** [comment]
It should be on the list of stuff for us to do, yep. I'll let @omaray decide the priority, but my vote is "not very important" right now due to the impending ability to auto-generate (and the fact that this surface is enormous....)

**Comment by stephenplusplus** [comment]
Sounds good. We had a feature request come up that is solved in the beta (https://github.com/GoogleCloudPlatform/gcloud-node/issues/1470)... is it okay to gradually introduce support for the beta API, or best to do it all at once?

**Comment by jgeewax** [comment]
That's tricky. I'd recommend avoiding a mix-and-match approach as it makes
things complicated (what if someone wants to enable the old API but isn't
OK with enabling features in another -- I don't want our answer to be "it
works but you have to enable the Beta API!")

**Comment by omaray** [comment]
Yes, Compute is not high priority right now. I need to confirm a couple of items before we can auto-generate the whole surface - but that's the end goal. Stay tuned.

**Comment by stephenplusplus** [comment]
Added this to our API Implementation Tracker: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1338
