### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1486]
Now that we've modularized, we need to rename the repository. Currently the links in the docs still point to https://github.com/GoogleCloudPlatform/gcloud-node, so those will need to be updated as well.

**Comment by stephenplusplus** [comment]
We are now google-cloud-node. Hooray, everyone! Good work, team!

**Comment by omaray** [comment]
Good work indeed! Thanks everyone!!
