### ISSUE TITLE
Documenting Gapic/Proto (autogen files)

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1492]
Opening an issue to track discussion on how we should go about documenting GAX from within our library.

**Comment by callmehiphop** [comment]
My initial thoughts are that users who take advantage of GAX will be a bit more advanced. That being said, it might not be unreasonable to simply link them to the proto files being used? Then from within our library we can document the methods that expose said APIs `v2`, `v1beta1`, etc.

It also might benefit us to look into adding the feature discussed here - https://github.com/GoogleCloudPlatform/gcloud-common/issues/80

**Comment by stephenplusplus** [comment]
cc: @jmuk @jmdobry

Is it a requirement for us to display autogen docs, or is linking to proto files sufficient?

**Comment by jmdobry** [comment]
For now at least, I think linking to proto files is sufficient.

**Comment by jmuk** [comment]
Cc: @omaray

We want the documentation for GAX (i.e. LanguageServiceApi). The generated files are more language-idiomatic and serve methods with additional features such as parameter-flattening / page-streaming, that are not seen in the proto files. We will also add auto-generated usage samples to individual method.

**Comment by omaray** [comment]
Correct. We want the documentation of GAPIC/GAX to show. Not every API will have a handwritten layer (or at least at the beginning). So we want to show the docs of the auto-gen too.

**Comment by stephenplusplus** [comment]
Just tagging as these are related: https://github.com/GoogleCloudPlatform/gcloud-common/issues/207

**Comment by stephenplusplus** [comment]
@swcloud @callmehiphop 

We're live with:

- Datastore: https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/master/v1
- Logging: https://googlecloudplatform.github.io/google-cloud-node/#/docs/logging/master/v2
- Pub/Sub: https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/master/v1
- Spanner: https://googlecloudplatform.github.io/google-cloud-node/#/docs/spanner/master/v1

**Comment by swcloud** [comment]
@stephenplusplus Looks amazing! We finally did it!! Really appreciate your great work!!!
