### ISSUE TITLE
OS testing

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1493]
One area that we need to improve upon before we go beta is automating tests on Windows and OSX.

It appears [Travis offers osx support](https://docs.travis-ci.com/user/multi-os/), but it is considered beta still.

- [x] Windows: Appveyor
- [x] OS X: Travis

**Comment by stephenplusplus** [comment]
Link dropping: https://www.appveyor.com/

**Comment by stephenplusplus** [comment]
@omaray @jgeewax We will need Appveyor enabled for our repo: https://ci.appveyor.com/project/googlecloudplatform/google-cloud-node -- then you'll need to give access to the "team" here: https://ci.appveyor.com/team

**Comment by dhermes** [comment]
Ditto on enabling https://ci.appveyor.com/project/googlecloudplatform/gcloud-python

**Comment by omaray** [comment]
No this is great!

@jonparrott and @elibixby would it be possible to give access to Node and Python.

Thanks!

**Comment by mziccard** [comment]
Can this also be enabled for `gcloud-java`?  https://ci.appveyor.com/project/googlecloudplatform/gcloud-java

**Comment by elibixby** [comment]
the @GoogleCloudPlatform/gcloud team has admin access on all these repos, and it doesn't look like AppVeyor requires Org level access. Are you unable to enable this yourself?

**Comment by dhermes** [comment]
@elibixby When I go to https://ci.appveyor.com/projects/new and click "Add" for the "google-cloud-python" project under the "GoogleCloudPlatform" it produces it under `/dhermes`, e.g.
https://ci.appveyor.com/project/dhermes/google-cloud-python-bqg0j

**Comment by elibixby** [comment]
It does the same for me. I don't see any way to produce a project under the org banner as those links request. Does anybody know if that's possible and if so how?

**Comment by dhermes** [comment]
http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations seems to have an answer (I am midway through reading)

**Comment by dhermes** [comment]
NVM this seems more up to date: https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization

**Comment by elibixby** [comment]
Alright, I have created GoogleCloudPlatform as an AppVeyor account. And made @GoogleCloudPlatform/gcloud an admin. Try logging in with github again after signing out and hopefully you'll see a drop down (if I understand everything correctly).

**Comment by dhermes** [comment]
Thanks @elibixby. I got the `google-cloud-python` settings copied over from my personal one and we are all set!

**Comment by stephenplusplus** [comment]
Got it set up for Node as well. Thanks @elibixby!

**Comment by stephenplusplus** [comment]
We're up and running. Thanks, everyone!

**Comment by quartzmo** [comment]
@blowmage and I have also added google-cloud-ruby. We imitated the configuration for google-cloud-node and it appears to be good, although jobs are all currently still queued, none has run.

**Comment by dwsupplee** [comment]
@elibixby would you also be able to set us up for google-cloud-php?

**Comment by elibixby** [comment]
@dwsupplee If you're a member of the @GoogleCloudPlatform/gcloud team you should be able to set it up yourself. I don't know anything about AppVeyor, maybe @dhermes or @stephenplusplus can help you out.

**Comment by dhermes** [comment]
@dwsupplee The previous comment (https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1493#issuecomment-245483120) from @elibixby was sufficient to get it set up for `google-cloud-python`. Ping me if you need a hand.

**Comment by dwsupplee** [comment]
Thank you @dhermes, unfortunately I'm not a member of the team so it doesn't look like I have access. Would you be able to add google-cloud-php for us?

**Comment by dhermes** [comment]
On it.

**Comment by dhermes** [comment]
Created: https://ci.appveyor.com/project/GoogleCloudPlatform/google-cloud-php/

Not sure what needs to happen to add you as a team member

**Comment by dwsupplee** [comment]
Thanks @dhermes!

**Comment by garrettjonesgoogle** [comment]
@elibixby , could the https://github.com/orgs/GoogleCloudPlatform/teams/gapic-team team be added as an admin on the AppVeyor account? In particular, the GAPIC team is exclusively responsible for google-cloud-java.
