### ISSUE TITLE
How to share App Engine SDK's local Datastore with google-cloud app?

### ISSUE THREAD

**Issue by MeLight** [GoogleCloudPlatform/google-cloud-node#1513]
Hi,
I'm building an app which should share the Datastore with an App Engine app. I want to test this locally, so I've read in the troubleshooting guide that I have to use `gcd.sh` and point it to a directory with a pre-created Datastore project. 

Is there a way to serve the App Engine SDK's Datastore from this folder? Or do I need to setup some sort of intricate process in order to copy the contents of the App Engine SDK Datastore to the one server from the special folder? 

I'm on Windows 10 for dev, and GCE Linux for deployment.

**Comment by stephenplusplus** [comment]
@pcostell

**Comment by pcostell** [comment]
Currently it's not possible to share local backends between the Cloud Datastore emulator and the App Engine specific emulator.

@stephenplusplus can you move this issue over to google-cloud-datastore?

**Comment by MeLight** [comment]
@pcostell so no way to develop it locally?

**Comment by stephenplusplus** [comment]
Uh oh, speaking of App Engine, looks like the GitHub issue mover is down :) https://github-issue-mover.appspot.com

Moved to https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/137

**Comment by stephenplusplus** [comment]
@MeLight you can indeed develop locally with the Datastore emulator and this library. We have a section in our docs about using the Datastore emulator as well: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.38.3/datastore

If you have more questions about how to use, try our tag on StackOverflow: http://stackoverflow.com/questions/tagged/gcloud-node

**Comment by ryanlinnane** [comment]
Is there any reason the backends can't be shared? I would guess that operating a full systems with all of its parts would be a more comfortable local experience if the datastore could be shared between devappserver and other programs.

**Comment by cgwy** [comment]
Heads up! If your GAE app uses python27 standard runtime, running locally, it can use the `cloud datastore emulator` now!

Documentation:
https://cloud.google.com/appengine/docs/standard/python/tools/using-local-server#browsing_the_local_datastore

Details on how to turn on this feature:
https://cloud.google.com/appengine/docs/standard/python/tools/migrate-cloud-datastore-emulator
