### ISSUE TITLE
Accessing google cloud storage - UNABLE_TO_GET_ISSUER_CERT_LOCALLY

### ISSUE THREAD

**Issue by abhiofdoon** [GoogleCloudPlatform/google-cloud-node#1517]
Hi,

I am behind a company firewall and I am trying to access Google cloud storage using the nodeJs Client API.
```js
var gcloud = require('gcloud');

var gcs = gcloud.storage({
  keyFilename: './key-file.json',
  projectId: 'awesome-project'
});

gcs.getBuckets(function(err, result) {
  if (err) {
      console.log(err);
    } else {
      console.log(result);
    }
});
```
I get the following error which I try to run this.
```sh
$ node gs.js
{ [Error: unable to get local issuer certificate] code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' }
```
Can i connect to google cloud storage using the API with SSL certificate validation disabled ?

Thanks,
Abhishek

**Comment by stephenplusplus** [comment]
I did a quick search and found a possible solution https://github.com/npm/npm/issues/9580#issuecomment-166605021

**Comment by abhiofdoon** [comment]
This seems to be at the nodeJs level.
Setting the environment variable
$ export NODE_TLS_REJECT_UNAUTHORIZED=0
enables making calls with ssl certificate checking disabled.

However is may be a very insecure way of doing things :)

**Comment by stephenplusplus** [comment]
Any ideas for how/if we should try to support this @jgeewax @omaray?

**Comment by stephenplusplus** [comment]
I don't believe there is a way to do this currently, as SSL and the HTTPS endpoint is important for security. I'm going to close, but anyone can correct me and we'll do what we can to make it work.
