### ISSUE TITLE
Dead references to gcloud-node

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/google-cloud-node#1519]
All of the links in README.md still point to gcloud-node instead of google-cloud-node.

Actually looks like there are quite a few dead refs (and note that github search only shows the top match or so from each file):
https://github.com/GoogleCloudPlatform/google-cloud-node/search?q=gcloud-node

**Comment by callmehiphop** [comment]
Thanks for reporting @zbjornson! This should be resolved per https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1520.
