### ISSUE TITLE
Is this official google API client library ?

### ISSUE THREAD

**Issue by abhiofdoon** [GoogleCloudPlatform/google-cloud-node#1522]
How is this client library different from https://github.com/google/google-api-nodejs-client/#google-apis-nodejs-client

In the long term should everyone be shifting to google-api-nodejs-client ?

Thanks,
Abhishek

**Comment by stephenplusplus** [comment]
We are the handcrafted, "idiomatic" alternative (see https://github.com/google/google-api-nodejs-client/#working-with-google-cloud-platform-apis, FAQ: https://googlecloudplatform.github.io/google-cloud-node). If you need an API that we don't support, that library is great solution.
