### ISSUE TITLE
Need a redirect from the old gh-pages site to the new one.

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/google-cloud-node#1523]
cloud.google.com has hundreds of links to variations of https://github.com/GoogleCloudPlatform/gcloud-node and https://googlecloudplatform.github.io/gcloud-node/

The old GitHub pages site (https://googlecloudplatform.github.io/gcloud-node/) does not redirect to the new https://googlecloudplatform.github.io/google-cloud-node/, therefore we have hundreds of broken links. 

Is it possible to publish something to the old gh-pages site that will redirect visitors to the new one?

**Comment by stephenplusplus** [comment]
The only thing I believe we can do is create a new repo called "gcloud-node" and create a "gh-pages" branch. But the downside to that is it would break the repository/issues/PR redirects.

@jgeewax @omaray for the official response.

Maybe we should start using custom domains that redirect to our docs, i.e. `cloud.google.com/google-cloud/node`

**Comment by omaray** [comment]
I'm noticing an update happened on this page: https://cloud.google.com/datastore/docs/client-libraries

where the Google Cloud Client Library for Node.js link has been updated already.

Is that your magic @jmdobry ?

**Comment by stephenplusplus** [comment]
Fixed with a JS redirect on the org's 404 page. @callmehiphop saves the day!
