### ISSUE TITLE
Binary data in BigTable column

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1526]
Hi, I am trying to store an encode protobuf in BigTable and I'm not able to insert binary data (represented as a Buffer) into a BigTable column. I have tried the following ways: 

```js
this.table.insert([
  key: `foo`,
  data: {
    event: new Buffer(),
  },
]);

this.table.insert([
  key: `foo`,
  data: {
    event: {
     data: new Buffer(),
    }
  },
]);
```

It seems to get stringified somewhere in the client library, which is making the data invalid.

**Comment by callmehiphop** [comment]
Hi @arbesfeld, we don't stringify any data before trying to insert data. However, we do transform any data you pass in into Buffers. Have you tried passing your data in as a string/number?

e.g.

```js
this.table.insert([
  {
    key: 'foo',
    data: {
      familyName: {
        columnName: 'data'
      }
    }
  }
]);
```

**Comment by callmehiphop** [comment]
@arbesfeld can you give me an example of what kind of data you're trying to save?

**Comment by callmehiphop** [comment]
@arbesfeld we've just merged some changes for the Bigtable API. Assuming what you're passing in is a Buffer, then it should pass through just fine to the API. When retrieving the data, if you want a Buffer returned to you, you'll need to set the `decode: false` option like so

```js
table.getRows({ decode: false }, function(err, rows) {});
```

**Comment by arbesfeld** [comment]
Hey @callmehiphop, I'm setting `decode: false` and getting seemingly all base64 encoded buffers when I call `.getRows()`. I passed in a binary-encoded Buffer. Is this the expected behavior?

**Comment by stephenplusplus** [comment]
@callmehiphop I think we should always create the Buffer from the response base64 value: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/3cbc93b9d770dd25aa5c6ed1f215e01518e42a03/packages/bigtable/src/row.js#L163

```js
    if (qualifier && chunk.value) {
      var value = Mutation.convertFromBytes(chunk.value, options);

      qualifier.push({
        value: value,
        labels: chunk.labels,
        timestamp: chunk.timestampMicros,
        size: chunk.valueSize
      });
    }
```

and do something like this in Mutation.convertFromBytes:

```js
  var buf = new Buffer(bytes, 'base64');
  var num = new Int64(buf).toNumber();

  if (!isNaN(num) && isFinite(num)) {
    return num;
  }

  if (options && options.decode === false) {
    return buf;
  }

  return buf.toString();
```
