### ISSUE TITLE
Requests made datastore v0.1.1 are shown as v1beta2 requests in API usage graph

### ISSUE THREAD

**Issue by richardkazuomiller** [GoogleCloudPlatform/google-cloud-node#1532]
I looked at my API usage in my GCP project and the graph showed that all of my requests to Datastore are made with the v1beta2 API, even though I've migrated some of my servers to v1beta3. Is this a problem with `@google-cloud/datastore`, a backend issue, or something I'm doing wrong?

**Comment by richardkazuomiller** [comment]
Sorry, accidentally submitted before actually writing anything. Must have accidentally hit some secret keyboard shortcut.

**Comment by richardkazuomiller** [comment]
These are my usage graphs:

<img width="1550" alt="screen shot 2016-08-26 at 3 49 40 pm" src="https://cloud.githubusercontent.com/assets/1243814/17996620/f36c6790-6ba4-11e6-97f3-92af94ba8ad5.png">

---

<img width="1562" alt="screen shot 2016-08-26 at 3 50 06 pm" src="https://cloud.githubusercontent.com/assets/1243814/17996621/f36e51fe-6ba4-11e6-91e1-d40ade4d83c4.png">

---

I think I'm using the new package right, but is there anything I need to do to make requests go to v1beta3 or v1? I need to do this before the old API is turned down

```
var gcloudDatastore = require('@google-cloud/datastore');

const datastore = gcloudDatastore({
  projectId: MY_PROJECT_ID,
  keyFilename: MY_KEY_FILE
});
```

**Comment by stephenplusplus** [comment]
Any usage of `gcloud` since [0.30.0, released 4/4/16](https://github.com/GoogleCloudPlatform/google-cloud-node/releases/tag/v0.30.0) and any version of `@google-cloud` or `@google-cloud/datastore` have been using v1beta3.

We will have a release soon for v1. The only thing you'll need to do is upgrade `@google-cloud/datastore`.

As for the usage graphs, I have to assume it's coming from some other Datastore usage, as long as you've been using the versions of our library stated above. If that doesn't explain it, we can ask @pcostell if he has any ideas.

**Comment by richardkazuomiller** [comment]
You're right – I have a service running on one server in my project that still uses the v1beta2 API, and it looks like all the v1beta2 logs are from that one server's IP.

I thought that v1beta3 traffic was being counted as v1beta2 traffic because I assumed that there would be some kind of log of API usage for every version. However, there are no logs or data on the usage graph for the other servers making requests to the v1beta3 API. I've entirely removed `gcloud` from most of my servers, so I am positive there is *some* v1beta3 usage. Do you know of any reason why this would happen?

**Comment by stephenplusplus** [comment]
I'm not sure, but @pcostell might have insight into that.

Going to close the issue since we're not talking about a bug in our library. Feel free to keep discussing.

**Comment by pcostell** [comment]
v1beta3 and v1 traffic unfortunately do not appear in the API console usage tracker: https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/133

**Comment by richardkazuomiller** [comment]
@pcostell Thank you. I'll subscribe to that issue.
