### ISSUE TITLE
BigQuery: missing useLegacySql option

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1540]
`useLegacySql`: https://cloud.google.com/bigquery/docs/reference/v2/jobs/query

**Comment by stephenplusplus** [comment]
@jmdobry I think we allow setting this option currently via passing through the user's provided `options` argument to `query` and `startQuery`. With these methods, it should look like:

```js
bigquery.query({
  query: 'SELECT ...',
  useLegacySql: false
}, ...

bigquery.startQuery({
  query: 'SELECT ...',
  useLegacySql: false
}, ...
```

Let me know if that's not working, or we're blocking the argument in another method.

**Comment by jmdobry** [comment]
I'll take a look

**Comment by jgeewax** [comment]
I don't think that's clear from the documentation... Can we update the table showing how options are passed transparently through to the API ?
