### ISSUE TITLE
Emit header for gRPC messages

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/google-cloud-node#1542]
gRPC connections currently don't have enough information in the request for us to do efficient traffic management/routing. 

Will you add a header that allows for us to optimize for this on the server? The header format is:

```
name: google-cloud-resource-prefix
value: projects/my-project-id
```

In general, the prefix would be the same as the JSON-over-http URL up to any custom method. For example, a Cloud Datastore commit message over JSON would hit the url `projects/my-project-id:commit`.

Here is an example usage in the cloud-bigtable-client: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/915/files#diff-1078787e69bc1d7c5bb8507f0a87a143R83

**Comment by dhermes** [comment]
@pcostell This should be true in Python as well?

```python
headers = [
    ('authorization', 'Bearer ' + access_token),
    ('user-agent', self._user_agent),
    ('google-cloud-resource-prefix', 'projects/my-project-id'),
]
```

[1]: https://github.com/GoogleCloudPlatform/gcloud-python/blob/6ce152cc097a113874a7713cceb99ce2eda13818/gcloud/_helpers.py#L572-L575

**Comment by pcostell** [comment]
Yes -- note that we don't need it for proto/JSON-over-HTTP, only for gRPC calls.
