### ISSUE TITLE
Upgrade to grpc@1

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1543]
Included are memory leak fixes: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1414#issuecomment-236866275

**Comment by richardkazuomiller** [comment]
Is this ready to be used with Datastore? I'd like to see if this fixes a memory issue I've been trying to solve.

**Comment by stephenplusplus** [comment]
We're in the process of releasing now. By the end of the day, it should be good to go.

**Comment by richardkazuomiller** [comment]
Yaaay thank you!

**Comment by stephenplusplus** [comment]
Sorry for the lag-- released just now: https://github.com/GoogleCloudPlatform/google-cloud-node/releases/tag/datastore-0.3.0. It will be part of the bundled package release shortly.
