### ISSUE TITLE
Broken URL doesn't redirect properly

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/google-cloud-node#1547]
Going to [this URL](https://googlecloudplatform.github.io/gcloud-node/#/docs/google-cloud/v0.37.0/bigquery) causes repeated polling for nonexistent files/a redirect loop instead of going to a legitimate 404 page.

**Comment by stephenplusplus** [comment]
That page loads okay for me. Could you be hitting a local cache?

**Comment by ace-n** [comment]
(Just updated the URL. Try again?)

**Comment by ace-n** [comment]
(Hmm...maybe this is a local issue or some cache race condition. I'll reopen this if I manage to repro it.)

**Comment by stephenplusplus** [comment]
It's true we don't have a 404 page. The link in the first post redirects to the latest docs because of a missing "v" in the version section of the URL. This is the correct link.

https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/v0.37.0/bigquery
