### ISSUE TITLE
Crypto operations do not work with Application Default Credentials

### ISSUE THREAD

**Issue by inlined** [GoogleCloudPlatform/google-cloud-node#1565]
#### Environment details

  - OS: Any (with application default credentials installed. E.g. GCE)
  - Node.js version: Any
  - npm version: Any
  - google-cloud-node version: Head

#### Steps to reproduce

  1. require `google-cloud`
  2. default initialize API
  3. Call getSignedUrl()

Expected: should work.
Actual: get error `Failed to obtain signed URL for file { SigningError: Could not get credentials without a JSON, pem, or p12 keyfile}"`

I took a bit of a dive into the code. `google-cloud-node` is using `google-auto-auth`, which is correctly returning the application default credential in this environment. Both `getSignedPolicy` and `getSignedUrl` call `getCredential` which only works if the developer provided a p12 or json service account file. Since Application Default Credentials are preferred where available, we should have a fallback to using `authClient.getToken()`. This can be used to call the [signBlob API](https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob), which lets you do crypto with just an access token.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#180
