### ISSUE TITLE
options.public to storage/File.createWriteStream doesn't make uploaded files public

### ISSUE THREAD

**Issue by aknuds1** [GoogleCloudPlatform/google-cloud-node#1566]
According to [API docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.1.1/storage/file?method=createWriteStream), `storage/File.createWriteStream` should take a boolean option `public` that makes the uploaded file publicly readable. However, in my experience this isn't the case.

I create the stream like this:

    let cloudFileStream = cloudFile.createWriteStream({
      public: true,
      resumable: false,
    })

And still, I have to call `cloudFile.makePublic` after the upload has finished, because otherwise the file is only accessible to the owner:

    cloudFileStream
      .on('finish', () => {
        cloudFile.makePublic()
      })

#### Environment details

  - OS: OS X El Capitan
  - Node.js version: 6.4.0
  - npm version: 3.10.6
  - google-cloud-node version: 0.39.0

**Comment by stephenplusplus** [comment]
Setting `public: true` will set the object's `predefinedAcl` to `publicRead`. Calling `file.makePublic()` will grant the `READER` role to `allUsers`. Do you have any existing rules that might be trumping the `predefinedAcl`?

To test, I created a new bucket and new file, so that no existing configuration could get in the way.

The bucket's permissions:
<img width="506" alt="screen shot 2016-09-06 at 9 05 39 am" src="https://cloud.githubusercontent.com/assets/723048/18274586/1a842fba-7411-11e6-816b-b3135804590c.png">

The bucket's default object permissions:
<img width="500" alt="screen shot 2016-09-06 at 9 05 58 am" src="https://cloud.githubusercontent.com/assets/723048/18274597/2a838a96-7411-11e6-9eb9-7994843c04a0.png">

The bucket's contents:
<img width="964" alt="screen shot 2016-09-06 at 9 06 25 am" src="https://cloud.githubusercontent.com/assets/723048/18274604/392c60ea-7411-11e6-9960-08c2fcc4c86a.png">

The file's permissions:
<img width="498" alt="screen shot 2016-09-06 at 9 06 46 am" src="https://cloud.githubusercontent.com/assets/723048/18274617/4501b9e2-7411-11e6-8c37-4ffc925114cd.png">

Where

**Comment by aknuds1** [comment]
So, the only issue here should be an existing rule trumping `predefinedAcl`? Am not aware of having any such rule, but I'll look.

**Comment by aknuds1** [comment]
@stephenplusplus How did you add the `allusers: Reader` bit? Does this correspond to `predefinedAcl: publicRead`?

**Comment by stephenplusplus** [comment]
Yes, that came from setting `predefinedAcl: publicRead`.

@jgeewax, am I giving out correct information?

**Comment by aknuds1** [comment]
@stephenplusplus OK, so that should mean that `predefinedAcl: publicRead` is equivalent to calling `file.makePublic()` does it not? I end up with the same in my file permissions, by calling `file.makePublic()`.

**Comment by Splaktar** [comment]
We saw this same issue lately as well. We used the CLI (since the UI didn't have this feature) to change the `predefinedAcl` on the whole bucket since we didn't want to call `file.makePublic()` on every file.

It would be ideal if the option worked as expected and make the file public.

**Comment by stephenplusplus** [comment]
I would like to resolve this the right way once and for all! I'm going to need some help from @jgeewax, @omaray, maybe @capstan. Simply put, what needs to be in an upload request body that makes the file being uploaded public? Thanks!

**Comment by aknuds1** [comment]
@stephenplusplus Come to think of it, how would you write a test for this issue? Apparently it's not solved, so seems as if you lack a test for this functionality.

**Comment by stephenplusplus** [comment]
We do: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/35573c31e834c841b99ae73f6cf5e647b76ae7cc/packages/storage/system-test/storage.js#L424 -- but if we're not doing it the right way, we'll need to rewrite the test.

**Comment by aknuds1** [comment]
@stephenplusplus I guess there's some sort of false positive there, looks that way at least.

**Comment by stephenplusplus** [comment]
Indeed, looking forward to fixing this :)

**Comment by Capstan** [comment]
@stephenplusplus When you upload an object, you can specify either a predefined ACL or a fully-enumerated ACL, and errors if you have both. If you don't want to bother writing client logic, you could just always turn `public: true` to the predefined ACL but then also use whatever client-provided ACL and let the service return the error that you cannot cross the streams. Seems like a bad idea to have the client specify one ACL that doesn't set it to public read and another in the same request that does. Or perhaps I'm misunderstanding and there's no additional user-provided ACL?

**Comment by stephenplusplus** [comment]
We're not really running into conflicting ACL specifications during the upload here. In the simplest case, a user might want to upload a file and make it public in one line, and it would look like this:

```js
bucket.upload('./localfile.txt', { public: true }, function(err) {})
```

That would send `POST https://.../o?name=localfile.txt&predefinedAcl=publicRead`.

Is this what our library should do, or is there more to it?

**Comment by Capstan** [comment]
I presume there's no body to the `POST` and it also contains an `uploadType` URL parameter that's either `media` or `resumable`? If so, then, that's exactly what it should do. Does the ACL you get back from such an object not list `allUsers: READER`?

**Comment by stephenplusplus** [comment]
The file does indeed get `allUsers: READER` permissions.

@aknuds1 @Splaktar can you show screenshots similar to the ones I've posted after uploading a new file? Everything seems to be working for me, as shown in my earlier post: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1566#issuecomment-244944739

**Comment by stephenplusplus** [comment]
It seems like we're doing this right as far as the API is concerned. If I'm missing something, we'll re-open and get back to work. Thanks!

**Comment by Splaktar** [comment]
Sorry, I ran out of bandwidth to debug this and then Hurricane Matthew hit. We were able to work around it for now. Thanks.
