### ISSUE TITLE
Should datastore base64 encode blob values?

### ISSUE THREAD

**Issue by dwsupplee** [GoogleCloudPlatform/google-cloud-node#1571]
According to [the datastore RPC docs](https://cloud.google.com/datastore/reference/rpc/google.datastore.v1#value) a blob value should be a set of bytes and does not need to be base64 encoded.

Just wanted to check in and see if there was a reason for this or if it is something that could be removed. We could see some decent improvements in the size of the values being stored if we no longer encode them.

**Comment by stephenplusplus** [comment]
Good call, thanks for the heads up :)
