### ISSUE TITLE
Updating single field of a model

### ISSUE THREAD

**Issue by MeLight** [GoogleCloudPlatform/google-cloud-node#1588]
I have model with multiple fields. The model in the Python App Engine app looks like this:
```
class Team(ndb.Model):
  field_a = ndb.StringProperty()
  field_b = ndb.StringProperty()
  field_c = ndb.IntegerProperty()
```

When running this code from the Node.js part of the app:
```js
var key = ds.key(['Team', team_id]);
    ds.update({
      key: key,
      data: [{name: "field_c", value: new_count, excludeFromIndexes: true}]
    }, function(err) {
      if (!err) {
        // Record saved successfully.
      }
    });

```

I get fields `field_a` and `field_b` **deleted** from the model. How can I update only one field of the object without deleting the other fields?

Thanks

**Comment by stephenplusplus** [comment]
You have to do a manual "get and update", which would look like:

```js
var key = ds.key(['Team', team_id]);

ds.get(key, function(err, entity) {
  if (err) {
    // Error handling omitted.
  }

  entity.data.field_c = newCount;

  ds.save({
    key: key,
    data: entity.data
  }, function(err) {
    if (!err) {
      // Record saved successfully.
    }
  });
});
```

**Comment by MeLight** [comment]
This doesn't work with ComputedProperty. Any ideas how to make that work too?

**Comment by MeLight** [comment]
In the same doc they have a scary red box claiming this:
![2016-09-24_1456](https://cloud.githubusercontent.com/assets/704484/18808318/45dc2e6a-8267-11e6-8390-1ccba0fa6aa0.png)


So I decided to stop using that feature altogether, and calculating that property manually when needed :/
