### ISSUE TITLE
projectID requirement not consistently documented

### ISSUE THREAD

**Issue by ptone** [GoogleCloudPlatform/google-cloud-node#1599]
on:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.40.0/google-cloud

Documents on compute engine setup as:

     var gcloud = require('google-cloud')();

But runtime errors, and the sample on the package home page make clear that the projectID has to be explicit (not sure why can't pick up from metadata server?)

https://googlecloudplatform.github.io/google-cloud-node/#/

**Comment by stephenplusplus** [comment]
We can't make an async request to the metadata server, but we do pick it up from the environment variable `GCLOUD_PROJECT`. We mention this in our [Authentication guide](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.40.0/guides/authentication), but it would be helpful to clear this up in our `config` parameter docs.

Sent a PR, please take a look: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1601
