### ISSUE TITLE
Source Code links broken in doc site

### ISSUE THREAD

**Issue by quartzmo** [GoogleCloudPlatform/google-cloud-node#1602]
#### Steps to reproduce

  1. Navigate to a docs page for a release using the new tag notation (`<package>-<version>`). For example:
      https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/0.3.0/datastore
  2. Click any "Source Code" link in the page. 
      ![image](https://cloud.githubusercontent.com/assets/6609430/18619329/68c02246-7dae-11e6-93e1-df29c077ff86.png)

      For example: 
      https://github.com/GoogleCloudPlatform/google-cloud-node/blob/0.3.0/packages/datastore/src/index.js#L305
      
      Result is 404. Correct URL should be:

      https://github.com/GoogleCloudPlatform/google-cloud-node/blob/datastore-0.3.0/packages/datastore/src/index.js#L305

This issue is the same as GoogleCloudPlatform/google-cloud-ruby#908, reported by @omaray. I am guessing that the fix will involve updating the GoogleCloudPlatform/gcloud-common site.

**Comment by callmehiphop** [comment]
Ahh! Good find.. I think we're going to need a way to generate the correct tag name. Does everyone follow the `{package}-{version}` format? 

Otherwise maybe we want to add the tag name to the <kbd>toc.json</kbd> file? Thoughts? @quartzmo @dwsupplee, @jdpedrie

**Comment by quartzmo** [comment]
We use a slash separator: `{package}/{version}` (I think the precedent we follow is git flow. Anyway, [it is allowed](http://schacon.github.io/git/git-check-ref-format.html).) Also, our package names are longer: `google-cloud-datastore`.

**Comment by callmehiphop** [comment]
Ok, well I think it might be easier/safer to just add the tag name to the <kbd>toc.json</kbd>? Otherwise we could just add some conditional logic in the app to try and guess it based on the language.

**Comment by quartzmo** [comment]
Tag name in `toc.json` sounds ok to me.

**Comment by jdpedrie** [comment]
We're not going to be able to split `google-cloud-php` into multiple packages for the foreseeable future, so allowing it to be configurable so we can opt out entirely makes the most sense to me.

**Comment by dwsupplee** [comment]
Configurable sounds best to me as well
