### ISSUE TITLE
[QUESTION] Did you guys use a Windows machine for encrypyting your AppVeyor keyfile or did you use a cloud service?

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/google-cloud-node#1603]

**Comment by stephenplusplus** [comment]
Used a Windows developer ISO to boot up a VirtualBox VM and run the commands. I think @callmehiphop can probably run some for you.

**Comment by dhermes** [comment]
Thanks.

>  I think @callmehiphop can probably run some for you.

Trying not to send the key over the wire.

> Used a Windows developer ISO to boot up a VirtualBox VM and run the commands.

Where does one obtain such an ISO?

**Comment by stephenplusplus** [comment]
I believe starting here will get you to it: https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced
