### ISSUE TITLE
Are there any plans on adding the abiltity to create LoadBalancers

### ISSUE THREAD

**Issue by jkurz** [GoogleCloudPlatform/google-cloud-node#1604]
Hello I would like to be able to programmatically create LoadBalancers in NodeJs.

Is there a plan on wrapping the networking API to allow for me to create the required pieces?

In a perfect world I want to make one call to create a LoadBalancer. This would allow for me to pass in the HealthCheck info, the backend service info, and get back the IP of the LoadBalancer. Preferably it would be nice if I could get the IP address back on the call, and then wait for the loadbalancer to get created asynchronously. This would allow for me to take the IP and create a DNS record with it, before the LoadBalancer has actually been created. Saving overall time of stack creation.

**Comment by stephenplusplus** [comment]
Thanks for the suggestion, this sounds like a great idea. As you probably know, the Compute Engine API is quite large. We are many APIs behind in what we support so far (ref: #1073), so we're asking for help fully fleshing out our support. This would be another place we could improve, so I've added the <kbd>help wanted</kbd> label to this issue. A PR would be great to help us get this feature implemented quickly.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-compute#14
