### ISSUE TITLE
Links in google-cloud-node/pubsub to API docs are 404

### ISSUE THREAD

**Issue by jdpedrie** [GoogleCloudPlatform/google-cloud-node#1609]
Hey fellas,

We ran into this issue earlier this week and I thought I'd check the other language libraries as well. It looks like Google recently moved the documentation location for PubSub, so a quick glance at your documentation shows the API documentation links under "More Information" are now 404.

Quick fix is:

```
Before: https://cloud.google.com/pubsub/reference/rest
After: https://cloud.google.com/pubsub/docs/reference/rest
```

**Comment by stephenplusplus** [comment]
Thanks!

**Comment by callmehiphop** [comment]
Might want to just open an issue on gcloud-common

**Comment by stephenplusplus** [comment]
I'll move it.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#190
