### ISSUE TITLE
jba broke gh-pages

### ISSUE THREAD

**Issue by jba** [GoogleCloudPlatform/google-cloud-node#1628]
@callmehiphop 

I pushed a bad commit (why do I have push rights)?

I then force-pushed the previous head over it, but I think one commit got dropped.

PTAL.

**Comment by jba** [comment]
I think it was c4a2ceacf6ab498c7ad319a1600fad5c24b6c14c that got dropped.

**Comment by jba** [comment]
I have push rights for google-cloud-go, but I guess the rights are not fine-grained enough.

What happened, BTW:

* I copied the node site as a start for the go site: `cp -r google-cloud-node google-cloud-go`
* I made changes and pushed.
* `cp` copied the `.git` directory, so ... _boom_.

**Comment by callmehiphop** [comment]
I think it's ok, all our releases look like they're there and we have a few going out today so I'll just regenerate all the things.

Anything look amiss to you @stephenplusplus ?

**Comment by stephenplusplus** [comment]
If it passes your check, it passes mine 👍  Thanks for letting us know @jba.
