### ISSUE TITLE
Python link in language drop-down sends user to gcloud-python

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#1651]
The language drop-down on the [Client Library Reference page for Node](https://googlecloudplatform.github.io/google-cloud-node/#/) sends users to gcloud-python when selecting Python:

![image](https://cloud.githubusercontent.com/assets/6609430/18977130/930d6f88-866c-11e6-9bd4-10560f442397.png)

It's a problem because sometimes we'll see a 404 appear.

[Expected]
It should point to google-cloud-python.

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#194

**Comment by stephenplusplus** [comment]
Sorry, thought this would have affected all of our docs sites, but it's just ours. @callmehiphop -- any ideas?

**Comment by callmehiphop** [comment]
Closing per https://github.com/GoogleCloudPlatform/gcloud-common/issues/194
