### ISSUE TITLE
Change title of tab from gcloud to google-cloud-node

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#1652]
When opening the [Client Library Reference page for Node](https://googlecloudplatform.github.io/google-cloud-node/#/) we can notice that the tab title says `gcloud`:

![image](https://cloud.githubusercontent.com/assets/6609430/18977204/18034c9e-866d-11e6-8ac4-ebae375e8b16.png)

[Expected Result]
We should update it to say `google-cloud-node`.

**Comment by stephenplusplus** [comment]
Good catch. It looks like this applies to all of the client libs. @quartzmo opened an issue [on common](https://github.com/GoogleCloudPlatform/gcloud-common/issues/195) to track a fix.
