### ISSUE TITLE
docs: update event emitters to use event tag

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1667]
Related: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1665#discussion_r81619234

http://usejsdoc.org/tags-event.html

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by eoogbe** [comment]
I am no longer on the team.
