### ISSUE TITLE
Dead link in docs

### ISSUE THREAD

**Issue by positlabs** [GoogleCloudPlatform/google-cloud-node#1671]
The doc: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.41.2/compute/zone?method=createDisk

The dead link, "See a Disk resource": https://cloud.google.com/compute/docs/reference/v1/disks

I'm guessing it should link to here: https://cloud.google.com/compute/docs/reference/latest/disks

**Comment by stephenplusplus** [comment]
Hmm, https://cloud.google.com/compute/docs/reference/v1/disks works for me. It redirects to `latest`. We point it to the specific version in case the "latest" API changes upstream and we aren't implementing it yet.

**Comment by positlabs** [comment]
Heh, must have been a service blip or something... the redirect is working for me, now

**Comment by stephenplusplus** [comment]
Phew! Thanks for looking out, though.
