### ISSUE TITLE
Geospatial queries for Node?

### ISSUE THREAD

**Issue by foreignmedia** [GoogleCloudPlatform/google-cloud-node#1683]
It looks like Python and Java SDKs have the ability to perform Geospatial queries using GeoRegions.  Is this coming for Node? If not, is there a way to perform a geospatial query in GQL?

**Comment by stephenplusplus** [comment]
We currently only have [`datastore.geoPoint()`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.41.2/datastore?method=geoPoint), but nothing similar to GeoRegions.

*From https://cloud.google.com/appengine/docs/java/datastore/geosearch#known_issues*:
> **Known issues**
> This is an alpha release of geospatial search. It has some limitations that will be removed in future releases
> - Geospatial search is only available in the Java runtime, Python support is coming soon.
> - Geospatial search is only accessible using App Engine's Datastore API, there is no GQL support at this time.

I'm not aware when we'll see support trickle down here, but I'll leave the issue open to remind us to keep an eye on it.

**Comment by foreignmedia** [comment]
Much appreciated. What is the recommended way to store/perform geospatial
queries on Google Cloud / App Engine when using node? Right now we've
failed back to GeoFire but its not ideal as Firebase is geared more for
dynamic data.

**Comment by stephenplusplus** [comment]
No problem, let me loop in the expert to make sure you receive the best advice! // cc: @pcostell

**Comment by pcostell** [comment]
Geospatial queries are currently only available in App Engine standard using the Java SDK as an alpha feature. 

If you'd like to use the feature, I'd recommend setting up your own application API which runs a small server in Java on App Engine standard. Also please note that since this is an alpha feature release, it has no SLA or deprecation policy.

**Comment by foreignmedia** [comment]
So, no officially supported/endorsed method to do Geo using Bigtable, SQL
or Datastore? Are Fusiontables something we can depend on or still
experimental?

**Comment by pcostell** [comment]
I was only answering the immediate question about how to use the Cloud Datastore geospatial feature. I am not the right person to talk to about how to do geo queries in Cloud Bigtable, Cloud SQL, or Fusiontables.

**Comment by stephenplusplus** [comment]
Thanks for helping out @pcostell.

For the other APIs, a question on StackOverflow might be a good course for answers. Team members from those APIs monitor those questions, so you'll likely find the best help there.

Maybe it's best to leave this issue "closed", as support outside of App Engine might not actually be coming. In any case, thanks for bringing this up. Hopefully we were able to dig up something useful, and for the rest, StackOverflow should fill in.

**Comment by victusfate** [comment]
Can anyone recommend something like geofire for cloud Datastore? (Geohash calc plus region lookups in nodejs)

It sounds like we'll need to write this ourselves migrating from Firebase
