### ISSUE TITLE
question: daily testing

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1685]
Since we've modularized our library, we've tried to speed up our builds by only testing the modules that have seen code changes. Because of this some modules are getting tested less since they receive fewer updates, I think it would be a good idea to set up a daily [cron job](https://docs.travis-ci.com/user/cron-jobs/) to run system tests for all modules.

Thoughts?

/cc @omaray @jgeewax

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#199

**Comment by callmehiphop** [comment]
@stephenplusplus not sure how relevant it is to everyone else? I propose this mainly because of our strategy for CI.

**Comment by stephenplusplus** [comment]
I think the idea and conversation could benefit everyone. Surely, we all have a day where we don't merge to master.

**Comment by callmehiphop** [comment]
Touche!
