### ISSUE TITLE
copy spanning locations and/or storage classes could not complete within 30 seconds

### ISSUE THREAD

**Issue by aschmid** [GoogleCloudPlatform/google-cloud-node#1687]
hi,

i am trying to move GCS object from a standard to a nearline bucket and sometimes i get this error:

`Copy spanning locations and/or storage classes could not complete within 30 seconds. Please use the Rewrite method (https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite) instead. - code: 413`

i looked through the docs [here](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.2.0/storage) but i could not figure out a way to do this with the node module.

is this possible?

**Comment by stephenplusplus** [comment]
We do actually have `rewrite` implemented now, merged in #1663. However, it'll likely be a week or so before it's released. You can use the master branch directly to get this behavior, or try something like:

```js
var gcs = require('@google-cloud/storage')({ ... })
var bucket = gcs.bucket('...')
var file = bucket.file('...')

function rewrite(newBucketName, newFileName, callback) {
  newBucketName = encodeURIComponent(newBucketName)
  newFileName = encodeURIComponent(newFileName)
  file.request({
    method: 'POST',
    uri: '/rewriteTo/b/' + newBucketName + '/o/' + newFileName
  }, callback)
}

rewrite('new-bucket-name', 'new-file-name', function(err, resp) {
  if (!err) {
    // yay!
  }
})
```

**Comment by aschmid** [comment]
i guess #1663 was not released yet right? 
is there an updated eta for it?

**Comment by stephenplusplus** [comment]
I'm sorry I didn't update you, it is out now in both @google-cloud and @google-cloud/storage: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.42.2/storage/file?method=copy

**Comment by aschmid** [comment]
cool thank you.
is there anything specific parameter i have to pass to the function or does it do a rewrite automatically under the hood? 
is this only on copy or on move too?

**Comment by stephenplusplus** [comment]
rewrite is used under the hood for both copy and move. It turns out the upstream rewrite API method can handle all that the copy endpoint does, and then some. Let me know if you run into any issues!

**Comment by aschmid** [comment]
great! will do...
