### ISSUE TITLE
Can't upload file with .webm extension

### ISSUE THREAD

**Issue by mikeal** [GoogleCloudPlatform/google-cloud-node#1691]
This is an incredibly strange bug.

```javascript
const storage = require('@google-cloud/storage')
const path = require('path')

let gcs = storage({
  projectId: 'myid',
  keyFilename: path.join(__dirname, 'keyfile.json')
})

const bucket = gcs.bucket('test')
const putFile = filename => bucket.file(filename).createWriteStream()
let t = putFile('test.webm')
t.write('asdf')
t.end()
```

Results in:

```
Error: Not Found
    at Request._callback (/Users/mikeal/git/shaolin/node_modules/gcs-resumable-upload/index.js:274:25)
    at Request.self.callback (/Users/mikeal/git/shaolin/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/mikeal/git/shaolin/node_modules/request/request.js:1045:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/mikeal/git/shaolin/node_modules/request/request.js:966:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

If you replace `'test.webm'` with `'test.txt'` or just some random stuff like `'dfasfdaisdf'` it'll work fine.

The exception comes out of request but I can't figure out what is different, and I wrote request ;(

This isn't because the data being written isn't a valid .webm file because I found this bug attempting to PUT real files.

**Comment by stephenplusplus** [comment]
I think this could be a resumable upload that was started, but didn't finish. In `gcs-resumable-upload`, we persist some `~/.config` data that could have been left in an incorrect state, making us think the file exists upstream, when it actually doesn't. We have a check in that library to handle this situation ([I thought](https://github.com/stephenplusplus/gcs-resumable-upload/blob/83b0fc5d0a3c23f7bd3a5f552644ec75fb512fe3/index.js#L235)), but it looks like another request returned the 404.

Potential fixes:

- Delete config data, `~/.config/configstore/gcs-resumable-upload.json`
- Use another filename with the `.webm` extension
- Disable resumable uploads `bucket.file(filename).createWriteStream()`

In any case, if you can track down the details of the request that returned Not Found, that should help me tighten up `gcs-resumable-upload` if it is just a local bug, and not something upstream.

**Comment by mikeal** [comment]
Oh wow, this is crazy. I had no idea this kind of state was kept around by default.

I'll do *all* of these fixes :)

**Comment by stephenplusplus** [comment]
It usually "just works", but it is a complicated bummer when it fails. Let me know if you think we should re-think the defaults. For now, I'll make sure the docs do a better job of explaining what's going on.

**Comment by mikeal** [comment]
Ya, it's definitely a bug I just don't know how to characterize it. There's no data in that bucket in the console so it's incredibly confusing when it happens. If anything, a better error would be great.

**Comment by stephenplusplus** [comment]
Could you check which version of gcs-resumable-upload is being used? And if you can still reproduce the error, could you track down which request gcs-resumable-upload made that returned the 404?
