### ISSUE TITLE
pubsub Invalid resource name given

### ISSUE THREAD

**Issue by 1N50MN14** [GoogleCloudPlatform/google-cloud-node#1694]
`topic.subscribe()` throws an error 

`Invalid resource name given (name=projects/xx/subscriptions/7fc49e57-7ec2-422a-a90c-d40297b763bc). Refer to https://cloud.google.com/pubsub/overview#names for more information.`

The subscription name `7fc49e57-7ec2-422a-a90c-d40297b763bc` does only contain letters [A-Za-z]), numbers ([0-9], dashes (-) and does not begin with the string `goog`. 

It should've passed.

#### Environment details

  - OS: Ubuntu
  - Node.js version:4.6.0
  - npm version:3.10.7
  - google-cloud-node version:0.37.0

**Comment by stephenplusplus** [comment]
Must start with a letter :)

**Comment by 1N50MN14** [comment]
Ops, sorry ;)

a letter to satisfy gcloud happy+uuid.v4() then ;)
