### ISSUE TITLE
Expose maxRetries & totalTimeoutMillis to gapic layer

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1696]
We'll need a way to honor `maxRetries` with requests made through the generated API. We will need to wrap each outbound call to implement our own exponential backoff retry strategy.

@callmehiphop will `retryRequest` work here, or will this require any extra work to be compatible with the promise API?

**Comment by callmehiphop** [comment]
I think all our gapic files still are using callback mode, so integrating with `retryRequest` then decorating the methods via `promisify` should work just fine.

We will probably need to rethink our strategy once gapic methods start returning promises,  but I vote we cross that bridge once we get to it.

**Comment by stephenplusplus** [comment]
I think the bridge is pretty close, @jmuk promise support is landed in gax, right? We just need the Language & Speech APIs regenerated. Let me know I'm mistaken!

**Comment by stephenplusplus** [comment]
Together with the gax team, we've decided to expose both `maxRetries` and `totalTimeoutMillis` to google-cloud users for 1.0.

**Comment by stephenplusplus** [comment]
@callmehiphop since this isn't <kbd>blocking beta</kbd> like I originally thought, it's not a big 🚨. But, if you have time soon, can you go over the methods that we would need to add an `options` argument to, just to be *absolutely sure* we won't have to break the API to support this configuration?

**Comment by callmehiphop** [comment]
@stephenplusplus are we only worried about APIs currently using GAPIC? I did a quick run through of those APIs and I didn't see any methods that didn't have some kind of options/config parameter.

**Comment by stephenplusplus** [comment]
I think we need to do all APIs that are gax-equipped now or later (basically, anything that is using gRPC). If we wait until we implement gax to realize we missed one, that would be a breaking change to add support.

**Comment by jmuk** [comment]
Found this through bug triage, I think this is done already. Am I right?

**Comment by stephenplusplus** [comment]
In some places, but widely, no. I've added a more general TODO to allow passing through *any* gax option from all of our generated API-wrappers: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1859
