### ISSUE TITLE
Should our promises be documented as first class?

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#1699]
Continuing https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1697#discussion_r83665859:

Should we be promoting promise use first, as in "this is the way to use our library", with a mention about callbacks? Since the demand for promises is so strong, I'm wondering if we might be better off changing our position to a promise library that supports callbacks instead of the other way around.

**Comment by SimenB** [comment]
As a complete outsider, I vote yes! 
Especially with async await on the horizon, it's a way better way of writing async code

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by eoogbe** [comment]
I am no longer on the team
