### ISSUE TITLE
BigTable asynchronous row handling

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1715]
Is there a way to asynchronously handle rows with a BigTable range query? What I'm trying to do is something like this:

```
table.getRows().on('data', async row => {
  await doSomeExpensiveWork(row);
});
```

**Comment by callmehiphop** [comment]
What about something like this?

```js
table.getRows()
  .pipe(through.obj((row, _, next) => {
    doSomeExpensiveWork()
      .then(() => next(null), next);
  });
```

**Comment by stephenplusplus** [comment]
Yep, that's what I would say. It will not pull more data from the stream until you're done processing the last result.

In case users of other APIs see this, this will work for any object stream from our APIs.
