### ISSUE TITLE
Datastore document IDs not returned on datastore.runQuery()

### ISSUE THREAD

**Issue by RobertHerhold** [GoogleCloudPlatform/google-cloud-node#1719]
Just upgraded to the latest datastore package w/ Promises. When I run `datastore.runQuery(myQuery)`, the result is an array containing the queried documents and cursor information. The documents do not contain any identifying information, and I don't see is any way to retrieve the IDs of those documents as I could before.

How should I go about getting these document IDs?

**Comment by stephenplusplus** [comment]
I believe this is caused by the change introduced in https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1682. Can you try that?

**Comment by RobertHerhold** [comment]
That's the problem - Thanks so much!

**Comment by stephenplusplus** [comment]
No problem, sorry we haven't found a great way to document breaking changes. Thanks for being patient!
