### ISSUE TITLE
Cloud Storage with local emulator

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1731]
There are a few "Mock s3" servers that run in memory/disk. Since the google cloud storage and S3 APIs are the same, I was wondering if there was a way to use one of these servers with the Cloud Storage client? If not, what is the recommended way to use this API for local development?

**Comment by stephenplusplus** [comment]
Can you link the mock libraries? I'm not sure they'd be the same, but soon we will support using a custom endpoint which accepts the requests from our API (#1630).

**Comment by arbesfeld** [comment]
Here are a few :

- https://www.minio.io/
- https://github.com/jubos/fake-s3

**Comment by nfarina** [comment]
I found that it was simple enough to create my own mock classes to emulate Google Cloud Storage just enough for my tests to pass. I posted my code to [this gist](https://gist.github.com/nfarina/90ba99a5187113900c86289e67586aaa) in case anyone finds it useful as a starting point. Note: written in ES6 with Flow annotations.

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-storage#18
