### ISSUE TITLE
Should we encourage folks to use yarn instead of npm?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1746]
https://www.atatus.com/blog/everything-you-wanted-to-know-about-yarn-package-manager/

It seems it's getting some good reviews, and may help us get the install time down to a reasonable number. Any thoughts?

**Comment by stephenplusplus** [comment]
I'm cool with recommending this 👍 How do you see us encouraging it?

- [ ] Where we have `npm install` now, show `yarn add`
- [ ] Where we have `npm install` now, add a quick link / explanation about yarn and its speed boost
- [ ] Add a mention to it in Troubleshooting question:
  - *Is the google-cloud module on npm really 800 MB?*
- [ ] Add a new question: "Can I use yarn?"
- [ ] Other?

**Comment by stephenplusplus** [comment]
I think with npm@5, the yarn performance benefits aren't as glaring. My vote would be to continue recommending npm.

@jmdobry @callmehiphop any thoughts?

**Comment by jmdobry** [comment]
We've been using Yarn in all our Node.js samples since Yarn was version 0.16. The Google App Engine docs have a section on using Yarn. I think it's worth at least mentioning Yarn.

**Comment by danoscarmike** [comment]
Ping for status on this?  Is there an action for google-cloud-node or can I close this issue?

**Comment by stephenplusplus** [comment]
I don't think it's necessary to mention [yarn](https://yarnpkg.com/en). As far as I know, any npm package is also supported by yarn, so we don't have to spell that out. I wouldn't go so far as to recommend that folks use yarn instead of npm. And I don't think yarn needs our help with marketing, if we were to only mention that it exists.

@lukesneeringer: how should we proceed?

**Comment by landrito** [comment]
I agree with @stephenplusplus. Lets stick with simply documenting npm. Closing this. @lukesneeringer reopen if you feel we need to mention yarn.
