### ISSUE TITLE
Minor clarification of GCS data validation docs; change default hash algo?

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/google-cloud-node#1749]
The docs for [createReadStream](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.4.0/storage/file?method=createReadStream) and [createWriteStream](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.4.0/storage/file?method=createWriteStream) say

> "By default, data integrity is validated with an MD5 checksum for maximum reliability, falling back to CRC32c when an MD5 hash wasn't returned from the API."

It appears that actually _both_ are calculated, and _both_ are verified if present (although the md5 check overrules the crc32c check), so I think it would be more accurate to say

> "By default, checksums are calculated using both MD5 and CRC32c on the fly; MD5 is used for the final validation for maximum reliability, falling back to CRC32c when an MD5 hash wasn't returned from the API (i.e. in the case of composite objects)."

But, using a cryptographic hash seems like an overkill default. What do you think of changing it to by default calculating CRC32c only, and not calculating MD5 unless the validation method is "MD5"?

(Also, if you specify "md5" then it does not appear to fallback to CRC32c if there was no MD5 returned -- ideally it would fallback instead of doing zero validation, I think?)

**Comment by stephenplusplus** [comment]
I'm fine with the docs change. As far as disabling MD5 check by default, that would be validating using the less-reliable method, by our own words. If it being expensive to compute is an issue to the user, they have the option to disable, which I think is good enough.

> (Also, if you specify "md5" then it does not appear to fallback to CRC32c if there was no MD5 returned -- ideally it would fallback instead of doing zero validation, I think?)

This seems ideal. If the user wanted MD5 validation specifically and we couldn't do it, that should be a failure.

**Comment by zbjornson** [comment]
Thanks as always for the prompt reply!

>  validating using the less-reliable method, by our own words

Sure, although I think those words might be google-cloud-node's? The [GCS docs](https://cloud.google.com/storage/docs/hashes-etags) advise CRC32C "for all cases":

> Google recommends that customers use CRC32C for all cases, as described in the Validation section below. Customers that prefer MD5 can use that hash, but that hash is not supported for composite objects.

Because it's configurable :heart:, I totally don't feel strongly about changing it, but I think most people would say MD5 is overkill for data integrity checks. (The risk of undetected corruption with CRC32c is 1/2^32, or 0.99999999977 detection.)

(Re: last point, makes sense.)

**Comment by stephenplusplus** [comment]
Oh jeez, if we just made that up, then I'm fine re-thinking this. We can follow that doc's advice and do crc32c by default and md5 if asked. Any interest in a PR? No pressure, if not, I'll get to it soon :)

Thanks for calling this out!
