### ISSUE TITLE
Incorrect "insufficient tokens for quota group and limit" error?

### ISSUE THREAD

**Issue by 1N50MN14** [GoogleCloudPlatform/google-cloud-node#1756]
Apologies if this is not really an issue, searched all closed/open issues and on the net, still can't figure it out.

PubSub is throwing the following error:
`Insufficient tokens for quota group and limit 'administratorCLIENT_PROJECT-100s' of service 'pubsub.googleapis.com', using the limit by ID 'XXX'``

I went through the quota usage in the Dashboard for pubsub and I'm way below the limit on all of them, this is not even running in production.

Any ideas what this might be? I know that I generate random subscription ids to ensure messages are received by all subscribers, could this be the cause?

Thanks  

#### Environment details
  - OS:Ubuntu 16 / Docker
  - Node.js version: 4.6.1
  - google-cloud-node version:0.43.0

**Comment by 1N50MN14** [comment]
closing

**Comment by MuthuD** [comment]
I'm facing the same issue at times. Not sure about the root cause. Can any one guide me on this?

Thanks in advance

**Comment by astroyang** [comment]
Hej @1N50MN14 We have similar problem while our usage is way below quota, we still receive this error. Can you please provide some hints about how you find the root cause? Thanks!

**Comment by 1N50MN14** [comment]
@astroyang I was giving each subscription a unique subscription name (uuid) to ensure messages arrive to a single subscriber at a time, so one way to reduce usage is to avoid that and instead ignore irrelevant messages. But the main thing that solved it was increasing the quota in the developer console if I remember correctly the default quota is 1K, I took it up to the maximum (10K); it wasn't clear you could actually do that from the console. Finally, I'm now using a different messaging queue for few reasons one of which I I thought 10K was too little - that did it ;)

**Comment by astroyang** [comment]
@1N50MN14 Thanks for your kind reply! It seems not exactly the same as our problem but I agree that 10K may seems not enough if you have a relatively active application! :)

**Comment by sx5640** [comment]
I ran into the same issue as well. In my case it was Administrative operations that limited the number of requests. It is set to 1,000 per 100 seconds (10 ops/s) by default, and can upgrade to 10,000 per 100 seconds (100 ops/s)

The administrative operations consist of Get, List, Create, Delete, ModifyPushConfig, SetIamPolicy, GetIamPolicy, TestIamPermissions. However publishing the message does not count as admin ops (I haven't try subscribing, but looks like it doesn't count as admin ops as well).

In my case every time before sending a message, I was checking if the topic exists or not, and try to create one if it doesn't. By removing that line, the error went away.
