### ISSUE TITLE
BigTableInstance.getRows sometimes returns 0 values silently

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1757]
I noticed when running `getRows` that I would sometimes get 0 results. No error was thrown so this took a while to uncover, and eventually I had to do it in batches:

```js
  let rows = [];
  const MAX_KEYS = 1000;

  for (const i = 0; i * MAX_KEYS < rowIds.length; i++) {
    const [newRows] = await eventsTable.getRows({
      decode: false,
      keys: rowIds.slice(i * MAX_KEYS, (i + 1) * MAX_KEYS),
      filter: [{
        column: {
          cellLimit: 1,
        },
      }],
    });

    rows = rows.concat(newRows);
  };

```

I'm not sure if this is even the right approach, since 1000 seems pretty arbitrary.

Potentially this is related to #1755? However I was only using ~9k keys which where ~100 characters each which should be under the 4mb limit.

**Comment by callmehiphop** [comment]
So I believe in v1 you weren't allowed to send more than 1mb worth of keys (after serialization). I'm not sure if such a limit exists in v2 however.

/cc @lesv

**Comment by stephenplusplus** [comment]
@lesv any insight on this one? Thanks!

**Comment by stephenplusplus** [comment]
@callmehiphop anyone else from Bigtable you can ping for us?

**Comment by sduskis** [comment]
I don't know enough about this case to give a clear answer.  Is the table populated with data for each of the keys?  Has someone tried to reproduce this case?  There isn't a known issue for the service failing, but I can to reproduce this with java and see if it succeeds.

**Comment by stephenplusplus** [comment]
@callmehiphop wdyt?

**Comment by callmehiphop** [comment]
@arbesfeld are you still seeing this?

**Comment by arbesfeld** [comment]
I'm not sure - I did a workaround with made requests to big tables with chunks of keys that were smaller and that seemed to fix the issue.

**Comment by stephenplusplus** [comment]
Cool, I think we can close this out. We have a note in our docs advising to chunk up requests as well.
