### ISSUE TITLE
Monitoring sample references unknown value

### ISSUE THREAD

**Issue by jmdobry** [GoogleCloudPlatform/google-cloud-node#1761]
https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/monitoring/src/v3/metric_service_api.js#L603

What is `var view = TimeSeriesView.FULL;`?

`TimeSeriesView` is undefined.

In the proto `TimeSeriesView` is defined as an enum, but apparently the enum object was not emitted in `metric_service_api.js`

**Comment by jmuk** [comment]
Accepted, this is a bug. For the reference, that can be accessed as `monitoringV3.ListTimeSeriesRequest.TimeSeriesView.FULL`.

**Comment by stephenplusplus** [comment]
@jmuk any updates on this?

**Comment by jmuk** [comment]
not yet. I've been busy on other things.

**Comment by stephenplusplus** [comment]
Was this fixed in your recent PR?

**Comment by jmuk** [comment]
Yes, that's fixed by https://github.com/googleapis/toolkit/commit/8488f7c3306f5c83ca5644f6042c366c5677d035 and regenerating monitoring fixed. Sorry I forgot mentions.

**Comment by stephenplusplus** [comment]
Cool, thanks!
