### ISSUE TITLE
404 link at docs

### ISSUE THREAD

**Issue by degroote22** [GoogleCloudPlatform/google-cloud-node#1774]
https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.43.0/google-cloud?method=storage

The read more link of storage is 404ing.
I guess this should be covered by some test.

**Comment by stephenplusplus** [comment]
The `Source Code` link?

@callmehiphop the source code links need help!

```diff
-https://github.com/GoogleCloudPlatform/google-cloud-node/blob/v0.43.0/google-cloud/src/index.js#L294
+https://github.com/GoogleCloudPlatform/google-cloud-node/blob/v0.43.0/packages/google-cloud/src/index.js#L294
```

**Comment by callmehiphop** [comment]
Thanks for reporting! 

Closing per https://github.com/GoogleCloudPlatform/google-cloud-node/commit/1b1e57566c82a8e291c42fbab33ea0a4a9111c27
