### ISSUE TITLE
bigquery silly bug, table.exists for undefined returns true

### ISSUE THREAD

**Issue by VikramTiwari** [GoogleCloudPlatform/google-cloud-node#1776]
#### Environment details

  - OS:macOS
  - Node.js version:v6.9.1
  - npm version:3.10.9
  - google-cloud-node version:^0.43.0

#### Steps to reproduce

  1. require `google-cloud`
  2. Run the function
```js
table.exists(undefined, function(err, exists){
// returns exists as true
})
```

**Comment by stephenplusplus** [comment]
Thanks for reporting!

**Comment by stephenplusplus** [comment]
I haven't been able to reproduce. The exists method looks like this:

```js
ServiceObject.prototype.exists = function(callback) {
  this.get(function(err) {
    if (err) {
      if (err.code === 404) {
        callback(null, false);
      } else {
        callback(err);
      }

      return;
    }

    callback(null, true);
  });
};
```

Since `callback` is `undefined` if used the way your example shows, I get an error in the terminal:

```
/Users/stephen/dev/play/gissue-1776/node_modules/@google-cloud/common/src/service-object.js:170
        callback(null, false);
        ^

TypeError: callback is not a function
    at /Users/stephen/dev/play/gissue-1776/node_modules/@google-cloud/common/src/service-object.js:170:9
```

Am I missing something?

**Comment by stephenplusplus** [comment]
@VikramTiwari since I'm still not sure about how to reproduce this one, I'm going to close. Please let me know if I have made an error in my attempt above.
