### ISSUE TITLE
Datastore Query returning only 'data' and no 'key'

### ISSUE THREAD

**Issue by DVassilev** [GoogleCloudPlatform/google-cloud-node#1777]
#### Environment details

  - OS: OS X
  - Node.js version: 4
  - npm version: 3
  - google-cloud-node version: 0.43.4 (latest as of writing)

#### Steps to reproduce

  1. Create a query for Datastore
  2. Run query and log object

The entities returned from a query are no longer in the [ { key, data} ] format. For some reason it now just returns the contents of data.

**Comment by stephenplusplus** [comment]
Sorry for the confusion. Please see #1768.
