### ISSUE TITLE
running pubsub against local emulator

### ISSUE THREAD

**Issue by fonzy2013** [GoogleCloudPlatform/google-cloud-node#1779]
I saw that the PUBSUB_EMULATOR_HOST is implemented but I can't figure out how to disable auth to get it to work. 
Can someone please point me in the right direction so I can publish and subscribe completely locally?

**Comment by stephenplusplus** [comment]
Can you add some output you're getting that shows auth is being attempted?

**Comment by fonzy2013** [comment]
I was merely looking for the documentation for it as I don't know how to even start running it.

**Comment by stephenplusplus** [comment]
Woops, sorry about that. We don't have very elaborate docs on starting the emulator, as [this document](https://cloud.google.com/pubsub/docs/emulator) does a great job of that. Starting the emulator sets some environment variables, `PUBSUB_EMULATOR_HOST` being one of them. Our code will acknowledge this, and re-route all API requests we make to that endpoint.

Hopefully this helps! If you have any more specific questions along the way, let me know.
