### ISSUE TITLE
@google-cloud/datastore 0.5.0 does not return entity keys with query results

### ISSUE THREAD

**Issue by floodfx** [GoogleCloudPlatform/google-cloud-node#1780]
#### Environment details

  - OS: MacOS 10.11.6
  - Node.js version: 6.9.1
  - npm version: 3.10.8
  - google-cloud-node version: 0.43.0
  - @google-cloud/datastore version: 0.5.0

#### Steps to reproduce

```
git clone git@github.com:GoogleCloudPlatform/nodejs-docs-samples.git
cd nodejs-docs-samples/datastore
```
Open ```quickstart.js```
Add code below to end of the file
```
// query for entities
var q = datastoreClient.createQuery(kind)
q.run((err, entities, nextQuery) => {
  console.log(err, entities, nextQuery)
  for(var i = 0; i < entities.length; i++) {
    var task = entities[i];
    console.log(`Task ${task}: Key${task.key}`);
  }
});
```

Run 
```
npm install
node quickstart.js
```

Keys returned with entity results.

Next update package.json to use 0.5.0 of @google-cloud/datastore

Run 
```
node quickstart.js
```

Keys are "undefined".

**Comment by floodfx** [comment]
Note the default version of @google-cloud/datastore for nodejs-docs-samples is "^0.1.1"

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/nodejs-docs-samples#250
