### ISSUE TITLE
Bigtable.insert isn't promisified?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1788]
https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.43.0/bigtable/table?method=insert

Looks like we don't have the promisified verison of insert which is a bummer because the code ends up looking like...

```js
bigtable.getInstances().then(function(data) {
  var instance = data[0][0];
  var table = instance.table(...);
  table.insert(entries, function(err, insertErrors) {
    ...
  });
});
```

Mixing the promise version and callbacks makes me feel :(

**Comment by callmehiphop** [comment]
No one wants a sad JJ! I'm on it.
