### ISSUE TITLE
Non-recoverable Failures from Language Service

### ISSUE THREAD

**Issue by aldenpotamus** [GoogleCloudPlatform/google-cloud-node#1796]
#### Environment details
  - **OS**: Ubuntu 14.04 LTS & Node.js Runtime on GCE
  - **Node.js version**: 6.9.0
  - **npm version**: 3.10.8
  - **google-cloud-node version**: 

    - google-cloud: 0.43.0
    - @google-cloud/language: 0.6.0
    - googleapis: 14.2.0

#### Steps to Reproduce
  1. Init
```js
var Language = require('@google-cloud/language');
var language = Language({ projectId: projectId });
```  
2. Parsing function:
```js
function analyzeSyntax(message) {
  var document = language.document({
    content: message,
    type: 'text',
    languages: 'en'
  });

  var config = {
    syntax: true,
    entities: true,
    sentiment: false,
    verbose: true
  };

  return document.annotate(config)
}
```
  3. Let system go dormant waiting for another text payload to parse
  4. Call 3 again, get intermittent failures.

#### Observed Behavior
It appears that there’s a grpc failure that not being handled properly in the language package.  From what I’ve read code 14 is Unavailable which should be retryable, but we’re seeing intermittent failures when calling annotate on a document.  This appears to happen most consistently when the service is left idle for a short time (~5min) and another identical request immediate after will succeed. 

I’ve confirmed that the issue is taking place in annotate and added a new event handler on unhandledRejected to see if I could get any more information (see below), but at this point it appears like it may be a handshake timeout or something else… but my understanding of code 14 is that it is transient and probably should just be handled by a retry.

Thanks in advance for any help around this issue, and see below for some version information as well as the text of the errors I’m seeing.

#### Errors
```
Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> { Error: {"created":"@1479230727.245093279","description":"Secure read failed","file":"../src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1479230727.245051044","description":"EOF","file":"../src/core/lib/iomgr/tcp_posix.c","file_line":235}]}
    at  <...>/node_modules/grpc/src/node/src/client.js:417:17
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  note: 'Exception occurred in retry method that was not classified as transient' } }  reason:  { Error: {"created":"@1479230727.245093279","description":"Secure read failed","file":"../src/core/lib/security/transport/secure_endpoint.c","file_line":157,"grpc_status":14,"referenced_errors":[{"created":"@1479230727.245051044","description":"EOF","file":"../src/core/lib/iomgr/tcp_posix.c","file_line":235}]}
    at <...>/node_modules/grpc/src/node/src/client.js:417:17
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  note: 'Exception occurred in retry method that was not classified as transient' }
```

**unhandledRejection event handler**
```
promise = {}
reason = {"code":14,"metadata":{"_internal_repr":{}},"note":"Exception occurred in retry method that was not classified as transient"}
```

**Comment by stephenplusplus** [comment]
Thanks for reporting this.

@jmuk we call a generated method [here](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/86755a78509f0267f137ad19f06ed23ba1757364/packages/language/src/document.js#L544)? This [config file](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/86755a78509f0267f137ad19f06ed23ba1757364/packages/language/src/v1/language_service_client_config.json) appears to configures a retry strategy. Does this take effect when the response code is 14?

**Comment by jmuk** [comment]
This is probably because I made the code to handle callback incorrectly. Filed as https://github.com/googleapis/gax-nodejs/issues/69.

**Comment by stephenplusplus** [comment]
Thanks for the update. I'll subscribe to that issue.

**Comment by stephenplusplus** [comment]
@jmuk is this one resolved?

**Comment by jmuk** [comment]
Right it's closed. It's better to update the `@return` comment but I think that's not urgent.
