### ISSUE TITLE
Loss of search API

### ISSUE THREAD

**Issue by sskoopa** [GoogleCloudPlatform/google-cloud-node#1798]
The appengine search API was in google-cloud@0.31.0 but has since been removed.  Is there a plan to bring it back?

See: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.31.0/search

**Comment by stephenplusplus** [comment]
There is some discussion about this going on in https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1262. I can't comment on the status of that API, but I've asked for an official comment to address those affected from our removing it from this library. For now, the only way to use it (without manually re-using the code that was removed) is to roll back to `0.31.0`. 

Please add any thoughts and subscribe to #1262.
