### ISSUE TITLE
dataset.save() should work with entities using the new datastore.KEY symbol

### ISSUE THREAD

**Issue by richardkazuomiller** [GoogleCloudPlatform/google-cloud-node#1803]
Before v0.5.0, we could do something like this:

```
const key = datastore.key(['Some','thing'])
datastore.get(key,(err,entity) => {
  entity.data.foo = 'bar'
  datastore.save(entity,callback)
})
```

This worked because `datastore.save`'s parameter and the object gotten from `datastore.get` had the same structure, but now `datastore.save` has to be called with `{key:<key>,data:<data>}`, it's more difficult to do simple updates to entities. Right now we have to do this:

```
const key = datastore.key(['Some','thing'])
datastore.get(key)
  .then(([entity]) => {
    entity.foo = 'bar'
    return datastore.save({
      key: key,
      data: entity
    })
  })
```

but I think this should work:

```
const key = datastore.key(['Some','thing'])
datastore.get(key)
  .then(([entity]) => {
    entity.foo = 'bar'
    return datastore.save(entity)
  })
```

Personally I preferred the old version where everything was `{key:<key>,data:<data>}` because it was more straightforward and didn't require a reference back to the `datastore` object, but if it's going to be changed it should at least be consistent across the board.

**Comment by stephenplusplus** [comment]
Makes sense, thanks for the suggestion. PR sent: #1804
