### ISSUE TITLE
e-mail handling

### ISSUE THREAD

**Issue by taboca** [GoogleCloudPlatform/google-cloud-node#1810]
Hi Google, 

I have a 4-5 years AppEngine in Python and considering moving some bits and pieces to a NodeJS based platform. One of the cases I have identified would be the E-mail Handling System. So far, I am using the e-mail handler with the GAE/Python recommendations. 

I have noticed, however, that the Google Node Engine infrastructure won't offer such e-mail infrastructure for the case of Receiving (also Sending). First, I would like to hear about possible plans for the following items: 

* (As pointed: would e-mail handling be offered for Google/Node infra?)
* Would it be possible to have an elegant solution, for example using e-mails that are associated with the 3rd-party (us developers) domains? 
* Or, what would you recommend as alternatives? I setup my own e-mail broker in Node using other services, such as my own infrastructure?

**Comment by taboca** [comment]
The following is the closest thing I see from what it would be a spec for the developer's, taken from the GAE/Python

## E-mail handling config in the app.yaml

```
inbound_services:
- mail

- url: /_ah/mail/.+
  script: handle_incoming_email.app
  login: admin
```

Then, in the code front, it uses a library https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/appengine/standard/mail/handle_incoming_email.py

**Comment by stephenplusplus** [comment]
Hey @taboca, thanks for the question. I'm going to ping some folks who might be able to help find an answer:

// @jgeewax @bjwatson @omaray @JustinBeckwith

**Comment by JustinBeckwith** [comment]
Hey folks!  We don't currently have a great solution for mail.  Our plan is to build a generalized service that will work across GCE, GKE, and GAE - but that's many (many) months away.  In the interim - we suggest taking a look at SendGrid.  Apologies!

**Comment by taboca** [comment]
Hi Justin, 

What about receiving? SendGrid is for sending right?

**Comment by taboca** [comment]
This seems to be an area that is lacking resources online — or a gap — maybe it may sense to have an article to covering the alternative solutions here, even if one has to do the basic appengine infrastructure (Python) to talk with the NodeJS one heh, and, as pointed, other services or the manual way of doing it.

**Comment by stephenplusplus** [comment]
I'm going to close this issue as there's nothing we can do from here (google-cloud-node). Feel free to continue discussing.
