### ISSUE TITLE
Regenerate GAPIC files

### ISSUE THREAD

**Issue by jmuk** [GoogleCloudPlatform/google-cloud-node#1816]
This issue tracks the regeneration process of gapic (auto-generated files). The new auto-generated files have some updates, including:
- class name suffix has changed. Previously `-Api`, now `-Client` (like `speechClient`).
- revised paged iterations style -- previously a stream, now same as what GCN has.
- bug fix on enum values.

Google-cloud-node repository has the the generated files in the following APIs.

- [x] language
- [x] logging
- [x] monitoring
- [x] pubsub
- [x] speech
- [x] vision

**Comment by stephenplusplus** [comment]
Woo!
