### ISSUE TITLE
package.json for natural language is missing 'string-format-obj' dependency

### ISSUE THREAD

**Issue by d1manson** [GoogleCloudPlatform/google-cloud-node#1826]
easy to fix, right?

**Comment by stephenplusplus** [comment]
:( On it. Thanks for reporting!

**Comment by stephenplusplus** [comment]
Released under v0.44.1 and @google-cloud/language 0.6.2. Thanks again!

**Comment by d1manson** [comment]
thanks for the quick patch!

**Comment by d1manson** [comment]
Wait, you put it in devDependencies not dependencies?!

**Comment by stephenplusplus** [comment]
Well that's embarrassing. Another patch coming soon!

**Comment by stephenplusplus** [comment]
google-cloud@v0.44.2 and @google-cloud/language@0.6.3 released with the *actual* fix.
