### ISSUE TITLE
No 

### ISSUE THREAD

**Issue by igorclark** [GoogleCloudPlatform/google-cloud-node#1835]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - google-cloud-node version:

#### Steps to reproduce

  1. require `google-cloud`
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
Accidental issue @igorclark?

**Comment by igorclark** [comment]
Argh! Sorry @stephenplusplus, in the middle of making a real one 😳

**Comment by stephenplusplus** [comment]
Haha no problem :)

**Comment by igorclark** [comment]
Hi @JustinBeckwith 👋 Not too sure why you've assigned me to a 5-year old closed issue! Just checking, are you expecting me to do anything?

**Comment by JustinBeckwith** [comment]
Apologies - not at all - this was a robot run amok 🤖

**Comment by igorclark** [comment]
Gotcha! No worries. Cheers 👍
