### ISSUE TITLE
Publish @google-cloud/monitoring master to npm

### ISSUE THREAD

**Issue by tjmehta** [GoogleCloudPlatform/google-cloud-node#1845]
Commit `79cc175fb3c841779eb60e4f5a73023eefa7fe1a` is not in latest version on npm (`@google-cloud/monitoring@v0.1.2`)

[Missing commits](https://github.com/GoogleCloudPlatform/google-cloud-node/commits/master/packages/monitoring)

**Comment by stephenplusplus** [comment]
Will do. Just need to confirm #1761 was resolved.

**Comment by tjmehta** [comment]
Cool, didn't know testing was ongoing. Will close for now

**Comment by stephenplusplus** [comment]
I'm going to reopen to remind me to publish asap. Thanks for the push!

**Comment by tjmehta** [comment]
I have a monitoring related question while I have you:

If I am using the monitoring package on GKE, and I reporting a custom [time series metric](https://cloud.google.com/monitoring/api/ref_v3/rest/v3/TimeSeries), will the `resource` field be populated automatically? If not, how do I get all the `container` monitored resource `labels`*?

##### *Container Monitored Resource Labels
```
project_id: The identifier of the GCP project associated with this resource (e.g., my-project).
cluster_name1: An immutable name for the cluster the container is running in. 
namespace_id2: Immutable ID of the cluster namespace the container is running in. 
instance_id: Immutable ID of the GCE instance the container is running in. 
pod_id: Immutable ID of the pod the container is running in. 
container_name: Immutable name of the container. 
zone: The GCE zone in which the instance is running.

**Comment by stephenplusplus** [comment]
Published `@google-cloud/monitoring` version `0.1.3`.

@landrito @jmuk @bjwatson -- anyone have some insight on @tjmehta's question?

**Comment by jmuk** [comment]
(probably better to open another issue for questions?)

No, it does not expand or fill those fields automatically. Autogen layer does not know that depth of the API methods.
There must be some data to fill those labels, but I don't have knowledge to answer that question.

**Comment by stephenplusplus** [comment]
Ideally, we just use the issue tracker for bugs about the project, but questions slip in from time to time. StackOverflow is the best place to ask general questions 👍
