### ISSUE TITLE
Feature request: make environment variables compatible with google-cloud-ruby

### ISSUE THREAD

**Issue by timanovsky** [GoogleCloudPlatform/google-cloud-node#1852]
It would be nice if node and ruby applications can use the same configuration environment variables, and same preceding logic.  In my particular project I'm using two variables: `DATASTORE_EMULATOR_HOST` and `GCLOUD_KEYFILE_JSON`. First have higher priority. If it is unset, datastore client goes to service  endpoint specified by content of `GCLOUD_KEYFILE_JSON`. For node application I need to implement it myself

See how it is used here for example: https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/ea2be47beb32615b2bf69f8a846a684f86c8328c/google-cloud-datastore/lib/google/cloud/datastore/credentials.rb

**Comment by stephenplusplus** [comment]
We do support the datastore emulator variable, and for JSON, try 'GOOGLE_APPLICATION_CREDENTIALS', which comes from when you authenticate using the gcloud SDK, but you can set the env var manually to point to a JSON key file. That should be supported in Ruby as well.

**Comment by stephenplusplus** [comment]
Going to close @timanovsky, but let me know if `GOOGLE_APPLICATION_CREDENTIALS` doesn't do the trick.

**Comment by lukewlms** [comment]
There's a solution here for using environment variables instead of an on-disk file (critical for our Heroku setup).  

You can authenticate with `credentials: { private_key, client_email }` rather than path to a json file.

https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1173
