### ISSUE TITLE
Vision Face detection uses non-standard words

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1857]
When I do face detection, the API surfaces uses certain terms for emotions, and we seem to be using arbitrary synonyms for those, which doesn't seem quite right...

I suspect it's because the sentence we were using for emotion to complete is "Is the face in this picture ______." When we should probably have used the sentence "Does the face in this picture show ____" for the emotions.

Us | API | What to do
---|---|---
Blurry|Blurred | Not sure
Dark|Underexposed | Not sure
Hat|Headwear | Change to headwear (eg, what about hijabs?)
Happy|Joy | Change to joy
Sad|Sorrow | Change to sorrow
Mad|Anger | Change to anger
Surprised|Surprise | Change to surprise

/cc @omaray (since this is beta blocking!)

**Comment by stephenplusplus** [comment]
PR sent: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1858
