### ISSUE TITLE
transition from TravisCI to CircleCI

### ISSUE THREAD

**Issue by danoscarmike** [GoogleCloudPlatform/google-cloud-node#1860]
`[stephen]`
#### To Dos
  - [x] Test against multiple Node versions (4, 6, 7)
  - [x] Exit early if one Node version fails (don't keep testing on the other Node versions)
  - [ ] OS X (requires [reaching out to Circle](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1860#issuecomment-288513381))
  - ~~Deploy to npm after tagged build ([maybe](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1860#issuecomment-286178092))~~

`[/stephen]`

Though we trust that the master branch is building successfully, the build failing on TravisCI with resulting red badge on project level README is not a good experience for our customers.  

Actions: move from TravisCI to CircleCI

Other options for discussion:
1. Change default branch from master; leave master for contributions and ongoing dev.
2. ???

@jgeewax @omaray @jmuk @stephenplusplus @callmehiphop

**Comment by stephenplusplus** [comment]
Related to point 1: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1466 -- quick introduction: when we split up our repo into sub-modules, our README was out of date with `npm install`-reality while we worked to release the sub-modules to npm.

Here's a link to the TL;DR by @jgeewax that has a short discussion that follows: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1466#issuecomment-238344315

Is it an option to simply remove the badge? I'm not sure it communicates anything meaningful to any audience. **Us**: "Oh look at that, Travis is broken again." **Contributors**: "My repo is red all the time on Travis, too!" (or) "Weird, `npm test` worked..." -- **Customers**: "This is broken!" (...but it's not).

If we can get CircleCI to run our builds on-time and accurately reflect master-- as opposed to the latest PR build where build failures are expected during development-- then maybe the badge will have value and provide some accountability for us. But for now, the Travis green badge isn't an award worth winning, considering it would take several hours across multiple days to achieve (seriously).

Here's when things are going well for a *PR build*, which only runs a subset of our tests, not including system tests. This is 1 hour for 1/6 (we now have 8) test VMs to run.

![image](https://cloud.githubusercontent.com/assets/723048/20903604/ed5ac5b8-bb09-11e6-8235-1997b17a7581.png)

--

Proposal: this issue becomes "Move to CircleCI" where we talk through the problems we face while transitioning, and we move the other discussion, re: switching the default branch, to [gcloud-common](https://www.github.com/GoogleCloudPlatform/gcloud-common), as we would probably want to be consistent across languages anyway.

// @jmdobry

**Comment by jmdobry** [comment]
We could quickly switch the badge from being a general Travis badge across all branches to being Travis badge tied to the master branch:

    https://travis-ci.org/GoogleCloudPlatform/google-cloud-node.svg

=>

    https://img.shields.io/travis/GoogleCloudPlatform/google-cloud-node/master.svg

**Comment by stephenplusplus** [comment]
That's definitely what we should have, but in either case, I'm still uncertain the badge is doing anything for us at this point, so I'd rather just ditch it altogether.

**Comment by bjwatson** [comment]
@stephenplusplus Has this already been done?

**Comment by stephenplusplus** [comment]
Not all the way, I'm keeping track with the TODOs in the first post.

**Comment by stephenplusplus** [comment]
Just a status update on this-- publishing to npm after a successful tagged commit is in the works, PR #2058.

**Comment by stephenplusplus** [comment]
A few thoughts on this, though. Here's how the PR currently works:

- User on local machine runs `npm run prepare-release x.x.x` from the module directory, i.e. packages/bigquery
- This uses `npm version` to bump the version in `package.json`, create the git tag, and then push it to master
- CI runs automatically (unit tests, snippet tests, system tests) and publishes to master

Things that make the argument for manual publishing sound better:

- Circle CI only tests Linux, it's not doing OS X (maybe someday) or Windows (that's handled separately through AppVeyor). To have the different build simulators communicate would be necessary to orchestrate a release after all greens.

- CI can easily fail (search "system test flakiness"), which would grind the whole publishing process to a halt. We'd have to manually intervene to publish in this scenario.

- Tagging locally is a bit backwards-- we shouldn't tag until we know all system tests are green. So, assuming we do that-- the user waits for all tests to pass across the different CI platforms before running `npm run prepare-release`-- why wouldn't they just publish it at that time, instead of having CI run all of the tests again?

I'm currently leaning towards manual here, but let me know if you have any ideas for how to proceed.

**Comment by bjwatson** [comment]
FYI @lukesneeringer, since you're looking into similar issues for Python.

**Comment by stephenplusplus** [comment]
There's a monthly fee for testing on OS X with Circle. However, it's apparently free for OSS projects, but someone will need to reach out to them:

> **What if I am building open-source?**
>
> We offer a total of four free linux containers ($2400 annual value) for open-source projects. Simply keeping your project public will enable this for you!
>
> We also offer the Seed plan for OS X open-source projects. Contact us at billing@circleci.com for access. If you are building a bigger open-source project and need more resources, let us know how we can help you!
>
> \- https://circleci.com/pricing/#faq-section-os-x

**Comment by lukesneeringer** [comment]
Is it really important to test specifically on OS X, and is "on push" the right way to do it if so? What is a type of problem that we have gotten that is Darwin-specific?

**Comment by stephenplusplus** [comment]
I would say it's not very important, and I'm not aware of any OS-X specific
issues. I believe the desire originated from @jgeewax.

**Comment by lukesneeringer** [comment]
If it is critical, then I would probably ask that we shift our focus to using CI for unit tests and having GCE instances that run unit and system tests on each type of platform.

But, in the meantime, I assert that Windows + *nix is enough.

**Comment by stephenplusplus** [comment]
I think we're all good for now, then. Hooray!

Opened https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1970 to have a place to talk about the GCE idea.
