### ISSUE TITLE
React Native?

### ISSUE THREAD

**Issue by littletower** [GoogleCloudPlatform/google-cloud-node#1863]
Hi,

Is there a way to make it run with React Native?
I'm running the following code:
```
var datastore = require('@google-cloud/datastore')({
    projectId: 'xxxx',
    keyFilename: '/xxxx-123456.json'
});
var gstore = require('gstore-node');
gstore.connect(datastore);

```

But it gives me the following error:

```
/myProject/node_modules/node-forge/js/forge.js: Deleting local variable in strict mode (53:4)
  at forge.js:53:4
onResponse
    DevServerHelper.java:257
execute
    RealCall.java:126
run
    NamedRunnable.java:32
runWorker
    ThreadPoolExecutor.java:1113
run
    ThreadPoolExecutor.java:588
run
    Thread.java:818
```

Any help would be appreciated :)

Thanks

**Comment by stephenplusplus** [comment]
This is similar to #1821, which reported a bug about our compatibility with webpack. We aren't developing our library for compatibility with these libraries, so any chance of it working is a coincidence. The error being reported is from `forge.js`. Please search around Google & StackOverflow for any clues on how to fix, and if nothing turns up, try reporting on the `node-forge` repository.

If we decide to support being run on React Native, I will ping you to let you know. For now, feel free to continue working around any bugs you find and share your progress here.
