### ISSUE TITLE
GCS Channel documentation has no example of notification

### ISSUE THREAD

**Issue by ngelinas** [GoogleCloudPlatform/google-cloud-node#1866]
The [GCS Channel documentation][0] does not show any example of how the Javascript channel object receives or handles notification.  The [Object Change Notification][1] article shows how an endpoint would receive a notification via a POST request but no Javascript example shows how one is received by the channel.

One can only speculate that the channel object emits a `change` event or perhaps inherits from `ReadableStream`.  Perhaps adding an example of a channel receiving a notification would be helpful.

[0]: https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.5.0/storage/channel
[1]: https://cloud.google.com/storage/docs/object-change-notification

**Comment by stephenplusplus** [comment]
We actually don't have any behavior like that designed around a Channel. I'm not sure if that was because of a technical reason or an oversight. I'll take a look into this.

**Comment by ngelinas** [comment]
Just to clarify, the issue I'm bringing up is that as far as I am aware, Channels are only built into the Node client library and are designed to listen for object change notifications.  My assumption is that they basically just receive the POST request sent by GCS for an object change and turn it into some kind of JSON blob with the meaningful data.

Unfortunately, the only code example involving channels is:
```javascript
var channel = gcs.channel('id', 'resource-id');
```

There's no example of what the presumed JSON blobs would look like or how to receive them.  Based on common Javascript/Nodejs practice, one would imagine something like so to be the design:
```javascript
var channel = gcs.channel('id', 'resource-id');
channel.on('change', function (event) {
  // do something with event.data assuming it's the JSON blob
});
```

Neither the [API][0] nor the [source code][1] show how to handle notifications using the `channel` object.  I hope this clarifies my questions.

[0]: https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.5.0/storage/channel?method=Channel
[1]: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/storage-0.5.0/packages/storage/src/channel.js#L44

**Comment by stephenplusplus** [comment]
I can understand why you expect that to be the functionality of our `Channel` class, but it is in fact just meant to stop an existing channel. As far as I know, a GCS Channel requires an application URL to send POST updates to. We can't act as that application, so that's where our functionality ends.

Let me know if any of those assumptions are incorrect, and we can could in fact offer more through our API.

**Comment by ngelinas** [comment]
Understood.  Thanks for resolving that quite clearly!  If I've understood this correctly, the way for a Node GAE application to subscribe itself to object change notifications would be as follows:

* [Authorize application/endpoint](https://cloud.google.com/storage/docs/object-change-notification#_Authorization)
* Send request to [`Objects: watchAll`](https://cloud.google.com/storage/docs/json_api/v1/objects/watchAll) with own application URL as `address`
* Handle POST requests sent to the application URL from GCS

None of the above would specifically require the Google Cloud Node.js Client lib.  I believe in this case that this issue can be closed.

**Comment by stephenplusplus** [comment]
Yes, that sounds right. I think we could probably add a method to our `File` class to let you create that watcher:

```js
file.createChannel({
  url: '...',
  resourceId: 'resource-id'
}, function(err, channel, apiResponse) {
  // `channel` is a Channel object.
  // channel.stop()
})
```

**Comment by stephenplusplus** [comment]
Woops, I forgot we already have [`bucket.createChannel`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.6.0/storage/bucket?method=createChannel).
