### ISSUE TITLE
vision: include original Likelihood score

### ISSUE THREAD

**Issue by rtw** [GoogleCloudPlatform/google-cloud-node#1881]
It would be great if the likelihood of emotions was send back in the response from the visionClient.detectFaces function. It is useful to the client code so that it can make decisions on the comparison of emotions.

It's intentionally removed replaced with Booleans in the gteLikelihood_ function.

Is there a reason this is done?  Do you want me to update it and submit a pull request?

**Comment by stephenplusplus** [comment]
I agree, we should return that original value. A PR would be *great* and very appreciated! While you're in there, can you keep our current boolean conversion, and simply add back in the `sorrowLikelihood` property? In other words:

```js
vision.detectFaces('image.jpg', function(err, faces, apiResponse) {
  // faces = [
  //   {
  //     ...
  //     confidence: 56.748849,
  //     anger: false,
  //     angerLikelihood: 1,
  //     blurred: false,
  //     blurredLikelihood: 1,
  //     headwear: false,
  //     headwearLikelihood: 1,
  //     joy: false,
  //     joyLikelihood: 1,
  //     sorrow: false,
  //     sorrowLikelihood: 1,
  //     surprise: false,
  //     surpriseLikelihood: 1,
  //     underExposed: false,
  //     underExposedLikelihood: 1
  //   }
  // ]
});
```

Thanks for bringing this up!
