### ISSUE TITLE
How can I ensure template tables inherit the time partitioning of the base table? 

### ISSUE THREAD

**Issue by annalalazaryan** [GoogleCloudPlatform/google-cloud-node#1882]
How can I ensure template tables inherit the time partitioning of the base table?

Thanks!

**Comment by stephenplusplus** [comment]
Hello! I'm not sure, but this should get a quicker/better response over on StackOverflow or even Twitter. Please feel free to link to any post you might make elsewhere, so anyone else who's wondering can follow along.
