### ISSUE TITLE
util.decorateRequest mechanism may edit user provided strings

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#1891]
#### Environment details

  - OS: all
  - Node.js version: all
  - npm version: all 
  - google-cloud-node version: `master`

#### Steps to reproduce

The request mechanism provided used by `Service` and `ServiceObject` go through the request body and modify all occurrences of the string `{{projectId}}` and replace it with the actual project Id.

```js
const translate = require('@google-cloud/translate');
translate.detect('{{projectId}}', (err, results) => {
  console.log(results);
});
```

Output: 
```
{ language: 'fr',
  confidence: 0.15950840711593628,
  input: '{{projectId}}' }
```

It is surprising that the above example discovers **french** in the input string `{{projectId}}`! It does so happen that the actual id for my project on Google Cloud is a Quebecois phrase.

The above example is a bit contrived, but it is possible for user input to happen to contain the string `{{projectId}}`.  This is a real concern for us in the Cloud Debug agent as we capture program state upon user request and send it to the debugger API. It is quite possible for the user application to have the above string, or any other possible string, that will be silently replaced in transit. Other services like Storage, compute or resource might also have plausible failure cases.

I do like the convenience of the projectId placeholder string auto-replaced to the projectId during transit, but this leaves open the _possibility_ that valid user input may get replaced accidentally. It might be a bit less elegant/convenient, but I think we should not use a mechanism that can accidentally edit user provided strings, however unlikely.

**Comment by ofrobots** [comment]
Bump. Any traction on this?

**Comment by stephenplusplus** [comment]
The only thing I can think of is a more randomized string, e.g. `{{projectId + uuid.v1()}}`. Do you have any ideas?

**Comment by bjwatson** [comment]
@stephenplusplus Could we add an optional boolean that says to interpret the string literally, rather than doing auto-replace? Kind of like the difference between `grep` and `fgrep`?

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-common/issues/10.
