### ISSUE TITLE
Not working createRecognizeStream from the recognize.js

### ISSUE THREAD

**Issue by bloodcarter** [GoogleCloudPlatform/google-cloud-node#1892]
It just freezes. Steps to reproduce:
1. Get some audio file.
2. Run recognize.js sync ./yourfile. See the results.
3. Run recognize.js stream ./yourfile. See how the function freezes.

**Comment by stephenplusplus** [comment]
I think this file is coming from another repo. Where is recognize.js? @jmdobry can you move this over to the correct repo?

**Comment by bloodcarter** [comment]
It's originally from https://github.com/GoogleCloudPlatform/nodejs-docs-samples. But what's the difference? The API is the same, right?

@stephenplusplus 
@jmdobry

**Comment by stephenplusplus** [comment]
Well that repo has its own code that could be the problem, not the code here. It's good to know there's an issue, I'm just making sure it's reported in the place that will get the right people to fix it!

**Comment by bloodcarter** [comment]
Yeah, because you have actually quite the same example in this repo. I've spent 2 days without a sleep trying to feed ANYTHING to the Speech API via stream using nodejs, c++ and java (on android) and the only way I got it to work is on android. In both c++ and node js streaming is just NOT WORKING....((((((
```
fs.createReadStream('./audio.raw')
  .on('error', console.error)
  .pipe(speechClient.createRecognizeStream({
    config: {
      encoding: 'LINEAR16',
      sampleRate: 16000
    },
    singleUtterance: false,
    interimResults: false
  }))
  .on('error', console.error)
  .on('data', function(data) {
......
```

**Comment by stephenplusplus** [comment]
We will do our best to resolve this! Thank you for bringing it to our attention.

**Comment by jmdobry** [comment]
I just attempted to reproduce the issue, following these steps (I'm on OS X):

1. `node -v` (printed `v6.9.1`)
1. `npm -v` (printed `3.10.8`)
1. `gcloud beta auth application-default login`
1. `git clone https://github.com/GoogleCloudPlatform/nodejs-docs-samples.git`
1. `cd nodejs-docs-samples/speech`
1. `npm install`
1. `wget https://cloud.google.com/speech/docs/samples/audio.raw`
1. `node recognize.js stream audio.raw`

This is what I got:

```
Data received: {"error":null,"results":"","resultIndex":0,"endpointerType":"START_OF_SPEECH"}
Data received: {"error":null,"results":"","resultIndex":0,"endpointerType":"END_OF_AUDIO"}
Data received: {"error":null,"results":"how old is the Brooklyn Bridge","resultIndex":0,"endpointerType":"ENDPOINTER_EVENT_UNSPECIFIED"}
```
