### ISSUE TITLE
Sorting files by timeCreated

### ISSUE THREAD

**Issue by sachq** [GoogleCloudPlatform/google-cloud-node#1895]
In gcloud NodeJs API client using `bucket.getFiles` Is there an option to sort files according to the `createdDate` or `modifiedDate`? I referred following link, [Gcloud NodeJs Docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.45.0/storage/bucket?method=getFiles), I couldn't find any such option.

**Comment by stephenplusplus** [comment]
I don't believe there is, but if the upstream Storage API allowed sorting options, that would be a nice feature to have.

@Capstan -- is there any place we can make feature requests for the Storage API?

**Comment by stephenplusplus** [comment]
I'll have to close here, but maybe @Capstan heard your suggestion and we'll see it implemented some day! :)

**Comment by Capstan** [comment]
And no, we don't have a public feature request location. Alternate sort orders are requested periodically, but we have no committed plans to introduce it.

**Comment by yash2code** [comment]
> And no, we don't have a public feature request location. Alternate sort orders are requested periodically, but we have no committed plans to introduce it.

interesting. curious to know why.
