### ISSUE TITLE
Duplicate keys in PubSub Message

### ISSUE THREAD

**Issue by tacticurv** [GoogleCloudPlatform/google-cloud-node#1898]
PubSub messages delivered via push model has the following structure.

```
{
    "message": {
        "data": "...",
        "attributes": {...},
        "message_id": "50932420203550",
        "messageId": "50932420203550",
        "publish_time": "2016-12-24T13: 18: 05.093Z",
        "publishTime": "2016-12-24T13: 18: 05.093Z"
    }
}
```
The messageId and publishTime keys are duplicated.

#### Environment details - From where the message was generated

  - OS: Ubuntu 14.04
  - Node.js version: 6.9.2
  - npm version: 3.10.9
  - google-cloud-node version: 0.45.1

#### Steps to reproduce

  1. require `google-cloud`
  2. topic.publish({data : "...", attributes : message}, options, function(err) {
        ...
    });
where message is a JSON object and options have raw enabled to true.

**Comment by stephenplusplus** [comment]
Thanks for reporting. Would you be able to provide a bit more specific steps on how to reproduce, including the value of `message`, as well as how/where to see the duplicated keys?

**Comment by tacticurv** [comment]
The keys inside the data or attributes are not duplicated. It is the the keys defined in the structure of PubSub Message. They come for any message when delivered via push model. If you look at the sample message I have share above it has keys "message_id" and "messageId" which have the same value. Same is the case with "publish_time" and "publishTime".

While the documentation gives the structure as 

```
{
 "message": {
  "attributes": {
   "string-value": "string-value",
   // ... more attributes
  },
  "data": "base64-no-line-feeds-variant-representation-of-payload",
  "message_id": "string-value",
  "publish_time": "string-value",
 },
 "subscription": "string-value"
}

```

**Comment by stephenplusplus** [comment]
Sorry for the very long delay on this. I tried to reproduce this, and here's what I'm seeing. Please let me know what I can do differently to reproduce what you're seeing:

```js
var pubsub = require('@google-cloud/pubsub')()
var topic = pubsub.topic('stephen-topic')

topic.get({ autoCreate: true })
  .then(() => {
    return topic.subscribe()
  })
  .then(([subscription]) => {
    subscription.on('message', msg => {
      console.log(JSON.stringify(msg, null, 2))
    })

    var message = {
      data: {
        userId: 3,
        product: 'book',
        event: 'rent'
      },
      attributes: {
        key: 'value',
        hello: 'world'
      }
    }

    var options = {
      raw: true
    }

    return topic.publish(message, options)
  })
  .then(console.log)
  .catch(console.log)
```
```json
{
  "ackId": "RUFeQBJMPgdESVMrQwsqWBFOBCEhPjA-RVNEUAYWLF1GSFE3GQhoUQ5PXiM_NSAoRRAACBQFfH1xW1V1X10aB1ENGXJ8ZCRuUhVSBkIFKlVYEQ16bVxXOVQIGHR-YHZjWxsJAE1TVo6Hs-JbZho9XxJLLD5-NTI",
  "id": "55163139188280",
  "data": {
    "userId": 3,
    "product": "book",
    "event": "rent"
  },
  "attributes": {
    "hello": "world",
    "key": "value"
  },
  "timestamp": "2017-02-16T19:40:11.015Z"
}
```

**Comment by stephenplusplus** [comment]
@tacticurv I'm going to close since I couldn't reproduce. This could be a case where it sorted itself out over time. But if not, please let me know so we can re-open and resolve it properly. Thanks for reporting.
