### ISSUE TITLE
translate() has no `verbose` option

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1903]
The API response includes the detected language, but there's no way to get that without looking at the raw API response. Could we add a verbose mode (ie, `{verbose: true}`) like several of our other libraries and have it include the translation along with the detectedLanguage code?

**Comment by landrito** [comment]
I am closing this since the verbose option has be swapped to being the default in the other APIs. @lukesneeringer do you know if we should switch translate to having that behavior as well? If so, lets open up a new issue.
