### ISSUE TITLE
Security handshake failed - long queries ( > 2 secs) (nodejs client) 

### ISSUE THREAD

**Issue by pcostell** [GoogleCloudPlatform/google-cloud-node#1905]
_From @VVZen on January 6, 2017 14:33_

Using the _google-cloud_ package, _node v 6_ and _npm-4.0.5_ on my local macOS machine (10.11.6).
When performing a query to the datastore sometimes the database would spit it out **_Security Handshake failed_** logs (more frequently just after rebooting my express server).
After some seconds (3-4), the query is finally resolved.
The errors all look like this:

`E0106 15:08:31.210244000 123145321271296 handshake.c:128] Security handshake failed: {"created":"@1483711711.210211000","description":"Handshake read failed","file":"../src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1483711711.210204000","description":"FD shutdown","file":"../src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}`

Here's a screenshot (after running a query to check if a user existed) :
![security_handshake_error](https://cloud.githubusercontent.com/assets/10340139/21720687/cd26b8cc-d424-11e6-80ad-33f237bb3395.png)

_Copied from original issue: GoogleCloudPlatform/google-cloud-datastore#156_

**Comment by dhermes** [comment]
We've seen the same types of logs leaked from core as well (in `google-cloud-python`)

**Comment by stephenplusplus** [comment]
https://github.com/grpc/grpc/issues/8839 -- maybe we need to configure a back-off setting when we open a gRPC channel: `grpc.initial_reconnect_backoff_ms`.

**Comment by stephenplusplus** [comment]
@jmuk any thoughts on if we should set this value to a higher number for Speech? Or more generally for the other APIs / from another place in the code (gax)?

**Comment by jmuk** [comment]
Oh, I didn't know the third parameter to the constructors.
I don't think this is specific to certain APIs, rather I guess it would be up to the connection between user's environment and the google servers. But yeah, setting some default reconnection_backoff (like 10000) on gax makes sense (also possibly the autogen layer should accept customization of these values).

I am also wondering:

- what would be the best value in this case?
- are there any drawbacks when the value gets bigger?

@murgatroid99 would know the answers, I guess?

**Comment by stephenplusplus** [comment]
Ping @murgatroid99

**Comment by murgatroid99** [comment]
Sorry, I don't know the answers to those questions

**Comment by jmuk** [comment]
In that case, let's leave this value as-is, unspecified.
When #1991 is fixed, users can specify the parameters by themselves.

**Comment by stephenplusplus** [comment]
PR sent: #2007, however I specified it as 5000ms instead of the default 1000ms. Users have been having success with 10000ms, but to play it safe, I went in the middle. Happy to set it to any value you think is appropriate.
