### ISSUE TITLE
PubSub usage example enhancement

### ISSUE THREAD

**Issue by angadn** [GoogleCloudPlatform/google-cloud-node#1906]
It isn't clear that messages need acknowledgement manually by developer. [This page](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.7.0/pubsub/subscription) seems to document this, but it can still be more explicit

**Comment by stephenplusplus** [comment]
An alternative is enabling `autoAck` when creating a subscription, https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.7.0/pubsub?method=subscribe

```js
pubsub.subscribe({ autoAck: true }, function(err, subscription) {})
```

I'm going to close this, but I left a note in our bigger-picture issue, #1084, where we can add a mention of this in the API overview section of our docs (yet to be created for Pub/Sub). If you know of another good place to put this within the docs, e.g. in the description of a method, a PR would be very helpful 👍 

Thanks for bringing this up!
