### ISSUE TITLE
Update "Example Applications" to use google-cloud instead of gcloud

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#1909]
**SCENARIO**
Navigating to the [README](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/README.md) of google-cloud-node, we see an `Example Applications` section showing examples of how to use the module.

**EXPECTED**
The examples should be using the `google-cloud` module (or one of the submodules `@google-cloud/{api}` when appropriate).

**ACTUAL**
It seems like a few of the applications still use the `gcloud` module (see image below). We should hence update the applications to use `google-cloud` instead.

![image](https://cloud.githubusercontent.com/assets/6609430/21776623/3a17be18-d650-11e6-8155-0e73e4624dfe.png)

**Comment by bjwatson** [comment]
@ace-n @callmehiphop This is a P0 issue. What's the status?

/cc @lukesneeringer

**Comment by callmehiphop** [comment]
@bjwatson it's a quick one, I'll have it done EOW.

**Comment by bjwatson** [comment]
Thanks, Dave.

**Comment by callmehiphop** [comment]
@bjwatson @lukesneeringer this should be good now - the only thing that *might* be left is that `gcloud-todos` still has gcloud in the repo name. Not sure if some one wants to rename that or not? I don't think Stephen or I have the permissions to do so.

**Comment by bjwatson** [comment]
Thanks @callmehiphop. You and @stephenplusplus now have access to https://github.com/GoogleCloudPlatform/gcloud-node-todos

**Comment by bjwatson** [comment]
Oh, I see what you're asking for. I'll let @lukesneeringer make that call.

**Comment by lukesneeringer** [comment]
[Renamed.](https://github.com/GoogleCloudPlatform/google-cloud-node-todos)
