### ISSUE TITLE
Speech createRecognizeStream pointer types seem... off?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1913]
When using the createRecognizeStream and events, it seems like the events and endpointerTypes don't make a ton of sense.

```js
var request = {
  config: {
    encoding: 'FLAC',
    sampleRate: 44100
  },
  singleUtterance: false,
  interimResults: false
};

fs.createReadStream('./audiomono.flac')
  .pipe(speech.createRecognizeStream(request))
  .on('data', function(data) {
    console.log(data);
  });
```

In this case, since no interim results were requested, it seems reasonable that you'd get an event only for the resulting transcription -- none of the others. What I actually get is:

```js
{ error: null,
  results: '',
  resultIndex: 0,
  endpointerType: 'START_OF_SPEECH' }
{ error: null,
  results: '',
  resultIndex: 0,
  endpointerType: 'END_OF_AUDIO' }
{ error: null,
  results: 'this is a very cool audio recording it is being handled as a stream',
  resultIndex: 0,
  endpointerType: 'ENDPOINTER_EVENT_UNSPECIFIED' }
```

I'm confused why I'm seeing these extra events (empty start/end events) and then the one I actually care about is "unspecified" ? Why isn't it saying "your transcription is ready" or something like that?

I'm also confused why the `error` field comes through on each event rather than on the 'error' event?

Finally, was there a reason we don't do custom events on this stream...? It seems like we have quite a few different events that might be interesting, but are shoving them all into the 'data' event rather than relying on custom ones like ... audioStart, audioEnd, recognizeResult (interim results), end (final result).

Any thoughts here?

**Comment by stephenplusplus** [comment]
@lukesneeringer since Speech is about to go through the same process as [Vision Partial Veneer](https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2298), is this feature request relevant?
