### ISSUE TITLE
speech.startRecognition should accept buffers

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1914]
What if we have a buffer from somewhere else, but want all the functionality of startRecognize? Shouldn't startRecognize be able to take a readable stream?

**Comment by stephenplusplus** [comment]
Do you mean **`startRecognition`** should be able to take a **Buffer**? You can do this currently under the `content` property:

```js
speech.startRecognition({
  content: new Buffer(['...'])
}, config, function(err, operation) {})
```

**Comment by jgeewax** [comment]
Gotcha. Can we make it just accept a buffer there as well ?

**Comment by stephenplusplus** [comment]
Good call, I think that should be safe to do. Here's the function where we'll add the `if (is.buffer(file)) { ... }` check: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/v0.45.0/packages/speech/src/index.js#L172

**Comment by jgeewax** [comment]
:+1:
