### ISSUE TITLE
Update "gcloud npmjs.com page" to mention it's deprecated

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#1921]
**SCENARIO**
Navigating to the gcloud npmjs.com page shows our old package to our users: https://www.npmjs.com/package/gcloud.

**EXPECTED RESULT**
We need to add a mention at the top of the page that this package is deprecated and we should add a link to the new google-cloud package instead: https://www.npmjs.com/package/google-cloud.

This way if users stumble upon the old gcloud package by mistake they will be redirected correctly to the latest library.

**Comment by omaray** [comment]
This was meant for google-cloud-node - not for ruby.

**Comment by stephenplusplus** [comment]
Done! https://www.npmjs.com/package/gcloud (npm doesn't display emoji or allow much styling at all (alignment, colors), which limited my creative expression)
