### ISSUE TITLE
publishTime not visible on Pub/Sub message from emulator

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1925]
I am testing out `publishTime` and it seems to not be present, at least while using the simulator. The `nanos` field is 0 which makes this check return false: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/pubsub/src/subscription.js#L367

**Comment by stephenplusplus** [comment]
Thanks for the report! This should do:

```diff
- if (publishTime.seconds && publishTime.nanos) {
+ if (is.number(publishTime.seconds) && is.number(publishTime.nanos)) {
```

**Comment by arbesfeld** [comment]
Thanks- should I make a PR?

**Comment by stephenplusplus** [comment]
It's hard to say no to that! 👍

**Comment by psilospore** [comment]
I also don't see publishTime from pubsub messages from the emulator. The docs also don't seem to show the publishTime field: https://cloud.google.com/pubsub/docs/emulator#using_the_emulator

```
{
  "messages": [
      {
          "subscription": "projects/PUBSUB_PROJECT_ID/subscriptions/SUBSCRIPTION_ID",
          "message": {
              "data": "TWVzc2FnZSBudW1iZXIgMQ==",
              "messageId": "10",
              "attributes": {}
          },
          "id": 1
      },
      ...
  ]
}
```

I know this is an old issue so let me know if I should create a new issue.

**Comment by kibertoad** [comment]
@stephenplusplus I think this should be reopened, latest and greatest version of emulator (google/cloud-sdk:547.0.0-emulators) is not populating `publishTime`, which is really messing up testing.

(I would have opened a new ticket, but template is incredibly intimidating)
