### ISSUE TITLE
Google Cloud Speech NodeJS veneer:  Examples in comments don't illustrate needed parameters

### ISSUE THREAD

**Issue by pbogle** [GoogleCloudPlatform/google-cloud-node#1926]
The examples in the comments in the NodeJS veneer won't work because they don't include needed parameters: e.g. the {} values in:
https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/speech/src/v1beta1/speech_client.js#L158

````
 var client = speechV1beta1.speechClient();
  var config = {};
  var audio = {};
  var request = {
      config: config,
      audio: audio
  };
  client.syncRecognize(request).then(function(responses) {
      var response = responses[0];
      // doThingsWith(response)
  }).catch(function(err) {
      console.error(err);
  });


````

**Comment by angadn** [comment]
+1 This was a major problem for me while implementation also, and I resolved it by reading through source-code. My guess is this thing is pretty much still a late-stage alpha

**Comment by stephenplusplus** [comment]
cc: @jmuk @landrito

**Comment by jmuk** [comment]
I see. This sample is auto-generated, and it missed to capture patterns like this. I've filed https://github.com/googleapis/toolkit/issues/941

**Comment by stephenplusplus** [comment]
Thanks, @jmuk!
