### ISSUE TITLE
BigTable mutate promise

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1933]
Looking at https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/bigtable/src/table.js#L903, I'm not sure if this is actually returning a promise as indicated in the documentation?

**Comment by stephenplusplus** [comment]
It does indeed run as a promise, but I can understand how it's a bit confusing. Internally, we write the methods as if a callback is being used, then use a utility function to support both callbacks and promises called `promisifyAll`: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/ae89b8ad6a5915cd516f1d29184a5fbb59830f88/packages/bigtable/src/table.js#L1051

Let me know if you weren't able to use `mutate` as a promise.
