### ISSUE TITLE
ETIMEDOUT errors with Google Cloud Storage

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#1934]
I am seeing a number of ETIMEDOUT errors that seem to be unhandled: https://sentry.io/share/issue/39333433362e323036353431313931/

Here is how I'm using the Google Cloud Storage:

```js
  return new Promise((resolve, reject) => {
    storage.bucket(bucketName).file(fileName).createWriteStream({
      metadata: {
        contentType,
      },
      gzip: true,
      public: true,
      resumable: false,
    })
    .on('error', err => {
      reject(err);
    })
    .on('finish', () => {
      resolve(`https://storage.googleapis.com/${bucketName}/${fileName}`);
    })
    .end(fileBuffer);
```
```js
  const [contents] = await storage.bucket(bucketName).file(fileName).download();
  return contents;
```

Both of these are in try/catch blocks, but it seems like the exception is not bubbling up at all.

**Comment by stephenplusplus** [comment]
I tried to reproduce this using a simulated API server, and got `request` to trigger the same line (https://sentry.io/share/issue/39333433362e323036353431313931/), but the `file.download` callback received the error as expected. Can you re-run this against the latest `@google-cloud/storage` to see if anything may have changed?

**Comment by stephenplusplus** [comment]
@arbesfeld let us know if you're setill having issues.
