### ISSUE TITLE
pubsub documentation - mention that no-listeners means no-auto-acks.

### ISSUE THREAD

**Issue by ozomer** [GoogleCloudPlatform/google-cloud-node#1942]
It's worth mentioning [here](https://github.com/GoogleCloudPlatform/google-cloud-node/blame/master/packages/pubsub/README.md#L33) that when a subscription is created with `autoAck: true`, and all 'message' listeners are removed, the subscription instance will stop acking new messages. i.e. messages are acked iff they are passed to at least one listener, and there is no need to worry about idle (zombie) subscription instances.

This is a good feature - I was worried that it might not be implemented until I checked the code.

**Comment by danoscarmike** [comment]
@ozomer thanks for pointing this out.  Would you like to create a PR to update the docs?

**Comment by ozomer** [comment]
You may open the PR yourself.
Thanks.

**Comment by stephenplusplus** [comment]
We're about to have a pretty big overhaul to the Pub/Sub API. This feature will not be implemented as originally planned. Please stay tuned for the PR / release of the new API.
