### ISSUE TITLE
High CPU usage in cloud storage

### ISSUE THREAD

**Issue by OrlandoCo** [GoogleCloudPlatform/google-cloud-node#1943]
Hello,

Im storing small images less than 80kb to google cloud storage, using this code:

```
var options = {  
  resumable: false,
  validation: 'crc32c',
  public=true
};

bucket.upload('local-image.png', options, function(err, file) {
//Image uploaded
});
```
Everything works as expected, but while uploading the image we get high CPU usage up to 100% in a 4 Vcore machine even with a single file. My nodeJs version is 6.9.4 LTS and my google-coud api is up to date and is running on Ubuntu 16.04 server.

We have tried changing the validation to false without success, it's there something Im missing?

**Comment by bjwatson** [comment]
@OrlandoCo Are you still experiencing this issue? Can you provide evidence that it is the client library that is spiking your CPU usage vs. something else on your system?

Also, are you running this on Google Cloud (App|Container|Compute) Engine, or are you running this elsewhere? I'm asking just to help pin down the source of the problem.

**Comment by OrlandoCo** [comment]
Hello @bjwatson , Yes at the moment we don't have any evidence, but if I have some spare time let me see if I can make a test, but we changed to Azure blob storage and Amazon s3 with their NodeJs API and the same develpment and the CPU never go higher than 20%.

We are running this on a physical development server and in a Linode cloud server both of them running a fresh ubuntu 16.04 server.

**Comment by bjwatson** [comment]
Thanks @OrlandoCo. A direct comparison of Google Cloud Storage against either S3 or Azure doing the same thing on the same platform would be helpful.

**Comment by stephenplusplus** [comment]
If you can find a way to show a comparison and fault towards this library, please let us know. Thanks for the time you've spent on this, @OrlandoCo.
