### ISSUE TITLE
Is there a way to use `access token` to access datastore

### ISSUE THREAD

**Issue by jainanshul** [GoogleCloudPlatform/google-cloud-node#1945]
I have a client side web app that does google login using google login api and as a result I get an access token. I would like that token to authenticate the user to access the datastore without having to hardcode the `service account` information in the code or to write a server component that interacts with datastore on webapp's behalf.

**Comment by salrashid123** [comment]
see issue https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1346

**Comment by jainanshul** [comment]
Suggestions as #1346 didn't work and frankly look hacky. I resorted to REST API calls and added autorization header to all the request. Pretty primitive but gets the job done.

**Comment by stephenplusplus** [comment]
This is not currently supported, but please follow #1346 to track the feature request.
