### ISSUE TITLE
Support HttpRequest property of LogEntry

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/google-cloud-node#1959]
The v2 logging API supports a top-level HttpRequest property that is separate from the payload:

https://cloud.google.com/logging/docs/api/reference/rest/v2/LogEntry#httprequest

Maybe this could be a special property added to the `metadata` argument?

Would be useful for the Winston transport PR (#1830) and the Bunyan transport lib (https://github.com/mlazarov/bunyan-stackdriver/).

**Comment by danoscarmike** [comment]
@ofrobots can you review this?  Is this useful to you?

**Comment by ofrobots** [comment]
@zbjornson to make sure my understanding is correct, are you proposing that `logging` *automatically* adding the 'current request' to all the log entries that happen to occur on behalf of that request? Or are you proposing an API or contract on Log Entry that would look at a specially named property on the metadata and use it format the `HttpRequest` field of the proto message?

**Comment by zbjornson** [comment]
@ofrobots sorry for being unclear -- I just want a way to be able to set the `HttpRequest` properties from the logging API. Maybe something like:

```js
var entry = log.entry({
  resource: { ... },
  httpRequest: { /* this is what I want to access */ }
}, logEntryPayload);
```

(Think that's the second thing you described.)

This could be something that your new Winston and Bunyan transports populate automatically, but otherwise I don't think the `log.entry` method behavior should change unless the user adds the `httpRequest` property explicitly (i.e. don't auto-populate it from the payload).

**Comment by stephenplusplus** [comment]
@zbjornson I think we support this currently the same way your example shows. Did we add that feature and forget to tag & close this issue, or is our code (which looks like it will support `httpRequest`) not actually working?

**Comment by stephenplusplus** [comment]
I'll close this, since I think we figured it out and forgot to close this issue.
