### ISSUE TITLE
grpc: duration & timestamp encoding/decoding support

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#1960]
Would be nice if we had better support for encoding/decoding durations and timestamps so the user could supply either a Date object or a number as opposed to an object with `seconds` and `nanos` keys supplied.

**Comment by stephenplusplus** [comment]
@callmehiphop would this still be a useful tool, or did our conversion to GAPIC eliminate this a bit?
