### ISSUE TITLE
Twitter feed style queries

### ISSUE THREAD

**Issue by thisbejim** [GoogleCloudPlatform/google-cloud-node#1962]
What might be the most efficient approach for querying a twitter style feed with the datastore? e.g. you have a Kind of `User` and `Status`:

Creation of User key:
```
datastore.key(['User', userId])
```

Creation of Status key:
```
datastore.key(['Status', statusId, 'User', userId])
```

Then each User has a `following` property that is an array of userIds of the people they follow. What would be the most efficient way to query for all statuses from all users that someone is following? 

For example, if you are using postgres/sequelize you can do something like:
```
const statuses = await Status.findAll({
  order: [['createdAt', 'DESC']],
  where: {
    // following is an array of userIds
    userId: following,
  },
});
```

What would be the equivalent using the node datastore?

**Comment by stephenplusplus** [comment]
Hey, good question! I think this is better suited for StackOverflow where fellow Datastore users could see the question and contribute. http://stackoverflow.com/questions/tagged/google-cloud-datastore If you find out anything interesting, feel free to update us!

**Comment by thisbejim** [comment]
[Stackoverflow thread](http://stackoverflow.com/questions/42045831/twitter-feed-style-queries-with-node-datastore).

**Comment by thisbejim** [comment]
Hey @stephenplusplus, the stackoverflow thread has not received any attention from the wider community, could you please share your opinion on the issue? Chances are, given that you are a contributor to this project, that you have the most appropriate experience to give guidance.

**Comment by thisbejim** [comment]
For anyone reading this later I recommend avoiding datastore/cloud as your platform of choice if you are looking to build something like a news feed, the datastore just isn't equiped to make efficient queries across multiple entities because there are no OR operators, e.g. you can't do something like:

```
followers = [userIds];
const query = datastore.createQuery('Status');
// query statuses by userId, only = available, need to able to apply each filter
// as an or equals
followers.map(id => query.filter('userId', '=', id));
const result = await db.runQuery(query);
```

To achieve a twitter like feed you would have to create multiple separate queries, which means you lose the ability to do pagination which is crucial to a functional feed.
