### ISSUE TITLE
Pub/Sub topic.get promise does not return a value nor an error

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-node#1967]
Reposting from a user forum question: 
I am trying to create\get a topic with the following code:

```js
var winston = require('winston');
var pubsub = require('@google-cloud/pubsub')({
  projectId: config.get("GCLOUD_PROJECT")
});

function createTopicPromise(topicName) {
  winston.info("Trying to create pubsub topic: " + topicName);
  return Promise.race([pubsub.topic(topicName).get({
    "autoCreate": true
  }).then(topicAndMore => topicAndMore[0]), new Promise((resolve, reject) => {
    setTimeout(() => {
      reject(new Error("pubsub topic creation timeout"));
    }, 30000);
  })]).catch(err => {
    winston.error("Failed to create topic " + topicName + ": " + err + " - retry in 1 sec");
    return new Promise(resolve => {
      setTimeout(() => resolve(createTopicPromise(topicName)), 1000);
    });
  }).then(topic => {
    winston.info("pubsub topic: " + topicName + " created successfully");
    createdTopicNames.add(topicName);
    return topic;
  });
}
```

The 30 seconds timeouts happen again and again - the topic.get promise does not return a value nor an error.

Any suggestions?
#### Environment details

  - OS:
  - Node.js version: pubsub 0.8.0
  - npm version:
  - google-cloud-node version:

#### Steps to reproduce

  1. require `google-cloud`
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by kir-titievsky** [comment]
More detail from the user: 


We are using the flex environment (linux?).
Node.JS version 4.5.0, not sure which npm version runs there.

We installed @google-cloud/pubsub directly (i.e. the dependencies contain: "@google-cloud/pubsub": "0.8.0"), so I don't know which "google-cloud" version is used.

Code works on my computer but not in the cloud.

**Comment by stephenplusplus** [comment]
This issue with hanging requests is being looked at under #1955.

**Comment by besummering** [comment]
I encounter the same issue with node v6.9.5. Can I know how this issue was resolved ?

**Comment by stephenplusplus** [comment]
@besummering can you open a new issue with a new description of the code you're using and the expected/actual outcomes? The issue template will also ask for environment details which will be helpful when debugging as well.
