### ISSUE TITLE
[Language] remove 'verbose' flag

### ISSUE THREAD

**Issue by jmuk** [GoogleCloudPlatform/google-cloud-node#1969]
An internal feedback pointed out about the verbose flag in the language API client. We don't have to do things like this on client-side, and just pass the response data to the users.

Note that this might affect some documents too. For example, `detectSentiment`'s response is not a number, but an object with `magnitude` and `score`.

**Comment by stephenplusplus** [comment]
Duplicate: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1782
