### ISSUE TITLE
Run tests in docker-node runtime

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-node#1970]
We have a bug this week pop up that could have been caught by running tests against the nodejs-docker runtime we use for App Engine:
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1955

Would it be possible to run the tests for this repo inside of that container, just to do a sanity check?

**Comment by JustinBeckwith** [comment]
cc @ofrobots @jmdobry

**Comment by landrito** [comment]
Closing: The Circle CI Version that we are using does not support the use of docker images.
