### ISSUE TITLE
Images API

### ISSUE THREAD

**Issue by MicronXD** [GoogleCloudPlatform/google-cloud-node#1971]
I'd like to voice my support for the inclusion of the [Images API](https://cloud.google.com/appengine/docs/python/refdocs/google.appengine.api.images) which is currently only available in the Standard Environment. I understand Tasks are on their way, and there are surely other features being prioritized. I hope to see the Images API soon prioritized, too.

**Comment by stephenplusplus** [comment]
Thanks! I see you've voted for the issue on our API tracker: #1338 -- anyone who sees this, feel free to vote!

**Comment by MicronXD** [comment]
@stephenplusplus, should I post *Images API* by itself in #1338?
I'd like someplace to direct others who are interested in the Images API where their vote won't be confused for a vote for Search.

**Comment by MicronXD** [comment]
(The Images API doesn't appear by itself. It's in a post bundled with Search)

**Comment by stephenplusplus** [comment]
Got it sorted, make sure your votes are correct! 👍
