### ISSUE TITLE
double leading slash when uploading a file to a bucket

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/google-cloud-node#1972]
#### Environment details

  - OS: GKE
  - Node.js version: 7
  - npm version: 4.0.5
  - google-cloud-node version: "@google-cloud/storage": "^0.5.0"

#### Steps to reproduce

```js
const bucket = Storage().bucket('gs://my-name')
const file = bucket.file('/foo/bar/lol.txt')
const readStream = fs.createReadStream('./lol.txt')
const writeStream = file.createWriteStream({ metadata: { contentType: 'text/plain' } })
readStream.pipe(writeStream)
```
Given the above code it uploads a file at `gs://my-name//foo/bar/lol.txt`

**Comment by stephenplusplus** [comment]
The bucket name should simply be `my-name`, not its URL:

```diff
- const bucket = Storage().bucket('gs://my-name')
+ const bucket = Storage().bucket('my-name')
```

And same for the file method:
```diff
- const file = bucket.file('/foo/bar/lol.txt')
+ const file = bucket.file('foo/bar/lol.txt')
```

With these changes, the file uploaded should land at: `gs://my-name/foo/bar/lol.txt`.

I don't think it'd be a big change if our library auto-removed any leading slashes from the input to `bucket.file()`, but given the explanation above of the correct way to use these methods, do you think it's necessary?

**Comment by kilianc** [comment]
@stephenplusplus I was using only `my-name` indeed, I messed up while trying to extract the use case.

> given the explanation above of the correct way to use these methods, do you think it's necessary?

Since I am not feeding the library anywhere a double leading slash it is very strange that this is the outcome. I mean `my-name` + `/foo` -> `my-name/foo`. I understand the other way around where in case of a missing leading slash it's assumed the user means root.

In my opinion this is straight up a bug, I can't think of anybody that needs to upload a file to `something//file.txt` IMHO.

🍻

**Comment by stephenplusplus** [comment]
You're right, that is weird. I'll mark as `help wanted`, so if anybody wants to strip leading `/` from within the `File` constructor, please help!

**Comment by stephenplusplus** [comment]
Oh, and 🍻

**Comment by kilianc** [comment]
I am looking at the code, I'll def try to help
