### ISSUE TITLE
Pubsub - Set timeout on ack method

### ISSUE THREAD

**Issue by askmon** [GoogleCloudPlatform/google-cloud-node#1979]
#### Environment details

  - OS: Ubuntu 14.04
  - Node.js version: 4.4.2
  - npm version: 2.15.9
  - google-cloud-node version: 0.46.2

For some reason, this past week, I started to see that some of my messages were not being acked/delivered, and I have to wait for the ack deadline, as in this image: 
![image](https://cloud.githubusercontent.com/assets/711732/22829823/811bd462-ef8b-11e6-80e8-aa5b77ba57e4.png)

I tried updating pubsub but wasn't successful.

I'd like to be able to set a timeout on `ack` request, so after some time it'd give me an error and I'd be able to retry the ack.

I found this on stackoverflow: http://stackoverflow.com/questions/41901108/acked-messages-are-lingering-at-the-google-pubsub it's very similar to what happens to me, but I don't know how I'd change the grpc behavior like this....

**Comment by stephenplusplus** [comment]
Thanks for reporting. As you've noticed, this currently isn't possible. To support, we would just need to allow an `options.timeout` property to the `ack` method, which we would pass through to gax. PR welcome if you're up for it!

**Comment by stephenplusplus** [comment]
Fixed in #2042.
