### ISSUE TITLE
Add configurable buffering to logging

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#1981]
It would be nice to have optional buffering in the the `logging` client library so that all the higher level layers (e.g. `logging-winston` and `logging-bunyan`) and users don't have to build this independently.

Ref: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1977#issuecomment-278805590

@stephenplusplus Thoughts?
/cc @cristiancavalli

**Comment by stephenplusplus** [comment]
Since we use gRPC, which keeps an open channel, is batching still beneficial?

**Comment by ofrobots** [comment]
My understanding, as per the [quota policy](https://cloud.google.com/logging/quota-policy) for Stackdriver Logging, the number of `write` calls are counted. Whether each of the calls go over the same channel wouldn't affect this, I expect.

@zbjornson has practical experience with the quota.

**Comment by stephenplusplus** [comment]
This convo started to sound familiar. Let me re-open https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1296
