### ISSUE TITLE
system test setup instructions out of date?

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#1982]
From https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/.github/CONTRIBUTING.md:

```
$ gcloud preview datastore create-indexes system-test/data/index.yaml
```

1. I think `preview` can be dropped now.
2. I cannot find the file `system-test/data/index.yaml`. I am guessing that this isn't the same as `./packages/vision/system-test/data/index.yaml`?

**Comment by stephenplusplus** [comment]
That file should actually be moved to the `packages/datastore/system-test/data/` directory. It looks like it got misplaced when we modularized the repo. PR? :)

**Comment by ofrobots** [comment]
Sure. But even after running the `create-indexes`, I get the following error with the `logging` system tests:

```
  1) Logging sinks should create a sink with a Bucket destination:
     Uncaught Error: The caller does not have permission
      at node_modules/grpc/src/node/src/client.js:434:17
```

I do have $GCLOUD_TESTS_PROJECT_ID and $GCLOUD_TESTS_KEY set to valid values.

**Comment by stephenplusplus** [comment]
I think the create indexes command will only relate to the Datastore tests.

For the Logging test, that's a new issue. I can reproduce that as well. That used to happen for me when we were developing it, but it hasn't since. @callmehiphop can you see if you get that error?
