### ISSUE TITLE
Add support for IN queries

### ISSUE THREAD

**Issue by bryanerayner** [GoogleCloudPlatform/google-cloud-node#1986]
This is a feature request, not a bug.

When can we expect support for IN queries in datastore.query.filter?

It would greatly simplify development. Is there documentation on what would be required to implement this feature? Seems like it should boil down to a slightly different change to a GRPC call, or is it more complicated than that?

**Comment by stephenplusplus** [comment]
Unfortunately, there isn't a way to do this yet. Last time this was brought up (#1376), it got bounced to the Datastore repo (issue: [Support the IN, OR, != operators in queries](https://github.com/GoogleCloudPlatform/google-cloud-datastore/issues/36)). According to that issue, the feature is still missing.

**Comment by simoami** [comment]
@stephenplusplus Just want to weigh in and said I'm another user blocked by lack of support for IN, OR and NE. I'm working on a connector for the loopback framework, while also using in a project. Looking at the google-cloud-datastore project, it seems to be specific to Java and Python. Is the Node version dependent any of them? If yes, then I understand.

Thanks

**Comment by stephenplusplus** [comment]
Yes, unfortunately. We can only talk to the Datastore API that exists today, and this feature isn't available to us.

**Comment by bryanerayner** [comment]
What would it take to add the support? This is a blocking issue for me - my options at this point are to either suffer from extremely inefficient queries, or to re-write a wrapper for the Datastore API which uses GRPC to talk to a "real" Datastore API in Java. Both are bad choices - If there could be a community contribution to add the IN operator support, I would be happy to be a part of that.

**Comment by stephenplusplus** [comment]
Having your help would be great. As far as I know, there isn't anything we can do yet, since the feature isn't in the Datastore API that the Datastore team is developing. Any information about its development needs to come from them.
