### ISSUE TITLE
logging-winston and logging-bunyan should deal with circular objects

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#1987]
Originally raised here: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1977#issuecomment-278743604

Related: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1983, https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1354

**Comment by ofrobots** [comment]
@stephenplusplus  I don't have the power to self-assign this.

**Comment by ofrobots** [comment]
To be clear, unlike @google-cloud/logging, the higher level layers for winston and bunyan should erase circularity.

**Comment by ofrobots** [comment]
I have been thinking of a way to do this that wouldn't be highly inefficient. As things stand today, `Entry.prototype.toJSON` already does two walks of the full object graph:

1. Upfront check for`isCircular`, and throw if it is.
2. The serialization via `Service.objToStruct_`.

Doing another object walk in the higher level `winston` and `bunyan` layers seems highly suboptimal.

What would be nicer, would be if I could customize the `objToStruct_` walk when the Entry has been constructed through the higher level layers.

There are two ways I can see for doing this:

1. Add a new property to entry that encodes behaviour (throw vs. erase) upon encountering a circular reference.
2. Given me a mechanism where I can hand you a pre-serialized Entry object with a `jsonPayload`.

Thoughts?

**Comment by zbjornson** [comment]
I feel like it's common for users to want logging to "just work" even if it's on a best-effort basis; I don't think many people want to add try/catch and error handling for logging. So, from a general perspective, option 1 sounds nice.

**Comment by ofrobots** [comment]
@stephenplusplus thoughts?

**Comment by stephenplusplus** [comment]
Option 1 works for me. `options.removeCircular`, default false. (better options name welcome, especially if there is prior art)
