### ISSUE TITLE
logging-{winston,bunyan} should integrate well with Logging UI and with Error Reporting

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#1989]
Originally raised here https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1977#issuecomment-278743604.

**Comment by danoscarmike** [comment]
@ofrobots can you confirm that this is does not change the surface?

**Comment by ofrobots** [comment]
@danoscarmike Do you mean if this is a semver major change on the `logging` API?

Actually the concrete pull request fixing this issue is here: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1997

This does not affect the `logging` module API at all. It is a behaviour change in how the `logging-winston` and `logging-bunyan`modules format messages, but this still isn't a semver major change. These said modules are still marked 'experimental' so this should be okay.

**Comment by gaofanmichael** [comment]
This issue was moved to googleapis/nodejs-logging-bunyan#5
