### ISSUE TITLE
Travis CI builds failing

### ISSUE THREAD

**Issue by jcking** [GoogleCloudPlatform/google-cloud-node#1994]
Travis CI builds are failing as newer versions of Node.js require C++11 support. The default environment for Travis CI is Ubuntu precise which has an older version of GCC prior to C++11 feature completeness. Moving to Ubuntu trusty should be good enough, this can be done via the beta described at https://docs.travis-ci.com/user/trusty-ci-environment/. Just have to had "dist: trusty" to .travis.yaml.

**Comment by jmuk** [comment]
The C compiler is necessary just because gRPC stops distributing their precompiled binary modules for Node 0.12. cc @murgatroid99
And also I'm wondering if we could drop Node 0.12 itself from Travis CI -- that version is already out of the support -- related to #1855 in a sense. cc: @ofrobots

**Comment by jcking** [comment]
Ah, so its mainly a side effect of not distributing the precompiled binaries. Are we going to rely on precompiled binaries for dependencies going forward, it seems like as node versions are dropped or as gRPC stops providing precompiled binaries for a specific version, this will become an issue again.

It should be noted that gRPC still states they support 0.12 and above, oddly. Though they are not providing precompiled binaries for 0.12.

**Comment by murgatroid99** [comment]
That's actually just outdated information in the README. We no longer support Node 0.12 or older.

**Comment by jcking** [comment]
Willing to accept a pull request updating the README?

**Comment by murgatroid99** [comment]
sure

**Comment by jcking** [comment]
Filed https://github.com/grpc/grpc/issues/9707 for the cleanup of remaining Node.js 0.12 references in gRPC. Will continue related chatter there.

**Comment by stephenplusplus** [comment]
Thank you for reporting, but we're [dropping Travis](https://github.com/GoogleCloudPlatform/google-cloud-node/pull/18741874) and generally don't rely on it for our day to day operations.
