### ISSUE TITLE
Documentation Fix : logging.log.entry metadata has wrong object format

### ISSUE THREAD

**Issue by eighteyes** [GoogleCloudPlatform/google-cloud-node#1996]
## Overview

Documentation Object Inconsistencies

### Working 
https://googlecloudplatform.github.io/google-cloud-node/#/docs/logging/0.7.0/logging
Describes the entry metadata.
 ```js
var resource = {
  type: 'gce_instance',
  labels: {
    zone: 'global',
    instance_id: '3'
  }
};
```

### Breaking 
https://googlecloudplatform.github.io/google-cloud-node/#/docs/logging/0.7.0/logging/entry
Wraps it in a resource key.
```js
var metadata = {
  resource: {
    type: 'gce_instance',
    labels: {
      zone: 'global',
      instance_id: '3'
    }
  }
};
```

## Reproduction
```js
 var metadata = {
  resource: {
    type: 'gce_instance',
    labels: {
      zone: 'global',
      instance_id: '3'
    }
  }
};
  var logFn = logging.log('sysout');
  var entry = logFn.entry(metadata, {
     msg: 'abc123'
  });
  logFn.write(entry, cb)
```

Throws the following protobuf error
```
Uncaught Error: .google.api.MonitoredResource#resource is not a field: undefined
```

## Resolution
Unwrapping the `resource` key from the field seems to be key here. This form also exists in the `logging.entry` doc, but I'm not sure what is intended there.

**Comment by callmehiphop** [comment]
@stephenplusplus based on https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1666 I think that the documentation is correct but code is not working as expected. Can you confirm that we did not revert those changes at some point?

**Comment by stephenplusplus** [comment]
Yeah, it is meant to work as shown in the `After` section of #1666.

@eighteyes I actually get the opposite behavior that you describe from a fresh install of @google-cloud/logging@0.7.0. Can you try un- and re-installing to be sure you're using the latest version?

**Comment by eighteyes** [comment]
Yes, I think this was it.

**Comment by stephenplusplus** [comment]
Phew 👍
