### ISSUE TITLE
Cloud DNS polling on change status? (change is almost like an LRO)

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#1999]
In Cloud DNS, when I create a change on a zone, I get back a Change -- which should have been a long-running operation, but isn't. This means that I can't easily attach a handler to "should the status of this change, run this callback".

Can we treat a dns#Change resource the same way as a long-running operation? And allow hooking up callbacks to those with some polling something?

**Comment by danoscarmike** [comment]
Pending DNS library support

**Comment by stephenplusplus** [comment]
@danoscarmike we do have support for DNS in the library via @google-cloud/dns.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-dns#10
