### ISSUE TITLE
bigquery: complete system tests

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2000]
Here's what we need to hit.

References:
- [C# tests](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/ExhaustiveTypesTest.cs)
- [`schema.json` and test data](https://gist.github.com/stephenplusplus/d9a0b1733a57381026b6222df5a60639)

| Data type                                | Queries (Legacy) | Queries (Standard) | tabledata.list | tabledata.insertAll | Creating a table | Query Params (Beta) |
|------------------------------------------|------------------|--------------------|----------------|---------------------|------------------|---------------------|
| scalar value columns                     |                  |                    |                |                     |                  |                     |
| repeated scalar value columns            | N/A (flattened)  |                    |                |                     |                  |                     |
| record value columns                     | N/A (flattened)  |                    |                |                     |                  |                     |
| repeated record value columns            | N/A (flattened)  |                    |                |                     |                  |                     |
| record value inside another record value | N/A (flattened)  |                    |                |                     |                  |                     |
| repeated value within a record value     | N/A (flattened)  |                    |                |                     |                  |                     |
| timestamp (UTC)                          |                  |                    |                |                     |                  |                     |
| datetime (no time zone)                  | N/A?             |                    |                |                     |                  |                     |
| date                                     | N/A?             |                    |                |                     |                  |                     |
| time                                     | N/A?             |                    |                |                     |                  |                     |
| bytes                                    | N/A?             |                    |                |                     |                  |                     |

**Comment by tswast** [comment]
As much as I'd love to have them, since query parameter support is still in beta, you can consider the query parameter system tests as not GA blocking.
