### ISSUE TITLE
Write more integration tests for BigQuery

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#2002]
Please see email I sent about the details and test cases from @tswast . 

Also, C# has [some examples](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.BigQuery.V2/Google.Cloud.BigQuery.V2.IntegrationTests/ExhaustiveTypesTest.cs) that might be worth looking at.

/cc @jskeet @jba @tswast @danoscarmike

**Comment by stephenplusplus** [comment]
Dupe of #2000 :)
