### ISSUE TITLE
Documentation for Transaction.deleteRows() does not match behavior

### ISSUE THREAD

**Issue by modeswitch** [GoogleCloudPlatform/google-cloud-node#2008]
Docs claim that if a callback is omitted, a Promise is returned (see: https://googlecloudplatform.github.io/google-cloud-node/#/docs/spanner/0.1.0/spanner/transaction?method=deleteRows).

When invoked without a callback, nothing is returned. See: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/7ba12d080b499e5461ba51f9e08d559d6c41aaaa/packages/spanner/src/transaction-

**Comment by stephenplusplus** [comment]
Thanks for catching this and reporting. It looks like those docs could use a sweep, as `transaction.deleteRows()` doesn't do anything asynchronously, it just queues the delete request until `transaction.commit()` is called. I've sent #2009 with the fixes. Sorry for the confusion.
