### ISSUE TITLE
Using delimiter "/" returns empty file list

### ISSUE THREAD

**Issue by maheshiv** [GoogleCloudPlatform/google-cloud-node#2010]
I have gone through this documentation https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.47.0/storage/bucket?method=getFiles to get the list of directories by passing delimiter "/". But it returns an empty list. If I did not pass delimiter, I can get all the files

```js
let opt = {
  delimiter: "/" 
};
bucket('samplebucket').getFiles(opt, (err, files, nextQuery, apiResponse) => {
    if (err) {
      console.log('Error', err);
      return res.send(400, err);
    } else {
      console.log(files); //Returns empty array [];
     console.log(apiResponse); //Returns undefined;
    }
  });
```
I am using lates google-cloud node module (V 0.47)

**Comment by stephenplusplus** [comment]
To get the list of directories, you'll have to turn off autoPagination:

```js
bucket.getFiles({
  delimiter: '/',
  autoPaginate: false
}, onGetFilesResponse)

function onGetFilesResponse (err, files, nextQuery, apiResponse) {
  if (err) {
    console.error(err)
    return
  }

  apiResponse.prefixes // ['your-folder/', 'your-other-folder/']

  if (nextQuery) {
    // More results exist. Run query again:
    bucket.getFiles(nextQuery, onGetFilesResponse)
  }
}
```

Related document on getting directories: https://cloud.google.com/storage/docs/json_api/v1/objects/list

**Comment by maheshiv** [comment]
Thanks @stephenplusplus. But in the documentation, it does not say about auto-paginate.

**Comment by LoicMahieu** [comment]
Thanks @maheshiv for pointing this issue.

Using this library for the first time in typescript and async / await, I did not see that.
Would be great to mention in documentation these inconsistency in promise and callback style.

Related to #2556

Thanks!
