### ISSUE TITLE
Why doesn't @google-cloud/common-grpc depend on modelo

### ISSUE THREAD

**Issue by matthewloring** [GoogleCloudPlatform/google-cloud-node#2011]
This appears to be intentional since it is mocked out in the tests: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/common-grpc/test/operation.js#L56. However, while experimenting with the `speech` api I get:

```
Error: Cannot find module 'modelo'
      at require (internal/module.js:12:17)
```

I have observed this on node v4.7.3. It is not a problem when installing with a version of `npm` that flattens dependencies since `modelo` is an official dependency of `@google-cloud/common`.

**Comment by stephenplusplus** [comment]
This was a bug, thanks for reporting. @google-cloud/common@0.1.5 released.

(ref: https://github.com/GoogleCloudPlatform/google-cloud-node/commit/972d043ae4b886ef0eabfa742770bbf8311c6796)

**Comment by matthewloring** [comment]
Thanks for the quick fix!

**Comment by ofrobots** [comment]
How did this leak to a release? Is there a test process that would catch similar issues in the future?
