### ISSUE TITLE
Spanner - Deleting rows with a composite key

### ISSUE THREAD

**Issue by angadn** [GoogleCloudPlatform/google-cloud-node#2023]
This line seems to be the cause of the problem - https://github.com/GoogleCloudPlatform/google-cloud-node/blob/bc0503e46b7fcea0ce3274b6d8dd31c7eef4dd1d/packages/spanner/src/transaction-request.js#L284

IMHO, given that monotonically increasing keys are discouraged, the lack of table operations upon composite keys (`String[][]`, not just `String[]`!) is a _major_ limitation. Even a quick-fix for this will be highly appreciated

**Comment by stephenplusplus** [comment]
Thanks for reporting! Any interest in sending a PR?

**Comment by angadn** [comment]
Absolutely - I gave it a good shot but struggling to figure out the appropriate structures expected by gRPC :-(

What's the expected value type for a composite key? I tried a list value but no luck

**Comment by richtera** [comment]
Same problem here. It's almost like the protobuffer implementation only reads single strings but the client code seems to be constructing the correct nested KeySet when using an array of arrays as the keys property.

**Comment by richtera** [comment]
Got a workaround. using deleteRows for each row and passing the keys as the main array (i.e. the composite keys) will delete the correct row.

**Comment by angadn** [comment]
I could swear I'd tried this and it didn't work 😞 could you please share your usage snippet?

Thanks in advance!

**Comment by richtera** [comment]
```javascript
    // NOTE all keys need to be strings. So for date I had to pass a ISO format timestamp.
    const rows = [{ key1: 'a', key2: 'b', key3: 'c' }, {key1: 'a2', key2: 'b2', key3: 'c3'}];
    database.runTransaction((err, transaction) => {
        rows.forEach(item => {
          console.log('delete', item.key1, item.key2, item.key3);
          transaction.deleteRows('builds', [item.key1, item.key2, item.key3]);
        });
        transaction.commit().then(data => {
          console.log(data);
          process.exit(0);
        }).catch(err => {
          console.error(err);
          process.exit(1);
        });
      });
```

**Comment by angadn** [comment]
@richtera Best run this by @stephenplusplus, but I'd given it a shot with something similar to this (traveling at the moment, so unable to test this but hope it helps!)

At [line 279](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/spanner/src/transaction-request.js#L279):

    mutation['delete'] = {
        table: table,
        keySet: {
          keys: arrify(keys).map(function(val) {
            return {values: commonGrpc.Service.encodeValue_(val)};
          })
        }
    };

If your snippet is working, then this should fix the problem altogether - again, as far as I remember this had failed me. I ended up giving up and going with Datastore instead.

**Comment by richtera** [comment]
It definitely works for me. But the caveat is that any values being sent in have to be strings. So if your key set contains a TIMESTAMP or INT64 make sure to send string equivalents to the keys array. This definitely caused a hiccup on my side. Essentially the values being sent in are used as query values and not update values.

**Comment by angadn** [comment]
@richtera Crap - just realised mine hadn't worked because I was passing an array-of-arrays, and you're passing an array of objects (key being the column name). Will make a PR for this fix as soon as time permits

**Comment by richtera** [comment]
Yea that's what I mean with "workaround" normally array of arrays makes sense, but doesn't work.

**Comment by stephenplusplus** [comment]
PR sent over in #2141.
