### ISSUE TITLE
Google Storage API Doc: File.makePrivate copy needs work

### ISSUE THREAD

**Issue by ashwinputhige** [GoogleCloudPlatform/google-cloud-node#2029]
It currently has the following text.
```
$/, ''), // Remove trailing slashes. name: name, id: '?GoogleAccessId=' + credentials.client_email, exp: '&Expires=' + expiresInSeconds, sig: '&Signature=' + encodeURIComponent(signature), type: responseContentType || '', disp: responseContentDisposition || '', gen: self.generation ? '&generation=' + self.generation : '' });

```

API is here - https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/0.6.0/storage/file?method=makePrivate .

**Comment by stephenplusplus** [comment]
Thanks for reporting. Fixed in https://github.com/GoogleCloudPlatform/google-cloud-node/commit/0384c799dbfea5f06c042e1920ac69308e4cfdd7 -- I'm pretty sure JSDoc was getting a false positive from the contents of our regex, which looked like the start of a JSDoc block (`(/\/*$/, '')`)

**Comment by callmehiphop** [comment]
Fixed per https://github.com/GoogleCloudPlatform/google-cloud-node/commit/0384c799dbfea5f06c042e1920ac69308e4cfdd7
