### ISSUE TITLE
Vision API detectText returns TypeError: formatMethodMap[type] is not a function

### ISSUE THREAD

**Issue by clarenceh** [GoogleCloudPlatform/google-cloud-node#2034]
#### Environment details

  - OS: MacOS
  - Node.js version: 7.6.0
  - yarn version: 0.21.3
  - @google-cloud/vision version: 0.8.0

#### Steps to reproduce

I have a testing script with sample images that worked before (i.e. successfully get the ocr text response). However, today I am having the same issue as reported in #1333 again.

Code:
```js
let vision = require('@google-cloud/vision')({
  projectId: 'my-expense-keeper',
  keyFilename: './keyfile/keyfile.json'
});

import { Observable } from '@reactivex/rxjs';

const fs = require('fs-extra');

// const types = ['labels'];
// const types = ['faces'];
// const types = ['logos'];
const types = ['text'];

const obj = fs.readJsonSync('./test-files/receipt-image-req-1.json', {throws: false});

// console.log(JSON.stringify(obj));

let buffer = new Buffer(obj.content, 'base64');

let visionObs = Observable.fromPromise(vision.detect(buffer, types));

visionObs.subscribe(
  data => {
    console.log(`Cloud vision api response: ${JSON.stringify(data)}`);
    process.exit(1);
  },
  err => {
    console.log(`Cloud vision api error: ${JSON.stringify(err)}`);
  }
);
```

Where the content is base64 encoded image content.

When run the above code with type set to 'labels', I can get the following response:
```json
[
  [
    "text",
    "label",
    "document"
  ],
  {
    "responses":[
      {
        "labelAnnotations":[
          {
            "mid":"/m/07s6nbt",
            "description":"text",
            "score":0.9377162
          },
          {
            "mid":"/m/05c0n6k",
            "description":"label",
            "score":0.591876
          },
          {
            "mid":"/m/015bv3",
            "description":"document",
            "score":0.5269188
          }
        ]
      }
    ]
  }
]
```

When run the above code with type set to 'labels', I can get the following error:
```
/Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:538
          return formatMethodMap[type](annotation, options);
                                      ^
TypeError: formatMethodMap[type] is not a function
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:538:39
    at Array.map (native)
    at decorateAnnotations (/Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:548:16)
    at Array.map (native)
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:409:10
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/vision/src/index.js:133:5
    at Object.handleResp (/Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/common/src/util.js:135:3)
    at /Users/clarence/workspace/mek/mek-image-api/node_modules/@google-cloud/common/src/util.js:466:12
    at Request.onResponse [as _callback] (/Users/clarence/workspace/mek/mek-image-api/node_modules/retry-request/index.js:120:7)
    at Request.self.callback (/Users/clarence/workspace/mek/mek-image-api/node_modules/request/request.js:186:22)
```

I have attached the image that I am using for your reference.

Thanks!
Clarence
![receipt-image-1](https://cloud.githubusercontent.com/assets/2868803/23456210/70fdefee-fead-11e6-8720-63d20dd31b0b.jpg)

**Comment by devhaoy** [comment]
Have the exact same issue since a few hours ago!

**Comment by huseyinkozan** [comment]
Same here

**Comment by jrusuarez** [comment]
We are having the same issue. Happening for all images that contain text. We were forced to disable the service in production.

**Comment by stephenplusplus** [comment]
@jmuk

**Comment by calibr** [comment]
looks like this PR does a trick https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2035, any way to fix this issue except patching the lib? or just wait for the lib to be updated?

**Comment by EQuimper** [comment]
+1

**Comment by stephenplusplus** [comment]
Vision has updated its API. I'm about to merge the code to handle the changes and we'll do some insta-releasing. Sorry for the trouble, everyone.

**Comment by nicklucking** [comment]
I'm having the same issue as well :) glad i found this thread.

**Comment by SellJamHere** [comment]
All for one and one for all! 👍

**Comment by patobrien** [comment]
Also seeing this issue while using https://www.npmjs.com/package/gcloud 

Line numbers are different but error char location is the same.

BTW @stephenplusplus do you plan to update gcloud 0.47?

**Comment by stephenplusplus** [comment]
`gcloud` is deprecated, but we will update the bundled package, `google-cloud`: https://www.npmjs.com/package/google-cloud

**Comment by callmehiphop** [comment]
Hey everyone, I've published a fix for this in [`@google-cloud/vision@0.8.1`](https://www.npmjs.com/package/@google-cloud/vision), please feel free to upgrade and let us know if the issue persists. Thanks!

**Comment by EQuimper** [comment]
I've test it and that worked :) @callmehiphop thank you :)

**Comment by vinz** [comment]
I've tested it too,.. It is working! Thanks @callmehiphop :)

**Comment by mengkez** [comment]
I got the same problem today. @callmehiphop How can I upgrade the google-cloude/vision? Thank you!

**Comment by lukesneeringer** [comment]
`npm install @google-cloud/vision@0.8.1`

**Comment by MYoung25** [comment]
@callmehiphop it looks like this may have resurfaced.  Your update worked beautifully for me until this morning.

I have double- and triple-checked that I'm actually running 0.8.1
