### ISSUE TITLE
Adding Speech_Context to the Speech API stops Recogniztion

### ISSUE THREAD

**Issue by LibertyBeta** [GoogleCloudPlatform/google-cloud-node#2036]
It seems that the Speech Context config breaks the recognition stream. 

#### Environment details

  - OS: *nix(Raspian, Ubuntu, etc)
  - Node.js version: 7.5
  - npm version:
  - google-cloud-node version: 0.6

#### Steps to reproduce

  1. require `google-cloud`
  2. Start Recognition Stream with a config values of 
  ```
const request = {
    config: {
        encoding: encoding,
        sampleRate: sampleRate,
        speech_context: ['one', 'two]
    },
    interimResults: true
};
```
 3. `.pipe()` audio stream to the Recognition Stream

**Comment by jmuk** [comment]
Looks like your code specifying `speech_context`, but that should be `speechContext`?
Did you know what happens on the recognition streams? Is there any errors reported?

**Comment by stephenplusplus** [comment]
@LibertyBeta I believe @jmuk caught the issue with `speech_context` vs `speechContext`, but please let us know if this is still an issue.

**Comment by arnoldad** [comment]
Actually, this does not seem to be resolved (at least in version 0.9.0 from npm)-trying to supply the speech context any which way results in the following error for me:

`Error: .google.cloud.speech.v1.RecognitionConfig#speechContext is not a field: undefined`

**Comment by stephenplusplus** [comment]
We started using v1 of the Speech API (compared to v1beta1 previously), and it looks like it expects an array for `speech_context` now: https://github.com/googleapis/googleapis/blob/2b761d5190e3de4764fb58c312286ae043aec02d/google/cloud/speech/v1/cloud_speech.proto#L215

That would mean:

```js
const request = {
  config: {
    encoding: encoding,
    sampleRateHertz, sampleRateHertz,
    profanityFilter: true,
    speechContexts: [
      {
        phrases: ["dog", "cat"]
      }
    ],
    languageCode: languageCode
  }
}
```

Sorry for the trouble. I opened an issue to fix our links in the docs: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2219

**Comment by arnoldad** [comment]
Thanks for the quick reply. I can confirm that this works as expected with the @google-cloud/speech NPM module version 0.9.0
