### ISSUE TITLE
Unable to insert row in Spanner where column type is FLOAT64 and value is integer

### ISSUE THREAD

**Issue by modeswitch** [GoogleCloudPlatform/google-cloud-node#2048]
My table has a FLOAT64 column, however some of my values happen to be integers (no fractional part). When I try to write these values, I get an error `Invalid value for column X in table Y: Expected FLOAT64`. If I add `0.0001` to each value before writing then the inserts are successful.

**Comment by jmuk** [comment]
@stephenplusplus -- is there a way to explicitly specify a float number here?

**Comment by stephenplusplus** [comment]
@vkedia - I'm experimenting with creating a `spanner.double()` method. The resulting API request sends the proto as:

```
{
  "insert": {
    "table": "Singers",
    "columns": [
      "SingerId"
    ],
    "values": [
      [
        {
          "numberValue": 8
        }
      ]
    ]
  }
}
```

An error is returned from the API:

```
Error: Row [8] in table Singers.
```

However, sending `8.1` as the value, the API request succeeds. Any idea if I'm making a simple mistake?

**Comment by vkedia** [comment]
Can you not set it to 8.0? I am not sure why 8 does not work. I will try to find out.

**Comment by stephenplusplus** [comment]
I think it's just a JavaScript thing: https://jsconsole.com/?8.0

**Comment by modeswitch** [comment]
Correct. If you want to test for `float` in JS you can do something like `!(Number.isNaN(n) || Number.isInteger(n))`.

Perhaps this is naive, but if you pass a `numberValue` to the Spanner API, shouldn't it be able to coerce an integer into a float?

**Comment by stephenplusplus** [comment]
@vkedia -- any preference how I should move forward with this?

**Comment by vkedia** [comment]
We do want people to be able to store a value like 8.0 in the database. I am surprised that sending 8 does not work. Can you do some magic to set it to 8.0 in the proto for now till I figure out whats going on with the backend?

**Comment by vkedia** [comment]
Oh I just realised this 8 vs 8.1 thing is a red herring. The error you got means that the row already exists in the table. Can you try with some other value which does not exist?

**Comment by stephenplusplus** [comment]
We're in business! Thank you.
