### ISSUE TITLE
google cloud spanner is closing connection

### ISSUE THREAD

**Issue by nor-bu** [GoogleCloudPlatform/google-cloud-node#2049]
I running my api based on swagger and node.

When my api is running for few minutes without a request and then i send an api request to it, I got this error:

```
{ Error: {"created":"@1488097564.272436000","description":"Delayed close due to in-progress write","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":406,"grpc_status":14,"referenced_errors":[{"created":"@1488097564.272434000","description":"Endpoint read failed","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1851,"occurred_during_write":1,"referenced_errors":[{"created":"@1488097564.272350000","description":"Secure read failed","file":"../src/core/lib/security/transport/secure_endpoint.c","file_line":166,"referenced_errors":[{"created":"@1488097564.272347000","description":"Socket closed","fd":24,"file":"../src/core/lib/iomgr/tcp_posix.c","file_line":249,"target_address":"ipv4:172.217.19.10:443"}]}]}]}
    at ClientReadableStream._emitStatusIfDone (/Users/aronsuarez/Code/asate/admin-apis/wiki-admin-api/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientReadableStream._readsDone (/Users/aronsuarez/Code/asate/admin-apis/wiki-admin-api/node_modules/grpc/src/node/src/client.js:169:8)
    at readCallback (/Users/aronsuarez/Code/asate/admin-apis/wiki-admin-api/node_modules/grpc/src/node/src/client.js:242:12) code: 14, metadata: Metadata { _internal_repr: {} } }
```
I think google spanner is closing the connection, why and how can prevent it from to that?

The only way that i see in the docs is to send periodically a SELECT 1 request to spanner.

Is this correct?

System Info:
node. 6.10.0
os: macOS latest
package: latest

Thanks for help

**Comment by vkedia** [comment]
You should not need to periodically sent Select 1 to spanner. This seems like underlying socket closing.
@callmehiphop @stephenplusplus Any ideas whats going on here.

**Comment by callmehiphop** [comment]
Possibly related to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2039

**Comment by jmuk** [comment]
@murgatroid99 any ideas about grpc options in this situation?

**Comment by vkedia** [comment]
Any updates on this?

**Comment by murgatroid99** [comment]
Actually, we just released gRPC 1.2.0, which should fix this problem

**Comment by lukesneeringer** [comment]
Closing as fixed in GRPC.

**Comment by nor-bu** [comment]
I have tested with the "@google-cloud/spanner" - 0.1.2 package and it dosen't work. This is the error

`(node:74588) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: {"created":"@1490192388.326156000","description":"Transport closed","file":"../src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1072}`

**Comment by lukesneeringer** [comment]
What version of GRPC do you have installed?

**Comment by nor-bu** [comment]
How can i check this, i have only installed the spanner package for node.

**Comment by lukesneeringer** [comment]
`npm list | grep grpc`

**Comment by nor-bu** [comment]
Version 1.1.2, this is the problem, i think this is installed with the spanner package correct?

**Comment by lukesneeringer** [comment]
The Spanner package uses `^` to tag its dependencies; `grpc` is a dependency of `@google-cloud/common-grpc@0.2.1`, and a new install correctly installs grpc 1.2.0.

Basically: Update your dependencies. :-)
