### ISSUE TITLE
Error: 403 User Rate Limit Exceeded

### ISSUE THREAD

**Issue by sahilbabbar** [GoogleCloudPlatform/google-cloud-node#2051]
Hi, 

Is it true that without a paid account the translation API will continue throwing the following error: 
```
code: 403,
  errors: 
   [ { message: 'User Rate Limit Exceeded',
       domain: 'usageLimits',
       reason: 'userRateLimitExceeded' } ],
  response: undefined,
  message: 'User Rate Limit Exceeded' }
```

**Comment by stephenplusplus** [comment]
@jmuk should this be the error returned from the Translate API?

**Comment by stephenplusplus** [comment]
According to the [FAQ](https://cloud.google.com/translate/faq):

> **Is there any free quota?**
>
> No, the Google Cloud Translation API is only available as a paid service. Please see [Pricing](https://cloud.google.com/translate/pricing) for more details.

Let me know if there's anything else we can help with.
