### ISSUE TITLE
Intermittent BigQuery failures

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2052]
Our [system test](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/d193dd5c5e0e59c3ae57bcb0c1bb652ec1287e05/packages/bigquery/system-test/bigquery.js#L504) which validates that we return a `PartialFailureError` when invalid data is inserted into a table.

The schema states that the `name` property must be a string.

Our request body looks like this:
```json
{
  "rows": [
    {
      "json": {
        "name": "dave"
      }
    },
    {
      "json": {
        "name": 11
      }
    }
  ]
}
```

The response is either:
```js
// incorrect (frequent)
{
  kind: 'bigquery#tableDataInsertAllResponse'
}

// correct (infrequent)
{
  "kind": "bigquery#tableDataInsertAllResponse",
  "insertErrors": [
    {
      "index": 1,
      "errors": [
        {
          "reason": "invalid",
          "location": "name",
          "debugInfo": "generic::invalid_argument: Conversion from int64 to string is unsupported.",
          "message": "Conversion from int64 to string is unsupported."
        }
      ]
    },
    {
      "index": 0,
      "errors": [
        {
          "reason": "stopped"
        }
      ]
    }
  ]
}
```

The first I noticed this error was Friday, 3/3/17.

@tswast any ideas? Thanks!

**Comment by tswast** [comment]
Nothing obvious to me. I'll pass this on to the BQ eng team.

**Comment by Splaktar** [comment]
Yes! This seems like what we're seeing as well!

Ever since we've updating to the google-cloud-node version that first introduced `PartialFailureError ` we've been having problems. The docs are very insufficient in how to handle these cases.

The [BigQuery table docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/bigquery/table?method=insert) are not correct with regards to the Promise handling:
```
table.insert(rows).then(function(data) {
  var insertErrors = data[0];
  var apiResponse = data[1];
});
```
Should be:
```
table.insert(rows).then(function(data) {
  var apiResponse = data[0];
  var insertErrors = data[1];
});
```

That said, why would you handle errors in the `then/success` function and not in `catch()`?

**Comment by Splaktar** [comment]
Here's what we're seeing in our logs:
```javascript
(node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 8): PartialFailureError: A failure occurred during this request.

data: [{"kind":"bigquery#tableDataInsertAllResponse"}]
apiResponse: {"kind":"bigquery#tableDataInsertAllResponse"}
insertErrors: undefined
```

I have been pulling my hair out trying to figure out how to get the `insertErrors` and then what should I do if there is an error?

With google-cloud-node v0.41.2, all of our BigQuery inserts succeeded. Now just by upgrading to google-cloud-node v0.47.0, v0.48.0, or v0.49.0, we're seeing a bunch of `PartialFailureError`s. It doesn't make any sense at all to us.

**Comment by stephenplusplus** [comment]
Well, I can say it hasn't been exactly obvious if a partial failure is an "error" in terms of how Node callbacks/promises historically have worked. A partial failure could mean 1/1000 requests failed, so communicating the whole API call as a failure can be misleading. 

Is it possible in versions prior to when we introduced PartialFailureError, you were considering the lack of presence of an "err" argument as a 100% success?

**Comment by stephenplusplus** [comment]
This is a Trobleshooting Errors document we link to in our docs: https://cloud.google.com/bigquery/troubleshooting-errors

**Comment by Splaktar** [comment]
We've been seeing the `PartialFailureError`s since 2/19 and had to roll back to the old google-cloud-node since it was causing our GAE Flex to spin up 20 instances and peg them all to 100% CPU. We've since fixed the CPU/instance issue, but we're still seeing a lot of `PartialFailureError`s and we never get any kind of indication why anything failed or what rows failed since `insertErrors` is never defined.

Our old code did this:
```
public insert(rows: T): Promise<boolean> {
    return new Promise((resolve, reject) =>
      this.table.insert(rows, {}, (error) => {
        error ? reject(error) : resolve(true);
      })
    );
  }
```
Then on the Promise we have:
```
.catch((error) => {
      throw new Error(`[${os.hostname()}] Error inserting into bigQuery for key: "${listing.key}": ${error}`);
    });
```

This seems like it would report to us any and all errors previously (which we did not see).

**Comment by stephenplusplus** [comment]
It doesn't look like that old code would have returned errors, since they were previously returned through the 'insertErrors' argument and not through the 'err' argument. The err, back then, was for request failures like 404, 503, but didn't include insertErrors.

So, I think like you said, you're also experiencing these intermittent failures, but they are coming from BQ's API and not ours. Unless there's another way we're supposed to be sending the requests than we do: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/bigquery/src/table.js#L1059

**Comment by Splaktar** [comment]
The [BigQuery table docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/bigquery/table?method=insert) have this `if (err.name === 'PartialFailureError') {` which doesn't seem to make sense to me given the data structure:
```
      kind: string,
      insertErrors: [
        {
          index: number,
          errors: [
            {
              reason: string,
              location: string,
              debugInfo: string,
              message: string
            }
          ]
        }
      ]
```

**Comment by Splaktar** [comment]
>It doesn't look like that old code would have returned errors, since they were previously returned through the 'insertErrors' argument and not through the 'err' argument. The err, back then, was for request failures like 404, 503, but didn't include insertErrors.

Ah, that's good to know! Thank you. Good in the way that we're not crazy, but not so good in that we've always been loosing data...  ugh.

**Comment by Splaktar** [comment]
The [BigQuery table docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/bigquery/table?method=insert) also refer to the following:
```
// insertErrors.errors (object[]):
// insertErrors.errors[].row (original row object passed to `insert`)
// insertErrors.errors[].errors[].reason
// insertErrors.errors[].errors[].message
```
But `insertErrors.errors[i].row` doesn't seem to be valid since `errors` only contain:
```
           {
              reason: string,
              location: string,
              debugInfo: string,
              message: string
            }
```

**Comment by stephenplusplus** [comment]
⚠️ This is a guess ⚠️ 

I believe the BigQuery API rolled out a fix for int64's not converting to strings, and it wasn't fully rolled out, which is why I was having intermittent failures. I can't be sure of this, but I haven't been able to get it to fail for a long enough amount of time to assume it "just works" now.

However, it *will* fail when I try to provide a boolean value with:

"Conversion from bool to string is unsupported."

I'm getting that consistently enough to assume that's not a feature BigQuery has, so I can assume the test should always fail.

> But `insertErrors.errors[i].row` doesn't seem to be valid since `errors` only contain:
```
           {
              reason: string,
              location: string,
              debugInfo: string,
              message: string
            }
```

Do you mean `insertErrors.errors[i].row.errors` is not an array, but is the object above?

**Comment by Splaktar** [comment]
I meant that `insertErrors.errors[].row` seems to be `undefined`.
Also `insertErrors.errors[].errors[]` from the docs would be `undefined`.

So from the docs, it seems like `insertErrors.errors[].row` should be removed and `insertErrors.errors[].errors[].message` should be `insertErrors.errors[].message`.

**Comment by stephenplusplus** [comment]
This is how it's documented:

```
function insertHandler(err, apiResponse) {
  if (err) {
    // An API error or partial failure occurred.

    if (err.name === 'PartialFailureError') {
      // Some rows failed to insert, while others may have succeeded.

      // err.errors (object[]):
      // err.errors[].row (original row object passed to `insert`)
      // err.errors[].errors[].reason
      // err.errors[].errors[].message
    }
  }
}
```

This is a real-world use of a PartialFailure error such as the one demonstrated in the example above: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/70682b180af42b3c56ecd08ac5353774b2e433a2/packages/bigquery/system-test/bigquery.js#L516

```js
table.insert([data, improperData], function(err) {
  assert.strictEqual(err.name, 'PartialFailureError');

  assert.deepEqual(err.errors[0], {
    errors: [
      {
        message: 'Conversion from bool to string is unsupported.',
        reason: 'invalid'
      }
    ],
    row: improperData
  });

  assert.deepEqual(err.errors[1], {
    errors: [
      {
        message: '',
        reason: 'stopped'
      }
    ],
    row: data
  });

  done();
});
```

**Comment by Splaktar** [comment]
Ah, yes those docs were updated. Of course I'm using Promises, so the code doesn't quite look like that. I'll open a separate issue for documentation issues related to BigQuery in google-cloud-node.

**Comment by stephenplusplus** [comment]
Going to close since we fixed the issue in our test. Not sure if the upstream API needs any work, or [if my guess was correct](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2052#issuecomment-287190801), but either way, nothing to do in GCN.
