### ISSUE TITLE
Bigtable API failure: cannot use SSDs

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2053]
We just started receiving this failure:

> Error: Transaction Failed : Transaction cannot complete : Your project can't use SSD nodes in this zone. Contact cloud-bigtable-feedback@google.com to request the capability.

(https://circleci.com/gh/GoogleCloudPlatform/google-cloud-node/199)

This doesn't happen with my project, but it does for our system tests project (`long-door-651`).

**Comment by jmuk** [comment]
cc: @danoscarmike

**Comment by stephenplusplus** [comment]
cc @lukesneeringer / ping @danoscarmike -- CI still unhappy aboutthis one.
