### ISSUE TITLE
Feature Request: BigQuery Promise API

### ISSUE THREAD

**Issue by MarkHerhold** [GoogleCloudPlatform/google-cloud-node#2074]
It appears that that BigQuery calls don't return promises. It would be great if it would.

**Comment by stephenplusplus** [comment]
This works for me with `@google-cloud/bigquery@0.8.0`

```js
var bigquery = require('@google-cloud/bigquery')()
bigquery.getDatasets().then(console.log)
```

What version of what module are you using?

**Comment by MarkHerhold** [comment]
The latest version. I looked at the docs again and it clearly mentions "If the callback is omitted, we'll return a Promise." on the query docs. Sorry about that.

**Comment by stephenplusplus** [comment]
No problem, just glad we got it sorted out!
