### ISSUE TITLE
#1990 seems to be breaking File.save

### ISSUE THREAD

**Issue by q42jaap** [GoogleCloudPlatform/google-cloud-node#2078]
#1990 is breaking my code:
I'm getting an error which is suppressed by makeAuthenticatedRequest.
The error which is suppressed: `value.hasOwnProperty is not a function` which is triggered on the line:
https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1990/files#diff-4ddf84f5cae46867fbddaf62136f04c3R521

The object `value` is looks something like this
<img width="287" alt="screen shot 2017-03-14 at 01 53 46" src="https://cloud.githubusercontent.com/assets/114642/23881186/2033ca24-0859-11e7-9314-2cecf7ccf528.png">

Reverting to 0.47.0 fixes this for me.

I'm doing a File.save (from the storage module).

The config for storage is `{projectId: '...'}`. I'm using the credentials provided by de gcloud sdk.

**Comment by stephenplusplus** [comment]
This is fixed in @google-cloud/storage (dupe #2070), but a new version of `google-cloud` hasn't been released yet. We'll be doing that tomorrow, but if you need a solution in the meantime, you can use `@google-cloud/storage` directly. Sorry for the trouble and thank you for reporting.
