### ISSUE TITLE
Module documentation is not being generated

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2079]
CircleCI currently builds pushes documentation updates to our gh-pages branch after a successful merge to master. However, nothing runs on a tagged commit. I believe something like this will work:

```sh
# scripts/circle/post-test.sh

if [ "${CIRCLE_TAG}" != "" ]
then
  # handle tags like `vision-0.6.0`
  # TODO: handle tags like `v0.34.0`
  export TAGGED_MODULE_NAME=${CIRCLE_TAG/-*}
  export TAGGED_MODULE_VERSION=${CIRCLE_TAG/*-}
fi

npm run prepare-ghpages $TAGGED_MODULE_NAME $TAGGED_MODULE_VERSION
```

@callmehiphop could you take a crack at this?

**Comment by stephenplusplus** [comment]
I believe we'll also need to trigger builds based on tags as described here: https://circleci.com/docs/1.0/configuration/#tags

**Comment by stephenplusplus** [comment]
@callmehiphop have you done anything with this? I'll take it if you haven't... or in 20 minutes, whichever comes first :)

**Comment by callmehiphop** [comment]
I have not!
