### ISSUE TITLE
Test top 4 APIs on GAE Flex, GKE, and GCP

### ISSUE THREAD

**Issue by omaray** [GoogleCloudPlatform/google-cloud-node#2080]
Test BigQuery, Storage, Datastore, and Logging client libraries on all the GCP platforms (don't include GAE Standard).

- [ ] GAE Flex
- [ ] GCE VM
- [ ] GKE

Close this issue once we confirm it all works.

**Comment by stephenplusplus** [comment]
GCP === GCE VM?

**Comment by jmuk** [comment]
I heard @lukesneeringer is working for Python, the same idea will be applied to Node.

**Comment by omaray** [comment]
Yes! My mistake. GCP means GCE VM.

**Comment by lukesneeringer** [comment]
I did do this.
