### ISSUE TITLE
Datastore - TTL like MongoDB (entities expiration)

### ISSUE THREAD

**Issue by VVZen** [GoogleCloudPlatform/google-cloud-node#2088]
As a feature request, it would be nice if there was a way to set an **expiration time** for entities.
In this way reset password tokens _(and many other things)_ would be a lot cleaner to implement using Datastore.

Thanks

**Comment by stephenplusplus** [comment]
Do you know if this feature in Datastore, and we just don't expose configuration of it? Or would this be a new feature for Datastore? (If so, we'll move it to a better repo for visibility)

**Comment by VVZen** [comment]
I don't know if other clients have this feature, but since I didn't find any mention to it I think they don't.
So maybe it would be better to move it directly to the Datastore repo!

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-datastore#165

**Comment by stephenplusplus** [comment]
Cool, moved! I'm subscribed in the new issue, so if there's anything we can do, we will re-open and add the feature here.
