### ISSUE TITLE
Corrupt download - Lines missing for special characters in PDF

### ISSUE THREAD

**Issue by kriffe** [GoogleCloudPlatform/google-cloud-node#2092]
Special characters in some pdf files (text with stream-section) result in missing lines when downloaded. No error produced. Suspect that something is terminating the stream from inside the content.

#### Environment details

  - OS: Windows/Centos 6.5
  - Node.js version: v4.4.5
  - npm version: 3.9.6
  - @google-cloud/storage version: 0.8

#### Steps to reproduce

```js
//Download stream_test.txt 

var gcs = require('@google-cloud/storage')({
  projectId: "abc123",
  keyFilename: './key.json'
});

var bucket = gcs.bucket('my-testbucket');

bucket.file('stream_test.txt').download().then(function(data){
	var item = data.toString();
	var split = item.split("\n");
	console.log("Expect 292 lines");
	console.log(split.length);
}).catch(function(err){console.log(err);});

//Stream file that results in missing lines (Part of PDF)
```
[stream_test.txt](https://github.com/GoogleCloudPlatform/google-cloud-node/files/848294/stream_test.txt)

**Comment by kriffe** [comment]
Facing the samme issue with data upload for save. But this can be fixed by conversion to binary. See example below.

`
var content = loadMyTestFileAsString();
var contentBuffer = new Buffer(content.toString("binary"),"binary");

var testfile = bucket.file('stream_test_upload.txt','utf-8');
testfile.save(contentBuffer,function(err){
	if (err){
		console.log(err);
	}
	else{
		console.log("Success!")
	}
});`

**Comment by stephenplusplus** [comment]
I ran some tests, and it seemed like things are working as expected:

```js
'use strict'

var assert = require('assert')
var fs = require('fs')
var storage = require('@google-cloud/storage')()

var bucket = storage.bucket('stephen-has-a-new-bucket')

var localFileContent = fs.readFileSync('./stream_test.txt')

// TEST 1: Upload, download, confirm same data
var uploadedFile = bucket.file('stream_test_uploaded.txt')

uploadedFile.save(localFileContent, function(err) {
  if (err) throw err

  uploadedFile.download(function(err, data) {
    if (err) throw err

    assert.deepStrictEqual(localFileContent, data)
  })
})

// TEST 2: Upload via GCS Console, download, confirm same data
var manuallyUploadedFile = bucket.file('stream_test.txt')

manuallyUploadedFile.download(function(err, data) {
  if (err) throw err

  assert.deepStrictEqual(localFileContent, data)
})
```

Are these tests not catching your issue somehow?

**Comment by kriffe** [comment]
Thank you for the fast reply. You are correct. There is nothing wrong with the data transfer. 

The issue seems to lay in the data conversion from Buffer to string (intended target base64). But that is a totally different issue. Have to figure out the right encoding suitable for PDF it seems.

```
var localFileContent = fs.readFileSync('./stream_test.txt')
var string = localFileContent.toString();
```
