### ISSUE TITLE
Info on optimistic locking perhaps ? 

### ISSUE THREAD

**Issue by walshe** [GoogleCloudPlatform/google-cloud-node#2095]
re google datastore - No info here about optimistic locking - e.g if there is some built in timestamp/version property for this e.g. when one reads, changes some properties and then saves - to be sure they were the last writer to the entity.

how are multiple processes supposed to be able to update different fields of an entity wothout inadvertently overwriting someone elses changes ?

example would be good

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - google-cloud-node version:

#### Steps to reproduce

  1. require `google-cloud`
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
This sounds like when you want to use Transactions-- is that an incorrect assumption?

We document that here: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/datastore (search "Transactions") as well as on its own page: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/datastore/transaction

**Comment by walshe** [comment]
@stephenplusplus  

Lets say they first transaction1 reads an entity {key:1, prop1:"bla", prop2:'foo'}.

Now transaction 2 reads that same entity {key:1, prop1:"bla", prop2:'foo'}

transaction 1 changes prop1 to '' and commits .  saved entity is {key:1, prop1:"", prop2:'foo'}.

transaction 2 now changes prop2 to '' and commits, now saved entity is {key:1, prop1:"bla", prop2:''} 


so transaction1's changes are lost

or have I missed something. Is the api smart enough to recognize an error when transaction2 tries to commit ?

**Comment by stephenplusplus** [comment]
Yes, I believe the API will bounce the second transaction if the data is not the same as it was when it started. Here's the official doc on Transactions: https://cloud.google.com/datastore/docs/concepts/transactions

**Comment by walshe** [comment]
@stephenplusplus 

I thought the transaction was mainly for making sure all or none of the statements inside it were applied. One would think it would mention the optimistic lock mechanism if there was one. How does it work , does each entity have an implicit timestamp or something ? I was looking in the src code for the node library but didn't see anything that made me think there was such a feature. Would be goog to get official word from someone in @google-admin

**Comment by stephenplusplus** [comment]
Would you mind posting this on StackOverflow using these tags: http://stackoverflow.com/questions/tagged/google-cloud-platform%20node.js%20google-cloud-datastore

It's more likely to get a response from a relevant Googler than here. Please link us and we will re-open and address this if there is more for us to do.

**Comment by walshe** [comment]
http://stackoverflow.com/questions/42842467/is-there-optimistic-locking-in-google-datastore-node-api @stephenplusplus
