### ISSUE TITLE
Inserting Date values into Spanner date column fails

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2097]
What I want to do:

```js
myTable.insert({id: 1, start_date: new Date(1976, 4, 1)}).then(function (data) {
  console.log(data);
});
```

What I have to do instead :(

```js
myTable.insert({id: 1, start_date: '1976-04-01'},).then(function (data) {
  console.log(data);
});
```

Can we make dates do "the right thing" ? Or is that not possible?

**Comment by stephenplusplus** [comment]
It is honored as a `TIMESTAMP` currently. We also have `spanner.date('08-08-08')` for `DATE`.

**Comment by jgeewax** [comment]
What about `spanner.date()` that takes the same constructor as `new Date()` ? Or even a date?

I imagine that I get a date as an actual JS date somehow, and want to put that into Spanner in a `DATE` column. In this world I'd have to... call `spanner.date(dateformat(mydateval, ...))` which makes me sad.

At the very least I'd like to be able to do `spanner.date(mydateval)` and have it do the right thing. Can we do that?

**Comment by vkedia** [comment]
Yeah I agree it would be nice to have a constructor on spanner.Date which takes the individual fields.

**Comment by lukesneeringer** [comment]
According to the [documentation][] and the [code][], `spanner.date()` already coerces a Date properly (in fact, it coerces strings to dates, not _vice versa_).

  [documentation]: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/spanner/src/index.js#L101
  [code]: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/spanner/src/codec.js#L28-L34

**Comment by lukesneeringer** [comment]
It also looks like [dates are encoded](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/spanner/src/codec.js#L155-L160). Does a `spanner.date` work and a `Date` not work? If so, we could fix it by changing line 156 to `value = new SpannerDate(value).value`.

**Comment by jgeewax** [comment]
The code linked here leads me to believe that the string representation (or the date representation) will work, but it *won't* handle the same parameters that `new Date` does.. but this may be for the best.

In code...

```js
// Copy and paste in the definition (spanner.date is promisified weirdly)
> function SpannerDate(value) {
...   if (is.undefined(value)) {
.....     value = new Date();
.....   }
... 
...   this.value = new Date(value).toJSON().replace(/T.+/, '');
... }
undefined
> new SpannerDate('2016-01-01').value
'2016-01-01'

// But, the you can't use the same arguments, since it only looks at the first:
> new SpannerDate(2016, 1, 1).value
'1970-01-01'
> new SpannerDate(2016).value
'1970-01-01'

// But then... it seems that Javascript is pretty stupid with the Date constructor...
> new Date(2016, 1, 1).toJSON()   // Months are zero-indexed, but days are not...
'2016-02-01T05:00:00.000Z'

// And I guess it's crazy to expect JS to say "nah you can't put in garbage crazy dates".
// In true JS style, it treats the second argument as "add (val) months" (zero-indexed)
// and the third as "add (val-1) days" (one-indexed)
> new Date(2016, 99, 99).toJSON()
'2024-07-08T04:00:00.000Z'
> new Date(2016, 99, 98).toJSON()
'2024-07-07T04:00:00.000Z'

> new SpannerDate(new Date(2016, 1, 1)).value
'2016-02-01'
```

So: I now retract my request to support the same arguments because `new Date` is ... certifiably insane. 

My new request is that we throw an error when you do `spanner.date(year, month, day)`. Is that doable?

**Comment by lukesneeringer** [comment]
> So: I now retract my request to support the same arguments because new Date is ... certifiably insane.

I was considering pointing out to you that the two lines you had in your original post were not equivalent because JavaScript uses zero-indexing for months (why? why? whyyyyyy?) :-)

> My new request is that we throw an error when you do spanner.date(year, month, day). Is that doable?

Yes, except what we will actually do is throw an error if you send a `Number` to `year` that is less than or equal to, say, `0 < x <= 9,999`. (Anything above that will be treated as a timestamp.)
