### ISSUE TITLE
Is there a way to ask Spanner for all columns using table.read?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2101]
It seems that using `table.read({keySet: {all: true}})` will give me all of the keys in my table, which is equivalent to saying `SELECT columns_i_specified FROM table`, but is there a way to say "Give me all columns" ? That's the equivalent of `SELECT * FROM table`?

I tried using `columns: {all: true}` which did not work, nor did leaving out the columns field entirely.

It feels like `table.read()` with undefined values for columns and keys should be the equivalent of `SELECT * FROM table`... no? That is:

`SELECT * FROM table` would be the same as...

```js
table.read();
```

Today this is not possible.

`SELECT * FROM table WHERE id IN ('1', '2', '3')` would be the same as...

```js
table.read({keys: ['1', '2', '3']});
```

`SELECT a, b FROM table` would be the same as...

```js
table.read({columns: ['a', 'b']});
```

Today this is possible but looks like....

```js
table.read({columns: ['a', 'b'], keySet: {all: true}});
```

`SELECT a, b FROM table WHERE id IN ('1', '2', '3')` would be the same as...

```js
table.read({columns: ['a', 'b'], keys: ['1', '2', '3']});
```

**Comment by vkedia** [comment]
Currently there is no way in the cloud spanner api to express this. You have to explicitly enumerate all the columns that you want to read.

**Comment by lukesneeringer** [comment]
My understanding from working on the Python library is that this is a backend restriction. @vkedia seems to be confirming this. Closing as such.
