### ISSUE TITLE
Transaction error in datastore returning odd and not friendly response

### ISSUE THREAD

**Issue by susanlinsfu** [GoogleCloudPlatform/google-cloud-node#2106]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 7.7.3
  - npm version: 4.1.2
  - google-cloud-node version: 0.49

I insert the following entity, but it will fail because the entity already exists:
```js
var transaction = datastore.transaction();
                    transaction.run(function(err) {
                        if (err) {
                            // Error handling omitted.
                            return callback('Database Error');
                        }

                        transaction.save([{
                            key: datastore.key(mykind, mykey]),
                            method: 'insert',
                            data: [{
                                name: 'par1',
                                value: val1
                            }, {
                                name: 'par2',
                                value: val2,
                                excludeFromIndexes: true
                            }
                        }]);

                        transaction.commit(function(err) {
                            if (!err) {
                                // Transaction committed successfully.
                                return callback(null, 'Everything is cool!');
                            }
                             console.log(err);
                        });
                    });
```

The error output is very hard to parse. Err returns this:
`
"{\"error\":\"Error: entity already exists: app: \\\"s~someapp\\\"<br/>path <<br/>  Element {<br/>    type: \\\"mykind\\\"<br/>    name: \\\"mykey\\\"<br/>  }<br/>><br/>\"}"`

It returns javascript object but it is difficult to parse if you need the error, type, and name fields. It is not in proper format and there are html entities in the response.

**Comment by lukesneeringer** [comment]
Hello @susanlinsfu, thanks for reporting. I agree this is not a good error, and will see what I can do about it.

**Comment by susanlinsfu** [comment]
@lukesneeringer Hi Luke, thanks for looking into the issue. I have an application with a deadline coming up this week which I need this feature to work. I understand there are many bugs and before this fix gets officially released it could be months. I have looked into the source code for transactions.js, but could not find where the error was being generated. I was wondering if you could informally just let me know where the error is being generated so I can fix this in my application within my own project? Cheers

**Comment by stephenplusplus** [comment]
@lukesneeringer this would either require a change in the Datastore API or our stripping the HTML tags from the response using something like [strip](http://gitnpm.com/strip):

```js
var errorMessage = 'entity already exists: app: "s~nth-circlet-705"<br/>path <<br/>  Element {<br/>    type: "Company"<br/>    name: "Google"<br/>  }<br/>><br/>'
require('strip')(errorMessage).replace(/\s+/g, ' ')
// 'entity already exists: app: "s~nth-circlet-705"path < Element { type: "Company" name: "Google" }>'
```

What do you think?

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-datastore/issues/8.
