### ISSUE TITLE
Add a tutorial-type page for Spanner like we have for Datastore

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2109]
The Datastore landing page in our docs has some really awesome content that explains how to do the common things (emulator, querying, pagination, creating entities, etc): https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/datastore

Can we have a similar page for Spanner?

**Comment by stephenplusplus** [comment]
I'm going to close to let this prior issue track development for all of the APIs: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1084
