### ISSUE TITLE
Add "table of contents" for the landing pages with lots of content?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2110]
Pages like the Datastore landing page (https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.49.0/datastore) have a ton of useful content, but there's no quick way to navigate to each section (e.g., "I forgot how to do transactional stuff... I just want a reminder about those transaction things").

Can we add a TOC-type box (maybe like the one that shows the available methods) for these pages? For example (I could just click "Transactions" in the box)

![image](https://cloud.githubusercontent.com/assets/112928/24099359/1bc59012-0d45-11e7-8088-2982519b920f.png)

(Though we may want to change some of the headings now that they're front-and-center).

**Comment by callmehiphop** [comment]
I moved this to https://github.com/GoogleCloudPlatform/gcloud-common/issues/221 since I think some additional configurations will probably be needed unless we embed HTML directly in the JSDoc.
