### ISSUE TITLE
bigtable table.getRows() method throws error "Received message larger than max"  to its callback

### ISSUE THREAD

**Issue by SenthilKumartd** [GoogleCloudPlatform/google-cloud-node#2111]
Hi,
While calling table.getRows() using bigtable throws the following error to its callback parameter:
"Received message larger than max"

This error seems, there is a limitation of 4MB in each return. How could i overcome this error while getting this kind of large amount of data in a single fetch from BigTable.

Regards,
Senthil

**Comment by lukesneeringer** [comment]
Hi @SenthilKumartd, thanks for reporting.
There is a default maximum message size of 4 MB in GRPC, but this can be overridden. We will look into adding this to the BigTable client.

For my own reference, I am referring to the Python folks' [discussion][] and [PR][] for this.

  [discussion]: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2880
  [PR]: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/2907

**Comment by lukesneeringer** [comment]
Discussing in triage: This may or may not be fixable depending on whether the max option can  be passed to GRPC in the non-GAPICs.

**Comment by arbesfeld** [comment]
Hi, any updates on this issue?

**Comment by stephenplusplus** [comment]
We have removed the maximum message size: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/8af56e9d0167125800457bcb65ccc8bea23f89de/packages/common-grpc/src/service.js#L139 

New installations of gRPC-using APIs will have this behavior. Please let me know if anyone is still seeing this issue.
