### ISSUE TITLE
Audit documentation

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#2114]
Let's audit our documentation to ensure that all snippets are correct and any external resources are still working properly.

### APIs

- [x] ~BigQuery~ (being delayed)
- [x] Datastore
- [x] Logging
- [x] Storage

**Comment by lukesneeringer** [comment]
@callmehiphop What is the status on this? (We are considering it a GA prerequisite, and we want to GA three of these next week, so just want to make sure this is happening.)

**Comment by lukesneeringer** [comment]
This has already been done, we were just bad at checking the items off the bullet list.
