### ISSUE TITLE
Review and preparation of grpc-1.2.0-pre1

### ISSUE THREAD

**Issue by jmuk** [GoogleCloudPlatform/google-cloud-node#2115]
gRPC team is preparing 1.2.0, and we want to make sure it's not breaking anything on google-cloud-node.

@stephenplusplus and @callmehiphop, please run tests with `grpc-1.2.0-pre1` (pushed in npmjs.com already).

cc: @murgatroid99

**Comment by stephenplusplus** [comment]
Tested and updated to grpc@1.2.0: https://github.com/GoogleCloudPlatform/google-cloud-node/commit/e353ce0c9010dde1a85edd2610dbca68a5f0619a
