### ISSUE TITLE
Bigtable Date system test broken

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2120]
After merging #2116, I noticed we had a system error:

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/e353ce0c9010dde1a85edd2610dbca68a5f0619a/packages/bigtable/system-test/bigtable.js#L895

```
Uncaught AssertionError: false == true
      + expected - actual

      -false
      +true
```

@callmehiphop could you ptal?

**Comment by rFlex** [comment]
@stephenplusplus just submitted a PR that should fix this issue. Could you please run the system tests on your side to confirm that everything is back to normal with that fix? Sorry for the troubles!

**Comment by stephenplusplus** [comment]
Will do, I really appreciate your help!
