### ISSUE TITLE
detectText provide base64

### ISSUE THREAD

**Issue by EasonWang01** [GoogleCloudPlatform/google-cloud-node#2123]
improve the function to able to read base64.

And improve your error message for more specific.

**Comment by stephenplusplus** [comment]
Can you show example code that you'd like to work, as well as the error (and how you got it)?

**Comment by EasonWang01** [comment]
https://github.com/GoogleCloudPlatform/cloud-vision/issues/112

**Comment by lukesneeringer** [comment]
As best as I can tell, he is referencing [this code][], which is in of itself quite cryptic.

  [this code]: https://github.com/GoogleCloudPlatform/web-docs-samples/blob/master/vision/explore-api/main.js#L39-L62

**Comment by EasonWang01** [comment]
Google's example got wrong here for "images" but only one content keys in the payload.
The problem might be the "s".
<img width="664" alt="00" src="https://cloud.githubusercontent.com/assets/11001914/24203945/0351d25c-0f52-11e7-9811-8ab6704e907f.png">

**Comment by stephenplusplus** [comment]
Our `detectText` function is here: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/a3c455f765822a24d87adb3c2469b5e31b8288f2/packages/vision/src/index.js#L1535 - which as you'll see, is just a wrapper around [`detect()`](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/a3c455f765822a24d87adb3c2469b5e31b8288f2/packages/vision/src/index.js#L284) that specifies the `text` type.

Your input is fed to [`findImages_`](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/a3c455f765822a24d87adb3c2469b5e31b8288f2/packages/vision/src/index.js#L284), a helper function which can take multiple forms of input and figure out how to send them to the API. The first case it handles is for Buffer types, which it will send through as base64.

So, I believe we support the feature you're looking for, however, provide the base64 string as a Buffer:

```js
var input = new Buffer(myBase64String, 'base64')

vision.detectText(input, ...
```

**Comment by stephenplusplus** [comment]
PR sent with an addition to the docs to make this more clear: #2145
