### ISSUE TITLE
Deprecate google-cloud metapackage.

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-node#2131]
We are deprecating the `google-cloud` metapackage.

This entails:

  * [x] updating our documentation to discourage it (#2119)
  * [x] deprecating it at npm

**Comment by lukesneeringer** [comment]
Now if you `npm install google-cloud`:

```
lukesneeringer@lukesneeringer0:~/Code/Google/test$ npm install google-cloud
npm WARN deprecated google-cloud@0.49.0: The google-cloud meta-package is not recommended; install individual packages.
```

**Comment by stephenplusplus** [comment]
Are we going to keep releasing `google-cloud`s, or nuh uh?

**Comment by lukesneeringer** [comment]
For the time being.

**Comment by jgeewax** [comment]
The docs still say that this is deprecated... Can we fix that?

(https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/v0.55.0/language)

**Comment by stephenplusplus** [comment]
`google-cloud` is deprecated on npm. What do we want it to say?

**Comment by jgeewax** [comment]
Then why do we have that as the docs on the main page ? E.g. if I click
into reading the docs, I'm brought to those.... I thought this ticket said
we weren't going to deprecate ... Did I misread?

**Comment by stephenplusplus** [comment]
Yeah, the package is deprecated, but @lukesneeringer says we still want to make new releases of it. I would prefer we stop making releases, since we are discouraging its use. But as it stands now, `require('google-cloud')` is still an accurate way to use the module, if you are looking for the all-in-one package.

**Comment by stephenplusplus** [comment]
Our last release of `google-cloud` was 3 months ago. We've shut down the gh-pages docs site, so I don't believe we are advertising `npm install google-cloud` anywhere anymore.
