### ISSUE TITLE
Translate API key required even though gcloud uses service account

### ISSUE THREAD

**Issue by timecatcher3** [GoogleCloudPlatform/google-cloud-node#2154]
Hi guys,

I am trying to initiate the translate api by calling gcloud.translate(); but it responds that "an API key is required to the Translate API". My gcloud initiate call uses the project-id and keyFileName for the Compute Engine service account, which I then use to call gcloud.storage() and that works. I wonder do I need to update my gcloud sdk?Maybe its a sdk issue.

Thanks,
timecatcher3

**Comment by stephenplusplus** [comment]
Thanks for reporting! What version of `google-cloud` are you using?

**Comment by timecatcher3** [comment]
Hi Stephen,

>gcloud version
Google Cloud SDK 148.0.1
beta 2016.01.12
bq 2.0.24
bq-nix 2.0.24
core 2017.03.24
core-nix 2016.11.07
gcloud 
gcloud-deps 2017.03.17
gcloud-deps-linux-x86_64 2017.02.21
gsutil 4.23
gsutil-nix 4.21

Thanks,
timecatcher3

**Comment by stephenplusplus** [comment]
Thank you, but we'll actually need the version of the `google-cloud` Node.js module itself, the one installed via `npm install google-cloud`. You can see the version by looking at your app's project.json file.

**Comment by stephenplusplus** [comment]
In any case, the answer is going to be to simply upgrade. `google-cloud` is deprecated now, so you'll get the best future-proofing if you install the individual modules now.

It sounds like you'd need:

- `@google-cloud/storage`
- `@google-cloud/translate`

Translate has dropped its requirement for an API key for a few releases now, so things should work as expected if you `npm install` the above modules, `npm uninstall google-cloud`, and make these slight changes in your code:

```diff
- var gcloud = require('google-cloud')(...)
- var storage = gcloud.storage()
+ var storage = require('@google-cloud/storage')(...)
- var translate = gcloud.translate()
+ var translate = require('@google-cloud/translate')(...)
```

Let me know if you run into any problems.

**Comment by stephenplusplus** [comment]
Going to close the issue, but I'm happy to help with any questions about upgrading.

**Comment by timecatcher3** [comment]
Thanks,
You were right it was just a matter of upgrading.

Quick question, I created and am running an ecommerce website. My google-cloud node controller is super generic, meaning it is irrelevant to the content it passes from cloud sql to the end user to load. Is there a way I could securely translate my page on the client side (within index.js) without exposing my api key?

**Comment by timecatcher3** [comment]
@stephenplusplus 

Quick question, I created and am running an ecommerce website. My google-cloud node controller is super generic, meaning it is irrelevant to the content it passes from cloud sql to the end user to load. Is there a way I could securely translate my page on the client side (within index.js) without exposing my api key?
