### ISSUE TITLE
datastore node.js API filter not working properly

### ISSUE THREAD

**Issue by singyiu** [GoogleCloudPlatform/google-cloud-node#2159]
#### Environment details

  - OS: MacOS
  - Node.js version: v5.10.1
  - npm version: v3.8.3
  - google-cloud-node version: "@google-cloud/datastore": "^0.7.1"

#### Steps to reproduce

```js
var datastore = require('@google-cloud/datastore')({
  projectId: 'XXX',
  keyFilename: 'XXX'
});

queryNearestGlobalSession = function (localSessionSnapshot, callback) {
  var startDate = new Date();
  var query = datastore.createQuery('GlobalSession');
  query.filter('startTime','>',startDate.getTime());
  datastore.runQuery(query, callback);
}
```

This following error was given when running the query:
```
{ [Error: no matching index found. recommended index is:<br/>- kind: GlobalSession<br/>  properties:<br/>  - name: channel<br/>  - name: user<br/>  - name: startTime<br/>] code: 412, metadata: Metadata { _internal_repr: {} } }
```

Filter operator "=" is working fine, but not the ">" nor the "<".
Tried two different data types (Time and Date, and Integer), both not working.

**Comment by stephenplusplus** [comment]
This just means you'll need to create an `index.yaml` file that looks like the one they whipped up for you in the error message. See [this document](https://cloud.google.com/datastore/docs/concepts/indexes) for more info on Datastore Indexes.
