### ISSUE TITLE
@google-cloud/logging memory leak for version 0.8.1

### ISSUE THREAD

**Issue by AleksNFedorov** [GoogleCloudPlatform/google-cloud-node#2166]
Memory leak when writing logs to cloud with @google-cloud/logging

Issue easily reproducible with code from [here](http://stackoverflow.com/questions/39366220/memory-leak-in-nodejs-gcloud-logging)

#### Environment details

  - OS: Mac OS/10.11.6
  - Node.js version: 6.3.1
  - npm version: 3.10.3
  - google-cloud-node version: @google-cloud/logging version 0.8.1

#### Steps to reproduce

  1. require `@google-cloud/logging`
  2. code from [here](http://stackoverflow.com/questions/39366220/memory-leak-in-nodejs-gcloud-logging)
  3. Send > 10K requests

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
Thanks for reporting. It sounds like this could be related to #2135. @ofrobots since you've already started looking into that issue, do you think this could be connected?

**Comment by AleksNFedorov** [comment]
Yep, I think it is the same

**Comment by lukesneeringer** [comment]
I am going to close as a duplicate, just for our tracking sanity. Thanks for reporting @AleksNFedorov
