### ISSUE TITLE
bigquery jobs list api: the stateFilter need useQuerystring in the request options

### ISSUE THREAD

**Issue by c0b** [GoogleCloudPlatform/google-cloud-node#2182]
the jobs list API says I can filter jobs by state: `done` `pending` or `running` but in some cases I want to know all pending and running jobs, instead of run jobs list twice, I found the bq server accepts if I provide the stateFilter twice in qs, that's by [httpie](https://pypi.python.org/pypi/httpie); it needs `stateFilter=pending&stateFilter=running&...` in the GET request parameters;
however with current `google-cloud-node` code, if I provide `stateFilter: [ 'pending', 'running' ]` in the [`getJobs`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/bigquery/0.9.0/bigquery?method=getJobs) call, the actual sent on the wire is `stateFilter[0]=pending&stateFilter[1]=running&...` which bq server just ignored

https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/list

when I research where did that `[0]` `[1]` comes from, it turns to be a default behavior in request options, users need to turn on `useQuerystring: true` to avoid that,
https://www.npmjs.com/package/request#requestoptions-callback

So here comes a diff I made it working locally, I think request interceptors may also be able to get it working; but you guys may want to integrate this `useQuerystring: true` to be the default

```js
--- ./node_modules/@google-cloud/bigquery/src/index.js.orig	2017-03-23 11:48:53.730426569 -0700
+++ ./node_modules/@google-cloud/bigquery/src/index.js	2017-04-03 03:13:23.873907848 -0700
@@ -613,15 +613,16 @@ BigQuery.prototype.getJobs = function(op
     options = {};
   }
 
   options = options || {};
 
   this.request({
     uri: '/jobs',
-    qs: options
+    qs: options,
+    useQuerystring: true,
   }, function(err, resp) {
     if (err) {
       callback(err, null, null, resp);
       return;
     }
 
     var nextQuery = null;
```

**Comment by c0b** [comment]
and improve your documentation that `stateFilter` accepts multiple values
https://googlecloudplatform.github.io/google-cloud-node/#/docs/bigquery/0.9.0/bigquery?method=getJobs

**Comment by c0b** [comment]
:nice:

**Comment by c0b** [comment]
after I upgrade to `@google-cloud/bigquery@0.9.2` this seems broken again

**Comment by c0b** [comment]
root cause found in https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2185/files#r111677936

the pr#2185 https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2185#issuecomment-291610741 was requesting a rush review, that is usually bad

such a simple PR I would make it myself

**Comment by stephenplusplus** [comment]
Thanks @c0b and sorry for not catching it in the PR. If you don't beat me to it, I'll send a PR and make a patch release with the fix tomorrow.

**Comment by stephenplusplus** [comment]
Sorry again @c0b. This is now out in @google-cloud/bigquery@0.9.3.
