### ISSUE TITLE
System test coverage for Cloud Spanner

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2197]
_From @vkedia on January 19, 2017 7:20_

System tests for Cloud Spanner should cover all these scenarios:

1. Basic read,query and writes for all the data types.
2. Read with indexes, read limits, different concurrency options, range reads. 
3. Reading back large amount of data (lot of rows, large rows) to exercise the stream resume, flow control and chunking logic.
4. Parameter binding in query for all the data types including nulls, null arrays, arrays containing null, array of structs, special values for double type (Nan, Infinity,-Infinity).
5. Read/modify/write using transactions.
6. Tests for admin operations such as creating/deleting a database, updating database schema, pagination for list operations.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node-private#20_

**Comment by stephenplusplus** [comment]
_From @callmehiphop on February 2, 2017 23:59_

@stephenplusplus is there anything in here that we don't already cover via system tests?

**Comment by stephenplusplus** [comment]
**Bold** = needs tests

1. Basic read,query and writes for **all the data types**. (We're missing `null`)
1. Read with indexes, **read limits**, **different concurrency options**, **range reads**.
1. **Reading back large amount of data (lot of rows, large rows) to exercise the stream resume, flow control and chunking logic.** (only tested in unit tests)
1. Parameter binding in query for **all the data types** including nulls, null arrays, arrays containing null, array of structs, special values for double type (Nan, Infinity,-Infinity).
1. Read/modify/write using transactions. (Not sure about the transactions)
1. Tests for admin operations such as creating/deleting a database, updating database schema, **pagination for list operations**.

**Comment by stephenplusplus** [comment]
_From @danoscarmike on February 7, 2017 21:39_

@stephenplusplus @callmehiphop can we please make progress on this this week?

**Comment by stephenplusplus** [comment]
_From @callmehiphop on February 8, 2017 19:59_

@danoscarmike sure!

**Comment by Chipintoza** [comment]
It will be good if you add some tests for this issues #2176
