### ISSUE TITLE
Build docs for all new releases

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2202]
I'm having a bit of trouble building the docs, and Circle is not very trustworthy when it comes to that part of the process. @callmehiphop can you please update the docs on gh-pages for the recently released modules? https://github.com/GoogleCloudPlatform/google-cloud-node/releases I did speech @ 0.9.0 (I think).

**Comment by stephenplusplus** [comment]
@lukesneeringer I think this is a pretty serious one. Our docs don't exist for our new releases :(

**Comment by callmehiphop** [comment]
Closing per https://github.com/GoogleCloudPlatform/google-cloud-node/commit/bd70126f9333b0e4ab80e6ceae56a30a452bb506
