### ISSUE TITLE
CI docs build process leaking files on master

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2206]
It looks like part of the post-test script on Circle is pushing gh-pages content to the master branch:

- script: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/scripts/circle/post-test.sh
- commit: https://github.com/GoogleCloudPlatform/google-cloud-node/commit/f24e607f7e98b8d9c57a2659d9e09b7459fd0832
- build log: https://circleci.com/gh/GoogleCloudPlatform/google-cloud-node/728

**Comment by callmehiphop** [comment]
in gh-pages? docs/manifest.json

**Comment by stephenplusplus** [comment]
In master.

**Comment by stephenplusplus** [comment]
Looking at that log, these seem like the problem spots which are part of `prepare-ghpages`:

```
D	.gitmodules
M	docs/manifest.json
A	gh-pages
Your branch is up-to-date with 'origin/master'.
git add docs/manifest.json
git commit -m "Update manifest for v0.51.1 [ci skip]"
```

I don't think `.gitmodules` should ever have been added and `gh-pages` definitely shouldn't be.

I found the commit here: https://github.com/GoogleCloudPlatform/google-cloud-node/commit/e6cdde093df6304b11375aff97aed547e2114f77
... but it's strangely **[not in the commit log??](https://github.com/GoogleCloudPlatform/google-cloud-node/commits/master)**

Anyway, @callmehiphop will you look into this? For now, I'm going to remove any docs generation from CI.

**Comment by eoogbe** [comment]
@callmehiphop Is this still relevant?

**Comment by callmehiphop** [comment]
@eoogbe I haven't started it, so I'm assuming so. @stephenplusplus I know you've done some tinkering with CI recently so you might be in a better spot to answer that question.

**Comment by stephenplusplus** [comment]
I haven't messed with the area where git operations are involved. CI hasn't been helping with docs since my last post on 4/11. I've just been building locally and `git reset`-ing master to get rid of the lingering files. It would be great if we could let CI take over again if this is a simple enough fix.

If it's not straightforward, it could be a race between fixing it and having the Cloud site host our docs, which I think is still happening someday (cc @lukesneeringer).

**Comment by stephenplusplus** [comment]
Closing since ongoing repo-extraction efforts are going to nullify our custom docs builds.
