### ISSUE TITLE
Incorrectly formatted FQDN's to googleapis.com

### ISSUE THREAD

**Issue by ericuldall** [GoogleCloudPlatform/google-cloud-node#2213]
I've noticed all of the references to the Fully Qualified Domain Name "googleapis.com" are incorrectly formatted. Per [RFC 1034](http://www.ietf.org/rfc/rfc1034.txt) FQDN's should have a trailing dot in order to remove any ambiguity and unnecessary lookups.

Explanatory documentation [HERE](http://www.dns-sd.org/trailingdotsindomainnames.html)

We were pointed to this doc by a Kubernetes network engineer at Google after having many DNS lookup issues inside of our GKE clusters. After running some tests we noticed a minimum 100ms improvement per request after adding the trailing dot.

I have a PR ready that I will post for review.

**Comment by lukesneeringer** [comment]
Hi @ericuldall,
Thanks for reporting.

I am not going to make the change suggested in #2214 for the reasons I covered there. However, you can continue to use this in your own implementation by specifying your `baseUrl` directly:

```javascript
new BigTable({ baseUrl: '...' });
```

**Comment by ericuldall** [comment]
I understand your concerns. I would highly suggest putting a warning for people using this library in a kubernetes cluster with a large number of http requests as the internal kube-dns will drop lots of requests without the trailing dot. This is because in the kubernetes resolve.conf they use a large number of ndots to check for internal services.

*resolv.conf sample*:
```
search default.svc.cluster.local svc.cluster.local cluster.local google.internal c.project.internal
nameserver 10.20.30.40
options ndots:5
```

One of the main problems is the setting: `sysctl -w net.netfilter.nf_conntrack_max=65535`
That table is of a finite size per host machine and if it overflows requests get dropped. Using the trailing dot seems to be an easy remedy to avoid all the internal lookups and bypass the problem completely.

Another option is to set the pod dnsPolicy, `DnsPolicy: Default` in the pod spec.

We will move forward creating instances with the overridden baseUrl for our needs. Thanks for looking into this.

**Comment by lukesneeringer** [comment]
Hmm, I understand. Let me think on this more and discuss it and see if my position changes. (It might.)

**Comment by stephenplusplus** [comment]
Due to an issue brought up in #2249, we're going to revert this change.
