### ISSUE TITLE
Update docs for speech v1

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2219]
The Google API docs show version `v1beta1`, but our API uses `v1` and our docs link to the Google API docs.

Trying to follow the logic from NL's recent release, if `v1beta1` is newer than `v1`, we're probably not going to see a docs update for `v1` (?). (Pretty sure we were using `v1beta1` before `v1`, but... 😕)

So, possible solutions for @lukesneeringer to choose between / add onto:

- [ ] Change the reference links in our docs to the .proto file (https://github.com/googleapis/googleapis/blob/master/google/cloud/speech/v1/cloud_speech.proto)
- [ ] Wait for the proto docs to be prettied up and put on the Google API docs (https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1beta1, but for v1)

**Comment by lukesneeringer** [comment]
In this case, since we are moving _to_ a GA API release, we should just update our docs.

**Comment by stephenplusplus** [comment]
Is that option #&shy;1, where we change our docs to link to the proto files on GitHub?

**Comment by r3wt** [comment]
where the fuck are the docs? we cannot implement because documentation missing and wrong

**Comment by lukesneeringer** [comment]
Oh, I see the problem. @jmdobry what needs to happen to get useful v1 docs on cloud-site?

**Comment by jmdobry** [comment]
The v1 docs are [already on cloud-site](https://cloud.google.com/speech/reference/rpc/google.cloud.speech.v1), or am I missing something?

**Comment by stephenplusplus** [comment]
Oh good! That's new since we opened this issue then. I will update our links to point there instead of v1beta1.
