### ISSUE TITLE
Create x-goog-api-client header for Translation, BigQuery, and Storage

### ISSUE THREAD

**Issue by bjwatson** [GoogleCloudPlatform/google-cloud-node#2222]
### What

We need to add the following HTTP header to methods in the Translation, BigQuery, and Storage client libraries:

`x-goog-api-client: "gl-node/{NodeJS version} gccl/{client library version}"`

### Why

This is most critical for Translation, because we discovered that we have no other way of tracking its usage. While we're at it, let's get this done for BigQuery and Storage, too.

This is P0 because every day this is not done is another day of data that we lose. Plus it will take time for users to upgrade to the versions of the client libraries in which this has been done.

**Comment by bjwatson** [comment]
@stephenplusplus I think that @lukesneeringer has discussed this with you already. I'm belatedly creating the issue to track its completion. Please note that this is P0.

**Comment by lukesneeringer** [comment]
@stephenplusplus Confirming: please do this as your next task. Thank you.

**Comment by bjwatson** [comment]
Fo' sho'. Thanks Stephen!
