### ISSUE TITLE
Fix GAPIC headers

### ISSUE THREAD

**Issue by bjwatson** [GoogleCloudPlatform/google-cloud-node#2225]
The issues with missing `gccl/` and stale `gapic/` version (`0.1.0`) needs to be fixed. This was observed with Vision. Its `x-goog-api-client` header is `"gl-node/6.6.0 gapic/0.1.0 gax/0.12.3 grpc/1.2.4"`.

Then please refresh all GAPICs, and publish their associated packages to npmjs.com.

After that, please update any affect cells in the HTTP header matrix, so I can review (I think Vision is the only API using GAPIC in that matrix).

**Comment by lukesneeringer** [comment]
Just sent up a PR for Vision. Will do the rest once my Artman changes are merged.

**Comment by lukesneeringer** [comment]
Just merged a new GAPIC for Vision, which @stephenplusplus is about to release.
Dropping to P2, but will regenerate all GAPICs soon (after Artman changes are merged).

**Comment by stephenplusplus** [comment]
Released vision@0.11.1 with the change.

**Comment by landrito** [comment]
@stephenplusplus #2228 needs to be released to add the 'gccl' header too!

**Comment by lukesneeringer** [comment]
Sorry, that was my fault; I did not grok that the `gccl` was not there, and I should have.

**Comment by stephenplusplus** [comment]
vision@0.11.2 published with those.

**Comment by stephenplusplus** [comment]
@bjwatson @lukesneeringer @landrito is this resolved?

**Comment by lukesneeringer** [comment]
I believe so.
