### ISSUE TITLE
Update objects using the Transactional commands in a remote transaction.

### ISSUE THREAD

**Issue by paritosh16** [GoogleCloudPlatform/google-cloud-node#2243]
Environment Details - 
* Operating System: Mac OS Sierra 10.12.4
* Node Version: v4.3.2
* Npm Version: v4.0.5
* @google-cloud/datastore version: v1.0.0

Steps to reproduce - 

I want to create a transaction object wherein there are multiple transactions on multiple kinds in Google Cloud Datastore. For example, I have one save operation, one delete operation and one update operation.

Sample code - 
```js
    var transactionObject = datastore.transaction()
    
    transactionObject.run(function(error) {
        if(error) {
          // An error occured.
        } else {
            // Create a brand new entity.
            transactionObject.save(key, function(error) {
              if(error) {
                // Error handling.
              } 
            });

            // Delete an entity.
            transactionObject.delete(key, function(error) {
              if(error) {
                // Error handling.
              } 
            });

            // Update the entities.
            transactionObject.get(key, function(error, entity){
              if(error) {
                // Error handling.
              } else {
                // Update the entities. 
                transactionObject.save(key, function(error) {
                  if(error) {
                    // Error handling.
                  } else {
                    transactionObject.commit();
                  } 
                });
              });
            }
        });  
```
If I add a `console.log()` in the callback function of the get function of the update entity code snippet, the log is successful. But the `console.log()` in the callback of the save operation does not execute.

How do I commit this transaction with all the chained transactional commands?

If I might have missed something obvious, I would be happy to fix that.

**Comment by stephenplusplus** [comment]
> If I might have missed something obvious,

Yes, but sorry that we didn't make it more obvious. In a transaction, the mutation methods (`save`, `insert`, `update`, etc), do not take a callback. What you're doing is queuing mutation requests until your `commit()` at the end.

gh-pages is down, so unfortunately I have to link to our source code to show you the examples. Here is what a `save` in a transaction should look like: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/e3341bc930b3b7f347bdebae270da34081db3774/packages/datastore/src/transaction.js#L420

Your example would be condensed down to this:

```js
var transactionObject = datastore.transaction()

transactionObject.run(function(error) {
  if(error) {
    // An error occured.
  } else {
    // Create a brand new entity.
    transactionObject.save(key)

    // Delete an entity.
    transactionObject.delete(key);

    // Update the entities.
    transactionObject.get(key, function(error, entity){
      if(error) {
        // Error handling.
      } else {
        // Update the entities. 
        transactionObject.save(key)
        transactionObject.commit();
      });
    }
  });  
```

**Comment by paritosh16** [comment]
@stephenplusplus Thank you for the quick answer. Appreciate the effort!
