### ISSUE TITLE
`error-reporting` Only Supports Authentication Using a Service Account Key

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/google-cloud-node#2245]
The `@google-cloud/error-reporting@0.1.0` package does not work locally or on App Engine Flexible Environment if a service account key is not specified.  That is, neither automatic nor manually specified errors are reported in the Error Reporting console.

#### Environment details

  - OS: OS X 10.12.4
  - Node.js version: v6.9.4
  - npm version: 3.10.10
  - google-cloud-node version: HEAD

#### Steps to reproduce

  1. Create an app that uses the `error-reporting` library and reports errors.
  2. Enable the Error Reporting API for the current project.
  3. Use `gcloud beta auth application-default login` to authenticate on a development machine with `gcloud` initialized to use the project with the Error Reporting API enabled.
  4. Run `NODE_ENV=production GCLOUD_PROJECT=<projectId> npm start`.

#### Actual Results

Errors are not reported in the Error Reporting console.

#### Expected Results

Errors should be reported in the Error Reporting console.

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
In case this is helpful, there's a new method on the @google-cloud/common Service class called `getProjectId()`. This uses the google-auto-auth client to detect and store the project ID on the instance as `service.projectId`.
