### ISSUE TITLE
@google-cloud/storage file getSignedUrl returns trailing dot in URL

### ISSUE THREAD

**Issue by ShaharHD** [GoogleCloudPlatform/google-cloud-node#2249]
Upon updating @google-cloud/storage to the latest package version (1.1.0) introduced a trailing dot in the url.
For example: `https://storage.googleapis.com./<bucket name>/<file name>...`

I've traced the cause of this due to GoogleCloudPlatform/google-cloud-node#2214

It seems valid by FQDN, on iOS, curl and wget no issue, but on Android: `HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.lang.IllegalArgumentException: Server name value of host_name cannot have the trailing dot`
(using OkHttp and Fresco)

Is this by design?

#### Environment details

  - OS: Heroku and MacOS
  - Node.js: `6.10.2`
  - yarn version: `0.23.2`
  - `"@google-cloud/storage": "^1.1.0"`

#### Steps to reproduce

  1. generate a signedUrl for file

On [Stackoverflow](http://stackoverflow.com/questions/43562555/google-cloud-storage-file-getsignedurl-returns-malformed-url)

**Comment by stephenplusplus** [comment]
@lukesneeringer should we:

1. Not revert the trailing `.` change in getSignedUrl()
1. Revert the trailing `.` change in getSignedUrl()
1. Revert the trailing `.` change in the Storage API
1. Revert the trailing `.` change in our whole API

**Comment by shaibt** [comment]
Can also confirm azure based services cannot use these trailing dot URLs provided by getSignedUrl - will fail to send an HTTP request

**Comment by ShaharHD** [comment]
@shaibt I've updated on [SO](http://stackoverflow.com/questions/43562555/google-cloud-storage-file-getsignedurl-returns-tailing-dot-in-url) that our solution for the problem was to add a temporary URI overwriter (to remove the trailing dot, might be done very efficiently using just a regex, but we choose to parse and reconstruct after fixing the the hostname trailing dot).

**Comment by stephenplusplus** [comment]
Thanks for sharing, and here's just a quick copy-paste for anyone who needs it:

```js
file.getSignedUrl(..., function(err, url) {
  url = url.replace('storage.googleapis.com.', 'storage.googleapis.com')
})
```

**Comment by ShaharHD** [comment]
@stephenplusplus that is a work around for a problem which was introduced to solve (and please correct me if I'm wrong) an issue on google backend.

If all Java  and C# based clients will simply overwrite the fix - doesn't it make the entire fix mute?

**Comment by stephenplusplus** [comment]
I'm honestly not sure-- I didn't investigate much into the reasoning behind the change, but it was discussed internally and decided by @lukesneeringer that it was something we wanted. My find/replace above is just a temporary workaround for anyone else that might need it, while we investigate a final solution.

**Comment by ShaharHD** [comment]
@stephenplusplus FYI GoogleCloudPlatform/google-cloud-node#2214 was IMHO an opinionated discussion with only @lukesneeringer being a minority "No" person.

I think the decision was made without being aware to the limitations of other environments support for "Absolute domain name" (which I agree is lacking, but simply because it wasn't widespread until now)

IMHO many will agree that this change needs to be reverted as once more node.js based deployments will pull the `1.1.0` version, many remote clients which uses signed URLs will start failing on invalid URLs.

**Comment by stephenplusplus** [comment]
[This comment](https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2214#issuecomment-293797083) is the basis of my earlier statement regarding why the change was introduced. The big decisions that affect our library go through @lukesneeringer, so when he's available, he will be able to address your feedback.

**Comment by ShaharHD** [comment]
@stephenplusplus Adding on your comment before, I'll add a 5.

5. Have a flag (defaulted to false) which add the trailing `.` to all requests

**Comment by stephenplusplus** [comment]
cc @swcloud

**Comment by stephenplusplus** [comment]
We're going to revert this library-wide. Thanks for your patience while we sorted this out.

**Comment by ShaharHD** [comment]
@stephenplusplus is there an ETA for the npm package to be updated?

**Comment by lukesneeringer** [comment]
@stephenplusplus Can you release a 1.1.1 today to fix this on Android?

Ironically, I got a request from another customer asking for the addition of the trailing `.` in all seven languages. I think we should potentially consider a flag. It is increasingly clear that some people really do need this. My original reason for saying no in #2214 was essentially, "We should not opt everyone in to this -- it might not work everywhere." But giving folks a _way to_ get this behavior clearly has value.

**Comment by stephenplusplus** [comment]
@callmehiphop are you available for a release?

**Comment by stephenplusplus** [comment]
`1.1.1` released.

**Comment by wyardley** [comment]
Would it be possible to set the `Host: ` header without the trailing dot but use the hostname with it for the target?
