### ISSUE TITLE
grpc DLL error when trying to use Natural Language Client API

### ISSUE THREAD

**Issue by mcthulhu** [GoogleCloudPlatform/google-cloud-node#2250]
I'm getting the following error when trying to use the @google-cloud/language package in an NW.js project. 

Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\Michael\Documents\NW projects\jorkens\node_modules\grpc\src\node\extension_binary\grpc_node.node

If it matters, I'm trying to call language.detectSyntax (s is a string of text and the lang variable contains 'fr'): 

language.detectSyntax(s, {language: lang, type: 'text'}, callback); 

The @google-cloud/translate API seems to be working fine with the same credentials. Any suggestions?

**Comment by stephenplusplus** [comment]
We don't offer explicit support for NW.js, so if anything works at all, that is a coincidence. For help, you could try posting the question to StackOverflow using the NW.js tag. You might find someone who has been through a similar problem before. If you figure anything out, feel free to cross-link or post back here with any results.
