### ISSUE TITLE
[Datastore] createQuery w/o parameters fails to take datastore instance namespace

### ISSUE THREAD

**Issue by bbamsch** [GoogleCloudPlatform/google-cloud-node#2261]
#### Environment details

  - OS: Ubuntu 14.04.5 LTS
  - Node.js version: 6.10.2
  - npm version: 3.10.10
  - google-cloud-node version: 1.0.0

#### Steps to reproduce

  1. require `google-cloud`
  2. instantiate datastore instace with 'namespace' option specified
  3. datastore.createQuery().hasAncestor(datastore.key(['test', 'test'])).run().catch(console.trace);

Example Code
```js
const Datastore = require('@google-cloud/datastore');
const datastore = new Datastore({projectId: '<project_id>', namespace: 'test'});

datastore
    .createQuery()
    .hasAncestor(datastore.key(['test', 'test']))
    .run()
    .catch(console.trace);
```

Produces Error
```
Trace: { Error: The query namespace is '' but ancestor namespace is 'test'.
    at /.../google-cloud-node/packages/datastore/node_modules/grpc/src/node/src/client.js:434:17
  code: 400,
  metadata: Metadata { _internal_repr: { 'google.rpc.debuginfo-bin': [Object] } } }
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by bbamsch** [comment]
Notably, the API provided here for Node.js does not support [Kindless Queries](https://cloud.google.com/datastore/docs/concepts/queries#kindless_queries) when namespace is provided due to this issue.

The [createQuery](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/v0.53.0/datastore?method=createQuery) documentation provided for the Node.js API does not seem to acknowledge that this is even possible.

**Comment by stephenplusplus** [comment]
Thanks for reporting! PR sent in #2263 with a fix. For an immediate fix, you can try this locally:

```js
const Datastore = require('@google-cloud/datastore');
const datastore = new Datastore({projectId: '<project_id>', namespace: 'test'});

var query = datastore
    .createQuery()
    .hasAncestor(datastore.key(['test', 'test']));

query.namespace = datastore.namespace;

query.run()
    .catch(console.trace);
```
