### ISSUE TITLE
@google-cloud/speech@0.9.1 return empty error object

### ISSUE THREAD

**Issue by r3wt** [GoogleCloudPlatform/google-cloud-node#2262]
I cannot tell if the callback is returning error or this is just a mistake. please advise

**Comment by r3wt** [comment]
the cause is specifying an undefined configuration parameter, such as `sample_rate`

**Comment by stephenplusplus** [comment]
Can you follow these steps from the suggested issue template? https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by r3wt** [comment]
Its your product, and you get paid to work on it. I dont.

**Comment by stephenplusplus** [comment]
Without further information, I am unable to help.

**Comment by lukesneeringer** [comment]
Hi @r3wt,
I am sorry that you are frustrated. As you determined, the `sampleRate` argument is actually now spelled `sampleRateHertz`.

We are in the process of trying to improve our documentation, which I agree could use quite a bit of love. Hopefully that is something that is improved in the near future.
