### ISSUE TITLE
README for GCS does not match docs

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/google-cloud-node#2270]
The [README](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/README.md#cloud-storage-ga) for how to use GCS doesn't match the [docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.1.0/storage), and the README seems wrong.

The README has:

```javascript
var storage = require('@google-cloud/storage');
```

Whereas docs have:

```javascript
var gcs = require('@google-cloud/storage')();
```

The former appears to lead to `TypeError: gcs.bucket is not a function` which suggests that the latter is correct.

**Comment by stephenplusplus** [comment]
In the README, the `gcs` variable is created by invoking the `storage` function (https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/README.md#using-the-cloud-storage-api-module):

```js
var storage = require('@google-cloud/storage');

// ...

var gcs = storage({
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
});
```

The top portion shows installing and requiring the module. The second example box shows instantiation.

**Comment by bgold0** [comment]
I'm getting `TypeError: storage is not a function` when I do the above code. Any idea why this would happen?

**Comment by stephenplusplus** [comment]
Hey @bgold0, the way to instantiate a client changed in `@google-cloud/storage@2.0.0`: https://github.com/googleapis/nodejs-storage/releases/tag/v2.0.0
