### ISSUE TITLE
Bigtable this.end() does not stop the stream?

### ISSUE THREAD

**Issue by arbesfeld** [GoogleCloudPlatform/google-cloud-node#2271]
Using Bigtable 0.9.1 - I seem to be getting more than 1 result after calling `this.end()`. Is this expected behavior?

**Comment by stephenplusplus** [comment]
I recall seeing this discussed in another issue, and it might be an issue with one of our dependencies. I will look into it. Thanks for reporting.

**Comment by stephenplusplus** [comment]
The issue I was thinking of doesn't actually relate to the Bigtable API, so throw that theory out the window.

I tried to reproduce, but couldn't. My script and results:

```js
var bigtable = require('@google-cloud/bigtable')()

bigtable.getInstancesStream()
  .on('data', function (instance) {
    console.log('instance')
    this.end()
  })
  .on('end', function () {
    console.log('over')
  })

// output:
instance
over
```

Without the `this.end()`:

```js
var bigtable = require('@google-cloud/bigtable')()

bigtable.getInstancesStream()
  .on('data', function (instance) {
    console.log('instance')
  })
  .on('end', function () {
    console.log('over')
  })

// output:
instance
instance
instance
over
```

Are you using a different method? Could there be other code interfering with when `this.end()` is called? Seeing your code might help.

**Comment by arbesfeld** [comment]
We're using `table.createReadStream()`. Here's what it looks like:

```javascript
    await new Promise((resolve, reject) => {
      table
        .createReadStream({
          decode: true,
          start: 'foo',
          end: 'bar'
          filter: [{
            column: {
              cellLimit: 1,
            },
          }],
        })
        .on('data', function onData(row) {
          this.end();
          resolve();
        })
        .on('end', resolve)
        .on('error', reject);
    });
```

Other methods could be using `table` at the same time, if that affects something?

**Comment by stephenplusplus** [comment]
Would it be a problem that `resolve()` is called from the `data` handler and `end`? `this.end()` will gracefully exit the stream, which means that the end event will be called.

**Comment by arbesfeld** [comment]
That would be acceptable for our application. We found that `onData` would continued to be called even after `this.end()`. We're on Node 7.9.0, and we found a workaround by introducing another variable outside of the promise.

**Comment by stephenplusplus** [comment]
Found the issue. PR incoming.

**Comment by stephenplusplus** [comment]
PR sent: #2276

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-bigtable#6
