### ISSUE TITLE
Storage: When moving a file, allow keeping old ACL

### ISSUE THREAD

**Issue by SimenB** [GoogleCloudPlatform/google-cloud-node#2274]
#### Environment details

  - OS: macOS
  - Node.js version: 6.10.2
  - npm version: yarn 0.23.3
  - google-cloud-node version: `@google-cloud/storage@1.1.0`

#### Steps to reproduce

  1. require `@google-cloud/storage`
  2. Instantiate it, and get a `bucket`
  3. call `const file = await bucket.upload(filePath, { public: true })`
  4. Verify file is publicly available from https://storage.googleapis.com/
  5. call `file.move(somewhere)`
  6. Try to access file from https://storage.googleapis.com/, get 403

What I want is either:
- some way to pass equivalent of `gsutil mv -p` flag, which "Causes ACLs to be preserved when copying in the cloud." 
  - `file.move(newName, { keepAcl: true })` or something like that
  - https://cloud.google.com/storage/docs/gsutil/commands/cp#options
- allow me to pass `destinationPredefinedAcl` to the `move` method
  - https://cloud.google.com/storage/docs/json_api/v1/objects/rewrite

**Comment by SimenB** [comment]
I suppose a workaround is to change the ACL after moving the file. The code doing the rename lives in a project which tries to just pass through options to the storage api though. So passing some custom acl (which defeats  of the nice `public: true` option) is something I'd really like to avoid.

The thing we do to avoid it is setting the default ACL of the entire bucket public. Which is fine (in our case), but not ideal.

**Comment by stephenplusplus** [comment]
Adding the `keepAcl` option sounds good to me. For a quick fix, something like this should work:

```js
file.interceptors.push({
  request: function(reqOpts) {
    if (reqOpts.uri.includes('rewriteTo')) {
      reqOpts.qs.destinationPredefinedAcl = '{{predefined acl value}}'
    }
    return reqOpts
  }
})
```

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-storage#21
