### ISSUE TITLE
Spanner library should have a way to track leaked sessions.

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-node#2292]
Due to a bug in user code or client library code, it is possible that a session is checked out from the pool but never released. We should make it easier for users to be able to detect such leaks and debug where in there code the leak occurred. One way can be to record a trace in a list or a map whenever a session is checked out and remove that trace when the session is released back to the pool. User should be able to look at this list and figure out the location in the code where all the unreleased sessions were checked out at. We can also log these stack traces when the pool is closed.

**Comment by danoscarmike** [comment]
As this is not blocking an imminent release perhaps we should consider P1?  Unless I am misunderstanding and there is a critical nature to the issue - security or similar?

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-spanner#18
