### ISSUE TITLE
500 response from BigTable after app has idled for a few minutes

### ISSUE THREAD

**Issue by gaballard** [GoogleCloudPlatform/google-cloud-node#2293]
This is similar to #1265, but that's been marked closed and this issue is still present.

We're using GraphQL along with the BigTable gcloud plugin to query BT. 

#### Environment details

  - OS: Mac OS X El Capitan (10.11.6)
  - Node.js version: 7.7.2
  - npm version: 4.1.2
  - google-cloud-node version: 0.49.0

#### Steps to reproduce

1. POST to the GraphQL endpoint
2. The BigTable plugin opens a read stream and returns data
3. Let the app idle for a few minutes
4. Run the same POST
5. The BT plugin will return this error:

```
{"code":500,"metadata":{"_internal_repr":{}}}
```

6. Run the exact same POST again
7. The plugin will work fine

**Comment by stephenplusplus** [comment]
Thanks for reporting. Do you have a sample repo or code I could use to reproduce the error? Also, just to make sure it's not something that has already been fixed, please try installing the latest Bigtable module, `@google-cloud@bigtable`.

**Comment by stephenplusplus** [comment]
@gaballard I'm going to close, since I'm unsure how to reproduce. I'm happy to re-open if you can report back after trying what I suggested above.

**Comment by gaballard** [comment]
@stephenplusplus - We did try upgrading the BigTable module but we're still encountering the issue from time to time... however, we can't seem to reproduce it with any regularity, so we don't have any code samples/examples at the moment. If we can figure out how to consistently reproduce the bug I'll update this issue. Thanks!
