### ISSUE TITLE
error-reporting:  Investigate Supporting Express 5

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/google-cloud-node#2294]
The cloud-errors-nodejs repository has PR [#98](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/98) that already contains some preliminary work.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/7.
