### ISSUE TITLE
error-reporting: Add deleteEvents and getEvents module methods

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/google-cloud-node#2296]
The cloud-errors-nodejs repository has PR [#99](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/pull/99) that already contains some preliminary work.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/9.
