### ISSUE TITLE
error-reporting: `serviceContext` not sent with `uncaughtException`

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/google-cloud-node#2297]
Is it possible that this is due to https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/blob/v0.1.x/lib/interfaces/uncaught.js#L56 calling `sendError` instead of `report` ?

This issue has been migrated from the cloud-errors-nodejs issue [#101](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/issues/101).

**Comment by ofrobots** [comment]
Is this still a problem? We no longer provide a built-in mechanism to handle uncaught exceptions.

**Comment by DominicKramer** [comment]
For completeness, I migrated the issue to this repo before closing it.  Yes, the code in this repo requires uncaught exceptions to be manually handled and thus this issue no longer applies.
