### ISSUE TITLE
error-reporting: Publish nodereport on SIGTERM

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/google-cloud-node#2299]
[nodereport](https://github.com/nodejs/nodereport) is a great package for getting crucial diagnostic info from a node process. We should publish that information to ER on SIGTERM so users get better visibility into the state of the process when the instance crashes (other than when the app itself is crashing).

This issue has been migrated from the cloud-errors-nodejs issue [#83](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/issues/83).

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/10.
