### ISSUE TITLE
error-reporting: Use the google-cloud-node API wrappers if it makes sense.

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/google-cloud-node#2300]
https://github.com/googleapis/api-client-staging/tree/master/generated/nodejs/google-cloud-node/packages/errorreporting are generated API wrappers on top of the Error Reporting API. Using them from this idomatic instrumentation module would make sense.

This issue has been migrated from the cloud-errors-nodejs issue [#59](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/issues/59).

**Comment by ofrobots** [comment]
Based on this [comment](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/issues/59#issuecomment-265302822) I don't think there is a definitive benefit of making this change.

There is no customer use-case that this solves that is not already solved by the existing code. I would suggest closing this issue.
