### ISSUE TITLE
error-reporting: Users can choose to report errors via Logs instead of using the report API

### ISSUE THREAD

**Issue by DominicKramer** [GoogleCloudPlatform/google-cloud-node#2301]
_This is an enhancement that should not be blocking the Beta launch of this module._

We can send errors to Error Reporting by calling the [report API endpoint](https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report) or by logging errors in Stackdriver Logging using [the appropriate structured format](https://cloud.google.com/error-reporting/docs/formatting-error-messages).

Today, cloud-errors-nodejs reports errors using the API endpoint.
This is a great default choice as it does not require any additional setup than enabling the API and do not forces to use Stackdriver Logging.

However, if users want to use Stackdriver Logging for application logging, it is better to capture logs and errors using the same mechanism, so that they can see errors in the Logs viewer too.

Users should be able to chose to report errors via Logs. We could imagine that when initializing this module, they can pass a logger that will be used to log errors.

This issue has been migrated from the cloud-errors-nodejs issue [#48](https://github.com/GoogleCloudPlatform/cloud-errors-nodejs/issues/48).

**Comment by ofrobots** [comment]
`logging-winston` and `logging-bunyan` already format errors so that error reporting can pick them up – so this is mostly implemented. What would still be good to do, IMO, is to add documentation here and on logging-{winston,bunyan} on how this works.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/11.
