### ISSUE TITLE
Page Not Found | DataStore | Authentication guide

### ISSUE THREAD

**Issue by hrovira** [GoogleCloudPlatform/google-cloud-node#2303]
![bad_link](https://cloud.githubusercontent.com/assets/293549/25975949/49444944-3666-11e7-9f18-19dc34dd5565.png)

Links to https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.53.0/guides/authentication

Redirects to https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/v0.53.0/not-found

#### Environment details

  - https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/v0.53.0/google-cloud

**Comment by stephenplusplus** [comment]
Thanks for letting us know. Fixed in commit: https://github.com/GoogleCloudPlatform/google-cloud-node/commit/b043cda5707df33bd500d1213bb71c1ae4f37920
