### ISSUE TITLE
Write correlation-id to log entries when available

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-node#2304]
By writing a correlation-id into the logging metadata, users can get request-correlated logs in pantheon.  See https://gist.github.com/JustinBeckwith/43dd04cfbc4551ddd8996a5b803da0b0 for details.

**Comment by landrito** [comment]
@JustinBeckwith I am having trouble seeing the gist.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-logging#23
