### ISSUE TITLE
PubSub Subscription Interval options is  not working

### ISSUE THREAD

**Issue by geun** [GoogleCloudPlatform/google-cloud-node#2308]
#### Environment details

  - OS:  mac osX
  - Node.js version: 6.10.2
  - npm version: 4.1.2
  - google-cloud-node version: 0.54

#### Steps to reproduce

  1. require `google-cloud`
  2. var topic = pubsub.get(TOPIC_NAME)
  3.  var options = { interval: 1000,
	maxInProgress: 1,
	autoAck: false,
	timeout: 90000}
  4. topic.subscribe(SUBSCRIPTION_NAME, options, (err, sub, apiResponse) => {
		if (err) {
			throw err;
		}

		sub.on('error', onErrorHandler);
		sub.on('message', onMessageHandler);
	});

**Comment by stephenplusplus** [comment]
This is how the interval option is being used: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/pubsub/src/subscription.js#L959

After every response, it fires another request to pull for messages after the amount of milliseconds specified as options.interval.

**Comment by geun** [comment]
Thanks quick reply. It was my fault. I'm going to close issue
