### ISSUE TITLE
Add support for GCS preconditions 

### ISSUE THREAD

**Issue by briangranatir** [GoogleCloudPlatform/google-cloud-node#2310]
**Request**: Add ability to specify preconditions in the options when creating a read or write stream

**Reason**: Want skip uploading a file if it has already been created.  This helps avoid race conditions and reduces potential costs.  Typically, checking if a file has already been created is done with the `if-generation-match:0` precondition

**Reference**: [Overview of Google Cloud Storage generations and preconditions](https://cloud.google.com/storage/docs/generations-preconditions)

**Comment by stephenplusplus** [comment]
You can actually specify this property (`generation`) when creating a File object. See https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.1.0/storage/bucket?method=file.

```js
var file = bucket.file('my-file', { generation: 0 })
```

Please give this a shot and let me know if it is what you're looking for!

**Comment by stephenplusplus** [comment]
@briangranatir since I think we already cover what you were requesting, I'm going to close the issue. If I misunderstood, or there's an issue with our implementation, please let me know.

**Comment by briangranatir** [comment]
Just for the record, this is exactly what I was looking for.  Thank you so much for the response.  Cheers!
