### ISSUE TITLE
Getting ESOCKETTIMEOUT when streaming through file.createReadStream()

### ISSUE THREAD

**Issue by MuthuD** [GoogleCloudPlatform/google-cloud-node#2317]
Hi,

We transform a large binary file (>150MB up to GBs) and publish the data to pubsub.

    OS: Google App Engine (Assuming its windows)
    Node.js version: LTS
    npm version: LTS
    google-cloud-node version: HEAD

#### Steps to reproduce

  1.  require `google-cloud`
  2.  let file = bucket.file([largebinaryfile]);
  3.  let readStream = file.createReadStream();
  4.  file.pipe(transformStream).pipe(writeStream)

readStream: Reads large file from bucket directly from bucket
transformStream: Does some operation 
writeStream: publishes transformed data to cloud pubsub

Problem, 
   readStream receives ESOCKETTIMEDOUT error more often, how to handle this is this value configurable through code?

Thanks

**Comment by stephenplusplus** [comment]
Can you double check the version of `google-cloud-node` that you're using? Only the latest release will retry on errors such as a socket timeout.

**Comment by MuthuD** [comment]
Hi Stephen,

Thanks for the response.

I'm using version "@google-cloud/storage": "0.7.0"

I will try with version 1.1.1 and let you know if there is any issue.

Thanks

**Comment by stephenplusplus** [comment]
@MuthuD how did it go?

**Comment by Scarysize** [comment]
Hey there, thought I would chime in here before opening a new issue in the `nodejs-storage` repo. I got the exact same issue on version **2.0.1**.

Here is the code producing the error:

```js
const readline = require('readline');

const storage = new Storage({projectId: config.projectId});
const bucket = storage.bucket(config.bucketName);
const remoteFile = bucket.file('events.txt');

const lineReader = readline.createInterface(remoteFile.createReadStream());

lineReader.on('line', /* do stuff */);
```

The code runs on GCE:

- **OS:** Linux 4.9.0-8-amd64 SMP Debian 4.9.110-3+deb9u3 (2018-08-19) x86_64 GNU/Linux
- **node:** v8.11.4

It reliably times out after 60 seconds of streaming.

Let me know if you need any further information.

**Comment by JustinBeckwith** [comment]
Thanks!  Opening this on the nodejs-storage repo is absolutely the way to go though 👍

**Comment by Scarysize** [comment]
👍 Okay, added a comment to a similar issue: https://github.com/googleapis/nodejs-storage/issues/27#issuecomment-420534576
