### ISSUE TITLE
Storage - file.js. Any way to set Source Encryption Key?

### ISSUE THREAD

**Issue by conundrum888** [GoogleCloudPlatform/google-cloud-node#2322]
Hi,
In File.js of the Storage package, the function setEncryptionKey() helps set the "x-goog-encryption-key" header. Is there a function to set the "x-goog-copy-source-encryption-key header"? Can a function be added for this please?

**Comment by lukesneeringer** [comment]
Hi @subra-vr,
Thanks for reporting this.

I just submitted #2324 which should give you what you need. Let me know if this solves your use case?

**Comment by subra-vr** [comment]
That should work, thanks.

**Comment by frankyn** [comment]
Hi, I'm just pinging the issue as I was trying to use the File.copy method to rotate customer-supplied encryption keys using node.

I tried the following, but I didn't have any luck. 

```node
var file = bucket.file("file_name");
var options = {baseHeader: "x-goog-copy-source-encryption"};
file.setEncryptionKey(encryptionKey, options); // file was already set with encryption key
file.copy("file_name", function(err, copiedFile, apiResponse) { // used the same filename
   copiedFile.setEncryptionKey(new_encryptionKey);
   copiedFile.save(); // rotate encryption key
});
```

**Comment by stephenplusplus** [comment]
Maybe we should have a method:

``js
file.rotateEncryptionKey(newKey, function(err) {});
```

This would handle doing the rewrite, and managing the headers. What do you think?

**Comment by frankyn** [comment]
+1 I agree can we move forward with this feature request? Ruby has this helper method in its client library. ([Documentation](https://googlecloudplatform.github.io/google-cloud-ruby/#/docs/google-cloud/v0.35.0/google/cloud/storage#customer-supplied-encryption-keys)).

**Comment by stephenplusplus** [comment]
Sounds good to me, and thanks for the reference.

**Comment by frankyn** [comment]
@stephenplusplus is there a status on this request?

**Comment by stephenplusplus** [comment]
@lukesneeringer has GCS on a code freeze while we are doing some code/repo re-organization. He can address the timeline aspect of this request.

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-storage#22
