### ISSUE TITLE
uploading buffer or string

### ISSUE THREAD

**Issue by p3sn** [GoogleCloudPlatform/google-cloud-node#2334]
Hi All, 

I can only find examples to upload a local file to cloud storage. But I would like to upload a file as a base64 string or as a buffer to google cloud storage. 

Is this possible with the google-cloud/storage package?

Regards, Peter

**Comment by p3sn** [comment]
Solved:

		const bucket = gcs.bucket('bucket_name');
		const gcsname = 'test.pdf';
		const file = bucket.file(gcsname);
		var pdfdata = "binary_pdf_file_string";
		var buff = Buffer.from(pdfdata, 'binary').toString('utf-8');

		const stream = file.createWriteStream({
			metadata: {
				contentType: 'application/pdf'
			}
		});
		stream.on('error', (err) => {
			console.log(err);
		});
		stream.on('finish', () => {
			console.log(gcsname);
		});
		stream.end(new Buffer(buff, 'base64'));

**Comment by stephenplusplus** [comment]
Yes, also [`file.save()`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.1.0/storage/file?method=save) for a shortcut.

**Comment by thecodingdog** [comment]
Thanks for this! I find the support for google cloud platform to be somewhat weaker for node (compared to python) so its great to find someone who's also facing (and solving) similar issues!

**Comment by drizzersilverberg** [comment]
@stephenplusplus how to add metadata & file type? so I able to view the image public ...

**Comment by amit0shakya** [comment]
getting issue 'Bucket is requester pays bucket but no user project provided' to save images in GCS.

**Comment by impulse** [comment]
Pulled my hair on this for writing a firebase integration test. I'll leave an example for writing a .json from memory here:

`
const bucket = admin.storage().bucket(testEnv.storageBucket);
const gcsName = mockObject.name;
const file = bucket.file(gcsName);
const contents = JSON.stringify(mockObject, null, 2);

file.save(contents, function(err) {
  if (!err) {
    // file written
  }
});
`

**Comment by codekeyz** [comment]
Any way to get saved file back in the callback ? I am using file.save() which works fine but the return response is just [].

**Comment by impulse** [comment]
> Any way to get saved file back in the callback ? I am using file.save() which works fine but the return response is just [].

According to the [documentation](https://cloud.google.com/nodejs/docs/reference/storage/1.6.x/File#save) it will return a Promise so you can use:

```js
file.save(contents).then(function() {
  file.get().then(function (data) {
    // use data
  }
});
```

**Comment by erikrakuscek** [comment]
Apologies for using this thread, but can anyone tell me how to download a JSON file from google cloud storage to a string?

**Comment by manzooralam** [comment]
Just you can call uploadFile() method passing base64 encode string & get uploaded url videos file
```
function uploadFile(media64Str: string): Promise<any> {
  const bucket = admin.storage().bucket('gs://xxxxxxx-bb282.appspot.com')
  const imageBuffer = Buffer.from(media64Str, 'base64')
  const imageByteArray = new Uint8Array(imageBuffer);
 const file = bucket.file('testImages/video.mp4');
  return file.save(imageByteArray)
    .then(() => {
      return file.getSignedUrl({
        action: 'read',
        expires: '03-09-2500',
      })
    })
    .then((urls: any[]) => {
      const url = urls[0];
      console.log(`media url = ${url}`)
      return url
    })
    .catch((err: any) => {
      console.log(`Unable to upload encoded file ${err}`)
    })
}
```

**Comment by bayerlse** [comment]
Hey there. For me all those methods are not working sadly.

Im trying to upload a base64 file via the same method as @manzooralam provided (except the signed url stuff). In the firebase console ui I'm also seeing that there was an upload, but I cant access the file:

![image](https://user-images.githubusercontent.com/38108896/111545943-2ebe1800-8777-11eb-86d3-dbd6cbc29500.png)

Any hints for that?

**Comment by JustinBeckwith** [comment]
Greetings!  The best way to get help here is to open a new issue in this repo:
https://github.com/googleapis/nodejs-storage/

Best of luck!

**Comment by aamirpinger** [comment]
> Hey there. For me all those methods are not working sadly.
> 
> Im trying to upload a base64 file via the same method as @manzooralam provided (except the signed url stuff). In the firebase console ui I'm also seeing that there was an upload, but I cant access the file:
> 
> ![image](https://user-images.githubusercontent.com/38108896/111545943-2ebe1800-8777-11eb-86d3-dbd6cbc29500.png)
> 
> Any hints for that?

solution for your problem:

change the following line
```
return file.save(imageByteArray)
```
to
```
return file.save(imageByteArray, {
      metadata: {
        metadata: {
          firebaseStorageDownloadTokens: REPLACE_THIS_WITH_ANY_TEXT_VALUE_EXAMPLE_UUID,
        },
      },
    });
```

**Comment by Flaviano-Rodrigues** [comment]
Hello. Help me Please!
 I'm trying to use the methods mentioned by you and I get this result:

![image](https://user-images.githubusercontent.com/112655909/213060299-e91aaad5-c172-4fae-b17d-281a1a84e3a5.png)

<br />

Sending base64 to backEnd:

```javascript
const reader = new FileReader()
reader.readAsDataURL(image)
reader.onload = (res) => {
  BackEnd('arquivos/setFile', {
    image: {
      name: image.name,
      type: image.type,
      size: image.size
    },
    base64: res.target.result,
  })
}
```


<br />

Sending base64 to Firebase:

```javascript
const bucket = admin.storage().bucket()
const imageBuffer = Buffer.from(base64, 'base64')
const imageByteArray = new Uint8Array(imageBuffer)
const file = bucket.file(`arquivos/${hash}.png`)

file.save(imageByteArray, {
  metadata: {
    metadata: {
      firebaseStorageDownloadTokens: hash
    }
  }
}).then(() => {
  console.log('Arquivo salvo com sucesso')
  return res.status(200).json({})
})
```

**Comment by mqrten** [comment]
Make sure to remove the URI prefix from the base64:

`function removeURIPrefix(imageBase64: string) {
  return imageBase64.includes(",") ? imageBase64.split(",")[1] : imageBase64;
}`

The image will remain broken in Firebase Storage but works when fetching it in your app via path.
