### ISSUE TITLE
Cannot delete the file after using upload() function

### ISSUE THREAD

**Issue by pratiknos** [GoogleCloudPlatform/google-cloud-node#2340]
I used the upload() method to upload some images from a local folder. After the callback function is called i tried to delete the images using fs.unlink() method. The images are not completely getting deleted. When i click on one of the image its displaying 'preview is not available'. Also if i try to Shift+del
the folder when node server is still running, folder is not getting deleted.
Here's my code (also attached the screenshot of the folder after i use unlink() method)

```js
forEachAsync
  .forEachAsync(fileArr, function(nextFor, file, index, fileArray) {
    var origFilename = file.replace(/^.*[\\\/]/, '') || "";
    var extension = origFilename.split('.');

    if (ext.includes(extension[1])) {
      var filename = shortid.generate() + "." + extension[1];
      bucket.upload("./" + file, {
        destination: "emp_img/" + filename
      }, function(err, uploadedFile) {
        if (!err) {
          logger.info("file uploaded")
          var fname = extension[0] ? extension[0].toLowerCase() : null;
          imgObj[fname] = {};
          imgObj[fname].file = filename;
          imgObj[fname].imgName = fname;
        } else {
          logger.error("File upload failed.");
        }
        nextFor();
      });
    } else {
      nextFor();
    }
  })
  .then(function() {
    fileArr.forEach(function(element, index) {
      try {
        fs.unlink(element);
        console.log("Removing successfully", element);
      } catch (error) {
        logger.error("Error removing image file in employee bulk.", error);
      }
    });
    
  	deferred.resolve(imgObj);
  });
```

![unlinkex](https://cloud.githubusercontent.com/assets/19407247/26632897/3efad84e-462f-11e7-97dd-7f727ee97200.png)

  - OS: Windows 7
  - Node.js version: v6.9.1
  - npm version: 3.10.8
  - google-cloud-node version: 0.7.0

#### Steps to reproduce

  1. require `google-cloud/storage`
  2. read a folder using fs.readdir 
  3. upload all the images in cloud storage using upload() method
  4.  try to delete the files in that folder using fs.unlink(file); 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
Hi @pratiknos! If I understand correctly, you're having trouble deleting files from your local disk? Our Storage API client library doesn't interfere or involve itself with that aspect of your script. You should be able to find better help for this on StackOverflow. Please let me know if I misunderstood. Thanks!

**Comment by pratiknos** [comment]
Hi @stephenplusplus 
Thanks for the quick reply.
I just want to let you know that if i comment the code for upload() method, then the files are getting deleted properly.
When I use the upload() function, the files will be deleted when i stop the node server otherwise i can see the files in the folder but cant open them.
