### ISSUE TITLE
Cloud Bigtable should have a gRPC channel pool

### ISSUE THREAD

**Issue by garye** [GoogleCloudPlatform/google-cloud-node#2343]
To avoid hitting single-channel limits, the client should leverage a channel pool.

**Comment by callmehiphop** [comment]
Is this something gRPC should implement? Seems like it might be something that could benefit all the APIs (not just Bigtable)

**Comment by garye** [comment]
It is indeed beneficial to all APIs. Cloud Bigtable contributed the Go implementation to a common location: https://github.com/google/google-api-go-client/blob/master/internal/pool.go. Perhaps something similar would work here.

**Comment by blueGinko** [comment]
I think I can look into this issue.

**Comment by vkedia** [comment]
+1. This is something that would definitely be beneficial for cloud spanner as well. Though for cloud spanner its slightly more complex since we want to control which channel out of the pool is used for a specific request.

**Comment by garye** [comment]
@vkedia Interesting, looks like the client-side load balancing technique wouldn't work here. Are you doing this in other languages for cloud spanner?

**Comment by vkedia** [comment]
@garye We do it in Java and Go. Essentially to interact with cloud spanner, one needs to create a `Session`. All other requests take in a session id. You get better performance if all requests with the same session id use the same channel (which is the channel that was used to send the initial session creation request). They way we do it is we pick a random channel while creating a session and then we maintain a map of session id to the channel that was used. Then for any request containing that session id we pick the channel from this Map.

**Comment by stephenplusplus** [comment]
@lukesneeringer I believe this would be better implemented in GAPIC / gax / gRPC that would be opt-outable for cases like Spanner or when the API requires a more manual approach to channel-related perf. What do you think?

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/gax-nodejs/issues/163.
