### ISSUE TITLE
Node.js 8 - npm install failed

### ISSUE THREAD

**Issue by unbornchikken** [GoogleCloudPlatform/google-cloud-node#2349]
Just a quick reference issue: install fails on Node.js 8 because of this issue: https://github.com/grpc/grpc/issues/11377

**Comment by oshalygin** [comment]
as in interim, may consider yarn as an alternative?
Just installed it w/o any issues.

**Comment by unbornchikken** [comment]
I get exactly the same errors on Windows with yarn like with npm. It uses excatly the same version of node-gyp and VC++ to build native dependencies, so it's expected.

**Comment by stephenplusplus** [comment]
[grpc@1.8.3 now supports Node 8](https://github.com/grpc/grpc/issues/11377#issuecomment-306856674).
