### ISSUE TITLE
When will the Search APIs be available from Node.js?

### ISSUE THREAD

**Issue by calsmith** [GoogleCloudPlatform/google-cloud-node#2352]
The Search APIs are available in Python, Java and Go. When will we be able to access Search APIs from Node.js? I can see that this was once supported but was removed: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1262 - can we add it back? I'm trying to perform full text search without relying on the Datastore

**Comment by stephenplusplus** [comment]
Unfortunately, we cannot provide any more information than I did here: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1798#issuecomment-260973418
