### ISSUE TITLE
Google translate detect invalid language(und) for string 123.

### ISSUE THREAD

**Issue by vishwasrao** [GoogleCloudPlatform/google-cloud-node#2353]
Hi All,
I was trying to use google translate module.
for string 123 it is detecting some invalid language.

```js
var translate = require('@google-cloud/translate');
var text= "123";
var translateClient = translate({
  projectId: '<ProjectID>',
  key: '<KEY>'
});
translateClient.detect(text, function(err, results) {
  if (!err) {
  console.log(results.language);
  }
});
```

Here i just gave small snippet to reproduce issue.

#### Environment details

  - OS:
  - Node.js version: v6.10.2
  - npm version: 5.0.1
  - google-cloud-node version: @google-cloud/translate": "^0.8.2

#### Steps to reproduce

  1. Save code as temp.js,Populate projectID and key and run it as node temp.js
  2. Language detected by google translate will be und.

**Comment by stephenplusplus** [comment]
According to a little blip of info on [this page](https://cloud.google.com/translate/markup), it apparently stands for "undetermined":

> If the source language or target language is unknown, use the “und” language specification to indicate undetermined language.

The context in this document isn't the same, but it's the only place I found that mentions `und` in a response means the language could not be determined. Sorry for the confusion!
