### ISSUE TITLE
docs: relative image paths broken in the npm version of the README

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#2357]
Compare the Error Reporting readme here:
https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/error-reporting

to the one on npm:
https://www.npmjs.com/package/@google-cloud/error-reporting

The image link is broken.

**Comment by stephenplusplus** [comment]
PR welcome :)

**Comment by eoogbe** [comment]
This issue may no longer be relevant due to its age. Feel free to re-open.

**Comment by eoogbe** [comment]
I am no longer on the team
