### ISSUE TITLE
@google-cloud/vision does not support proxy with HTTP(S)_PROXY

### ISSUE THREAD

**Issue by refextu** [GoogleCloudPlatform/google-cloud-node#2367]
#### Environment details

  - OS: Docker
  - Node.js version: 7.10.0
  - npm version: 4.2.0
  - google-cloud-node version: google-cloud/vision: ^0.11.2

#### Steps to reproduce

* set HTTP(S)_PROXY via ENV
* block all outgoing traffic w/o proxy try to detect or annotate via nodejs api

expected: response from google server
actual: no response/block by firewall

**Comment by stephenplusplus** [comment]
Our Vision API has a couple of layers beneath us which make the API requests:

- google-gax
- gRPC

@lukesneeringer which of these (if any) do you think should investigate this issue?

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/gax-nodejs#141
