### ISSUE TITLE
@google-cloud/dlp: event-based scanning snippet doesn't return findings

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/google-cloud-node#2368]
[This snippet](https://github.com/swcloud/api-client-staging/blob/nodejs-dlp/generated/nodejs/dlp/src/v2beta1/dlp_service_client.js#L355-L377) doesn't return any findings.

**Comment by ace-n** [comment]
FYI - we're hoping to have something that depends on this completed by the end of the month. @stephenplusplus would it be possible to have this fixed by June 24th?

**Comment by stephenplusplus** [comment]
Would you be able to provide the snippet you're working with, I assume it includes

**Comment by ace-n** [comment]
This must've been an issue on the API side - looks like everything's been fixed. :)
