### ISSUE TITLE
Add GCS bucket labels feature

### ISSUE THREAD

**Issue by swcloud** [GoogleCloudPlatform/google-cloud-node#2370]

**Comment by stephenplusplus** [comment]
We currently support setting any property of the  [Bucket resource](https://cloud.google.com/storage/docs/json_api/v1/buckets) in `storage.createBucket()`:

```js
storage.createBucket({
  labels: {
    myLabel: 'my label value'
  }
}, function(err, bucket) {})
```

If a user wants to update the labels, they can use `bucket.setMetadata()`:

```js
bucket.setMetadata({
  labels: {
    myLabel: 'my new label value'
  }
}, function(err) {})
```

Do we need more than this?

**Comment by stephenplusplus** [comment]
Got an update on what is wanted:

- `bucket.deleteLabels([labelName, ...], function(err) {})`
- `bucket.getLabels(function(err, labels) {})`
- `bucket.setLabels({ labelName: 'labelValue' }, function(err) {})`

@danoscarmike does this look correct?

**Comment by danoscarmike** [comment]
Yes, looks right to me.  @jskeet for vis.
