### ISSUE TITLE
Attaching event handlers to a writeable stream? 

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/google-cloud-node#2372]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: OSX
  - Node.js version: 8.0.0
  - npm version: using yarn
  - google-cloud-node version:  1.1.1

#### Steps to reproduce

It doesn't appear that the writeStream exposes an event handler via the `.on` function.  Any plans or am I doing something wrong?

```javascript
      const photoURL = 'catGifsBecauseWhoDoesntLikeCatGifs.jpg';
      const originalFileName = 'cats1337.jpg'
      const originalImageName = `${photoURL}_original_${originalFileName}`;

      const remoteOriginalWriteStream = bucket.file(originalImageName).createWriteStream();
      remoteOriginalWriteStream.on('finish', () => resolve(photoURL)); // undefined is not a function (btw my favorite javascript error description)
```
This is the Node API for writeable streams.
https://nodejs.org/api/stream.html#stream_event_finish

**Comment by stephenplusplus** [comment]
Hello @oshalygin! I'm not sure exactly what's going on there, but we use and support the native Stream APIs. I put this script together to try to reproduce, and couldn't:

```js
var storage = require('@google-cloud/storage')()
var bucket = storage.bucket('stephen-has-a-new-bucket')

var writeStream = bucket.file('new-file.txt').createWriteStream()
writeStream.on('finish', () => console.log('hi'))
writeStream.end('new data')

// $ node .
// hi
```

> // undefined is not a function (btw my favorite javascript error description)

😆

**Comment by stephenplusplus** [comment]
I'm going to close, but please let me know if you can show further evidence we have a bug, and we will re-open promptly. Thank you for helping.

**Comment by oshalygin** [comment]
Yeah I was blowing something up in my code when I was trying to test some of the functionality and the tests were passing but for some reason the application code wasn't working.  Classic case :(

Thanks @stephenplusplus this helped alot!
