### ISSUE TITLE
Circle: OS X failures

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2386]
Builds are currently failing on OS X:

```
. scripts/circle/test.sh returned exit code 3
```

**Comment by lukesneeringer** [comment]
With a nice and useless error!

**Comment by stephenplusplus** [comment]
I've disabled OS X testing temporarily.

**Comment by stephenplusplus** [comment]
It looks like something has changed since I last worked on this. There has only been one switch available to me, "**Build OS X project**" on https://circleci.com/gh/GoogleCloudPlatform/google-cloud-node/edit#build-environment.

Last I left that page, I set it to "Off". Now, it's "on", but builds are not running on OS X. There is likely more configuration to enable this behind the [Org Settings](https://circleci.com/gh/organizations/GoogleCloudPlatform/settings) route that I cannot access.
