### ISSUE TITLE
Error reporting returns wrong module name in error

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-node#2389]
Using @google-cloud/error-reporting, and I get this error:

```
ERROR:@google/cloud-errors: Unable to find credential information on instance. This library will be unable to communicate with the Stackdriver API to save errors. 
```

Really confused me for a second until I realized that we left a hard coded string in the error reporting module :) 

cc @ofrobots

**Comment by ofrobots** [comment]
Fix here: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2391
