### ISSUE TITLE
@google-cloud/bigquery API is not obeying useLegacySql parameter

### ISSUE THREAD

**Issue by pamelafox** [GoogleCloudPlatform/google-cloud-node#2398]
I have npm installed big-query, and have this in my package.json:
`@google-cloud/bigquery": "^0.9.5",`

I then use this code to issue a standard SQL query that works fine in the Web UI:
```js
  const bigqueryClient = bigquery({
      projectId: 'woebot-logs',
      useLegacySql: false,
      autoPaginate: false,
      useQueryCache: false
    });
var query = 'SELECT COUNT(*) FROM `woebot-logs.dynamodb.UserProfile`';
bigqueryClient.dataset('dynamodb').query(query, function(err, rows) { ... });

```
However, when I run that code, I get:

```js
{ [ApiError: Invalid table name: `woebot-logs:dynamodb.UserProfile`]
  code: 400,
  errors: 
   [ { domain: 'global',
       reason: 'invalid',
       message: 'Invalid table name: `woebot-logs:dynamodb.UserProfile`',
       locationType: 'other',
       location: '`woebot-logs:dynamodb.UserProfile`' } ],
  response: undefined,
  message: 'Invalid table name: `woebot-logs:dynamodb.UserProfile`' }
```

It appears to me that it is not obeying useLegacySql parameter. I've attempted variations on it, like 'false' instead of false, but no difference.

It works fine if I use [] for the table name, as it interprets it as Legacy SQL.

How can I get it to accept standard SQL? I already have all my queries in standard SQL and would like to keep using them. Thank you!

**Comment by stephenplusplus** [comment]
Hello, thank you for reporting. Would you try placing those options on the API call itself? I believe that will clear up the issue:

```diff
  const bigqueryClient = bigquery({
      projectId: 'woebot-logs',
-      useLegacySql: false,
-      autoPaginate: false,
-      useQueryCache: false
    });
- var query = 'SELECT COUNT(*) FROM `woebot-logs.dynamodb.UserProfile`';
+ var query = {
+   query: 'SELECT COUNT(*) FROM `woebot-logs.dynamodb.UserProfile`',
+   useLegacySql: false,
+   autoPaginate: false,
+   useQueryCache: false
+ }
bigqueryClient.dataset('dynamodb').query(query, function(err, rows) { ... });
```

Sorry for the slow response. I think this will sort out the problem, but let me know if there are still any issues, and we will try again!

**Comment by pamelafox** [comment]
Yep, that does indeed seem to work. I'm not sure if I misread stuff or something, but thanks for the help!
