### ISSUE TITLE
Why is "dlp" in the left-nav in lower case?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2400]
<img width="273" alt="screen shot 2017-06-20 at 10 03 57 am" src="https://user-images.githubusercontent.com/112928/27322859-d614956a-559f-11e7-9f79-c53eebc0d81a.png">

This looks totally inconsistent with the rest of the UI....

/cc @omaray

**Comment by jgeewax** [comment]
It's also basically empty of comments on how to use this. Can we either take it away until it has useful content or fix it and add content that helps people to use the API?

**Comment by jgeewax** [comment]
@lukesneeringer : We're showing ugliness on our docs for over a week now... can we get this fixed?

**Comment by lukesneeringer** [comment]
Sorry, I was OOO when you filed this.

@stephenplusplus Does the @name field need to be added to autogen?

**Comment by stephenplusplus** [comment]
Yep, it does.

**Comment by lukesneeringer** [comment]
Okay, I can do that.

**Comment by stephenplusplus** [comment]
@lukesneering can the generated layer add a sample snippet in the `@example` block? That is what is required to resolve:

> It's also basically empty of comments on how to use this. Can we either take it away until it has useful content or fix it and add content that helps people to use the API?

**Comment by callmehiphop** [comment]
This appears to be resolved.
