### ISSUE TITLE
DLP link to docs is broken

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2412]
In the readme (on https://github.com/GoogleCloudPlatform/google-cloud-node/tree/master/packages/dlp) we link to https://googlecloudplatform.github.io/google-cloud-node/#/docs/dlp

This shows a 404....

**Comment by stephenplusplus** [comment]
Fixed in https://github.com/GoogleCloudPlatform/google-cloud-node/commit/fbcb81d9ad824fdc3a99cfc7b8bae4ae42b0ff40
