### ISSUE TITLE
DLP docs don't list common auth credentials in the docs

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2414]
DLP docs for the constructor (https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/v0.55.0/dlp) lists a port and servicePath, but not the auth credentials...

That is, the following works:

```js
var dlp = require('@google-cloud/dlp').v2beta1({
  projectId: 'jjg-cloud-research',
  keyFilename: '/Users/jjg/key.json'
});
```

Can we update the docs so that these fields are listed as available? Otherwise it's not clear whether this client is somehow different from the others...

/cc @stephenplusplus

**Comment by lukesneeringer** [comment]
@landrito, could we add this to the documentation for `options` in autogen?

**Comment by landrito** [comment]
Yep, will look work on it this week.
