### ISSUE TITLE
Pub Sub - Illegal value for maxMessagesvalue element: 1000 (undefined type [object Object])

### ISSUE THREAD

**Issue by alejomendoza** [GoogleCloudPlatform/google-cloud-node#2418]
#### Environment details

  - OS: OSX 10.11.5 
  - Node.js version: v7.10.0
  - yarn version: v0.24.6
  - google-cloud-node version: 0.13.3

#### Steps to reproduce

  1. Subscribe to a topic   `topic.subscribe(subscriptionName .. etc`
  2. Publish more than 100 messages.
 3.  You will get the error `protobuf.js [sm]:1930 Uncaught Error: [INTERNAL] Illegal value for maxMessagesvalue element: 1000 (undefined type [object Object])`
<img width="970" alt="screen shot 2017-06-28 at 11 52 48 pm" src="https://user-images.githubusercontent.com/5351127/27671910-221a6b38-5c5d-11e7-809a-5c634df20b27.png">

See screenshot attached 

Thanks!

**Comment by jgeewax** [comment]
Thanks for reporting @alejomendoza 

@stephenplusplus : Is this a low-level protobuf bug? or gRPC? or something we're doing wrong?

**Comment by alejomendoza** [comment]
I'm using electron (devtool) to debug and test my code. Not sure if I'm doing something wrong.

**Comment by stephenplusplus** [comment]
I was able to publish 100+ messages:

```
var pubsub = require('@google-cloud/pubsub')()
var topic = pubsub.topic('stephen-topic')

topic.get({ autoCreate: true }, err => {
  if (err) throw err

  var numMessages = 101
  var messages = []
  while (numMessages--) messages.push({ test: true })

  topic.publish(messages, console.log) // [ no err, messageIds returned ]
})
```

So, I have a feeling its the integration with electron, which is not something we explicitly support. I'm happy to take a look, however, if you can provide an easy way that I can reproduce the error.

**Comment by lukesneeringer** [comment]
`maxMessagesvalue` is an odd spelling. Why is it not `maxMessages` or `maxMessagesValue`? Maybe that is the issue?

**Comment by stephenplusplus** [comment]
Thanks for letting us know!
