### ISSUE TITLE
datastore.save() with upsert should allow get-or-create

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2419]
Ideally, datastore's upsert would be one of those "get or create" type methods, but I can't figure out how to make it act like get or create...

That is, what I want to do is:

```js
function getOrCreate(id, name) {
  var entity = {
    key: datastore.key(['User', id]),
    method: 'upsert',
    data: {
      name: name
    }
  };
  return datastore.save(entity).then( function (data) {
    return data[0][0]; // Or whatever to return the entity as it actually exists in datastore
  });
```

Turns out that the data coming back in the promise is ... some mutation results?

```js
datastore.save(entity).then( function (data) {
  console.log(data[0].mutationResults[0]);
});
```

spits out:

```
{ key: null,
  version: '1498776439005000',
  conflictDetected: false }
```

Which is lovely to know, but doesn't really help me at all.

Can we please make this method actually useful to people who want to use get-or-create? (For comparison, Datastore from App Engine can do this in Python...) Also, let me know if I'm crazy and just using this wrong. The docs aren't too descriptive about the output from the promises when you specify the method to use in the save request.

/cc @pcostell @stephenplusplus

**Comment by stephenplusplus** [comment]
I'm probably the crazy one, but "upsert" doesn't seem like it should "get" at all. We return the raw response from the API (those super-cool stats). We could return the entity, but it would just be us giving back what the user gave us when they called `upsert`. Let me know if I'm missing something.

**Comment by jgeewax** [comment]
Right -- what we don't have is an atomic way of saying "update" (merge) this data with whatever is stored already, and treat it as `{}` if missing, then return me the results.

That makes me sad -- it seems super useful.

So yes, if the `.save()` method only ever "sets" (overwrites) the value, then there's no point in it returning what you just sent.

Does it make sense to add support for a "getOrCreate" style method? With a merge/overwrite parameter that let's you control whether we'll blast out whatever is there, or flatten your provided data on-top of that data (like `Object.assign()`) and return the result either way? Aka, can I turn this bug into a feature request? :-D

**Comment by stephenplusplus** [comment]
Gotcha, I would agree that would be nice. Would we take "options.merge" to .update() and .upsert()?

**Comment by stephenplusplus** [comment]
Or maybe only put the option on .save(), so the pure definitions of the other mutation methods remain?

**Comment by jgeewax** [comment]
> Or maybe only put the option on .save(), so the pure definitions of the other mutation methods remain?

I think we should be careful not to dirty up the official methods with trickery like this (since not everyone will want it at first).

When calling this method, it will require:

1. Create a transaction
2. Try getting the entity
3. If it does exist, `let merged = Object.assign({}, remoteData, localData);`
4. Update the entity
5. Commit the transaction

That's quite a bit to do in a single call, and to be controlled by an option. Perhaps this is better off as it's own method?

The use case here is "I just want to remotely set `user.meaningOfLife = 42`" Currently that involves several steps, whereas in something like Firebase it's far fewer.

What I currently have to do:

```js
let txn = datastore.transaction();
txn.run( (err) => {
  let key = datastore.key(['User', 100]);
  txn.get(key).then((data) => {
    let user = data[0];
    user.meaningOfLife = 42;
    txn.save(entity);
    return txn.commit().then((data) => {
      console.log('All set!');
    });
  });
});
```

What I want to do:

```js
let key = datastore.key(['User', 100]);
datastore.merge(key, {meaningOfLife: 42}).then( (results) => {
  console.log('All set!');
});
```

And when I decide I need to do more advanced things, I leave the merge data blank (or make it a callback) and do my edits like a transaction, but focused on a single entity that I plan to modify

```js
let key = datastore.key(['User', 100]);
datastore.merge(key).then( (entity, txn) => {
  entity.meaningOfLife = 42 + new Date().getTime();
  // Upon leaving this, we should automatically call txn.save(entity) and txn.commit();`
}).then( (results) => {
  console.log('All set!');
});
```

This is all fantasy-land requests, so please point out all the silly things that can go wrong with this -- I'm 99% sure that something can go poorly :-)

**Comment by stephenplusplus** [comment]
I like `merge()` 👍, but I don't think we should have the dual-mode where it acts like `get()` -- I would rather we just let `datastore.get()` be the recommended path for... getting, but let me know if that's not cool.

> I'm 99% sure that something can go poorly :-)

What were you thinking? Potential confusion of how JS objects would be merged? I think "merge" should imply to the user we'd do a deep extend, so even a deeply-nested object wouldn't get completely overwritten:

```js
{
  value: {
    nested: {
      insideNested1: {
        a: 1,
        b: 2,
        c: 3
      },
      insideNested2: {
        x: 24,
        y: 25,
        z: 26
      }
    }
  }
}

datastore.merge(key, {
  value: {
    nested: {
      insideNested1: {
        d: 4
      }
    }
  }
})

// result:
{
  value: {
    nested: {
      insideNested1: {
        a: 1,
        b: 2,
        c: 3,
        d: 4
      },
      insideNested2: {
        x: 24,
        y: 25,
        z: 26
      }
    }
  }
}

// NOT the result (this would be a shallow extend)
{
  value: {
    nested: {
      insideNested1: {
        d: 4
      }
    }
  }
}
```

Does this all sound like what we're going for? Just for consideration, another name choice could be "extend()".

**Comment by lukesneeringer** [comment]
> I like `merge()` :+1:, but I don't think we should have the dual-mode where it acts like `get()` -- I would rather we just let `datastore.get()` be the recommended path for... getting, but let me know if that's not cool.

Most ORMs I have used have the concept of `get_or_create` and `update_or_create` (see [here][1] in Django, for example). The reason is because it is a _really_ common pattern: I need this thing to be in the database. It may or may not be there, and these are some sensible defaults for other things (the stuff I am not actually querying on) to set if not.

This is needed all the time, e.g. for bootstrapping a new database for your application that has sane things in it for your app to work. It is also very common when writing migrations.

  [1]: https://docs.djangoproject.com/en/1.11/ref/models/querysets/#get-or-create

**Comment by stephenplusplus** [comment]
I think I'm getting mixed up between this method acting like a "merge" vs a "get or create" vs a "get or merge". Could you please whip up what the ideal additions to our API looks like, and what they're doing behind the scenes?

**Comment by stephenplusplus** [comment]
Here's what seems like the core of what we want. Please let me know, in as much detail as possible, what additional features are required.

#### `datastore.merge(key, data)`
  - *key* - The Datastore Key object.
  - *data* - The data to merge with the existing data associated with the key.

Steps:

  1. Create a transaction
  1. `transaction.get(key)`
    1. If it exists, `data = extend(remoteData, data)`
    2. If it doesn't exist, do not modify `data`
  1. `transaction.upsert(key, data)`
  1. `transaction.commit()`

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-datastore/issues/10.
