### ISSUE TITLE
Add easy link from docs to the code

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2430]
For the methods we have in our docs, is it possible to add a link to the code so that we don't have to click around trying to navigate from the docs for (say) datastore.save -> code for the method?

**Comment by lukesneeringer** [comment]
This would be a really nice feature. It does not look like something JSDoc supports out of the box. We could use `@see` but the GitHub links would have constantly changing line numbers, which would make maintenance tough.

I think we could write a plugin that could do this, however. The JSDoc AST already has enough information.

**Comment by stephenplusplus** [comment]
I think we have what you're looking for, but let me know if I misunderstand:

![image](https://user-images.githubusercontent.com/723048/27871314-497839c4-6173-11e7-895c-4ff8568f8338.png)
https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/v0.55.0/datastore?method=save

**Comment by lukesneeringer** [comment]
So we do. I did not see that.

Would it be possible to change our template to have that be next to the header, rather than at the very bottom of a very long and drawn out explanation with multiple examples?

I am thinking along the lines of having it right-aligned right next to the name of the method.

**Comment by stephenplusplus** [comment]
Historic reason: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/790#issuecomment-130470583

**Comment by callmehiphop** [comment]
@stephenplusplus I think @lukesneeringer's suggestion is good, we can still put other links (upstream docs, etc.) at the bottom but maybe some smaller text next to the method name that says `view source` or similar.

**Comment by stephenplusplus** [comment]
I'm fine with it that way, or the way it is!

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/gcloud-common#229

**Comment by stephenplusplus** [comment]
The positioning issue can be resolved in the common repo-- that's where the change would be made, and it would affect all of our libraries.
