### ISSUE TITLE
Datastore insert/upsert/update methods aren't documented?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2431]
@stephenplusplus mentioned this in a comment, so I went looking for some code...

Seems like `insert` is here: https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/datastore/src/request.js#L464

Why are these methods not documented ? (I'm looking at https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.0.0/datastore)

**Comment by stephenplusplus** [comment]
This is indeed strange. Looking into it.

**Comment by stephenplusplus** [comment]
@callmehiphop do you have any ideas for what could be excluding these, or why? We had them in 0.8.0: https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/0.8.0/datastore?method=upsert, but lost them by 1.0.0: https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.0.0/datastore?method=upsert

**Comment by callmehiphop** [comment]
Looking into this now, but those methods are part of `DatastoreRequest` so for some reason the mixin methods have disappeared.

**Comment by callmehiphop** [comment]
Looks like we added a filter to check if a dox block was a method by checking for a `typedef` tag. However as a side-effect, any methods that have 0 tags (params, examples, etc.) also were considered non-methods.

I went ahead and documented the parameters for the missing methods, which fixes the issue, however we may want to consider refactoring that filter as well?

**Comment by stephenplusplus** [comment]
Can you link the code you found that / if there was a related issue it was solving? I think it would be better to do the refactor, so we can be sure we're not accidentally omitting other parts of the docs we haven't realized yet.

**Comment by callmehiphop** [comment]
Sure it was [parser.js#L48](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/scripts/docs/parser.js#L48). This function makes an assumption that if there are no tags associated with the JSDoc (params, examples, returns etc.) then it probably is not a method.

**Comment by stephenplusplus** [comment]
It looks like that change was made to properly parse the `error-reporting` docs. Can you recall why that change was necessary from this PR: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2181/files? Maybe we can find another way to solve the problem that line was correcting.

**Comment by callmehiphop** [comment]
Honestly, no I don't remember :(. I'm guessing the logging stuff uses JSDoc tags differently than us?

**Comment by stephenplusplus** [comment]
Yay: https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.0.6/datastore?method=update
