### ISSUE TITLE
ERROR:@google/cloud-errors prints to stdout instead of stderr

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/google-cloud-node#2432]
```
ERROR:@google/cloud-errors: Encountered an error while attempting to transmit an error to the Stackdriver Error Reporting API. ApiError: User not authorized.
```

I didn't catch this for a long time because it is being printed to stdout instead of stderr.

**Comment by DominicKramer** [comment]
It appears that the `log-driver` module that we use for outputting messages always uses `console.log` to output messages.

To address your issue, I've created a `log-driver` PR (https://github.com/cainus/logdriver/pull/6) to add support for specifying a log level at which `console.error` will be used instead of `console.log` for outputting messages.

**Comment by kilianc** [comment]
@DominicKramer that's funny, the headline of the repo is `node logger that only logs to stdout` 🤣

**Comment by DominicKramer** [comment]
@stephenplusplus The `log-driver` module only outputs to standard out.  A logdriver PR [#6](cainus/logdriver#6) was not accepted since the path is to keep that module using only standard out.  What is your perspective on addressing the fact that errors are not printed to standard error?

**Comment by stephenplusplus** [comment]
My instincts say they should print to `stderr`, but I'd defer to what you and @ofrobots think / have seen in the wild.

**Comment by ofrobots** [comment]
Agree with printing to `stderr` – that is more reasonable for libraries. Perhaps we can switch to a different logger, e.g. [npmlog](https://npm.im/npmlog), etc.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/12.
