### ISSUE TITLE
Unable to install @google-cloud/language from npm

### ISSUE THREAD

**Issue by ericmcgregor** [GoogleCloudPlatform/google-cloud-node#2434]
Can not install google cloud language from npm.  I was able to successfully install other parts of the google cloud node package like storage, but for some reason the language hangs on installation.  

The last message it prints out before hanging is:

fetchMetadata: sill pickManifestFromRegistryMetadata spec >=0.9.1 <0.10.0 tag latest versions [ '0.1.0'

Please advise.  am i the only one with this issue?

#### Environment details

  - OS: osx
  - Node.js version: 4.8.3
  - npm version: 4.6.1
  - google-cloud-node version: can't install

#### Steps to reproduce

  1. npm install --save @google-cloud/language

**Comment by stephenplusplus** [comment]
@callmehiphop can you try this out?

**Comment by ericmcgregor** [comment]
was able to get this working today.  Not sure what the issue was with NPM yesterday.  sorry for the post.

**Comment by stephenplusplus** [comment]
No problem, glad it's working now!
