### ISSUE TITLE
datastore: document unit testing with the emulator

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2441]
After ... far too long trying to figure out how to do testing, I stumbled upon `google-datastore-emulator`, which makes life way easier.

Can we document that a nice test runner if you use datastore would look something like...

```js
const spawn = require('child_process').spawn;
const DatastoreEmulator = require('google-datastore-emulator');

// Create a datastore emulator.
const datastoreEmulator = new DatastoreEmulator({
  projectId: 'projectId',
  storeOnDisk: false,
  clean: true,
});

// Args passed to this runner should be forwarded to mocha.
// Things can be run as node script.js --args or just nodescript --args
let args = process.argv;
if (args[0] == process.execPath) {
  args = args.slice(1);
}
args = args.slice(1);

// Start the emulator.
datastoreEmulator.start().then(() => {
  // Run mocha as a child process.
  const mochaProcess = spawn('mocha', args, { stdio: 'inherit' });
  // When the process exits, stop the emulator, and exit with the same exit code.
  mochaProcess.on('exit', (code, signal) => {
    datastoreEmulator.stop().then(() => {
      process.exit(code);
    });
  });
});
```

**Comment by lukesneeringer** [comment]
@stephenplusplus This seems reasonable. How long would it take to add a page like this?

**Comment by jgeewax** [comment]
We should also note that you need to install the Cloud SDK, and the beta commands, and the datastore emulator :)

**Comment by callmehiphop** [comment]
Where would something like this live on the site? My initial thought would be to add some kind of guide to the `Getting Started` section that gives a general overview of unit testing for any module with a list of emulator modules (where applicable) per API?

**Comment by lukesneeringer** [comment]
I would be fine with that. I would probably be okay making this something that happens after the repo reorg; we could do Datastore early.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-datastore/issues/11.
