### ISSUE TITLE
Spanner client should provide a way for users to specify timeouts

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-node#2442]
Currently it seems that there is no way for users to override the default timeouts for Spanner rpc calls. We should add such a way especially since Spanner rpc calls like ExecuteStreamingSql can take arbitrarily long based on how much data one is streaming and other parameters. So there is really no good default value except for unlimited or something really large.

**Comment by stephenplusplus** [comment]
This is actually tracked in #1859, which I agree is important, and affects many of our APIs.

**Comment by smick** [comment]
What is the ETA for supporting default timeout overrides? The nodeJs client currently limits queries to 30 seconds, whereas the web UI allows for longer running queries. This is a huge limitation for customers like us looking to query even moderately large datasets with simple filters and joins.
