### ISSUE TITLE
Auth error:Error: invalid_grant on windows 7

### ISSUE THREAD

**Issue by svsh227** [GoogleCloudPlatform/google-cloud-node#2455]
I am using @google-cloud/speech but while doing node app.js I am getting  Auth error: Error: invalid_grant.
I am searching on google but I couldn't get my solutions. Please tell me how to remove this error.
My code is:

```js
const Speech = require('@google-cloud/speech')({
  projectId: 'natural-numbus-123456789',
  keyFilename: './myman-123456789.json'
});
process.env.GOOGLE_APPLICATION_CREDENTIALS = './myman-123456789.json'
const projectId = 'natural-numbus-123456789';
const fileName = "gs://cloud-samples-tests/myman/brooklyn.flac";
const options = {
  encoding: 'FLAC',
  sampleRateHertz: 16000,
  languageCode: 'en-US'
};
Speech.recognize(fileName, options)
  .then((results) => {
    console.log(results);
    const transcription = results[0];
    console.log(`Transcription: ${transcription}`);
  })
  .catch((err) => {
    console.error('ERROR:', err);
  });
```

On linux its working fine. But on windows i got error.

**Comment by stephenplusplus** [comment]
The `invalid_grant` error is a notoriously difficult one to debug. I would try removing these lines:

```
process.env.GOOGLE_APPLICATION_CREDENTIALS = './myman-123456789.json'
const projectId = 'natural-numbus-123456789';
```

By providing those paths during the Speech instantiation, the API client has all it needs.

As far as it working on Windows and not Linux, that is hard for me to come up with an explanation. Is there anything unique/worth mentioning about how you are running the program? Are you running parallel processes, local systems, containers? Also, please list the versions of the environment (OS, Node.js, npm, `@google-cloud/storage`).

**Comment by stephenplusplus** [comment]
@svsh227 Please let me know if you are still having problems getting this working.
