### ISSUE TITLE
Support for batch upload

### ISSUE THREAD

**Issue by caccialdo** [GoogleCloudPlatform/google-cloud-node#2457]
From reading [this section](https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch) of the REST API documentation for GCS, it seems the service supports batch uploads.

Looking at the [code](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/common/src/util.js#L235) generating the request, it doesn't look like there is any way to leverage that feature.

Our team is looking at uploading more than 100,000 small JS files to GCS and would benefit from a native batch upload support from the Node library.

**Comment by stephenplusplus** [comment]
I saw a little notice on that page:

> Note: Currently, Google Cloud Storage does not support batch operations for media, either for upload or download.

We don't support the batch API for the other calls (updating metadata, deleting objects, etc), and I'm not sure if that's something that we intend to support (cc @lukesneeringer to make the call).

I would recommend disabling resumable uploads for the small files you are uploading, which would look like:

```js
var file = bucket.file('my-file')

file.createWriteStream({ resumable: false })
// or
file.save('data', { resumable: false }, callback)
```

**Comment by caccialdo** [comment]
@stephenplusplus My bad for misreading this note. I didn't really batching was only supporting for metadata or actions on files.

I'm sure there's a reason for such limitation. Would be curious to know the reason behind it though.

**Comment by stephenplusplus** [comment]
No problem. I'm going to close, since we don't have any changes to make in this library. If we decide to support batching on the API calls that can handle it, we can re-open. If anyone happens to see this who can chime in with an answer on why, feel free :)
