### ISSUE TITLE
Problem with speechRecognition  response 

### ISSUE THREAD

**Issue by iankit3** [GoogleCloudPlatform/google-cloud-node#2460]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 6.9.2
  - npm version: 4.0.5
  - google-cloud-node version:
  - google-cloud/speech : 0.6.0

#### Steps to reproduce

  1. require `google-cloud`
  2.  .....

Basically it is not an issue (NOT A ISSUE)
Need some help.
I am using the speechToText node apis

I have a function 
```
    //some function
    function startStreamingRecognize(audioStream, encoding, sampleRate, webSocket) {

      const request = {
        config: {
          encoding: "LINEAR16",
          sampleRate: 44100,
          languageCode: 'en-US',
        }
      };

      const recognizeStream = speech.createRecognizeStream(request)
        .on('error', (error) => {
          console.error;
        })
        .on('data', (data) => {
          if ('results' in data && data.results.length > 1)
            webSocket.send(data.results);
        });
      audioStream.pipe(recognizeStream)
    }


    //calling the speech fn for every msg recieved
    ws.on('message', function incoming(message) {
      STREAM.push(message); // STREAM is a global variable
      recog(STREAM, 'LINEAR16', 44100, ws);
    })
```
The results that i am getting is like below attached img 
![my_speech_ws](https://user-images.githubusercontent.com/9150788/28264469-b1ac3d30-6b08-11e7-9688-b4be0d569fb0.png)
I am not getting the results while recording

But the expected is like Duplex like response as below as it works at 
[Google](https://cloud.google.com/speech)
![google_speech_ws](https://user-images.githubusercontent.com/9150788/28264493-dcff0026-6b08-11e7-8357-ebee8d41562e.png)

Is there something wrong with , how i am dealing with streams 
             or
Is as simple as adding some
  ```
  recognitionConfig {
     interim_results: true,
   }
```
Can you please help or you can close this.

**Comment by iankit3** [comment]
Closing it as it is working by adding `interimResults": true` instead of `interim_results` 
I am very sorry  :)   :(

**Comment by lukesneeringer** [comment]
Hi @iankit3,
Glad you got everything working! :-)
