### ISSUE TITLE
docs: (google-cloud) gapic versions acting as first class APIs

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2462]
The nav bar on the docs site:

![image](https://user-images.githubusercontent.com/723048/28323856-f6e7b952-6ba7-11e7-8a5b-3a80b3876741.png)

These are all from the packages _inside_ of google-cloud, e.g. `v1` is from `@google-cloud/datastore` (https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.0.6/v1). We need to find a way to stuff them back inside of their proper parent, so that `v1` is nested under the `Datastore` link.

**Comment by lukesneeringer** [comment]
@stephenplusplus Poke on this (on Monday). I really, really want to get this to disappear. It looks really awful.

**Comment by stephenplusplus** [comment]
Many hours went to this last week, and it's unfortunately quite a lift. I might need to rethink my approach, with some guidance from @callmehiphop.

A quick fix that came to mind would be linking directly to the sub-module's API documentation page. UX takes a hit in this case, because the context of viewing docs in the umbrella mode would be lost.

**Comment by lukesneeringer** [comment]
Let's discuss in the standup on Monday (after we get through the common stuff since we are combining the languages). I would be okay with a stopgap solution considering we only need to get through a month or two. I just want something that does not look embarrassing. :-)

**Comment by stephenplusplus** [comment]
The docs are fixed. Here's [master](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/master/google-cloud) and the latest release, [0.56.0](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/google-cloud).
