### ISSUE TITLE
[Storage-request] Provide an example of setting the default storage class for a bucket.

### ISSUE THREAD

**Issue by frankyn** [GoogleCloudPlatform/google-cloud-node#2471]
Hi,

This is a request to provide an example of setting the default storage class for a Storage bucket. The current method for updating the storageClass isn't clear or visible in the documentation. Although, I'm not sure if it makes sense for the Nodejs community to have this documented. I'm open to interpretation! 

```
var gcs = require('@google-cloud/storage')({projectId: "spec-test-ruby-samples"});

var bucket = gcs.bucket("bucketname");

bucket.setMetadata({storageClass: "STORAGE_CLASS"});
```

**Comment by stephenplusplus** [comment]
PR sent to add a method "bucket.setStorageClass()"! #2473

**Comment by frankyn** [comment]
Thanks @stephenplusplus! I'll follow-up with comments to that PR.
