### ISSUE TITLE
table.import fails with an error that says "not a query job" with code 400

### ISSUE THREAD

**Issue by cpl-no-takahashi** [GoogleCloudPlatform/google-cloud-node#2480]
Hello

I am having an issue with `table.import(...)`.
I am trying to import a csv data file to my table, but it errors out and the error says that it is not a valid query.
Now I am not trying to run a query so this error really confuses me and I cannot seem to find anything related to this issue on the official doc either.
It would be really awesome, if you could point me to the right direction.

Thank you in advance.

#### Environment details

  - OS: AWS Linux
  - Node.js version: 5.7.1
  - npm version: not present
  - google-cloud-node version: 0.9.6

#### Steps to reproduce

  1. require `google-cloud`
  2. create table (assuming there's dataset already)
  3. table.import('my/local/data.csv', () => { .... });
  4: error: 
  ```
  { [ApiError: Job 82403560600:job_BegGnEVvszMIy79s1PjxS8VpIc4 is not a query job]
  code: 400,
  errors:
   [ { domain: 'global',
       reason: 'invalid',
       message: 'Job 82403560600:job_BegGnEVvszMIy79s1PjxS8VpIc4 is not a query job' } ],
  response: undefined,
  message: 'Job 82403560600:job_BegGnEVvszMIy79s1PjxS8VpIc4 is not a query job' }
  ```

**Comment by stephenplusplus** [comment]
Hi @cpl-no-takahashi, sorry for the trouble. I haven't been able to reproduce. When you use a local file path with `table.import`, it is using a different method, `table.createWriteStream` behind the scenes. In case you want to see if you have different results using that method, the code should look something like this:

```js
var fs = require('fs')

fs.createReadStream('my/local/data.csv')
  .on('error', err => {})
  .pipe(table.createWriteStream({ sourceFormat: 'CSV' }))
  .on('error', err => {})
  .on('complete', job => {
    job
      .on('error', err => {})
      .on('complete', () => {})
  })
```

Since I can't reproduce, could you provide a gist or repo that I can clone, which would give me an isolated instance of the issue?

**Comment by cpl-no-takahashi** [comment]
Hello @stephenplusplus 

Thank you for the response. I don't have to repository at the moment, but I am pasting the test code that I was using. I hope this helps.

```javascript
'use strict';

const fs = require('fs');
const bq = require('@google-cloud/bigquery')({
	projectId: '<private>',
	keyFilename: __dirname + '/bigquerykeyfile.json'
});

const dataset = bq.dataset('report_staging');

const TABLE = 'test101';

console.log('start');

dataset.get(function (error, ds) {
	if (error) {
		return console.error(1, error);
	}

	console.log('create table');

	ds.createTable(TABLE, { schema: 'id:string,action:string,ts:timestamp' }, function (error, table) {
		if (error) {
			if (error.code !== 409) {
				console.error(2, error);
			}
			table = ds.table(TABLE);
		}
		table.import(__dirname + '/test2.csv', { sourceFormat: 'CSV' }, function (error, job) {
			if (error) {
				return console.error(3, error);
			}

			console.log('Import complete look at the job');

			job.getQueryResults(function (error, rows) {
				if (error) {
                                        // This is where I see the said error
					return console.error(4, error);
				}
				console.log('done:', rows.length);
			});
		});
```

**Comment by stephenplusplus** [comment]
Thanks for the snippet, I think I see the issue now. Instead of the `job.getQueryResults` line, just use the returned job's event emitter:

```js
job
  .on('error', function (error) {
    console.error(4, error);
  })
  .on('complete', function (apiResponse) {
    console.log('done:', apiResponse.statistics.load.outputRows);
  });
```

Let me know if there are any issues with this!

**Comment by cpl-no-takahashi** [comment]
Awesome. Thank you for the help!
