### ISSUE TITLE
Docs example -> Storage -> File -> createReadStream

### ISSUE THREAD

**Issue by deltaepsilon** [GoogleCloudPlatform/google-cloud-node#2481]
The example for [file.createReadStream](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.41.2/storage/file?method=createReadStream) calls the event ```response``` when it should be ```data```.

Current:
```javascript
remoteFile.createReadStream()
  .on('response', function(response) {
    // do stuff
   });
```

Current:
```javascript
remoteFile.createReadStream()
  .on('data', function(response) {
    // do stuff
   });
```

**Comment by stephenplusplus** [comment]
We emit `response` with the HTTP response. The docs show:

```js
remoteFile.createReadStream()
  .on('error', function(err) {})
  .on('response', function(response) {
    // Server connected and responded with the specified status and headers.
   })
  .on('end', function() {
    // The file is fully downloaded.
  })
  .pipe(fs.createWriteStream(localFilename));
```

The `pipe` call with another stream channels the `data` events to it automatically, which is why we don't document it specifically.
