### ISSUE TITLE
Cannot install @google-cloud/storage

### ISSUE THREAD

**Issue by chrisabrams** [GoogleCloudPlatform/google-cloud-node#2482]
#### Environment details

  - OS: OS X 10.12.4
  - Node.js version: 8.2.1
  - npm version: 5.3.0
  - google-cloud-node version: dunno?

#### Steps to reproduce

  1. `npm install @google-cloud/storage`

Results in:

```
npm install @google-cloud/storage
npm ERR! code E404
npm ERR! 404 Not Found: @google-cloud/storage@latest
```

**Comment by chrisabrams** [comment]
@JustinBeckwith im going to assume this was a fat finger? :O

**Comment by JustinBeckwith** [comment]
Aye, apologies :)
