### ISSUE TITLE
Node Vision SDK underperforming in simple case when compared to the GCloud Vision demo

### ISSUE THREAD

**Issue by maephisto** [GoogleCloudPlatform/google-cloud-node#2490]
#### Environment details

  - OS: MacOS
  - Node.js version: 8.1.4
  - npm version: 5.0.3
  - @google-cloud/vision version: 0.11.4

#### Steps to reproduce

1. download the sample image
![sample](https://user-images.githubusercontent.com/3056582/28569874-fe84c01c-713b-11e7-8cb7-dce5e0cb10f0.png)

As it is pretty clear, you'd expect it to return the capital letter "M" in the text detection field.

  2. Fire up a text editor and run the below node snippet in a env that already has GCloud authentification setup. You will also need the Vision API enabled

```javascript
'use strict';

const vision = require('@google-cloud/vision')();

const options = {
  imagePath: __dirname + '/sample.png'
}

vision.detectText(options.imagePath).then((result) => {
  console.log('this is the result', JSON.stringify(result));
});
```
 Now the result looks like this:
```json
[
   [

   ],
   {
      "responses":[
         {
            "faceAnnotations":[],
            "landmarkAnnotations":[],
            "logoAnnotations":[],
            "labelAnnotations":[],
            "textAnnotations":[],
            "fullTextAnnotation":null,
            "safeSearchAnnotation":null,
            "imagePropertiesAnnotation":null,
            "cropHintsAnnotation":null,
            "webDetection":null,
            "error":null
         }
      ]
   }
]
```

If i test the same sample image on GCloud Vision landing page demo, the result is correct: the letter `M`
![screenshot 2017-07-25 11 01 34](https://user-images.githubusercontent.com/3056582/28569985-64ad0a34-713c-11e7-89fc-8f81763122b0.png)

https://cloud.google.com/vision/

Since this is a pretty clear image and 1 single character, I'm having trouble understanding why does the accuracy differ.
I noticed this issue also on other sample images - they work in the demo but not using the Node SDK.

**Comment by stephenplusplus** [comment]
This is interesting, indeed. Thanks for reporting.

Here is the request and response payload:

```js
// request
[
  {
    "image": {
      "source": {
        "imageUri": "https://user-images.githubusercontent.com/3056582/28569874-fe84c01c-713b-11e7-8cb7-dce5e0cb10f0.png"
      }
    },
    "features": [
      {
        "type": "TEXT_DETECTION"
      }
    ]
  }
]

// response
{
  "responses": [
    {
      "faceAnnotations": [],
      "landmarkAnnotations": [],
      "logoAnnotations": [],
      "labelAnnotations": [],
      "textAnnotations": [],
      "fullTextAnnotation": null,
      "safeSearchAnnotation": null,
      "imagePropertiesAnnotation": null,
      "cropHintsAnnotation": null,
      "webDetection": null,
      "error": null
    }
  ]
}
```

@lukesneeringer any ideas?

**Comment by maephisto** [comment]
Thank you for verifying the issue @stephenplusplus.
Looking forward to any ideas on how to overcome this issue.

**Comment by lukesneeringer** [comment]
Poking to say I have seen this and want to look at it ASAP.

**Comment by lukesneeringer** [comment]
Hey @maephisto,
I went to troubleshoot this just now, and realized you are on an old version. We actually changed this API pretty drastically in 0.12.0; can you try it and see if you still have this problem?

**Comment by maephisto** [comment]
Thanks for the tip @lukesneeringer did not know that 0.12 is already available!

I've upgraded and re-tested.
Using `textDetection` has the same empty result.
But now, using `documentTextDetection` successfully detects the text `M\n`

Below is the tested code:
```javascript
'use strict';

const vision = require('@google-cloud/vision')({});

vision.documentTextDetection({ source: {filename: 'sample.png' }}).then((result) => {
  // the character "M" shows up correctly
});
vision.textDetection({ source: {filename: 'sample.png' }}).then((result) => {
  // Result is still empty
});
```

**Comment by lukesneeringer** [comment]
@maephisto Thanks. We will look at it again!

**Comment by maephisto** [comment]
@lukesneeringer thank you! any updates yet?

**Comment by lukesneeringer** [comment]
Okay, I _finally_ had some time to do some investigation on this.
I can confirm that it is not a problem with the client library, because API explorer does the same thing:

![text_detection](https://user-images.githubusercontent.com/4346/30284718-909fab7e-96d0-11e7-8312-9ca53f4fb912.png)

![document_text_detection](https://user-images.githubusercontent.com/4346/30284724-9359d8d0-96d0-11e7-967f-30549ea33552.png)

I am sending this issue over to the Vision team to hopefully get a resolution.

**Comment by lukesneeringer** [comment]
![document_text_detection](https://user-images.githubusercontent.com/4346/30284807-d95c59ca-96d0-11e7-97cd-8251c275c6e1.png)
![text_detection](https://user-images.githubusercontent.com/4346/30284815-dcbf70d4-96d0-11e7-82d2-881b03dec7b4.png)

**Comment by lukesneeringer** [comment]
Okay, I got a reply back from the backend team. However, the bad news is that they basically said, "It is machine learning; not much we can do." :-/

I recommend using DOCUMENT_TEXT_DETECTION.

**Comment by m3hari** [comment]
Hitting this in 2024. The demo on https://cloud.google.com/vision?hl=en#demo performs much better than the SDK. 

We are using the `builtin/latest` model. It seems there is no much we can do 🤔 

Any help or suggestion would be appreciated
