### ISSUE TITLE
Have you any plans for add App Engine?

### ISSUE THREAD

**Issue by adostal** [GoogleCloudPlatform/google-cloud-node#2496]
I would like use automatic deploy via cloud functions. But now is not very ussefull because this client doesn't have API for App Engine.

Have you any plans for add App Engine?

**Comment by lukesneeringer** [comment]
Hi @adostal,
Right now, we do not have any short-term plans to add the App Engine API, although this is something it would be interesting to do in the future.

Thank you for asking, and we will keep this request in mind!
