### ISSUE TITLE
API key authentication doesn't work for Cloud Natural Language

### ISSUE THREAD

**Issue by anotheri** [GoogleCloudPlatform/google-cloud-node#2498]
#### Environment details

  - OS: `Ubuntu`
  - Node.js version: `8.1.4`
  - npm version: `5.0.3`
  - `"@google-cloud/language": "^0.11.0"`

#### Steps to reproduce

```
  const language = require( '@google-cloud/language' )( {
    projectId: <MY_PROJECT_ID>,
    key: <MY_API_KEY>
  } );
```

It throws:
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): 
Error: Could not load the default credentials. 
Browse to https://developers.google.com/accounts/docs/application-default-credentials 
for more information.
```

It works with `credentials` object and with config json file, but it fails with API key.
Please advise or fix.

**Comment by anotheri** [comment]
And it looks like API key auth doesn't work for other packages as well, see: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1424

**Comment by lukesneeringer** [comment]
This is something that just got a decent bit of discussion internally on the Python side, where we _did_ have support and [actively removed it](https://github.com/GoogleCloudPlatform/google-cloud-python/pull/2823/). Essentially, API keys are a discouraged form of authentication at this point, and we do not intend to support them in client libraries.

**Comment by anotheri** [comment]
@lukesneeringer thanks for the answer; that'd be super helpful to add a clear note that API key auth is not supported in the documentation then.
