### ISSUE TITLE
Translate API usage

### ISSUE THREAD

**Issue by hung-phan** [GoogleCloudPlatform/google-cloud-node#2505]
#### Environment details

OS: Mac OS 10.12.6
Node.js version: 6.11.0
npm version: 3.10.10
google-cloud-node version: 1.0.0

#### Steps to reproduce

```
const gcloud_translator = require('@google-cloud/translate')({ key: GCLOUD_API_KEY, promise: Promise });

module.exports.translate = (msg, from, to) => {
	// https://googlecloudplatform.github.io/google-cloud-node/#/docs/translate/1.0.0/translate?method=translate
	return gcloud_translator
		.translate(msg, { from, to })
		.then(data => {
			const translation = data[0];
			// const api_response = data[1];

			return Array.isArray(msg) ? arrify(translation) : translation;
		});
};
```

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/translate-1.0.0/packages/translate/src/index.js#L371 and https://github.com/GoogleCloudPlatform/google-cloud-node/blob/translate-1.0.0/packages/translate/src/index.js#L410

This is causing inconsistency in returning messages via the API. For example, 

```
gcloud_translator.translate('Hello world', { from: 'en', to: 'vn' }).then(data => {
  const translation = data[0];

  // translation is a string
})
```

```
gcloud_translator.translate(['Hello world'], { from: 'en', to: 'vn' }).then(data => {
  const translation = data[0];

  // translation is also a string, which is unexpected
})
```

In other case like

```
gcloud_translator.translate(['Hello world', 'How are you doing?'], { from: 'en', to: 'vn' }).then(data => {
  const translation = data[0];

  // translation is an array, which is expected
})
```

I think this line https://github.com/GoogleCloudPlatform/google-cloud-node/blob/translate-1.0.0/packages/translate/src/index.js#L410 should rely on the default input instead of arrify version to return correctly data to the caller

**Comment by lukesneeringer** [comment]
Hmm. I agree that this is a bug. We probably need to store whether we got a string or an array originally so that we can send back the right thing even if we get an array with a length of 1.

**Comment by stephenplusplus** [comment]
Agree as well. To fix would be a breaking change, forcing us to go to `2.0.0`.

**Comment by hung-phan** [comment]
The same problem apply for `detect` https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/translate/src/index.js#L179 and https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/translate/src/index.js#L154

**Comment by lukesneeringer** [comment]
@stephenplusplus I am of two minds about that. I agree that it is different, but it is not clear to me whether it is _breaking_. The current behavior does the flatly wrong thing. I expect not many users use arrays with a length of 1 (the case where you do is when it is dynamically populated).

**Comment by stephenplusplus** [comment]
I can see that side, and that would be a more convenient side to lean to, so we don't have to bump the major. However, I think the right thing is to mark it as breaking-- it is indeed a bug, but the user wasn't using our API incorrectly. When they upgrade and try to use the same code, they're going to be dealing with a different type of argument than they were before. That's my justification for why I would mark it as breaking, regardless of other statistics that could try to define a gray area. Regardless, I'm happy to proceed with how you see it, based on your experience.

**Comment by lukesneeringer** [comment]
I am going to make a call that this is a semver-minor change. My rationale is that it is actually _a correction of broken behavior_, that a regular developer is unlikely to rely on (since if you were doing that on purpose, you would send a string and not an array).

**Comment by hung-phan** [comment]
We have that behaviour in production for our chat system. Sometimes, we have to bundle all messages and translate them as once, however there is case where user only send a single message that is where the array of length 1 comes from.

**Comment by lukesneeringer** [comment]
@hung-phan That is sort of the situation I figured you were in. I am assuming that once we return an array properly, your code will still do the right thing?

**Comment by hung-phan** [comment]
Yes
