### ISSUE TITLE
[Storage API] Content-Disposition Header can't be passed on upload

### ISSUE THREAD

**Issue by MDSLKTR** [GoogleCloudPlatform/google-cloud-node#2507]
If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Debian Jessie
  - Node.js version: 6.11.1
  - npm version: 3.10.10
  - google-cloud-storage: 1.2.1

#### Steps to reproduce

have these CORS settings:
```
bucket.setMetadata({
    cors: [
        {
            origin: ['*'],
            responseHeader: ['Content-Type', 'Cache-Control', 'Expires', 'Last-Modified', 'Content-Disposition'],
            method: ['*'],
            maxAgeSeconds: 3600,
        },
    ],
}, (err) => {
    logger.log(err);
});
```
have these options to pass on upload
```
let options = {
                    gzip: true,
                    validation: false,
                    contentType: 'application/octet-stream',
                    contentDisposition: 'attachment',
                    metadata: {
                        contentType: 'application/octet-stream',
                        contentDisposition: `attachment; filename='${fileObject.remoteFileName}`,
                    },
                    headers: {
                        contentType: 'application/octet-stream',
                        contentDisposition: 'attachment',
                    },
                };
```
Upload a file to the bucket with above options:
```
bucket.upload(fileObject.sourcePath, options)
                        .then((data) => {
                            logger.log(`[STORAGE]: ${fileObject.remoteFileName} uploaded`);
                            innerResolve();
                        })
                        .catch(err => {
                            logger.log(err);
                            innerResolve(null);
                        });
```

As you can see i tried every variant but the header is never included in the response when requesting the file from the permalink. If i set the Content Disposition via the gcloud console gui, it works immediately.

Thanks in Advance,
Simon

**Comment by stephenplusplus** [comment]
Thanks for filing. I'm having luck with all of this, actually. Would you mind putting together a sample repo that I clone and run? I've set the metadata on a bucket as you did, uploaded the file with the settings as you did, and `curl -I {publicUrl}` and saw the disposition header returned.

And just a quick note, the way to set the header is just in the metadata:

```js
let options = {
  // ...
  metadata: {
    contentDisposition: '...'
  }
}
```

**Comment by MDSLKTR** [comment]
Turns out i had completly ignored the case that for this specific file type where  i was using `createWriteStream` which was lacking the options object completly. So setting up a testcase actually made me look closer again 👍. Thanks for the clarification on the settings and the quick support!
