### ISSUE TITLE
bigquery: API improvements

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2511]
#### Querying

- [x] Change high-level query to use jobs.
- [x] Auto-generate Job IDs on client
- [x] Allow for user specified prefix for Job IDs

#### Jobs

- [ ] Media upload support
- [ ] Fields
- [ ] Labels
- [ ] "all" flag for job.list

#### Tables

- [x] Partitioning
- [x] Views
- [x] Labels
- [x] Expiration
- [x] etag Support

#### Datasets

- [ ] ACL support
- [x] Labels
- [x] Default expiration
- [x] etag Support

**Comment by landrito** [comment]
@stephenplusplus can you update this issue with a little bit more detail for documentation purposes.

**Comment by stephenplusplus** [comment]
*redirects request to @callmehiphop*
