### ISSUE TITLE
Ability to specify serviceContext for logging-winston

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#2513]
_Originally reported by @vic3lord on https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2435._

Having the same issue, also I cannot state serviceContext Object in logging-winston directly without using error-reporting.

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/logging-winston/src/index.js#L174

Let me know if I can do anything to help, even to provide info.

**Comment by ofrobots** [comment]
Hi @vic3lord. Is your application running on GCP or elsewhere? On GCP running apps, we should auto-discover the service. However, if you are running locally, on-premise or elsewhere, that's the case where would use the 'global' resource descriptor. Is that your case?

**Comment by vic3lord** [comment]
I am running it on gke, I want to separate each container name to be a different service both in cloud logging and error-reporting, since each container is an actual service.
