### ISSUE TITLE
Please provide more specific guidance on "google-cloud is deprecated"

### ISSUE THREAD

**Issue by DazWilkin** [GoogleCloudPlatform/google-cloud-node#2518]
For those of us who don't use Node on a daily basis and can't immediately map the consequences of the unbundling of the gCloud packages, please provide more detailed guidance to help us through this change.

I assume this problem recurs across the documentation for each of supported GCP services:

## Currently

https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/storage/file

>google-cloud is deprecated
Due to the scope of our API rapidly increasing, you may notice a decrease in performance if you continue to use the bundled module, google-cloud.

>Going forward, please install only the individual service modules that you need, such as @google-cloud/storage.

but the documentation reflects what's now not-recommended:

```javascript
var gcloud = require('google-cloud');
var gcs = gcloud.storage();
```

## Recommend

> If you are using or would prefer to use the bundled module:

```javascript
var gcloud = require('google-cloud');
var storage = gcloud.storage();
```

> Recommend: If you are using or would prefer to use the individual service module for storage:

```javascript
var Storage = require('@google-cloud/storage');
var storage = Storage();
```

**Comment by landrito** [comment]
Hi Daz, Thanks for pointing this out! We'll get this documentation updated soon.

**Comment by stephenplusplus** [comment]
There is a context flip that happens depending on the module you're reading about. In this case, you're browsing the documentation for `google-cloud`, so you are shown examples about how to use the Storage API from within it. If you browse to the [`@google-cloud/storage` page](https://googlecloudplatform.github.io/google-cloud-node/#/docs/storage/1.2.0/storage), you'll get the appropriate instantiation example:

```js
var gcs = require('@google-cloud/storage')({
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
});
```

We could extend the `google-cloud` example as you suggested, however we would be saying that "npm install @google-cloud/storage" will give you the same API as the one `google-cloud` bundles, which isn't always true.

I would suggest we simply link to the module from the deprecation notice:

![image](https://user-images.githubusercontent.com/723048/29135835-6e113040-7d09-11e7-8ca3-46d9937a710b.png)

That will land the user on the right spot to learn about getting started with the new module.

**Comment by DazWilkin** [comment]
Ah, I didn't realize there are per-module pages too... @stephenplusplus solution is good.

I'm arriving at the docs (mostly) through the front page. Now you point out the per-module pages, I see the dropdown to choose between them. I had not noticed it until then.

**Comment by landrito** [comment]
Ah thanks for the clarification on this @stephenplusplus!
