### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by mastoj** [GoogleCloudPlatform/google-cloud-node#2521]
There is a small typo in the documentation here: https://googlecloudplatform.github.io/google-cloud-node/#/docs/logging/1.0.3/logging/entry

the code `if (!error) ` should be `if (!err)`.

**Comment by stephenplusplus** [comment]
Thanks for reporting! Fixed in e83cb8b9e4ca39e6acc342045e3701039fe9117e
