### ISSUE TITLE
Cloud Storage: "Invalid Credentials" API response for default credentials in Cloud Functions

### ISSUE THREAD

**Issue by shaibt** [GoogleCloudPlatform/google-cloud-node#2527]
I have a few Firebase Cloud Functions (all node js of course) calling GCS objects using the @google-cloud/storage SDK for node JS (ver 1.2.1). 
For 3 hours today all calls from the function to the GCS API failed with "invalid credentials". Only when I redeployed the function using the firebase CLI did they start working again (no change to the function code). This has never happened before.
This is how the function authenticates:
`const gcs = require('@google-cloud/storage')();`

Really worrisome I cannot rely on the default authentication within the cloud platform to work. If I explicitly use a service account will this make sure problem doesn't reoccur?

#### Environment details
  - OS: Firebase/Google Cloud function environment
  - Node.js version: Firebase/Google Cloud function environment
  - google-cloud-node version: 1.2.1

**Comment by stephenplusplus** [comment]
Where you have `const gcs = ...`, is that within the function scope that is executed, or at the top level of the script?

Here are some related issues (although not the same error message):
- https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438
- https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2489

> If I explicitly use a service account will this make sure problem doesn't reoccur?

Yes, it should.

**Comment by shaibt** [comment]
Hi Stephen, 
The `const gcs = ...` line is declared at top of the script - not inside the function. This is following the firebase function code examples at [firebase/functions-samples](https://github.com/firebase/functions-samples). 
Reading the issues you linked to seems its better practice to move into the function scope. 

And, in addition, your recommendation is not use the default credentials and use an explicit service account?

**Comment by stephenplusplus** [comment]
Only going from recent reports of errors, I would say that's a safer bet until further investigation. Whichever you decide to try, please report back if there are any more errors and I'll re-open this issue. For now, I think we can say the same solution for #2438 will resolve this issue as well. Sorry for the trouble.

**Comment by shaibt** [comment]
Stephen,

In parallel I opened a support ticket to the Firebase team ~3 weeks ago and I've received a confirmation that they are actively working on a fix their side.
