### ISSUE TITLE
Tracing might not work as the following modules were loaded before the trace agent was initialized: ["once","assert-plus","qs"]

### ISSUE THREAD

**Issue by kilianc** [GoogleCloudPlatform/google-cloud-node#2531]
#### Environment details

  - OS: alpine
  - Node.js version: 7.10
  - npm version: N/A
  - google-cloud-node version: @google-cloud/trace-agent@2.1.2

#### Steps to reproduce

  1. require `trace-agent`

`ERROR:@google-cloud/trace-agent: Tracing might not work as the following modules were loaded before the trace agent was initialized: ["once","assert-plus","qs"]`

And this still shows up in `stdout` instead of `stderr`, we realized this was happening by mistake. see https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2432

**Comment by stephenplusplus** [comment]
I think the issues you opened on [cloud-trace-nodejs](https://github.com/GoogleCloudPlatform/cloud-trace-nodejs/issues/540) is the right place. We don't have that project in this repo.
