### ISSUE TITLE
Google Cloud Video Intelligence Node.js Library Doc link 404s

### ISSUE THREAD

**Issue by jpatokal** [GoogleCloudPlatform/google-cloud-node#2532]
The "v1beta1" link under the APIs navigation bar throws a "Not Found" error when clicking the link. 

The offending link: https://googlecloudplatform.github.io/google-cloud-node/#/docs/video-intelligence/0.1.1/video-intelligence --> https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/not-found

**Comment by stephenplusplus** [comment]
We're back! https://googlecloudplatform.github.io/google-cloud-node/#/docs/video-intelligence/0.1.1/video-intelligence/v1beta1

The only issue is with the "Data Types" link. #2486 is tracking the solution.
