### ISSUE TITLE
Update readme to include what keyFilename is

### ISSUE THREAD

**Issue by gauntface** [GoogleCloudPlatform/google-cloud-node#2534]
The readme uses keyFilename throughout but gives no link or description of what the "keyFilename" is.

**Comment by stephenplusplus** [comment]
We have a little blurb:

```
// Authenticating on a per-API-basis. You don't need to do this if you auth on a
// global basis (see Authentication section above).
```

We should just move that out from the code block and link to the Authentication section: https://github.com/GoogleCloudPlatform/google-cloud-node#authentication

**Comment by stephenplusplus** [comment]
The line is also awkward now, since we modularized. It should just be something like:

```md
See [Authentication](#authentication) above.`
```
