### ISSUE TITLE
Update module to use Promises.

### ISSUE THREAD

**Issue by gauntface** [GoogleCloudPlatform/google-cloud-node#2535]
Promises are pretty much the expected way of working with async code, if it's not supported, please update the code to do and if it is, please alter the demos in the readme to use promises and reference the callback approach as an option to using this API.

**Comment by stephenplusplus** [comment]
Dupe: #1699

This is in action as we move each `@google-cloud/{{module}}` out to its own repo, e.g. https://github.com/GoogleCloudPlatform/google-cloud-node-storage
