### ISSUE TITLE
Allow authentication without using keyfile method

### ISSUE THREAD

**Issue by Jahans3** [GoogleCloudPlatform/google-cloud-node#2536]
Using a keyfile is giving me version control and deployment headaches. With the other libraries and SDKs I use I am able to pass the values one by one, reading them from environment variables.

Using the language SDK however, I must pass a filepath to the SDK when I initialise it. Why is this? Would it not be better to allow us to pass values individually, so they can be more easily stored safely?

To avoid committing the file, I have to store the entire file in an environment variable in Heroku, and prior to initialising the SDK I write the contents to a file, then point the SDK to the file I just created. This doesn't seem like the intended solution, but I cannot find another way of doing this without committing the file to version control.

Thanks

#### Environment details

  - OS: Mac OS Sierra
  - Node.js version: 7.10.0
  - npm version: yarn v24.4
  - google-cloud-node version: 0.10.4

**Comment by stephenplusplus** [comment]
Check out https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/guides/authentication

You could set options.credentials with the JSON.parsed env var, or store the client_email and private_key properties from your key file as separate env vars and pass them as options.credentials.client_email and options.credentials.private_key.

**Comment by Jahans3** [comment]
Thanks @stephenplusplus, sorry for not noticing that.
