### ISSUE TITLE
Would it be possible to use @google-cloud/pubsub in Firebase Cloud Functions?

### ISSUE THREAD

**Issue by cristiano-belloni** [GoogleCloudPlatform/google-cloud-node#2537]
Hello, sorry if it's the wrong place. If it is, which is the most appropriate place to ask this question?

Would it be possible to use the module `@google-cloud/pubsub` in Firebase Cloud Functions as described in [the docs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.13.1/pubsub)?

If yes, would we need to specify a `projectId` and `keyFilename` or the authentication would be automatic like everywhere else in GCP?

**Comment by stephenplusplus** [comment]
It does work automatically, although you caught us while we're still sorting out an issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438#issuecomment-320952103

You could use the automatic authentication, until it gives you an issue (which might be never), or you could use the `options.keyFilename` or `options.credentials.client_email` and `options.credentials.private_key` settings.

One important thing you should do is instantiate the Pub/Sub module from within the called function itself, and not the script.

Let me know if you have any issues.

**Comment by cristiano-belloni** [comment]
Hi, @stephenplusplus! nice to meet you again :)

> One important thing you should do is instantiate the Pub/Sub module from within the called function itself, and not the script.

Mhhh... what do you mean with this?

**Comment by stephenplusplus** [comment]
You as well, it's been a while!

Sorry for being confusing. So, if a GCF script looks like this:

```js
'use strict'

var pubsub = require('@google-cloud/pubsub')

exports.myCloudFunction = function() {
  var pubsubClient = pubsub()
}
```

Instantiate the client inside of `exports.myCloudFunction`. This will make sure a proper automatic authentication cycle is restarted, mitigating the problems discovered in #2438.

**Comment by cristiano-belloni** [comment]
Cool! I'll be sure to instantiate inside and upload from CLI. many thanks as always.

**Comment by stephenplusplus** [comment]
Happy to help, come back anytime!
