### ISSUE TITLE
Cause for this error?

### ISSUE THREAD

**Issue by jyc979** [GoogleCloudPlatform/google-cloud-node#2539]
I keep getting the following error

"RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by <_Rendezvous of RPC that terminated with (StatusCode.INVALID_ARGUMENT, Invalid audio channel count)>)"

When trying to use the Google Cloud Speech API, I'm trying to use the sample audio file saved on my local computer. But it works fine with cloud-sample-test audio file given by google. Any possible fixes?

**Comment by stephenplusplus** [comment]
Hey @jyc979, sorry for the trouble. Could you paste the code you're using to make the API call that is failing? Additionally, the version of the Speech module that you are using.

**Comment by jyc979** [comment]
`import os
 import io
def transcribe_file(speech_file):
    """Transcribe the given audio file."""
    from google.cloud import speech
    from google.cloud.speech import enums
    from google.cloud.speech import types
    client = speech.SpeechClient()

    with io.open(speech_file, 'rb') as audio_file:
        content = audio_file.read()

    audio = types.RecognitionAudio(content=content)
    config = types.RecognitionConfig(
        encoding='FLAC',
        sample_rate_hertz=44100,
        language_code='en-US')

    response = client.recognize(config, audio)
    alternatives = response.results[0].alternatives

    for alternative in alternatives:
        print('Transcript: {}'.format(alternative.transcript))`

Speech module was v1. I passed in the path of an audio file on my machine

**Comment by jyc979** [comment]
Also this is another error that I'm running into, it'd be really nice if you could take a look at this as well. After I obtain an access token, I use the audio sample that I created which is in .flac extension and is stored in Google Cloud storage(set to be public), then I use this command

```
curl -s -H "Content-Type: application/json" \
    -H "Authorization: Bearer Access Token” \
    https://speech.googleapis.com/v1/speech:recognize \
    -d @sync-request.json
```
to run the sync-request.json file that points to the audio that is stored in my google cloud storage, however it keeps giving me an error saying that I do not have the permission to call it.

**Comment by lukesneeringer** [comment]
Moving this over to google-cloud-python.

**Comment by lukesneeringer** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-python#3833
