### ISSUE TITLE
[Spanner] The default value (strong: true) hasn't been set when create a read-only transaction which cause slow data update

### ISSUE THREAD

**Issue by adamliuxy** [GoogleCloudPlatform/google-cloud-node#2542]
Hi,

If you follow the steps I listed below, I think you will get a very slow data update operation which will consume larger than 10 seconds(```table().update()```).
I found that if I add the option ```{strong: true}``` to call ```runTransaction```, the update function will run at a reasonable speed.

According to the [docs](https://cloud.google.com/spanner/docs/timestamp-bounds), the default timestamp bound types of the read-only transaction is ```Strong```. 
But I think the Spanner SDK ignore the default option in [database.runTransaction](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/spanner/src/database.js#L872-L884).

#### Environment details

  - OS: macOS 10.11.6
  - Node.js version: 8.1.3
  - npm version: 5.0.3
  - google-cloud-node version: 0.7.1

#### Steps to reproduce
1. require ```require('@google-cloud/spanner')```
2. Connect to Spanner
3. Select an instance and a database without any workload
4. create a table with this schema:
```
`CREATE TABLE bar (
	user_id STRING(64) NOT NULL,
	role STRING(64),
	level INT64
) PRIMARY KEY (user_id)`
```
5. insert sample data:
```
let sampleData = [
	{'user_id': '1', 'role': 'coder','level': 1},
	{'user_id': '2', 'role': 'coder', 'level': 1}
];
```
6. create a read-only transaction
7. use this transaction to run the following sql
8. and then update the record
```
let options = {
	readOnly: true
};
console.time('Step 1 read-only-transaction consume:');
database.runTransaction(options, function (err, transaction) {
	if (err) {
		throw (err);
	}

	let query1 = {
		sql: 'SELECT * FROM bar as t WHERE t.role = @role',
		params: {
			role: 'coder'
		}
	};
	transaction.run(query1, function (err1, dataset) {
		if (err1) {
			throw err1;
		}
		console.timeEnd('Step 1 read-only-transaction consume:');
		transaction.end();

		console.time('Step 2 DB update consume:');
		let dbOperation = [
			{user_id: '1', level: 2},
			{user_id: '2', level: 2}
		];

		database.table('bar').update(dbOperation, function (err2, apiResponse) {
			if (err2) {
				throw err2;
			}
			console.timeEnd('Step 2 DB update consume:');
		});
	});
});
```
9. Get the following result(the step 2 consume large than 10 seconds)
```
Step 1 read-only-transaction consume:: 1562.155ms
Step 2 DB update consume:: 15148.733ms
```

Thanks!

**Comment by stephenplusplus** [comment]
cc @vkedia

**Comment by vkedia** [comment]
Ideally the time taken by the update operation should be independent of what happened in the preceding read only transaction. Read only transactions do not take any locks not matter what timestamp bound it is so they will never conflict with a read write transaction.
Is it possible that somehow the database.runTransaction is starting a read write transaction?

**Comment by adamliuxy** [comment]
It's so weird that if I replace ```transaction.end()```with ```transaction.commit()``` in the read-only transaction, the update operation will run at a reasonable speed.
So how to start a read-only transaction properly? @vkedia 
I just follow this example: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/spanner/transaction.js#L30-L43

**Comment by callmehiphop** [comment]
@vkedia it is very possible that a read/write transaction is being returned here. Part of the original requirement was to begin a configurable amount of read only and read/write transactions when the client is instantiated. In the event that one type of transaction was unavailable return the other.

**Comment by vkedia** [comment]
@callmehiphop You should be able to verify that hypothesis by turning off the prewarming behavior (by setting the amount of r/w sessions to 0). Can you try to reproduce this?
Also if a session which was prewarmed with r/w transaction is used for read only transaction, it should still start a new reaonly transaction and discard the previously begun r/w transaction.

**Comment by adamliuxy** [comment]
Any updates?

**Comment by vkedia** [comment]
@lukesneeringer @callmehiphop This seems like a significant performance issue. Can we appropriately prioritize this?

**Comment by vkedia** [comment]
This also raises the question as to what does `transaction.end` do for read write transactions? Is it a no-op? Maybe it should instead raise an error?

**Comment by vkedia** [comment]
BTW now that we have figured out that this is due to a bug in the library, the label for this should be Bug and not perf.
