### ISSUE TITLE
logging: excessive log write time on Cloud Functions

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#2544]
_Originally reported by @deremer at https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2438#issuecomment-323405864._

> I've also discovered that in our cloud functions write.log() is taking about 15s to log to StackDriver... If I revert to console.error it is almost instantaneous. I've zeroed the delay in precision on to the call of log.write. If I print to console just before that line and then just after it is routinely 10-15s.

> We thought degraded performance of our functions was related to load, when in fact it seems to just be this method call...

**Comment by ofrobots** [comment]
Repro:

```js
const functions = require('firebase-functions');
const logging = require('@google-cloud/logging')();

const syslog = logging.log('mylog');

exports.helloWorld = functions.https.onRequest((request, response) => {
  let t = process.hrtime();
  syslog.error('sample stackdriver log entry').then(() => {
    t = process.hrtime(t);
    const ms = (t[0] * 1000) + (t[1] / 1e6);
    response.send(`Hello from Firebase! took ${ms}ms.`);
  }).catch((e) => {
    response.send(`syslog.error gave error ${e}`);
  });
});
```


```
Hello from Firebase! took 16715.34293ms.
```

I suspect that the problem is that logging (and other veneer libraries) do things lazily. For example, application default credentials, default resource detection, etc. are all done lazily and happen to take 16 seconds on the first request. Since cloud functions are aggressively throttled, this means that independent request take this long unless they happen to hit a warm function (i.e. if the request load is high enough).

/cc @stephenplusplus @jasonpolites

**Comment by stephenplusplus** [comment]
> application default credentials, default resource detection, etc. are all done lazily and happen to take 16 seconds on the first request

Have you tested that it takes 16 seconds locally?

**Comment by ofrobots** [comment]
Some initial profiling:

```
helloHttp ebzwjsaqqgdv 1503093039728 Function started helloHttp ebzwjsaqqgdv 
helloHttp ebzwjsaqqgdv 1503093039730 Log#write helloHttp ebzwjsaqqgdv 
helloHttp ebzwjsaqqgdv 1503093047004 Log#write#writeWithResource helloHttp ebzwjsaqqgdv 
helloHttp ebzwjsaqqgdv 1503093047005 Log#write#logging.request helloHttp ebzwjsaqqgdv 
helloHttp ebzwjsaqqgdv 1503093047192 Log#write#callback from logging.request helloHttp ebzwjsaqqgdv 
helloHttp ebzwjsaqqgdv 1503093047194 Function terminated helloHttp ebzwjsaqqgdv 
```

The timestamps are in milliseconds. It seems that the majority of the time is spent in `Metadata#getDefaultResource`.

**Comment by ofrobots** [comment]
Majority of the time is in `google-auto-auth:getEnvironment`:

```js
  getEnvironment (callback) {
    async.parallel([
      cb => this.isAppEngine(cb),
      cb => this.isCloudFunction(cb),
      cb => this.isComputeEngine(cb),
      cb => this.isContainerEngine(cb)
    ], () => {
      callback(null, this.environment);
    });
  }
```

Specifically, `isContainerEngine` is the slowest operation (probably because that looks for a key in the metadata service 404 in the metadata service).

I wonder if using `async.parallel` is the best choice here. The slowest operation becomes the bottleneck, even though, for cloud functions, the local environment is enough for us to make the determination.

**Comment by stephenplusplus** [comment]
@deremer -- we believe we've chased down the fix. Would you mind testing again? The fix should be automatically picked up by a new install of `@google-cloud/logging`.

**Comment by ofrobots** [comment]
Seems to be fixed in my own experiments. Let's keep this issue open until we can get feedback from @deremer.

**Comment by ofrobots** [comment]
I believe this is fixed. @deremer Please re-open if you still see issues.

**Comment by deremer** [comment]
@ofrobots Sorry, I lost track of this one... but I did want to let you know that based on my usage, this issue does in fact appear to be resolved. Also confirmed that only a redeploy of the function is required for the fix to take hold. Thanks for the fix!
