### ISSUE TITLE
[Bug] PubSub subscription: maxInProgress and interval in subscription.js do not work as expected

### ISSUE THREAD

**Issue by wei-hai** [GoogleCloudPlatform/google-cloud-node#2545]
#### Environment details

  - OS: MacOS
  - Node.js version: 8.3.0
  - npm version: 5.3.0
  - Google Cloud SDK 167.0.0
  - bq 2.0.25
  - core 2017.08.11
  - gcloud
  - gsutil 4.27

I set `maxInProgress` to 1 and `interval` to 1000, with 4 cores and using cluster module every 1 second the consumer should pull 4 messages, however within 1 second it pulled 27 messages. Do I misunderstand the way it works?

```
topic.subscribe(subscriptionName, {
      autoAck: false,
      interval: 1000,
      maxInProgress: 1,
      encoding: 'base64'
    }, (err, sub) => {
      if (err) {
        cb(err);
        return;
      }
...
```

**Comment by stephenplusplus** [comment]
Honestly, I'm not sure. But before we dive too deep into that, it would probably be better for you to prepare for the new release of the Pub/Sub module, which is a big rewrite with many new options for flow control. It's expected to release within the new few days, but it's in PR status currently: https://github.com/GoogleCloudPlatform/google-cloud-node/pull/2380

We're still working on the docs, but for now, these are the relevant options you'll have when creating a Subscription object: http://stephenplusplus.github.io/gcloud-node/#/docs/pubsub/master/pubsub/topic?method=createSubscription (see `options.flowControl`)

**Comment by wei-hai** [comment]
it looks like that in node js setTimeout doesn't respect the argument `interval` so that it fires too early, you may want to use a more accurate timer to replace the default setTimeout function in subscription.js, line 958.

**Comment by stephenplusplus** [comment]
How did you find out it doesn't respect `interval`?

**Comment by wei-hai** [comment]
I calculated the time diff between `Subscription.prototype.startPulling_` and output it in log, it turned out that the time diff is much smaller than `interval`

**Comment by wei-hai** [comment]
okay, I seem to find out why `interval` is not respected, when a message is ACKed, it triggers `refreshPausedStatus_` and then in `refreshPausedStatus_` it invokes `startPulling_` to update the status of `maxInProgress`. So if a message is ACKed before `setTimeOut()` fires it pulls more messages than scheduled. If there is too much data on PubSub initially and a consumer just starts, the destination server may be unable to handle the excessive write operations and will crash.

**Comment by ralfschimmel** [comment]
@stephenplusplus I am actually seeing this exact behaviour. I create a subscription on a topic, with `flowControl.maxMessages: 10` . Nevertheless when starting the subscriber it receives infinite data (queue was about 200K when this happened) and my pods go OOM. This meant recovery was really hard. How would I circumvent this? (0.14.1)

**Comment by stephenplusplus** [comment]
Hey @ralfschimmel, could you open a new issue? This issue was in reference to old code from <0.14.
