### ISSUE TITLE
When filtering a key lookup an error is raised

### ISSUE THREAD

**Issue by greenstatic** [GoogleCloudPlatform/google-cloud-node#2547]
The following GQL query for Google's Datastore works as I need:

`SELECT * FROM game WHERE Key(player, 838174389) = allPlayers`
where allPlayers in an array of keys.

But I am unable to copy this query into Node.js (using the official google-cloud-node npm package). The following doesn't work:
`let key = datastore.key('player', datastore.int("838174389"));
let query = datastore.createQuery('game');
query.filter(key, '=', 'allPlayers');`

I get a:

> property.trim is not a function error

I would perform the query directly using GQL, however at the time of writing, such a thing is not possible using the Node.js Datastore library (only Java and Ruby client libraries support it). As a temporary fix I could save the array `allPlayers` as an array of strings and then query using the string representation of a key, however this seems like more of a workaround than proper fix.

#### Environment details

  - OS: Linux Debian (testing)
  - Node.js version: v7.6.0
  - npm version: 4.1.2
  - google-cloud-node version: (@google-cloud/datastore) - 1.1.0

**Comment by stephenplusplus** [comment]
cc @pcostell -- do we have a way to support this query?

**Comment by pcostell** [comment]
This query is currently supported, I assume you just need to reverse the arguments to query.filter: `query.filter('allPlayers', '=', key)`

Note that we use equality, which is the [supported way in Cloud Datastore to search for elements in an array](https://cloud.google.com/datastore/docs/concepts/queries#array_values).

**Comment by stephenplusplus** [comment]
Thanks, @pcostell!

@greenstatic I'm going to close the issue, but please let us know if you have any more issues.
