### ISSUE TITLE
DNS Record.fromZoneRecord_ doesn't handle multiple records correctly (MX)

### ISSUE THREAD

**Issue by timwsuqld** [GoogleCloudPlatform/google-cloud-node#2552]
#### Environment details

  - OS: Linux
  - Node.js version: 4.2.6
  - npm version: 3.5.2
  - google-cloud-node version: 0.6.2

#### Steps to reproduce

When importing zone files (bind format) using `zone.import`, we call `Record.fromZoneRecord_` on each line. However, when you have multiple of the same record that should in be a single result set (i.e. MX records), it actually creates a record set per line, which doesn't result in the correct zone being created.

The `resourceRecordSets` `rrdatas` should be a list (https://cloud.google.com/dns/api/v1/resourceRecordSets#resource) of all the records, not multiple resourceRecordSets. The result is only the last MX record is imported.

This would probably also cause problems if for example you have multiple TXT records, or multiple A records.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-dns#8
