### ISSUE TITLE
extensionHeaders in method File.getSignedUrl do not work as expected

### ISSUE THREAD

**Issue by teemeh** [GoogleCloudPlatform/google-cloud-node#2559]
It's only noted in the documentation that the "extensionHeaders" needs to be an object with not a single example or link. While not using such key-value pair in config object, I can easily retrieve the file, setting a self-defined header in way described below, which I believe is the most common way, doesn't allow me to retrieve the file anymore with the error message "The request signature we calculated does not match the signature you provided."

#### Environment details

  - OS: ubuntu
  - Node.js version: v6.11.2
  - npm version: irrelavent
  - google-cloud-node version: latest

#### Steps to reproduce

1.`var myHeaders = { myHeader: "myHeader"};`
2.Then inside the config object, we have the key-value pair `extensionHeaders: myHeaders,`.
The config object then is fed to File.getSignedUrl().

No matter how I try (node.js request module or curl), the uncommented key-value pair (step 2) will always cause error, whereas the error is gone as soon as I comment that one line out in step 2 (logically, it doesn't matter if I delete the customized request header when doing the request). Not sure if it's the server's problem or google-cloud-node.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-storage#76
