### ISSUE TITLE
Speech v1.1 beta 1 protos

### ISSUE THREAD

**Issue by lukesneeringer** [GoogleCloudPlatform/google-cloud-node#2575]
@stephenplusplus Can you release a `google-proto-files` incorporating the Speech v1.1 beta1 protos as staged on the `speech-v1_1beta1` branch? Thanks.

**Comment by stephenplusplus** [comment]
Sorry, I can't seem to find the proto files in that branch. If you or someone else has them, you can link/send me them, and I will put them in a google-proto-files release.

**Comment by lukesneeringer** [comment]
Sorry about that!
They are now in this PR: https://github.com/googleapis/googleapis/pull/442

It should be merged very shortly.

**Comment by lukesneeringer** [comment]
Except that PR lacks the proto. Tracking it down.

**Comment by stephenplusplus** [comment]
I am pretty sure this is resolved.
