### ISSUE TITLE
ERROR: Can't install google-cloud npm package.

### ISSUE THREAD

**Issue by adsm1987** [GoogleCloudPlatform/google-cloud-node#2582]
#### Environment details

  - OS: Ubuntu 17.04
  - Node.js version: 8.4.0
  - npm version:  5.3.0
  - google-cloud-node version: 0.55.0

#### Steps to reproduce

Just try to install this module and is giving 404 in the npm registry!

Example:
`npm install google-cloud-node`

**Comment by stephenplusplus** [comment]
It's just called `google-cloud`. Does `npm install google-cloud` work?

**Comment by adsm1987** [comment]
`abraham@abraham-XPS-15-9560:/var/www/tvg4-e2e-server$ npm install google-cloud
npm ERR! code E404
npm ERR! 404 Not Found: @google-cloud/bigquery@0.9.6
`

**Comment by stephenplusplus** [comment]
@callmehiphop and I were able to install `google-cloud@0.55.0` successfully. I have to imagine this is some kind of temporary outage with npm.

> npm ERR! 404 Not Found: @google-cloud/bigquery@0.7.0

But, for me:

> npm install @google-cloud/bigquery@0.7.0
> + @google-cloud/bigquery@0.7.0

Can you keep an eye on it for the next little while and see if it sorts itself out?

**Comment by adsm1987** [comment]
i already tryed 2 hours ago and it's was the same... I will try tomorrow and see if it 's fixed if not ,i will try to downgrade my npm/node versions...

**Comment by adsm1987** [comment]
Updated: It's about the new npm version: 5.3.0 and node 8.4.0 with a downgraded version is working...

**Comment by ofrobots** [comment]
@adsm1987  Looking at the paste-bin (https://pastebin.com/31HmSAVi), it seems like you're still installing `google-cloud-node` rather than `google-cloud`.

**Comment by ricovitch** [comment]
I am also stuck at installing the packages from the @google-cloud namespace, with any nodejs/npm versions i tried, on windows7.
I'm trying to install the firebase-admin package which depends on some the @google-cloud packages.

Results of the following command on different configurations : npm install firebase-admin --save
* Node 8.4.1 - npm 5.3.0 : 404 Not Found: @google-cloud/common@0.13.4
* Node 7.10.1 - npm 4.2.0 : fetch failed https://registry.npmjs.org/@google-cloud/storage/-/storage-1.2.1.tgz
* Node 5.11.0 - npm 3.8.6 : fetch failed https://registry.npmjs.org/@google-cloud/storage/-/storage-1.2.1.tgz

I also tried with yarn with the same kind of failures : yarn add @google-cloud/common
* yarn 0.27.5 : error An unexpected error occurred: "https://registry.npmjs.org/@google-cloud%2fcommon: User not found"

**Comment by stephenplusplus** [comment]
Thanks for the info @ricovitch. I'm getting a Windows 7 VM set up so I can try to reproduce.

@adsm1987 -- have you tried again with npm@5.3.0 by chance? Curious to know if that resolved itself.

**Comment by adsm1987** [comment]
@stephenplusplus nop i used `nvm` and like i said, i downgraded the `npm` version to install it

**Comment by stephenplusplus** [comment]
@lukesneeringer do you have any resources to test the installation on Windows 7? I'm not having much luck with my VM efforts.

**Comment by lukesneeringer** [comment]
I have a Windows 7 machine at home I can try with.

**Comment by greghart** [comment]
What is in everyone's `.npmrc`? 

I had run into this as well, and found for my case it was isolated to:

```
_auth=...
```

Obviously this would make it an NPM issue, and in fact after 
 some searching, I found https://github.com/npm/npm/issues/17966 already exists.

**Comment by stephenplusplus** [comment]
I'm going to close, but please let me know if anyone is still having problems.
