### ISSUE TITLE
Error Reporting features for a Symbolizer Service

### ISSUE THREAD

**Issue by ubershmekel** [GoogleCloudPlatform/google-cloud-node#2586]
Hi Google Cloud Node,

I'm running a service that symbolizes embedded C stack traces and sends them to a Stackdriver Error Reporting dashboard. The way I go about it is a bit hacky because `@google-cloud/error-reporting` doesn't grant full control. Here's something similar to what I'm doing:

```
    const ev = googleErrorReporter.event();
    ev.serviceContext = {
        service: 'firmware',
        version: '0.0.2',
    };
    ev.eventTime = '2017-09-01T06:43:59.139Z';
    ev.setMessage('A message 2');
    ev._autoGeneratedStackTrace = symbolizedStackText;
    googleErrorReporter.report(ev);
```

I have 2 feature requests:

1. Make a formal api where I can tweak all the exception parameters. E.g. I don't want to override `_autoGeneratedStackTrace`, a private property in order to completely control the stack trace. I would use `report(error)` with a modified `err.stack` but then I can't tweak the `serviceContext` per reported crash.
2. Allow me to post a linked github issue. My service will handle the deduplication and github ticket creation - I just want the crash report api to allow me to link to the issue without a human doing that manually. Would also be cool if I had a way to link from the github issue to the specific error dashboard.

Cheers and thanks!

**Comment by DominicKramer** [comment]
Thank you for your feedback.

I like your suggestion in your first bullet point, and I think being able to specify a custom stack trace is good.

I'm not sure exactly what functionality you will need from the error reporting library in your second point.  That is, are you requesting that the error reporting API allow a URL for a GitHub issue to be reported along with an error that is encountered?  Please let me know.  Thanks.

**Comment by ubershmekel** [comment]
Yes @DominicKramer I mean it'd be nice to be able to have an `issueLink` field in the error report so I can automate this: ![link issue screenshot](https://i.imgur.com/wttw8gL.jpg)

FYI this is how I'm currently reporting the exception. So perhaps the first feature request is kind of implemented 

```

function generateStackMsg(msg: string, frames: Frame[]): string {
    const lines = [msg];
    lines.push(generateStack(frames));
    return lines.join('\n');
}

export function generateStack(frames: Frame[]): string {
    const lines = [];
    for(const fra of frames) {
        if(fra.column !== null && fra.column !== undefined) {
            lines.push(`    at ${fra.function} (${fra.file}:${fra.line}:${fra.column})`);
        } else {
            lines.push(`    at ${fra.function} (${fra.file}:${fra.line})`);
        }
    }
    return lines.join('\n');
}

export function reportError({service, version, message, frames, timestamp}: ErrorReport) {
    if (!timestamp) {
        timestamp = new Date();
    }
    const event = {
        "eventTime": timestamp.toISOString(),
        "serviceContext": {
            "service": service,
            "version": version,
        },
        "message": generateStackMsg(message, frames),
        "context": {
            "httpRequest": {
                "method": "",
                "url": "",
                "userAgent": "",
                "referrer": "",
                "responseStatusCode": 0,
                "remoteIp": ""
            },
            "user": "",
            "reportLocation": {
                "filePath": "",
                "lineNumber": 0,
                "functionName": ""
            }
        },
    }
    googleErrorReporter.report(event, undefined, undefined, () => {
        // I can't remember why I did this `undefined undefined` callback
        // I think I was debugging node exiting and not sending out the report during a unittest
        console.log('google error rep', arguments);
    })
```

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/14.
