### ISSUE TITLE
Collapse API versions if APIs only have a single version

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/google-cloud-node#2587]
Currently, the DLP API (as an example) has a documentation hierarchy like this: `DLP` &rarr; `v2beta1` &rarr; `DLPServiceClient`.

Would it be possible to reduce this to: `DLP` &rarr; `DLPServiceClient` ?

**Comment by stephenplusplus** [comment]
We are probably not going to make any changes to our GitHub hosted docs, as our repos start to migrate out onto cloud.google.com.
