### ISSUE TITLE
git@github.com:google-cloud/vision Permission denied

### ISSUE THREAD

**Issue by JohnReedLOL** [GoogleCloudPlatform/google-cloud-node#2588]
I have no clue if this is the right place for this issue: https://github.com/tejitak/node-cloud-vision-api/issues/12

Tell me if it's the right place. Then tell me how to fix it or don't and see if I can fix it myself.

................

Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - google-cloud-node version:

#### Steps to reproduce

  1. require `google-cloud`
  2. ?

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by stephenplusplus** [comment]
You can report this to `npm`:

```
npm ERR! If you need help, you may report this entire log,
npm ERR! including the npm and node versions, at:
npm ERR! http://github.com/npm/npm/issues
```
