### ISSUE TITLE
Deploying Speech Recog in production

### ISSUE THREAD

**Issue by iankit3** [GoogleCloudPlatform/google-cloud-node#2589]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 6.9.2
  - npm version: 4.0.5
  - google-cloud-node version: 0.6.0

**Working fine in local but not in production**
Hi all ,
I have a Speeeh Recognition app that uses nodejs client lib that works well in local env but it is not responding in production.
Local ENV Setup
* All service keys and project id is setup
* Have installed and authenticated google-cloud `gcloud auth`

Prod END Setup
* Tried setting up `keyFilename : './secret.json'` -- NOT WORKING
* Tried `  const speech = Speech({
        projectId:projectId,
        email:"serviceAccountEmail,
  	keyFilename:path 
  });` -- NOT WORKING
*  
![image](https://user-images.githubusercontent.com/9150788/30027572-2a11792c-919f-11e7-904a-062dced5a0b6.png)

Am i doing something wrong ? I have followed this [https://cloud.google.com/docs/authentication/production](url)

**Comment by stephenplusplus** [comment]
What error are you receiving?

**Comment by iankit3** [comment]
Nothing @stephenplusplus . And if i don't add ENV vars then not authenticated Error. I am following the guide , I think i am doing everything correct . Can you think of any specific gotchas .
Can you point me to some docs specific .

I am very happy to see a quick response . Can i provide you something specific.

Thanks a lot @stephenplusplus

**Comment by stephenplusplus** [comment]
Thanks, @iankit3. I think we should start by just sharing the code you're using. Can you show what code is not working as expected?

**Comment by iankit3** [comment]
`const { Duplex } = require('stream')
const fs = require('fs');
const stream = require('stream');
var util = require("util");
var chalk = require("chalk");


const loggerFile = fs.createWriteStream('speechlog.txt', { flags: 'a' });
const loggerFileOverwrite = fs.createWriteStream('speechlog.txt');

var streamCount = 0;


function streamingRecognize(audioStream, encoding, sampleRate, webSocket) {
  const Speech = require('@google-cloud/speech');

  const projectId = 'projectId';
  const speech = Speech();

  const request = {
    config: {
      encoding: encoding,
      sampleRate: sampleRate,
      maxAlternatives: 3,
      languageCode: "en-IN",
    },
    singleUtterance: true,
    interimResults: true,
    verbose:true
  };

  // Stream the audio to the Google Cloud Speech API
  const recognizeStream = speech.createRecognizeStream(request)
    .on('error', (error) => {
      console.error(error);
      console.log(`ERROR: ${error}`) ;
      logger.log(`Error: ${error} \n`);
    })
    .on('data', (data) => {
      if ('results' in data && data.results.length > 0) {
        var result = JSON.stringify({isFinal:data.results[0].isFinal , transcript:data.results[0].transcript});
        if (result.length > 2) {
          try {
            webSocket.send(result);
          } catch (exception) {
            console.error("EXCEPTION OCCURED", exception);
          }
        }
      }
    });

  audioStream.pipe(recognizeStream)
  logger.log(`New Stream Recieved from client ---Current stream Count :${streamCount++}-- \n`);
}

const logger = {
  log: function (logs) {
    loggerFile.write(logs);
  },
  clear: function () {
    loggerFileOverwrite.write('');
  }
}

module.exports = {
  streamingRecognize: streamingRecognize,
  logger: logger
}`

The same above code works in my local because i have insalled gcloud lib for linux and have authenticated `gcloud auth` but i can't do the same in prod .

So the issue is with Auth.

Thanks @stephenplusplus

**Comment by stephenplusplus** [comment]
I think the authentication is working properly, or you would be getting an error. Can you add a "finish" event handler to the `recognizeStream`, so that we can see if the request is at least completing successfully?

**Comment by iankit3** [comment]
Added 
```js
.on('finish', (data) => console.log(data))
```

```js
const recognizeStream = speech.createRecognizeStream(request)
    .on('error', (error) => {
      console.error(error);
    })
  .on('finish', (data) => console.log(data))
    .on('data', (data) => {
      if ('results' in data && data.results.length > 0) {
        var result = JSON.stringify({isFinal:data.results[0].isFinal , transcript:data.results[0].transcript});
        if (result.length > 2) {
          try {
            webSocket.send(result);
          } catch (exception) {
            console.error("EXCEPTION OCCURED", exception);
          }
        }
      }
    });
```

Not getting any response/erro/log

I tried running the same application in other systems . Followed same gcloud auth process also but still not working . I think there is some magic in my machine :) @stephenplusplus

**Comment by stephenplusplus** [comment]
Haha, hopefully we can figure it out! One thing that could have thrown the results of that test is `finish` doesn't receive any arguments, so logging it might not have stood out.

But in any case, is it possible to put together a script that can be run by itself to reproduce the bug? Currently, your `streamingRecognize` function accepts arguments that I can't see. If it was possible to condense it to the simplest possible reproduction case, I should be able to move quicker trying to debug this.

**Comment by iankit3** [comment]
Thanks @stephenplusplus for all the help. Will make a very trimmed down version of the problem meanwhile, I will do some more hit and trial.

**Comment by stephenplusplus** [comment]
Thanks for your patience with my requests! I look forward to solving this one-- hopefully it's something simple.

**Comment by iankit3** [comment]
hi @stephenplusplus as said i tried few things . So the outcome is that `auth` is working because fine because all the places that `quickstart.js` (the audio file to text converter) from the examples works perfectly . So you can remove the auth label from the issue.

**Comment by stephenplusplus** [comment]
@iankit3 I am going to close this issue and hope that you were able to resolve the problem! If not, let me know and we can keep looking into it.
