### ISSUE TITLE
compute.getVMs filter by zone not working

### ISSUE THREAD

**Issue by seattlevine** [GoogleCloudPlatform/google-cloud-node#2595]
I cannot filter instances by zone using compute.getVMs. Filtering by other things, such as labels, is successful.

  - Node.js version: 4.6.0
  - google-cloud-node version: 1.0.0

#### Steps to reproduce
    1. Setup instances in zone us-west1-a
    2. From one of the instances, execute the following code
        var compute = require('@google-cloud/compute')();
        var zone = "us-west1-a";
        var options = {
          filter: "zone eq " + zone
        };
        compute.getVMs(options).then(function(data) {
          console.log(data);
        });
    3. No data is returned.

**Comment by stephenplusplus** [comment]
Thanks for reporting, I will take a look at that. For now, could you see if this works?

```js
var compute = require('@google-cloud/compute')();
var zone = compute.zone("us-west1-a");
zone.getVMs().then(function(data) {
  console.log(data);
});
```

**Comment by seattlevine** [comment]
Yes, that does work.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-compute#15
