### ISSUE TITLE
Support for eventual consistency for ancestor queries [datastore]

### ISSUE THREAD

**Issue by irri** [GoogleCloudPlatform/google-cloud-node#2599]
In the documentation for Data Consistency under `Consistency guarantees` and `Datastore read policy` respectively (https://cloud.google.com/datastore/docs/concepts/structuring_for_strong_consistency#datastore_read_policy) it says:

> Ancestor queries (those that execute against an entity group) are strongly consistent by default, but can be made eventually consistent by setting the Datastore read policy (discussed below).

> To improve performance, you can set a query's read policy so that the results are eventually consistent.

However, in the Node.js tab it says:

```
// Read consistency cannot be specified in google-cloud-node.
```

I have a use-case in where a particular query to an entity group doesn't require strong consistency. Setting eventual consistency for ancestor queries is currently supported by the C#, Go, Java, PHP and Ruby libraries. Is there any future plans on incorporating this option in Node.js?

**Comment by stephenplusplus** [comment]
Thanks for asking! I'm wondering if that doc is out of date. Our `runQuery` method allows you to switch consistency to "eventual" (https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore/1.1.0/datastore/query?method=run):

```js
query.run({ consistency: 'eventual' })
```

Let me know if that's not what you're looking for.

**Comment by irri** [comment]
Thanks! That was exactly what I was looking for!
