### ISSUE TITLE
Release notes pubsub 0.14.0

### ISSUE THREAD

**Issue by jasperkuperus** [GoogleCloudPlatform/google-cloud-node#2607]
The release notes for pubsub 0.14.0 mention breaking changes and refer to a PR and the newer API documentation. It's hard to find out what parts of the API did change. Could a small bullet list with the methods that did change be included in the release notes? Now it's hard to see the impact of the API changes. Or am I overlooking a clear list of the API changes?

**Comment by stephenplusplus** [comment]
I agree, that would have been nice of us.

@callmehiphop is there any such list, or something quick you can whip up?

**Comment by lukesneeringer** [comment]
I thought we (Google DPE, not @callmehiphop) wrote a migration guide? Did that get dropped for Node?

**Comment by stephenplusplus** [comment]
Is there one for Vision? I never knew about one, but we can link to it in [our notes](https://github.com/GoogleCloudPlatform/google-cloud-node/releases/tag/vision-0.12.0).

**Comment by callmehiphop** [comment]
I'm going to cut a release and whip up some notes asap!

**Comment by callmehiphop** [comment]
@jasperkuperus I've updated the [release notes](https://github.com/GoogleCloudPlatform/google-cloud-node/releases/tag/pubsub-0.14.0) with a list of breaking changes!

**Comment by jasperkuperus** [comment]
@callmehiphop Awesome! That's great! I did find out myself that `Subscription.pull` was removed. That worth mentioning as well?

**Comment by callmehiphop** [comment]
@jasperkuperus good call!
