### ISSUE TITLE
PubSub: Error: Getting metadata from plugin failed with error: email is required

### ISSUE THREAD

**Issue by rexxars** [GoogleCloudPlatform/google-cloud-node#2609]
#### Environment details

  - OS: Ubuntu 16.04
  - Node.js version: 8.1.4
  - npm version: 5.3.0
  - google-cloud-node version: 0.14.1

#### Steps to reproduce

  1. Using the following code (obviously with project ID and keyFilename pointing to a valid key)
```js
var pubsub = require('@google-cloud/pubsub')
var pubsubClient = pubsub({
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
});

var topic = pubsubClient.topic('my-topic');

var publisher = topic.publisher();
var message = new Buffer('New message!');
publisher.publish(message)
  .then(() => console.log('Success'))
  .catch(err => console.error(err))
```
  2. Run it. 
  3. Errors with `Getting metadata from plugin failed with error: email is required`. Stracktrace is just a single line: `node_modules/grpc/src/node/src/client.js, global.<anonymous>:554`

Downgraded the pubsub module to 0.13.2 and changed from the publisher pattern to the old `topic.publish()` way of doing things, and everything works as expected.

**Comment by callmehiphop** [comment]
@rexxars thanks for filing an issue! I've been trying to reproduce this with the steps you've provided, but I have been unable to do so successfully. Is it possible there's an issue with your key file?

**Comment by rexxars** [comment]
Super weird. I used the exact same key with 0.13.2 and it worked fine. Tried to reproduce now without any luck. Closing.

**Comment by callmehiphop** [comment]
Other users have reported seeing the same error intermittently, so it could have just been a fluke.

**Comment by djbelcher** [comment]
I've notice this error whenever I have a file name with more than one '.' in the name.

For example, given a keyFileName of './conf/spanner.default.creds.json' will produce the error above.
However, changing the path to './conf/spanner-default-creds.json' will work fine.

Putting this comment in here in case others spend two hours trying to debug the same issue like I just did. :)

**Comment by rexxars** [comment]
Ran across this problem again sometime later and realized that the client is actually using the filename to determine the format. I had a kubernetes secret mounted to a file that was just called `pubsub`, and it wouldn't work. Once renamed to `pubsub.json` it worked fine. I think this behavior is weird, personally.
