### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by FalconerTC** [GoogleCloudPlatform/google-cloud-node#2618]
Spelling error on [https://googlecloudplatform.github.io/google-cloud-node/#/docs/compute/0.7.1/compute/instance-group?method=getVMs](https://googlecloudplatform.github.io/google-cloud-node/#/docs/compute/0.7.1/compute/instance-group?method=getVMs)

CTRL+F 'isntance'

**Comment by stephenplusplus** [comment]
Thanks for reporting! PR welcome, if you're up for it :)
