### ISSUE TITLE
Cloud Spanner client should use RetryInfo in gRPC trailer to figure out retry delays

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-node#2646]
Cloud spanner client library automatically retries transactions that failed with ABORTED error. Currently it computes the retry delay in code using exponential backoff. But Cloud Spanner sends a RetryInfo trailer whenever it aborts a transaction that tells after how much the transaction should be retried.
Client library should be changed to extract the retry delay from this trailer and use that to sleep.

https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto#L41

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-spanner#21
