### ISSUE TITLE
google cloud speech api is not working in node js

### ISSUE THREAD

**Issue by jagadesh18** [GoogleCloudPlatform/google-cloud-node#2652]
I am using Google Cloud Speech API in Node.js. When I send a local audio file it gives the result but when I try to send a live stream it gets stopped within a second. Can anyone help me with this?

    I am using this file: [recognize.js][1]

      [1]: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/speech

**Comment by stephenplusplus** [comment]
@jagadesh18 can you give more info about how to reproduce?

**Comment by stephenplusplus** [comment]
@jagadesh18 Without reproduction steps, I'm not sure how to reproduce. It sounds unique to the modules you're using and your code. It might be best to ask on [StackOverflow](https://stackoverflow.com/questions/tagged/google-cloud-platform%20node.js%20google-cloud-speech). If you discover there is a bug in this library, please come back and let us know.
