### ISSUE TITLE
Broken link in cloud spanner documentation

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-node#2653]
If I go to v1 page under spanner documentation:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/spanner/0.5.0/v1

The link to "Data Types" is broken:
https://googlecloudplatform.github.io/google-cloud-node/#/docs/spanner/0.5.0/spanner%2Fv1%2Fdata_types

This link takes me to not found.

**Comment by stephenplusplus** [comment]
Closing as a duplicate of #2546.
