### ISSUE TITLE
Cloud Spanner documentation should talk about supported types

### ISSUE THREAD

**Issue by vkedia** [GoogleCloudPlatform/google-cloud-node#2654]
On the cloud spanner documentation, I could not find any mention of what data types are supported and how are these to be specified in the client library. For eg how would I specify a date or a timestamp or a float or bytes. I have seen customers specifying bytes as Base64 encoded since the rpc protocol talks about that. But the client library does Base64 encoding on their behalf.

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-spanner#22
