### ISSUE TITLE
timeout option supported in v1 ?

### ISSUE THREAD

**Issue by bloodcarter** [GoogleCloudPlatform/google-cloud-node#2655]
There was a PR for v1beta adding timeout option. But I can't see it in v1.
https://github.com/GoogleCloudPlatform/google-cloud-node/pull/1915

**Comment by stephenplusplus** [comment]
[Since our API changed in 0.10.0](https://github.com/GoogleCloudPlatform/google-cloud-node/releases/tag/speech-0.10.0), the `timeout` property goes in a second argument:

```js
speech.streamingRecognize(config, { timeout: 999 })
```

Let me know if you have any issues!

**Comment by bloodcarter** [comment]
@stephenplusplus Am I understand correctly that this option will help me avoid Deadline Exceeded GRPC client error?
