### ISSUE TITLE
bigquery: set user-agent

### ISSUE THREAD

**Issue by kwent** [GoogleCloudPlatform/google-cloud-node#2659]
Hi,

I'm trying to override the user-agent used by biquery.

I browsed the code but i don't see any obvious way to do it.

Could you walk me or is it something which would needs to be implemented ?

Regards

**Comment by stephenplusplus** [comment]
The User-Agent cannot be overridden. It identifies the library `@google-cloud/bigquery` to the API servers. What is the reason you would need to change it?

**Comment by kwent** [comment]
Hi @stephenplusplus,

In order for Google to obtain usage insights while participating to the **Google Cloud Technology Partners**, they ask us to modify the **User Agent** compliant with RFC
(https://tools.ietf.org/html/rfc7231#section-5.5.3) matching our product name/version ... 

```
Suggested format
"<prod_name>/ver (GPN:<company name>; <other comments>) <other prod>/ver "*
Example
"Product_A/1.1 (GPN:Partner_ABC; staging) Product_B/1.3
Google­HTTP­Java­Client/1.20.0"
```

We currently use in our product the bigquery nodejs library and are trying to figure out how could we make this happen.

Regards

**Comment by stephenplusplus** [comment]
I see now, thank you for explaining.

@lukesneeringer we currently write the U-A string ourselves, without allowing user input. How would you like us to address this issue?

**Comment by kwent** [comment]
Hi,

Any progress on this ticket ?

Regards

**Comment by stephenplusplus** [comment]
@lukesneeringer ?

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-bigquery#10
