### ISSUE TITLE
Unable to query on two indexed fields with 1 being date [Datastore]

### ISSUE THREAD

**Issue by DaveyEdwards** [GoogleCloudPlatform/google-cloud-node#2660]
#### Environment details

  - OS: Windows 10
  - Node.js version:  6.11.2
  - npm version: 3.10.10
  - google-cloud/datastore: "^1.1.0",

I am unable to pass in multiple query filters if one of them is checking for a date.  It gives the error _Your Datastore does not have the composite index (developer-supplied) required for this query._  It also produces this result if I try to sort based on the date.

In the indexes tab inside Google Cloud console there is nothing.  Any information I try to find about this it talks about having your index composites inside index.yaml.  With google-cloud-node I do not have this yaml file, and don't think I need it?  If I do where would I need to connect it.

Query filter by date + _id (both indexed) not working
![image](https://user-images.githubusercontent.com/15203899/31319389-567161a2-ac17-11e7-8588-7e755f24e3d5.png)

Querying date alone works
![image](https://user-images.githubusercontent.com/15203899/31319418-06ba8eda-ac18-11e7-87ad-8cf28efb927e.png)

Querying matched _id works
![image](https://user-images.githubusercontent.com/15203899/31319391-6b752f5c-ac17-11e7-9a3d-2e688e2a8294.png)

Multiple query filters do work
![image](https://user-images.githubusercontent.com/15203899/31319811-63589532-ac1e-11e7-884f-d036643716d9.png)

**Comment by stephenplusplus** [comment]
Check out the [Index docs](https://cloud.google.com/datastore/docs/tools/indexconfig)! They will do a better job than I can explaining what a file looks like, when/why you need it, and how to use the gcloud sdk to create them.
