### ISSUE TITLE
Support IN query filter in node - Array queries for IDs 

### ISSUE THREAD

**Issue by mansona** [GoogleCloudPlatform/google-cloud-node#2662]
In the [Java documentation](https://cloud.google.com/appengine/docs/standard/java/datastore/queries) it mentions that you can create a filter using the **IN** operator that is described as follows: 

> IN | Member of (equal to any of the values in a specified list)
> The IN operator also performs multiple queries: one for each item in the specified list, with all other filters unchanged and the IN filter replaced with an EQUAL filter. The results are merged in order of the items in the list. If a query has more than one IN filter, it is performed as multiple queries, one for each possible combination of values in the IN lists.

This raises two questions: Firstly when it says "performs multiple queries" does it mean in the client or on the _other side of the RPC_? I ask so that I can get an idea of the performance profile of this. 

Secondly is there any plan to unify the operators across all client libraries? i.e. will we be getting the **IN** operator in the node client?

**Comment by stephenplusplus** [comment]
cc @pcostell

**Comment by stephenplusplus** [comment]
This issue was moved to GoogleCloudPlatform/google-cloud-datastore#189

**Comment by stephenplusplus** [comment]
@mansona sorry for the delay. I've moved this issue to a better location for help with Datastore.
