### ISSUE TITLE
Use with React-Native? "Unable to resolve module 'fs'

### ISSUE THREAD

**Issue by acomito** [GoogleCloudPlatform/google-cloud-node#2664]
#### Environment details

  - OS: mac siera 10.12.6
  - Node.js version: v8.2.1
  - react-native version: Expo v21
  - google-cloud-node version: "@google-cloud/vision": "^0.12.0",

#### Steps to reproduce

  1. start a new expo project
  2. yarn add @google-cloud/vision
  3. import Vision from "@google-cloud/vision"
  4. start your expo app
  5. red screen of death with "Unable to resolve module 'fs'

Is there anyway for this package to check if it's a react-native environment and disable any node-specific code? For now, I'm moving over to regular old HTTP with axios.

**Comment by lukesneeringer** [comment]
As you ascertained, we do not currently support browser-side JavaScript. This is probably feasible for some APIs, however, including this one. We will keep it in mind.

**Comment by stephenplusplus** [comment]
Closing in favor of this issue: #531
