### ISSUE TITLE
Cloud Speech API Deprecation

### ISSUE THREAD

**Issue by chasemaier** [GoogleCloudPlatform/google-cloud-node#2674]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: Ubuntu 14.04
  - Node.js version: v8.1.4
  - npm version: v5.5.1
  - google-cloud-node version: v0.10.3

#### Steps to reproduce

  1. `require('@google-cloud/speech');`
 
I'm looking for some clarification about the state of this library (the library itself is alpha?) and the Google Cloud Speech API itself (now no longer in beta).

I've previously used the Java v1beta1 sdk to interact with the beta api. I recently got an email that the Google Cloud Speech API beta compatibility was ending soon, so am re-implementing the service in Node rather than Java. Primarily I just need to be able to do streamingRecognize real-time transcriptions.

I'm somewhat unclear on if this library interacts with and is up to date with the "production" non-beta API. The linked documentation: https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/speech, https://googlecloudplatform.github.io/google-cloud-node/#/docs/speech/0.10.0/speech doesn't seem to say explicitly.

E.g. Even in the 0.10 documentation, there seems to be two paths named pretty much the same thing (v1 and speechV1)
* https://googlecloudplatform.github.io/google-cloud-node/#/docs/speech/0.10.0/speech/v1/speech_client?method=streamingRecognize
* https://googlecloudplatform.github.io/google-cloud-node/#/docs/speech/0.10.0/speech?method=streamingRecognize

How does these differ?

Some examples say:
````js
var speech = require('@google-cloud/speech');

var client = speech.v1({
  // optional auth parameters.
});
````

Others just say:
````js
var speech = require('@google-cloud/speech')({
  projectId: 'grape-spaceship-123',
  keyFilename: '/path/to/keyfile.json'
});
````

What's the difference here? Any clarification would be appreciated.

Just want to be sure that, given the messaging below, using this library (v0.10) and these methods will utilize the "GA" version of the API as expected.

> We released the Generally Available (GA) version of the Cloud Speech API on April 18, 2017, and the service will be fully graduating from Cloud Speech API Beta on November 30, 2017. This is an extension of our original timeline for a July 31 transition. Our records show that you have recently been using the beta endpoint even after the prior notice. In order to continue using Cloud Speech API, you must migrate to the Cloud Speech API GA version before November 30, 2017. Google Cloud Speech API Beta endpoint will cease to function from this date.

**Comment by lukesneeringer** [comment]
Hi @chasemaier,
Thanks for stopping by.

> I've previously used the Java v1beta1 sdk to interact with the beta api. I recently got an email that the Google Cloud Speech API beta compatibility was ending soon, so am re-implementing the service in Node rather than Java. Primarily I just need to be able to do streamingRecognize real-time transcriptions.

This refers to the `v1beta1` endpoint on the Speech API service itself. It does not refer to the Java (or Node) client libraries, or the `v1` endpoint.

> Just want to be sure that, given the messaging below, using this library (v0.10) and these methods will utilize the "GA" version of the API as expected.

I can not speak for the Java library, but the Node library _only_ interacts with the `v1` (GA) API endpoint unless you explicitly ask it for something else. (I am 95% sure this is true for Java also.)

> I'm looking for some clarification about the state of this library (the library itself is alpha?) and the Google Cloud Speech API itself (now no longer in beta).

Our library is now in beta. If we still say alpha somewhere, then I need to fix that. :-)

We intend to move the Node speech library into GA / stable very soon (within the next couple weeks). Based on what we have learned with this and other libraries, we will be making one backwards incompatible change (a change to the constructor -- it will be semver major but it should take you less than five minutes to update your code), and then very shortly after that we will be pushing out 1.0.

**Comment by chasemaier** [comment]
Yeah, I've seen lots of references to the libraries being alpha and not appropriate for production use.
* Just one example: https://github.com/GoogleCloudPlatform/google-cloud-node#cloud-speech-alpha

Also looking at https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/speech/src/index.js#L69-L72, it seems the two variations are simply identical -- would you suggest using one over the other? The documentation seems to switch between them.

> Some examples say:
> ````js
> var speech = require('@google-cloud/speech');
> 
> var client = speech.v1({
>   // optional auth parameters.
> });
> ````
> 
> Others just say:
> ````js
> var speech = require('@google-cloud/speech')({
>   projectId: 'grape-spaceship-123',
>   keyFilename: '/path/to/keyfile.json'
> });
> ````

Thanks for the response, just wanted to be sure using the node library wasn't going to end up hitting the wrong endpoint or something. Sounds like that won't be a problem, so that's good to hear.

**Comment by lukesneeringer** [comment]
> Yeah, I've seen lots of references to the libraries being alpha and not appropriate for production use.

Thanks, I will try to stomp those. The library is beta (and will be GA soon).

> it seems the two variations are simply identical -- would you suggest using one over the other?

The `v1` is provided as an optional "version pin". You may decide whether to use it or not.

Basically the idea here is:

  * We may provide a public beta that is _ahead of_ `v1`. If you want to use those features, you will have to pin to that beta version.
  * A very long time from now, there may be a `v2`. If there is, it will become the new default, and you will have to pin to `v1` to continue to use `v1`. (This will be a semver-major change.)

**Comment by stephenplusplus** [comment]
I replaced the outdated Alpha reference in the README.
