### ISSUE TITLE
App Engine Namespace API / Multitenancy

### ISSUE THREAD

**Issue by flyboarder** [GoogleCloudPlatform/google-cloud-node#2675]
There is nothing for app engine multitenancy using Namespaces API. Digging through the docs says to read more on the Java/Python Multitenancy pages, however there is no App Engine API in order to do this.

**Comment by lukesneeringer** [comment]
I am sorry, I am confused. Could you point me to a link with the docs you are looking at?

**Comment by flyboarder** [comment]
https://cloud.google.com/appengine/docs/standard/java/multitenancy/multitenancy

There is no nodejs version of the above namespace feature.

**Comment by stephenplusplus** [comment]
We do not have an App Engine API at this time. It is in our "API Implementation Tracker" (#1338), but there are no guarantees or timelines; these are just requests by users.
