### ISSUE TITLE
DLP: Check quasi_id types

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/google-cloud-node#2678]
cc @lukesneeringer 

For DLP's [`kAnonymityConfig`](https://cloud.google.com/dlp/docs/reference/rest/v2beta1/dataSource/analyze#KAnonymityConfig) and [`lDiversityConfig`](https://cloud.google.com/dlp/docs/reference/rest/v2beta1/dataSource/analyze#LDiversityConfig), can we check that the `quasiIds` field's sub-objects specify a `columnName` property?

For example, the following is currently (as of #2668) not caught clientside:
```
const badCfg = "kAnonymityConfig": {
 "quasiIds": [
   {
     "shouldBe_columnName": "Name"
   },
   {
     "shouldBe_columnName": "Age"
   }
 ]
}
```

**Comment by landrito** [comment]
So one way we could do this is to add a check to all request objects to make sure that there are no fields that do not conform to the schema provided in the proto.  I'd have to look at what that would mean for streaming calls though.

@lukesneeringer do you think it's reasonable to add this validation step before shooting off a request?

**Comment by lukesneeringer** [comment]
Probably not. We _consistently_ get bitten when we do client-side validation.

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-dlp#3
