### ISSUE TITLE
"Text" type

### ISSUE THREAD

**Issue by kirillgroshkov** [GoogleCloudPlatform/google-cloud-node#2680]
I'm migrating my code from using Datastore API in Java to Node. I need 2 codebases (Java and Node) to work with same production database and have all types read/write correctly.

In Java I had a type `Text`. I Node I cannot figure out how to save an entity with a field of type `Text`. If I save a js object - it creates `EmbeddedEntity` (so I cannot read it in Java as `Text`). If I save as string - it creates `String`, not `Text`.

Is `Text` just a Java API thing? How do I made Node to write a field that Java can read it as `Text`?

**Comment by stephenplusplus** [comment]
I was reading about the `Text` type [here](https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/datastore/Text):

> Ordinary Java strings stored as properties in Entity objects are limited to 1500 bytes. However, Text objects can also be stored in properties, and are unlimited in size. However, they will not be indexed for query purposes.

In Node, the way you do that looks like:

```js
datastore.save({
  key: datastore.key('Kind'),
  data: {
    shortString: 'short string',
    longString: '-- string > 1500 bytes --'
  },
  excludeFromIndexes: ['longString'] // <-- This is what makes it like the Java "Text" type
})
```

Please let me know if you have any issues making this work as you expect.

**Comment by whyseman** [comment]
@stephenplusplus I tried the code you provided, I see on GCP that the properties aren't being indexed but the **entity type** is set to **String** instead of **Text**.

Here's an example of my code
```js
let task = {
    key: entityName,
		data: [{
			name: 'json',
			value: datastoreJSON,
			excludeFromIndexes: true
		},
		{
			name: 'node',
			value: json.EUI,
			excludeFromIndexes: true
		},
	],
};
```
I need the **value** to be type of **Text** and not **String** on entity type. Does anyone know how to do this using the npm library?
