### ISSUE TITLE
Datastore: Can't filter by __key__ with numeric ID

### ISSUE THREAD

**Issue by mdcanham** [GoogleCloudPlatform/google-cloud-node#2681]
#### Environment details

  - OS: OSX 10.12
  - Node.js version: v6.9.4
  - npm version: 3.10.10 (but am using Yarn 0.21.3)
  - google-cloud-node version: ^1.1.0

#### Steps to reproduce

    import Datastore from '@google-cloud/datastore';
    const datastore = Datastore({
			projectId: "alumni"
    });

    let key = datastore.key(['alumnus', 4786706423218176]);

    let query = datastore.createQuery('alumnus')
    ...

#### What's the issue
This hard-coded ID is a know ID of one of the entities in the 'alumnus' collection. However this query returns no results.

**Comment by stephenplusplus** [comment]
@pcostell any ideas how to help?

**Comment by mdcanham** [comment]
All sorted. Was just a silly mistake on my end where I wasn't returning the object back with the response. Datastore was working just fine!
