### ISSUE TITLE
How to activate debug logs of the API

### ISSUE THREAD

**Issue by charly37** [GoogleCloudPlatform/google-cloud-node#2683]
Hi,

I m having some issue with the datastore API where the query hang without any responses. Here is a quick extract of my code:
```
var aGcpProjectName = '**********'
var datastore = require('@google-cloud/datastore')({
  projectId: aGcpProjectName,
  keyFilename: '/SAD/*********'
});
```
and later
```
log.info('Going to querry Google DataStore Service');
var query = me._dataStore.createQuery('BobStacks');
var aReturnPromise = me._dataStore.runQuery(query)
  .then((results) => {
    //Task entities found.
    const tasks = results[0];
    log.info('find all Google DataStore Over', results);
    if (tasks.length>0) {
      log.info('resolve');
      resolve(tasks);
    }
    else {
      log.info('Empty list when geting all from GDS.');
      resolve(null)
    }
  })
  .catch(function (err) {
    log.error('Error when findall. Error detail: ', err);
    reject(Error("It broke"));
  });
```
I see the first log "Going to querry Google DataStore Service" and nothing after that.

The interesting fact is that it seems to happen after 24 hours (if I restart the server after that it will works fine for some time until this happen again).

I would like to have more logs on the Datastore API itself and was thus wondering **if there is a way to activate more logs for the library itself ?** I check the FAQ and documentation but did not find the option.

For extra info here are the versions I use:
```
[root@stackviewer-1-n987w WebServerNodeJs]# node --version
v6.11.3

[root@stackviewer-1-n987w WebServerNodeJs]# npm list --depth=0
topology-manager@0.0.1 /var/www/WebServerNodeJs
+-- @google-cloud/datastore@1.1.0
+-- body-parser@1.18.2
+-- bunyan@1.8.12
+-- cookie-parser@1.4.3
+-- express@4.9.0
+-- express-session@1.15.6
+-- express-ws@2.0.0
+-- jsdoc@3.5.5
+-- mongoose@4.12.3
+-- ngclipboard@1.1.1
+-- node-cron@1.2.1
+-- passport@0.4.0
+-- passport-ldapauth@2.0.0
+-- request@2.83.0
+-- request-debug@0.2.0
+-- serve-static@1.11.1
+-- swagger-tools@0.10.3
+-- tr-ng-grid@3.1.7
`-- utils-merge@1.0.1
```

**Comment by lukesneeringer** [comment]
If Datastore is a gRPC API (and I think it is), the best way is to set these two environment variables:

  * `GRPC_VERBOSITY`: `DEBUG`
  * `GRPC_TRACE`: `http`

That should give you a substantial amount of debug output detailing every request and response going through the API.

**Comment by stephenplusplus** [comment]
@charly37 Datastore is a gRPC API, so those environment variables should work. If you discover anything that might be a bug of ours, please let us know.

**Comment by charly37** [comment]
Thx ! I will give it a try an open a dedicated ticket if I find something.
