### ISSUE TITLE
publisher.js omitted from generated docs

### ISSUE THREAD

**Issue by ace-n** [GoogleCloudPlatform/google-cloud-node#2686]
[publisher.js](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/99bd00c33b29aa35fd4575868fdb32a3f921b7fa/packages/pubsub/src/publisher.js) is not included in the generated docs - neither [online](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/pubsub) nor locally.

**Comment by callmehiphop** [comment]
Looks like it's only for the meta package, the `pubsub` package has it ([source](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.1/pubsub/publisher)).

@stephenplusplus how often do the meta package docs get built..? Or do I need to update it to pull the latest pubsub version?

**Comment by stephenplusplus** [comment]
It looks like we have it documented for the `@google-cloud/pubsub` docs: https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.1/pubsub

We are in the process of extracting all of our APIs out to their own repo, e.g. https://github.com/googleapis/nodejs-logging. This process usually takes a few days, then the docs end up on cloud.google.com, e.g. https://cloud.google.com/nodejs/docs/reference/logging/1.1.x/

I image `@google-cloud/pubsub` will be up soon for extraction.
