### ISSUE TITLE
Logging Bunyan Error: google/logging/v2/logging.proto could not be found

### ISSUE THREAD

**Issue by Jeremiahgibson** [GoogleCloudPlatform/google-cloud-node#2688]
#### Environment details

  - OS: Linux Ubuntu 17.04
  - Node.js version: 6.10.3
  - npm version: 3.10.10
  - google-cloud-node version:  "google-cloud/logging-bunyan": "^0.5.0", "bunyan": "^1.8.10"

#### Steps to reproduce

  1. require `@google-cloud/logging-bunyan`
  2. Attempt to log to stack driver using logger.debug({httpRequest:  {url: req.url}}, 'Some message');
  3. All of this was done from within a kubernetes container in a google project container cluster.

### Dependency Tree Diff

 google-cloud/logging@1.0.6   ->   google-cloud/logging@1.1.0 
 google-gax@0.13.5                      ->   google-gax@0.14.2
 
### Npm debug log output

(node:16) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: google/logging/v2/logging.proto could not be found in /var/www/node_modules/google-cloud/logging/protos
/var/www/node_modules/google-gax/lib/grpc.js:172
  throw new Error(filename + " could not be found in " + protoPath);
  ^
 Error: google/logging/v2/logging.proto could not be found in /var/www/node_modules/google-cloud/logging/protos
    at Function.GrpcClient._resolveFile (/var/www/node_modules/google-gax/lib/grpc.js:172:9)
    at GrpcClient.loadProto (/var/www/node_modules/google-gax/lib/grpc.js:161:33)
    at new LoggingServiceV2Client (/var/www/node_modules/@google-cloud/logging/src/v2/logging_service_v2_client.js:94:15)
    at /var/www/node_modules/@google-cloud/logging/src/index.js:789:21
    at Immediate.setImmediate (/var/www/node_modules/google-auto-auth/index.js:161:9)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by julienvincent** [comment]
Getting this too but when using `@google-cloud/logging` as a dependency for another lib

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-logging#14

**Comment by gaofanmichael** [comment]
This issue was moved to googleapis/nodejs-logging-bunyan#2
