### ISSUE TITLE
Documentation has broken link

### ISSUE THREAD

**Issue by ryanmats** [GoogleCloudPlatform/google-cloud-node#2690]
https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.12.0/vision/v1/data_types?method=BatchAnnotateImagesResponse

Clicking on the 'AnnotateImageResponse' link leads to a 'Not Found.'

**Comment by stephenplusplus** [comment]
Thank you for reporting. We have another issue to track this: #2546 (different page, but same general problem).
