### ISSUE TITLE
Missing documentation for latest versions > 14.1

### ISSUE THREAD

**Issue by thvd** [GoogleCloudPlatform/google-cloud-node#2696]
If i look at the documentation page https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.1/pubsub the latest version visible is 14.1. But in Github (https://github.com/GoogleCloudPlatform/google-cloud-node/releases) i see versions up to 14.5, but where is the documentation?

**Comment by stephenplusplus** [comment]
Sorry, thank you for pointing that out. I've published them now: https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.5/pubsub.
