### ISSUE TITLE
Node v8.8.0 supports http2 by default. Does this change anything for gRPC?

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/google-cloud-node#2697]
See https://nodejs.org/en/blog/release/v8.8.0/ for the release notes. Can we slim down the gRPC installation if http2 is built in?

**Comment by lukesneeringer** [comment]
gRPC is in the process of writing a native JavaScript client, which will be based on this, but it will be a few months before it is ready. They also plan on having some kind of dual-installation process so that you get the full C library on Node 6 and the native library on Node 8.

**Comment by stephenplusplus** [comment]
Closing as duplicate of #2697.
