### ISSUE TITLE
Missing migration guide from the removed subscriber.pull method

### ISSUE THREAD

**Issue by thvd** [GoogleCloudPlatform/google-cloud-node#2698]
When we started using the NodeJS Pubsub library there was a `Subscriber.pull` (https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.13.1/pubsub/subscription?method=pull) method in order to pull the messages. In the latest 14.x versions it has been removed, no problem with that. But where can I find the migration path? Is there any comparable alternative to this method?

**Comment by stephenplusplus** [comment]
Ping @callmehiphop for advice.

**Comment by callmehiphop** [comment]
Somehow this one flew under the radar, sorry about that. @thvd please take a look at https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2670, I think it has the answer you're looking for!
