### ISSUE TITLE
Confused about row(key).exists()

### ISSUE THREAD

**Issue by briangruber** [GoogleCloudPlatform/google-cloud-node#2702]
I'm confused about using the `exists()` method on a `row(key)`, hoping to get clarification. 
If I want to check if a row exists I thought I would do this

```
table.row(key).exists().then(result => {
  let exists = result[0]
}
```

If the row does exists then I do step into the `.then` and exists will be `true`. But if it doesn't exist I actually get an exception of `Unknown row: key`. So, then what is the point of `exists` if when it doesn't exist it throws an error? Is `result[0]` expected to always be `true` and if it doesn't exist I'm supposed to use the exception? Or am I missing something?

Thanks!

**Comment by callmehiphop** [comment]
Sounds like a bug! Just to confirm - are you reporting this for the Bigtable client?

**Comment by briangruber** [comment]
Yes, this is for the node module `@google-cloud/bigtable`

**Comment by stephenplusplus** [comment]
cc @Chipintoza who reported this in https://github.com/googleapis/nodejs-spanner/issues/23 (so you can track this)

**Comment by lukesneeringer** [comment]
This issue was moved to googleapis/nodejs-bigtable#5
