### ISSUE TITLE
Datastore: deletes not "taking"?

### ISSUE THREAD

**Issue by chadbr** [GoogleCloudPlatform/google-cloud-node#2703]
#### Environment details

  - OS: dev: macos latest, server nodejs appengine runtime
  - Node.js version: 8.7
  - npm version: 5.5.1
  - google-cloud-node version: @google-cloud/datastore: 1.1.0

from yarn.lock:
```
"@google-cloud/datastore@^1.0.4", "@google-cloud/datastore@^1.1.0":
  version "1.1.0"
  resolved "https://slb-swt.pkgs.visualstudio.com/_packaging/kinetix/npm/registry/@google-cloud/datastore/-/datastore-1.1.0.tgz#386e9c9bdc4397945c8a47983821470f47041889"
  dependencies:
    "@google-cloud/common" "^0.13.0"
    "@google-cloud/common-grpc" "^0.4.0"
    arrify "^1.0.0"
    concat-stream "^1.5.0"
    create-error-class "^3.0.2"
    extend "^3.0.0"
    google-gax "^0.13.0"
    google-proto-files "^0.12.0"
    is "^3.0.1"
    lodash.flatten "^4.2.0"
    modelo "^4.2.0"
    prop-assign "^1.0.0"
    propprop "^0.3.0"
    split-array-stream "^1.0.0"
```
---

quick summary - 
-create an entity
-delete the entity
     --no errors, 
     --result looks like the delete 'took' --
       "[{"mutationResults":[{"key":null,"version":"306","conflictDetected":false}],"indexUpdates":5}]"

-read for the entity -- the entity returns!??

Anyone else seeing this? Maybe a dependent package problem?

Thanks - Chad

**Comment by stephenplusplus** [comment]
Can you show in code how you're testing? I'm not getting a result with this pattern:

```js
var key = datastore.key('Kind')
var data = {
  innerData: true
}

datastore.save({key, data})
  .then(() => datastore.delete(key))
  .then(() => datastore.get(key))
  .then(console.log) // [undefined] 
```

**Comment by chadbr** [comment]
Unfortunately we have a lot of layers - 

I'll pull together a repo.

It's a little more complicated than explained. We're using a key that is a concatenation of 2 properties... and reading with a single property. Something like:

key = foo|01 == id=foo, seq=01
key = foo|02 == id=foo, seq=02
key = foo|03 == id=foo, seq=03

we write them one by one,

delete with key foo|01

then read with index 'foo'

**Comment by chadbr** [comment]
@stephenplusplus I'm going to close this for now - I've written some tests on the same logic and it seems to be working fine...

There must be a logic error some place else in the code.

Thanks for looking -- sorry to bother.

  Chad

**Comment by stephenplusplus** [comment]
No bother, let me know if I can help with anything!
