### ISSUE TITLE
int values on embedded entities stored as string

### ISSUE THREAD

**Issue by jcsv** [GoogleCloudPlatform/google-cloud-node#2704]
Hi, 

We are detecting on embedded entities that int attributes are stored as string. Let me show an example:
```
{
  "properties": {
    "humidity": {
      "integerValue": "1"
    },
    "light": {
      "integerValue": "1"
    },
    "battery": {
      "integerValue": "17"
    }
  }
}
```

When using Doubles or Boolean there is no problem:

```
{
  "properties": {
    "snr": {
      "doubleValue": 35.15
    },
    "rssi": {
      "integerValue": "-116"
    },
    "time": {
      "integerValue": "1509123474"
    },
    "station": {
      "stringValue": "0960"
    },
    "avgSnr": {
      "doubleValue": 40.73
    },
    "location": {
      "arrayValue": {
        "values": [
          {
            "integerValue": "37"
          },
          {
            "integerValue": "-6"
          }
        ]
      }
    },
    "seqNumber": {
      "integerValue": "2094"
    },
    "duplicate": {
      "booleanValue": false
    }
  }
}
```

Even when I remove the double quotes on the entity editor it are stored as string when saving.

Thanks.

**Comment by stephenplusplus** [comment]
Hello! Can you show the code you're using? I'm not sure where that object is coming from without context.

**Comment by lukesneeringer** [comment]
Hi @jcsv,
Additionally, can you tell us what API you are using? Thanks. :-)

I believe that Spanner and possibly BigQuery as well do represent some integers (in particular, INT64) as strings in some places, in order to not lose precision due to JavaScript's lack of an integer type. I am unsure when, if ever, that is supposed to bubble up to you.

**Comment by stephenplusplus** [comment]
@jcsv What @lukesneeringer said is correct. We store them as strings to pass to the API. It will still be recognized as the correct type because of the `integerValue` key.

If we're misunderstanding something, please let me know.
