### ISSUE TITLE
bigquery: consider moving from getQueryResults to listTableData

### ISSUE THREAD

**Issue by pongad** [GoogleCloudPlatform/google-cloud-node#2709]
The current `query` method uses [`getQueryResults`](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/getQueryResults) RPC to read rows of the results. However, benchmark shows that [`listTableData`](https://cloud.google.com/bigquery/docs/reference/rest/v2/tabledata/list) run significantly faster. Experiments in Go shows `getQueryResults` take 70% longer.

The choice of RPC is an implementation detail and can be changed whenever. However, `listTableData` returns fewer fields. In Java, we decided to tweak the API surface to make it easier to change RPC later. Of course, the change to API needs to happen before GA.

Will Node require any API change?

**Comment by stephenplusplus** [comment]
Could you explain the RPC calls in order from "SELECT url FROM [publicdata:samples.github_nested] LIMIT 100" to "resultingRows.forEach(...)"?

**Comment by pongad** [comment]
Current Go implementation works like this:
1. use `job.insert` to start the job
2. use `getQueryResults` with `max_results=0` to wait for the job to finish
  a. you can read the schema off of this RPC
3. use `tabledata.list` to actually iterate over results.

Currently in Java, we return some statistics with *each page*. These stats will be removed because `tabledata.list` doesn't return these stats.

**Comment by pongad** [comment]
I believe this should be P1. If this requires surface changes, it must happen before GA.

**Comment by callmehiphop** [comment]
Nevermind! I just looked through the Go implementation and connected all the dots. I do not believe a surface change will be necessary in order to swap.

**Comment by pongad** [comment]
@callmehiphop Thank you for verifying. Since no surface change is required for swap, this is no longer a GA blocker. I'll put this at P2, but please change if you feel differently.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-bigquery#12
