### ISSUE TITLE
Documentation for nodejs getMetadata doesn't indicate all options

### ISSUE THREAD

**Issue by tejohnso** [GoogleCloudPlatform/google-cloud-node#2718]
Looking for example at [getMetadata](https://googlecloudplatform.github.io/google-cloud-node/#/docs/google-cloud/0.56.0/storage/file?method=getMetadata) there's an indication that userProject can be supplied as an option, but there's no indication that we can include any key and it is going to be passed to the underlying *request* package as part of the *qs* (querystring) configuration for [the request](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/v0.56.0/packages/storage/src/bucket.js#L1073). 

So while `getMetadata({userProject: true})` might work, `getMetadata({fields: "generation"})` also works. This is a minor issue, but it would be nice if it was more clear that what we're really passing as configuration is any querystring value that should be included. Curious to know why userProject is singled out there.

Also, as an aside, the documentation indicates userProject is a boolean.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-storage#77
