### ISSUE TITLE
Suggestion: Flag to ignore common 409 conflicts 

### ISSUE THREAD

**Issue by moander** [GoogleCloudPlatform/google-cloud-node#2720]
If functions like pubsub SubscriberClient#createSubscriptions had a flag to ignore 409 ALREADY_EXISTS it would be possible to write code like this:

```js
try {
    await client.createTopic(..);
    
    await client.createSubscription(..);    
}
catch (err) {
    console.log(err)
}
```

Instead of this
```js
try {
    try {
        await client.createTopic(..);
    } 
    catch(err) {
        if (err.code !== 409) {
            throw err;
        }
    }

    try {
        await client.createSubscription(..);
    } 
    catch(err) {
        if (err.code !== 409) {
            throw err;
        }
    }
}
catch (err) {
    console.log(err)
}
```

**Comment by stephenplusplus** [comment]
Try [`topic#get({ autoCreate: true })`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.5/pubsub/topic?method=get). Same with [`subscription#get({ autoCreate: true })`](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.5/pubsub/subscription?method=get).

**Comment by moander** [comment]
Thank you :)

```js
const topic =  pubsub.topic('foo');
await topic.get({autoCreate:true});

const sub = topic.subscription('bar');
await sub.get({autoCreate:true});        
```
