### ISSUE TITLE
datastore: system tests don't run in Node 4.x

### ISSUE THREAD

**Issue by callmehiphop** [GoogleCloudPlatform/google-cloud-node#2722]
#### Environment details

  - OS: Mac OS
  - Node.js version: 4
  - npm version: 3
  - google-cloud-node version: master

---

Looks like we are using a Buffer method that wasn't added until Node 5. Here's the error:

```sh
  1) Datastore create, retrieve and delete should excludeFromIndexes correctly:
     TypeError: Buffer.alloc is not a function
      at Context.<anonymous> (system-test/datastore.js:85:31)
```

**Comment by lukesneeringer** [comment]
@callmehiphop This one should be easy:

1. `npm install safe-buffer`

2. `const Buffer = require('safe-buffer').Buffer;`

QED

**Comment by callmehiphop** [comment]
Yeah I know, I came across it while testing/reviewing a different PR and just wanted to make sure it didn't get lost before I could get to it
