### ISSUE TITLE
pubsub: add Subscription#setOptions()

### ISSUE THREAD

**Issue by tonila** [GoogleCloudPlatform/google-cloud-node#2723]
We are upgrading pubsub from 0.13.x to 0.14.x and current API documentation does not seem to answer our questions.

Documentation states that "subscription options do not persist across multiple instances". 

With current knowledge, I assume it means, that subscription, that you see at cloud console does not store subscription options, so you need to set them for each instance you receive from the cloud.

But how do you set options, since [subscription](https://googlecloudplatform.github.io/google-cloud-node/#/docs/pubsub/0.14.5/pubsub/subscription) does not seem to have function for that?

Currently we are just always using topic.createSubscription() for new and existing subscriptions and it seems to work fine, but I am wondering, what is the intended way of doing this?

**Comment by stephenplusplus** [comment]
You can set the options at the time of creating the Subscription reference object.

```js
topic.createSubscription('name', { /* options */ })
// or...
var subscription = topic.subscription('name', { /* options */ })
```

You do bring up a good question-- how can you set the options when you get a Subscription from `topic.getSubscriptions()`? @callmehiphop ?

**Comment by callmehiphop** [comment]
You currently can't, sounds like maybe we need to make a setter.

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-pubsub#12
