### ISSUE TITLE
First query in application takes a long time

### ISSUE THREAD

**Issue by EJB3927** [GoogleCloudPlatform/google-cloud-node#2727]
The first query I perform in my application always takes approximately 10 seconds or more, but subsequent queries will take a normal length of time.

#### Environment details
Application is running on CloudFunctions, where the issue also exists.

Local environment details:
  - OS: macOS Sierra
  - Node.js version: 7
  - npm version: 3.10.10
  - google-cloud/datastore version: 1.1.0

#### Steps to reproduce

```javascript
        const taskKey = datastore.key(['Token', token]);
        const query = datastore.createQuery('Token').filter('__key__', '=', taskKey);
        var data = datastore.runQuery(query).then((results) => {
            if (results[0].length > 0) return results[0][0];
            else return null;
        }).catch(err => {
            return err;
        });
```

**Comment by stephenplusplus** [comment]
Hey @EJB3927, thanks for reporting. The first API call generally takes more time, due to the authentication step of fetching a token. Are you providing a JSON key file for auth when you instantiate the `datastore` client, or are you letting Cloud Functions automatically auth?

Also, what amount of time is normal for that query?

**Comment by EJB3927** [comment]
We're letting authentication be performed automatically via the GOOGLE_APPLICATION_CREDENTIALS environment variable, even in my local environment. A normal query takes somewhere on the order of a couple dozen milliseconds.

**Comment by stephenplusplus** [comment]
Unfortunately, this seems to be a common issue: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2374#issuecomment-320631692

I'm going to re-open that issue and try to get some input from the relevant teams.
