### ISSUE TITLE
pubsub: not working inside docker (no error output)

### ISSUE THREAD

**Issue by victorperin** [GoogleCloudPlatform/google-cloud-node#2733]
#### Environment details

  - OS: Fedora 25 (Docker 17.09)
  - Node.js version:  Using image `node:9.0.0-alpine` (same problem with older versions)
  - npm version: 5.5.1
  - google-cloud-node version: `"@google-cloud/pubsub": "0.14.7"`

#### Steps to reproduce
I created a repository reproducing the steps, to make it easy to everyone understand what is the problem.
https://github.com/victorperin/google-pubsub-node-docker-bug

Seems to be some kind of lib missing, but I don't know how to find it.

**Comment by victorperin** [comment]
Tried to reproduce with all pubsub dependencies and found that the problem is with `'@google-cloud/common-grpc`

**Comment by victorperin** [comment]
Digging down the rabbit hole i found the responsible is the `grpc` package itself.

**Comment by stephenplusplus** [comment]
This issue was moved to grpc/grpc-node#85

**Comment by BrunoQuaresma** [comment]
Any prediction of update the common-grpc package?

**Comment by victorperin** [comment]
Waiting for it too.

**Comment by stephenplusplus** [comment]
The latest release of grpc is `1.7.2`. `common-grpc` depends on `^1.7.1`, so `1.7.2` will be picked up for new installs.

**Comment by BrunoQuaresma** [comment]
I tried to make a new install but still not working 😞

**Comment by callmehiphop** [comment]
@stephenplusplus pubsub no longer depends on `common-grpc`, so for it to pick up these changes up, we would need to update `gax-nodejs` which would also require gapics being regenerated.
