### ISSUE TITLE
Can't save empty arrays

### ISSUE THREAD

**Issue by gstreetmedia** [GoogleCloudPlatform/google-cloud-node#2734]
As of the April 2016 release of Datastore, empty arrays are supported. 

However, line 949 in request.js  of  datastore@1.1.0

`entityProto.properties = entityObject.data.reduce(function(acc, data) {
          var value = entity.encodeValue(data.value);`

data.value will always be undefined if the array is of length === 0

thus, you cannot save something like

```
{someObject: { 
     myProperty : []
}
```

**Comment by stephenplusplus** [comment]
I just tried this:

```js
var key = datastore.key('Kind');

datastore.save({
  key,
  data: {
    someObject: {
      myProperty: []
    }
  }
}, function(err) {
  datastore.get(key, function(err, results) {
    console.log(results)
  });
});
```

It outputs:

```
{
  someObject: {
    myProperty: []
  }
}
```

Can you give reproduction code with "Actual" vs "Expected" results?

**Comment by stephenplusplus** [comment]
Going to close as I cannot reproduce.
