### ISSUE TITLE
Cloud Datastore Emulator Can't Find Java on Mac

### ISSUE THREAD

**Issue by yonathan06** [GoogleCloudPlatform/google-cloud-node#2735]
**## Sorry, you can delete this issue, it is not related to here. Posting on stackoverflow** 

#### Environment details

  - OS: macOS 10.12.6
  - Node.js version: 8.9.0
  - npm version: 5.5.1

#### Steps to reproduce

running `gcloud beta emulators datastore start` produces error:
 `ERROR: (gcloud.beta.emulators.datastore.start) The java executable on your PATH is not a Java 7+ JRE. The Google Cloud Datastore emulator requires a Java 7+ JRE installed and on your system PATH`

the problem is, I do have java installed. When running `java -version` I get:
`java version "9.0.1"`
`Java(TM) SE Runtime Environment (build 9.0.1+11)`
`Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)`

I reinstalling java and rebooting, nothing works
Any help?

**Comment by stephenplusplus** [comment]
Feel free to link the question / come back with the answer in case anyone else runs into the same problem.

**Comment by calsmith** [comment]
Same problem starting the datastore emulator:
`ERROR: (gcloud.beta.emulators.datastore.start) The java executable on your PATH is not a Java 7+ JRE. The Google Cloud Datastore emulator requires a Java 7+ JRE installed and on your system PATH`

java -version returns:
```
java version "10" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10+46)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10+46, mixed mode)
```

Does the emulator exclusively support Java 7 and no higher?

**Comment by yonathan06** [comment]
For me it works with Java 9
Managed to fix it by uninstalling java and datastore emulator, and reinstalling it again, and restarting the machine after each action (an old fashion fix)

**Comment by Kazade** [comment]
Same problem here on Fedora, `java -version` reports:

```
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+11)
OpenJDK 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

Definitely seems to be something wrong with the Java runtime detection.

**Comment by bgarrett-rt** [comment]
Note: At least on Mojave, when you are prompted to install Java SDK, the OS displays a dialog saying you need to install java. However, the More Info link takes you to a generic Oracle page where it is easy to accidentally install the JRE rather than the JDK. I manually installed the java 8 JDK and things worked right away.
