### ISSUE TITLE
Haven't been able to make use of PubSub past v0.14.2

### ISSUE THREAD

**Issue by lostpebble** [GoogleCloudPlatform/google-cloud-node#2738]
#### Environment details

  - OS: Linux / Windows
  - Node.js version: 8.9.0
  - npm version: yarn
  - google-cloud-node version: pubsub 0.14.8

#### Steps to reproduce

  1. Try use `@google-cloud/pubsub` versions above `0.14.2` with other `@google-cloud/*` libraries.
  2. Get error messages like so:

```
TypeError: Channel's second argument must be a ChannelCredentials
```

Which I assume has something to do with GRPC or the like.

I'm not sure what's causing it exactly, but it seems like there is a mismatch between the versions of grpc between packages which could be it.

I'm seeing `grpc@1.6.0` installed because of `@google-cloud/datastore#@google-cloud/common-grpc` and `@google-cloud/datastore#google-gax`. But it seems that the newer versions of PubSub are making use of `grpc@1.7.1`.

I feel like dependency management in JavaScript is never really a good time, so I can understand.

**Comment by stephenplusplus** [comment]
Duplicate #2699
