### ISSUE TITLE
Wrong url on documentation

### ISSUE THREAD

**Issue by heryvandoro** [GoogleCloudPlatform/google-cloud-node#2743]
Wrong url references on "Likelihood" documentation. (FaceAnnotation and SafeSearchDetection)

Here is correct url : https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.12.0/vision/v1/data_types?method=Likelihood

Wrong url : https://googlecloudplatform.github.io/google-cloud-node/#/docs/vision/0.12.0/Data%20Types%2Fv%2Fdata_types?method=Likelihood

**Comment by stephenplusplus** [comment]
*Duplicate: #2546*

Thanks for reporting. We are moving all of our docs off from GitHub pages and onto cloud.google.com. It is unlikely we will resolve this specific problem, as the transfer is happening quite quickly. Sorry for the inconvenience.
