### ISSUE TITLE
Vision API calls don't work with destructuring

### ISSUE THREAD

**Issue by brabster** [GoogleCloudPlatform/google-cloud-node#2747]
Hi there,

I was trying to use destructuring with the Vision API, and I came across this weird problem. I did:

```javascript
const { batchAnnotateImages } = vision(config);
batchAnnotateImages(...).then(....)
```
and the call failed with a TypeError:
```
TypeError: Cannot read property '_batchAnnotateImages' of undefined
at ImageAnnotatorClient.batchAnnotateImages (/foo/bar/baz/node_modules/@google-cloud/vision/src/v1/image_annotator_client.js:161:14)
```
Looks like something to do with incorrectly binding... this call works:

```javascript
const result = vision(config).batchAnnotateImages(...)...
```

This call fails with the TypeError:
```javascript
const client = vision(config);
const bai = client.batchAnnotateImages;
bai(...)...
```

Workaround is to just call directly on the client rather than using destructuring, but for me this is weird and confusing behaviour and probably best to fix or document. Hope that helps, shout if you need anything else!

  - OS: Linux
  - Node.js version: 8.9.1
  - npm version: 5.5.3
  - google-cloud-node version: 0.12.0

**Comment by stephenplusplus** [comment]
Thanks for reporting. I believe this is just the nature of JavaScript's `this`. When you reference a function of a class to be used later, `this` needs to be bound. For example:

```diff
const client = vision(config);
- const bai = client.batchAnnotateImages;
+ const bai = client.batchAnnotateImages.bind(client);
bai(...)...
```

@callmehiphop is there anything unique about destructuring, where this should be easier?

**Comment by stephenplusplus** [comment]
I believe the solution is just to bind the method, so that context is not lost when you run it later. If @callmehiphop or anyone else knows a more clever way to do this, please let us know!
