### ISSUE TITLE
Constructors require options object

### ISSUE THREAD

**Issue by thefill** [GoogleCloudPlatform/google-cloud-node#2750]
Datastore module for nodejs fails to use application-default-credentials or GOOGLE_APPLICATION_CREDENTIALS env variable.

#### Environment details

  - OS: macOS High Sierra 10.13.1 (17B48)
  - Node.js version: v6.11.5 | v8.1.2
  - npm version: 3.10.10
  - yarn version: 0.21.3
  - google-cloud-node version: 
    - google-cloud/datastore: "^1.1.0"
  - gcloud version
    - Google Cloud SDK 178.0.0
    - beta 2017.09.15
    - bq 2.0.27
    - core 2017.10.30
    - gsutil 4.28

#### Steps to reproduce

  1. setup gcloud via "gcloud init"
  2. For failure with application-default-credentials
     a. gcloud beta auth application-default login
     b. command informs that ~/.config/gcloud/application_default_credentials.json has been created
     c. all documentations suggests that datastore should work when user authenticate via gcloud
     d. in node app: 
     ```
     import * as Datastore from "@google-cloud/datastore";
     const datastore = new Datastore();
     ```
     c. error returned in console 
     ```
     Cannot read property 'apiEndpoint' of undefined
     ```
3. For failure with GOOGLE_APPLICATION_CREDENTIALS env variable
     a. create & download json service account key via google console
     b. Set env variable 
     ```
     export GOOGLE_APPLICATION_CREDENTIALS=/some/path/to/key.json
     ```
     c. all documentations suggests that datastore should check env variable GOOGLE_APPLICATION_CREDENTIALS for path to the key file
     d. in node app: 
     ```
     import * as Datastore from "@google-cloud/datastore";
     const datastore = new Datastore();
     ```
     c. error returned in console 
     ```
     Cannot read property 'apiEndpoint' of undefined
     ```
4. What works:
     a. create & download json service account key via google console
     d. in node app: 
     ```
     import * as Datastore from "@google-cloud/datastore";
     const datastore = new Datastore({
          keyFilename: '/some/path/to/key.json'
     });
     ```
     c. no error returned, datastore client works

Am I doing something wrong? Is that a correct behaviour? 

This forces a developer to hardcode the path to credentials while in local dev.

**Comment by stephenplusplus** [comment]
This is actually an issue with our constructors requiring an options object. In those scenarios, this will work:

```js
import * as Datastore from "@google-cloud/datastore";
const datastore = new Datastore({}); // annoying empty object
```

Sorry for the inconvenience. We will fix it.

**Comment by thefill** [comment]
@stephenplusplus indeed empty object cleared the issue. Thanks for an ultra-fast response ;-)

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-common/issues/14.
