### ISSUE TITLE
Error Reporting could send reported errors to console when in dev mode

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/google-cloud-node#2754]
Today, when using the Error Reporting module in development, a warning is printed: 

WARN:@google-cloud/error-reporting: Stackdriver error reporting client has not been configured to send errors, please check the NODE_ENV environment variable and make sure it is set to "production" or the ignoreEnvironmentCheck property is set to true in the runtime configuration object

This is very good. However, when an error is reported, it is swallowed.

Suggestion: when NODE_ENV is not set to "production", the module could simply print the reported errors to console.log().

This would allow testing that error reporting is properly setup while developing.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-error-reporting/issues/15.
