### ISSUE TITLE
TypeError: client.setCredentials is not a function

### ISSUE THREAD

**Issue by Samartan** [GoogleCloudPlatform/google-cloud-node#2758]
Hello everyone! I have been trying to follow the Cloud vision with Node.js codelab. I am able to start the google sign in flow but after I have selected an account to sign in. I get TypeError as explained below.

Sorry for changing the title that many times. I got a bit sloppy there. 

Please run down the following list and make sure you've tried the usual "quick fixes":

  [done] Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
  [done] Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  [done] Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  [done]  Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: MacOs
  - Node.js version:v8.9.1
  - npm version:5.5.1
  - google-cloud-node version: v6.11.1

#### Steps to reproduce
Follow steps from the codelab.

Error shown:
```
home/user/cloud-vision/start/lib/oauth2.js:172
      client.setCredentials(tokens);
             ^
TypeError: client.setCredentials is not a function
    at /home/user/cloud-vision/start/lib/oauth2.js:172:14
    at /home/user/cloud-vision/start/node_modules/google-auth-library/lib/auth/oauth2client.js:95:13
    at Request._callback (/home/user/cloud-vision/start/node_modules/google-auth-library/lib/transporters.js:113:17)
    at Request.self.callback (/home/user/cloud-vision/start/node_modules/google-auth-library/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/user/cloud-vision/start/node_modules/google-auth-library/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/user/cloud-vision/start/node_modules/google-auth-library/node_modules/request/request.js:1085:12)
```

Further Information: 

The credentials set up is proper because I put in the details into the "Complete" version of the Codelab and I could sigin perfectly. So I thought there must be something wrong with the coding part but I have checked it twice and everything is the same as in the codelab. 

Thanks!

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-vision#15
