### ISSUE TITLE
pubsub: published messages with more than 5000 characters truncated

### ISSUE THREAD

**Issue by emilyplusplus** [GoogleCloudPlatform/google-cloud-node#2760]
#### Environment details

  - OS: macOS High Sierra
  - Node.js version: 8.1.3
  - npm version:5.5.1
  - google-cloud-node version: 0.15.0

#### Steps to reproduce

  1. require `@google-cloud/pubsub`
  2. authenticate properly
  3. publish message to existing topic and message with > 5000 characters will be truncated as if their is a character limit of 5K

**Comment by callmehiphop** [comment]
Thanks for reporting @emilyplusplus, this should be a quickfix, but PubSub is currently in a code freeze. This is a really quick fix however, so hopefully we can address it soon.

**Comment by emilyplusplus** [comment]
@callmehiphop Glad to hear it should be an easy fix and glad to bring it to your attention. Out of curiosity do you know where I might want to look in source to identify problem (just a hunch on where problem may lie?) so that I might look on my own and see if I can identify a temporary fix?

**Comment by callmehiphop** [comment]
There's actually a [gRPC flag](https://github.com/GoogleCloudPlatform/google-cloud-node/blob/master/packages/pubsub/src/connection-pool.js#L401) we need to set to allow a larger message size. By default it only allows payloads to be 4MB (I think).

**Comment by emilyplusplus** [comment]
@callmehiphop ok. i tried upping the constant you linked to to 40000001 but didnt' see any change. Additionally 5000 characters should be well under 4MB so i doubt its the message size that's at fault. seems to be more of a hard character limit or something of that sort. But thanks so much for your timely response. I will continue seeing what I can find

**Comment by stephenplusplus** [comment]
This issue was moved to googleapis/nodejs-pubsub#14
