### ISSUE TITLE
How to disable grpc in the node client?

### ISSUE THREAD

**Issue by hugozap** [GoogleCloudPlatform/google-cloud-node#2762]
I'm having issues with queries hanging with both the python and node client ( probably due to network conditions ). In Python setting GOOGLE_CLOUD_DISABLE_GRPC=True fixed the issue, but that didn't work with the node library. Is there a way  to do it ? Thanks

**Comment by stephenplusplus** [comment]
Hey @hugozap, sorry, but we only use gRPC when available. What issue are you having? Maybe it's something there's a gRPC setting for: https://github.com/grpc/grpc/blob/13e185419cd177b7fb552601665e43820321a96b/include/grpc/impl/codegen/grpc_types.h#L148

**Comment by hugozap** [comment]
Thanks @stephenplusplus The issue I had with the node lib was that when running a query, the callback was never called. Same results with Python (it just hang) until I set the env var GOOGLE_CLOUD_DISABLE_GRPC so I guess the same issue is affecting node but the envvar is not recognized from node.

**Comment by stephenplusplus** [comment]
Which API are you trying to use? If you lay out some more details and the call that's not being answered, we could try to rope in the right people for some help.

**Comment by stephenplusplus** [comment]
I'm going to close, but feel free to open a new issue or comment here with the details of the hanging requests. It's not clear at this point if it's on us (the library code) or the API service, but with more info, we can make sure it's pointed to the right team.
