### ISSUE TITLE
topic.subscribe frequently takes over 30 seconds to fire callback

### ISSUE THREAD

**Issue by jamorales-bsft** [GoogleCloudPlatform/google-cloud-node#2766]
#### Environment details

  - OS: mac os
  - Node.js version: 8.9.1 and 6.11.0
  - npm version: 3.x and 5.5.0
  - google-cloud-node version: 0.13.2

#### Steps to reproduce

  1. require `google-cloud`
  2. Do PubSub.createTopic on an existing topic, then just do a topic.subscribe and sometimes it takes over 30 seconds

Is this considered normal behavior? Today topic.subscribe was taking over 60 seconds causing 

Error: Deadline Exceeded
    at /var/components/live-meeting-session/node_modules/grpc/src/client.js:554:15

due to the default 60 second timeout used in the library

**Comment by callmehiphop** [comment]
@jamorales-bsft I would suggest upgrading to the latest version of PubSub, although watch out for some breaking changes. Otherwise if that's not an option, maybe @stephenplusplus has some suggestions for troubleshooting `0.13.x`.

**Comment by stephenplusplus** [comment]
I think it's best to upgrade as well, especially with issues like this. Please let us know if you're still having issues after using the latest version, 0.16.0: https://github.com/googleapis/nodejs-pubsub/releases/tag/v0.16.0 - Here are some notes about the breaking changes: https://github.com/googleapis/nodejs-pubsub/releases/tag/v0.14.0 -- please just ask if you have any issues during the migration.

**Comment by sinkcup** [comment]
I am using "@google-cloud/pubsub": "^0.16.4" on Cloud Functions, still having this problem.

```
exports.webhook = functions.https.onRequest((req, res) => {
  res.setHeader('content-type', 'text/plain')
  switch (req.method) {
    case 'POST': {
      console.log('webhook POST');
      console.log(req.body);
      const topicName = 'webhook-events';
      const pubsub = new PubSub();
      const data = JSON.stringify(req.body);
      const dataBuffer = Buffer.from(data);
      pubsub
        .topic(topicName)
        .publisher()
        .publish(dataBuffer)
        .then(results => {
          const messageId = results[0];
          console.log(`Message ${messageId} published to ${topicName}.`);
          return messageId;
        })
        .catch(err => {
          console.error('ERROR:', err);
        });
      res.status(200).send();
      break;
    }
    default:
      res.status(200).send();
  }
});
```

log:

![image](https://user-images.githubusercontent.com/4971414/36726544-17b99828-1bf5-11e8-93f7-2aa88a9eac8e.png)

**Comment by callmehiphop** [comment]
@stephenplusplus any thoughts on this?

**Comment by sinkcup** [comment]
platform     | npm pubsub |                      api       | result
---------------|------------------|----------------------------|----------------
GCF          |  0.16.4          | publisher().publish() | errors very often
GCF          |  0.16.4          | pubsub.getTopics()  | no error but slow, 60-90ms
appengine | 0.13.2           | topic.publish()          | no error but slow, 1s
appengine |  0.16.4          | publisher().publish() | no error but slow, 1s

https://us-central1-bothub-uat.cloudfunctions.net/webhookFacebook
![image](https://user-images.githubusercontent.com/4971414/36823562-b4565fe2-1d38-11e8-9d4d-c4dbc46be41e.png)

![image](https://user-images.githubusercontent.com/4971414/36829409-067b0e00-1d5a-11e8-9cc5-2c75e46be24e.png)

![image](https://user-images.githubusercontent.com/4971414/36829659-3338b2e8-1d5b-11e8-97a6-2f65bac76d21.png)

**Comment by sinkcup** [comment]
@stephenplusplus I had test them, see the table above.
