### ISSUE TITLE
All Links to API documentation for Datastore are 404

### ISSUE THREAD

**Issue by n0wak** [GoogleCloudPlatform/google-cloud-node#2769]
Every link the READMEs here for the API Documentation for the datastore
https://googlecloudplatform.github.io/google-cloud-node/#/docs/datastore
goes to a 404. Looks like a redirect is happening on google's end to https://cloud.google.com/nodejs/docs/reference/datastore/latest/

**Comment by stephenplusplus** [comment]
@lukesneeringer @jmdobry

**Comment by ChrisBartonLC** [comment]
Same from https://cloud.google.com/nodejs/docs/reference/libraries

**Comment by jmdobry** [comment]
I just pushed a fix, should be live momentarily

**Comment by ChrisBartonLC** [comment]
FYI it does seem a bit of a mission to get to the docs if you are not very experienced:

1) https://cloud.google.com/docs/
2) Click 'VIEW NODE DOCS' Square
3) Click ''VIEW DOCUMENTATION' Square
4) Click 'APIs & Libraries' Square
5) Click 'Node.js Packages' Square
6) Click '@google-cloud/datastore' Square

**Comment by ChrisBartonLC** [comment]
This is also pretty confusing for a first time user:

1) https://cloud.google.com/datastore/docs/
2) Click 'APIs & Libraries' Square
3) Click 'Client Libraries' Square
4) Select 'NODE.JS'
5) Search for hard to find link 'Node.js API Reference Documentation'

**Comment by stephenplusplus** [comment]
Fix confirmed. @jmdobry do you know the right people we can forward @ChrisBartonLC's feedback to?

**Comment by ChrisBartonLC** [comment]
done
