### ISSUE TITLE
GPRC `requestStream` not ending on piped steam `end` call.

### ISSUE THREAD

**Issue by jiren** [GoogleCloudPlatform/google-cloud-node#2774]
On `end` call piped stream stopped processing but it is not canceling GRPC operation, so a program needs to wait until GRPC end.
 
This issue is related to bigtable-node [#6](https://github.com/googleapis/nodejs-bigtable/issues/6)

Need access of `retryStream` to abort.

https://github.com/GoogleCloudPlatform/google-cloud-node/blob/9b562af3bc4b6a0ecffd7f3529951bdb7971c8f1/packages/common-grpc/src/service.js#L398

**Comment by stephenplusplus** [comment]
Can you elaborate on where you need access from?

**Comment by stephenplusplus** [comment]
I'm not sure how to proceed with this request. If this is still an issue, please let me know and we will re-open.
