### ISSUE TITLE
Google pubsub in react project.

### ISSUE THREAD

**Issue by lafeber** [GoogleCloudPlatform/google-cloud-node#2776]
As soon as I include

    var pubsub = require('@google-cloud/pubsub')

in my react project, I get the error:

    TypeError: existsSync is not a function
    ./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js.exports.find
    node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js:16
      13 | };
      14 | 
      15 | exports.find = function(package_json_path,opts) {
    > 16 |    if (!existsSync(package_json_path)) {
      17 |         throw new Error("package.json does not exist at " + package_json_path);
      18 |    }
      19 |    var package_json = require(package_json_path);

I'm relatively new to react, and debugging it doesn't seem as nice as in ruby projects. Any ideas?

EDIT: probably related to: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2664

**Comment by stephenplusplus** [comment]
Hey @lafeber, you indeed found the issue I was going to re-route to. We don't have any official support for these external environments ([the browser](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/531), [React Native](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2664), etc).

If we do eventually get this on the roadmap, we will update those issues.
