### ISSUE TITLE
[Datastore] Setting zero for latitude or longitude on GeoPoint type breaks the value

### ISSUE THREAD

**Issue by lostpebble** [GoogleCloudPlatform/google-cloud-node#2778]
#### Environment details

  - OS: Windows
  - Node.js version: 8.9.1
  - google-cloud-node version: "@google-cloud/datastore": "^1.1.0",

#### Steps to reproduce

  1. Create entities with GeoPoint values, which have latitude and/or longitude set to 0
  2. Use the `@google-cloud/datastore` library to save those entities
  3. Look in the Datastore console and see that the GeoPoint value has been set incorrectly (shows an exclamation mark in a red symbol)

Before saving, I've printed to console what my array payload looks like with my entities:

```
[
 {
  data: {
    amount: Double { value: 12 }
    date: Fri Dec 15 2017 15:37:43 GMT+0200 (South Africa Standard Time) {}
    location: GeoPoint value: { longitude: 0, latitude: 0 }
    tags: ["blue", "red"],
    worthy: false,
  },
  excludeFromIndexes: [],
  key: Key {
    namespace: "pebbledbed-test-namespace", 
    kind: "TestEntityIntId",
    parent: Key { ... },
    id: "5661458385862656"
  }
 }
]
```

As you can see, it comes out in the console (something) like this:

![image](https://user-images.githubusercontent.com/1508863/34045277-d5e422c0-e1b0-11e7-8e40-4af0e296e36b.png)

And when I click on that property, it shows that both longitude and latitude are empty of any values - whereas they should both be set to zero.

**Comment by stephenplusplus** [comment]
Interesting. I see that as well, however, when I read the data back with `datastore.get(key)` and log the GeoPoint value, it shows up correctly:

```js
{ latitude: 0, longitude: 0 }
```

My guess would be that the UI is doing an incomplete validation that is considering the `0` value invalid. I wouldn't worry about this, unless it is causing any issues. Let me know if that's the case.

I'll mark this closed, as it is not a bug in our library. @alexander-fenster @lukesneeringer @jmdobry do you know how we can pass along this feedback to the relevant team?
