### ISSUE TITLE
Pub/Sub retry settings: needs common api between data & admin ops, better docs.

### ISSUE THREAD

**Issue by kir-titievsky** [GoogleCloudPlatform/google-cloud-node#2788]
This is a bug to track progress on an email discussion about setting custom retry settings. 

Previous suggestion:
In src/v1/publisher_client.js the gapicConfig contains the contents of the config file you mentioned, and it is passed down to gaxGrpc:

https://github.com/googleapis/nodejs-pubsub/blob/96fd4d6347ca0546a8b8581c1db61e2edb0548d8/src/v1/publisher_client.js#L166

    var defaults = gaxGrpc.constructSettings(
      'google.pubsub.v1.Publisher',
      gapicConfig,
      opts.clientConfig,
      {'x-goog-api-client': clientHeader.join(' ')}
    );
Here the third parameter, opts.clientConfig, gives configOverrides to gaxGrpc.constructSettings, and, given the name, I guess it might be able to override options.
opts.clientConfig comes from PublisherClient constructor parameter. So I guess you might try settings opts.clientConfig to override any default configuration.

If it does not work for you, please let me know - better with code example - and I'll create an issue for pubsub package.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-pubsub/issues/35.
