### ISSUE TITLE
Google Speech API: enableWordTimeOffsets = true not working for streamingRecognize

### ISSUE THREAD

**Issue by bloodcarter** [GoogleCloudPlatform/google-cloud-node#2793]
enableWordTimeOffsets option yelds empty "words" array at least for streamingRecognize and al least for Russian. 

Env:
  - OS: Linux ip-172-31-16-252 4.9.62-21.56.amzn1.x86_64 #1 SMP Thu Nov 16 05:37:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
  - Node.js version: v7.2.1
  - npm version: 3.10.10
  - google-cloud-node version:  @google-cloud/speech@0.10.3

Code:
```
var recognizeStream = Speech.streamingRecognize(
    {
      config: {
        enableWordTimeOffsets: true,
        encoding: self.inputFormat.encoding,
        sampleRateHertz: self.inputFormat.sampleRate,
        languageCode: "ru-RU"
      },
      singleUtterance: false,
      interimResults: true
    }
  );

recognizeStream.on('data', (data)=>{...});
```

**Comment by stephenplusplus** [comment]
Closing in favor of https://github.com/googleapis/nodejs-speech/issues/15
