### ISSUE TITLE
Properties excluded from indexes are not retained on cloud datastore update

### ISSUE THREAD

**Issue by plaisted** [GoogleCloudPlatform/google-cloud-node#2796]
#### Environment details
 - Google cloud functions.
 - Datestore lib: 1.3.3

#### Steps to reproduce

1. Insert entity with property excluded from index. (eg `entity.foo`)
2. Get property using nodejs library:
```
let result = await datastore.get(entityKey);
```
3. Change different property and update:
```
result[0]["bar"] = "bar";
await datastore.update(result[0]);
```
4. Foo is now included in indexes.

This does not occur using the c# libraries with the same commands. Is there a way to prevent this? I would expect the update to retain the index setup for the entity so that on update `foo` remains un-indexed.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-datastore/issues/44.
