### ISSUE TITLE
Datastore: nextPageCursor in runQuery changes every time when last entity gets modified

### ISSUE THREAD

**Issue by Nagaraj-Prabhu** [GoogleCloudPlatform/google-cloud-node#2799]
Hi,

I'm using datastore client library of version 1.3.3

The 'endCursor' in the runQuery result changes when I update the last item of that query result. If I try to fetch the next set of items using the cursor which I got with the previous query,  it returns set of entities in which the first entity will be the duplicate of last entity in the previous set.
like
.................
5007404484788224
5289011263307776
5805078561685504
-- new set --
5805078561685504
4785039263924224
4655690686660608
.........

Here is the code I have used to fetch the entities from datastore
query = dataStore.createQuery(Kind);
query.select(<parameters>);
.order(<property>, {
                    descending: true,
                })
.limit(10);
dataStore.runQuery(query, function(err, entities, cursorInfo) {
    console.log(err);
}
runQuery sometimes fails with error: 'Error parsing protocol message' while fetching entities using the cursor.

 Steps to reproduce
1. Fetch 1 - 10 items. The client holds the cursor
2. Modify 10th item
3. Try to retrieve 11 - 20 using the cursor of Step 1. It fails

Please help me in this regard.

Thanks!

**Comment by stephenplusplus** [comment]
Closing in favor of duplicate on nodejs-datastore: https://github.com/googleapis/nodejs-datastore/issues/46
