### ISSUE TITLE
Issue template has 404 links

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#2802]
###### Copied from original issue: https://github.com/googleapis/nodejs-speech/issues/28

<a href="/talkingnews"><img src="https://avatars2.githubusercontent.com/u/1552808?s=88&v=4" height=44 width=44 align=left></a>@talkingnews<br>February 19, 2018 4:26 PM

Both of the links below in the template are broken - can't find suitable alternatives

  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

**Comment by stephenplusplus** [comment]
@alexander-fenster Should we point these to something new, or just get rid of them?

**Comment by alexander-fenster** [comment]
@jmdobry can you please comment?

**Comment by jmdobry** [comment]
I invite @stephenplusplus and @alexander-fenster to change https://github.com/GoogleCloudPlatform/nodejs-repo-tools/blob/master/templates/nodejs/issue_template.tpl to your liking.

**Comment by stephenplusplus** [comment]
PR sent https://github.com/GoogleCloudPlatform/nodejs-repo-tools/pull/103

**Comment by stephenplusplus** [comment]
Fixed in https://github.com/GoogleCloudPlatform/nodejs-repo-tools/pull/103
