### ISSUE TITLE
progressPercent is always 0

### ISSUE THREAD

**Issue by Maqsim** [GoogleCloudPlatform/google-cloud-node#2803]
#### Environment details

  - OS: macOS 10.12.6
  - Node.js version: 8.9.3
  - npm version: 5.6.0
  - google-cloud-node version: 1.1.0

#### Steps to reproduce

  1. require `@google-cloud/speech`
  2. Set config:
```
const transcriptionRequestParams = {
    encoding: 'LINEAR16',
    profanityFilter: false,
    sampleRateHertz: 16000,
    enableWordTimeOffsets: true
  };
```
  3. Upload file into bucket and run `longRunningRecognize`:
```
return uploadToBucket(filePath)
    .then(bucketFile => launchAsyncRecognition(bucketFile, transcriptionRequestParams))
    .then(handleTranscriptions);

function launchAsyncRecognition(bucketFile, config) {
  const audio = { uri: googleBucketLink + '/' + bucketFile.name };
  const request = { config, audio };

  return speechClient.longRunningRecognize(request);
}
```
  4. Inside `handleTranscriptions` add `.on` for `progress`:
``` 
  const operation = data[0];

  operation.on('progress', function (metadata, apiResponse) {
    console.log(metadata);
  });
```
  5. Console log is:
```
{ progressPercent: 0,
  startTime:
   { seconds: Long { low: 1519465382, high: 0, unsigned: false },
     nanos: 856653000 },
  lastUpdateTime:
   { seconds: Long { low: 1519465383, high: 0, unsigned: false },
     nanos: 354594000 } }
```

Thanks in advance for any help.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-speech/issues/34.

**Comment by stephenplusplus** [comment]
Are you handling the `error` event as well? And does `progress` get emitted more than once?

**Comment by Maqsim** [comment]
@stephenplusplus There is no errors for sure (the transcribing ends successfully). Only once.

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/gax-nodejs/issues/192.
