### ISSUE TITLE
Google Container Builder

### ISSUE THREAD

**Issue by Philmod** [GoogleCloudPlatform/google-cloud-node#2805]
Hey!

What would be the process to add GCB to this node library? It would be very useful in order to call this API from GCF for example.

Thank you,
Philippe

Disclaimer: I work in the GCB team

**Comment by stephenplusplus** [comment]
Hello! 👋 We actually have an issue for new API requests: https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1338. Please add it over there when you have a chance.

// cc @alexander-fenster if you want to add anything
