### ISSUE TITLE
Cloud functions. The request signature we calculated does not match the signature you provided

### ISSUE THREAD

**Issue by alexanderkhitev** [GoogleCloudPlatform/google-cloud-node#2807]
I had a task, after registering users in the application (registering through facebook) to keep facebook avatar in firebase storage, as facebook links have a limited period of work. I implemented the function I'll write below, but I get the following error **The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method**, when I try to use a link to an image. Please tell me how it can be fixed?   

    const functions = require('firebase-functions');
    const admin = require('firebase-admin');
    const gcs = require('@google-cloud/storage')({keyFilename: "service-account-credentials.json"});
    const uuid = require('uuid');
    const imageDownloader = require('../lib/Images/image-manager.js');
    const path = require('path');
    const timestamp = require('unix-timestamp');
    
    module.exports = functions.https.onRequest((req, res) => {
        const token = req.header('X-Auth-MyApp-Token');
        const imageURL = req.body.imagePath;
        const bucketName = functions.config().googlecloud.defaultbacketname;
        const bucket = gcs.bucket(bucketName);
    
        var userID = '';
        const shortID = uuid.v1();
        const filename = shortID + '.jpg';
        var profileImagePath = '';
    
        return admin.auth().verifyIdToken(token).then(decodedToken => {
            userID = decodedToken.uid;
    
            return imageDownloader.downloadImageToLocalDirectory(imageURL, filename)
        }).then(localImagePath => {
    
            profileImagePath = path.normalize(path.join('userImages', userID, 'profileImages', filename));
            const uploadProm = bucket.upload(localImagePath, {
                destination: profileImagePath,
                uploadType: "media",
                metadata: {
                    contentType: 'image/jpeg'
                }
            });
    
            return uploadProm;
            }).then(() => {
            console.log('success uploaded');
            const config = {
                action: 'read',
                expires: '03-01-2400',
                contentType: 'image/jpeg'
            };
    
            const userRefPromise = admin.database().ref()
                .child('users')
                .child(userID)
                .once('value');
    
            const profileImageFile = bucket.file(profileImagePath);
    
            return Promise.all([profileImageFile.getSignedUrl(config), userRefPromise])
            }).then(results => {
            const url = results[0][0];
            const userModel = results[1].val();
            const userCheckID = userModel['id'];
    
            console.log("get url", url);
    
            // save to database
    
            const userImagesRef = admin.database().ref().child('userImages')
                .child(userID)
                .child('userProfileImages')
                .push();
    
            const timeStamp = timestamp.now();
            console.log('timeStamp', timeStamp);
            const imageModelID = userImagesRef.key;
            const userImagesRefPromise = userImagesRef.update({
                'path': url,
                'id': imageModelID,
                'fileName': filename,
                'timeStamp': timeStamp
            });
    
            const userRef = admin.database().ref()
                .child('users')
                .child(userID)
                .child('currentProfileImage');
            const userRefPromise = userRef.update({
                'path': url,
                'id': imageModelID,
                'fileName': filename,
                'timeStamp': timeStamp
            });
    
            return Promise.all([userImagesRefPromise, userRefPromise]);
        }).then(() => {
            const successJSON = {};
            successJSON["message"] = "Success operation";
            return res.status(200).send(successJSON);
        }).catch(error => {
            console.log(error);
            const errorJSON = {};
            errorJSON["error"] = error;
            return res.status(error.code).send(errorJSON);
        });
    });

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-storage/issues/144.
