### ISSUE TITLE
Documentation for breaking changes on google vision releases

### ISSUE THREAD

**Issue by peteboere** [GoogleCloudPlatform/google-cloud-node#2808]
Where can I find clear documentation for breaking changes on @google-cloud/vision which seems to have a public API rewrite on every minor point release.

For example 0.11 -> 0.12 has an API rewrite but this is documented in the release notes of this repository. The current release is marked as 0.16 but I can find not documentation, or even acknowledgement of breaking changes since 0.12.

**Comment by stephenplusplus** [comment]
Which API are you using? We keep the release notes in the API's own repo, e.g. https://github.com/googleapis/nodejs-storage

**Comment by peteboere** [comment]
Ok thanks, I kept turning up:
https://github.com/GoogleCloudPlatform/google-cloud-node/releases
This was what I was looking for:
https://github.com/googleapis/nodejs-vision/releases
