### ISSUE TITLE
Key return in json DataStore

### ISSUE THREAD

**Issue by DerlysF** [GoogleCloudPlatform/google-cloud-node#2809]
Hello its possbile i return an key from datastore, 
together from another informations?

Exemple, i have an entity in my datastore, that its called James e have 15 years, when i do an request returns me these informations, and no returns me a key of the entity.

Can someone help me?

**Comment by stephenplusplus** [comment]
This sounds like a great question for the community of developers using `@google-cloud/datastore`. Here's a link that will take you to the right place to post: https://stackoverflow.com/questions/tagged/google-cloud-platform+node.js+datastore
