### ISSUE TITLE
Broken links:

### ISSUE THREAD

**Issue by Optimus-73** [GoogleCloudPlatform/google-cloud-node#2812]
Broken links:
- [ ] https://cloud.google.com/vision/docs/face-tutorial > Begore you begin > step five > node.js tab > package.json.
- [ ] https://cloud.google.com/vision/docs/face-tutorial > Create the service object > node.js tam > line four.

**Comment by stephenplusplus** [comment]
Hey @Optimus-73, thanks for reporting! We actually don't control that page from here, so the best way to get the feedback to the right team is with the "SEND FEEDBACK" link at the bottom of the page.
