### ISSUE TITLE
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.

### ISSUE THREAD

**Issue by ravirajdj** [GoogleCloudPlatform/google-cloud-node#2814]
When I access the signed url from browser it gives a message stating "SignatureDoesNotMatch"

I checked below link but no luck.

https://github.com/GoogleCloudPlatform/google-cloud-node/issues/1976

Below is my function code

`
     }).then(() => {

                 const thumbFile = bucket.file(thumbFilePath)
                 const config = {
                   action : 'write',
                   expires : '03-09-2400'
                   

                 }
                 return Promise.all([
                   thumbFile.getSignedUrl(config),
                   file.getSignedUrl(config)

                 ])
`

Error Message:

`[<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>
The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method.
</Message>
<StringToSign>
GET 13575340800 /mango-b715d.appspot.com/asART_Nikola-Tesla_Wallpaper_V03.png
</StringToSign>
</Error>](url)`

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-storage/issues/177.
