### ISSUE TITLE
Can't find mapping between ILSVRC2012_ID and human readable strings

### ISSUE THREAD

**Issue by stefano9-4** [GoogleCloudPlatform/google-cloud-node#2823]
Hi,

I am working on a personal project that adds noise to the images of the ILSVRC2012 validation set in order to miss-classify them (using Google's cloud vision).  My problem is that I can't seem to find the correct mapping between the IDs that are provided to me by the devkit task 1&2 provided here: http://www.image-net.org/challenges/LSVRC/2012/nonpub-downloads.

Online I found this: https://gist.github.com/xkumiyu/dd200f3f51986888c9151df4f2a9ef30 and this: https://gist.github.com/xkumiyu/dd200f3f51986888c9151df4f2a9ef30 but when I try to compare the IDs to the labels they don't seem to match with neither of the lists.

Any help would be greatly appreciated :-)

**Comment by JustinBeckwith** [comment]
This issue was moved to googleapis/nodejs-vision#70
