### ISSUE TITLE
Create labels for semver-{major,minor,patch}

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#2827]
The Node.js library repos should have `semver-{major,minor,patch}` labels so that it is easier to identify the semver impact of any given PR.

**Comment by JustinBeckwith** [comment]
@GoogleCloudPlatform/yoshi  any thoughts on this one?  I'm generally in favor of adding these and using them, but I have a very nodejs centric view of the world :)

**Comment by theacodes** [comment]
I'm -1. More labels is not better. We'll just forget to apply these unless we write a bot to enforce them.

**Comment by jadekler** [comment]
-1, this would be moot in Go since we never "backport" any changes.

**Comment by dazuma** [comment]
I'm also -1, as it's not clear what benefit it gives us for the cost of more labels and process. Are we trying to automate updating the version number based on this?

Note that different language communities do have different approaches to semver. The Ruby team, for example, tends to avoid semver-major changes like the plague, to avoid diamond dependency issues.

**Comment by theacodes** [comment]
Python is similar, and no semver major changes in *any* language can occur
without my signoff.

As we get Node.js and Ruby moved over to the releasetool used by Python,
the release engineer will be prompted to pick the version change after
compiling a changelog. While having releasetool show these labels might be
helpful, ultimately it's up to the engineer to make the choice based on the
changes since the previous release. I'm happy to demonstrate this to anyone
who's curious, and me and @crwilcox are working to get this done within the
next few weeks (barring priority interrupts).

**Comment by ofrobots** [comment]
I'm only asking for Node.js. I don't have opinions on whether other languages should have the labels.

To ensure accuracy, I would impose a simple requirement: No change can land unless it has a semver label.

> and no semver major changes in *any* language can occur without my signoff.

Having these labels will get these changes onto your radar. I think these might be sneaking past you  at present 😃.

> As we get Node.js and Ruby moved over to the releasetool used by Python

I would like the semver impact to be determined before the change *lands* – not at release time.

**Comment by ofrobots** [comment]
> Note that different language communities do have different approaches to semver. 

Yes language communities are different, and I think it makes sense to have semver labels in the Node.js repos if we are to match expectations of the community.

> The Ruby team, for example, tends to avoid semver-major changes like the plague, to avoid diamond dependency issues.

Diamond dependency isn't a problem in the Node.js ecosystem. 

In the Node.js community, semver is a means of *communication* of changes.  Semver major are expected and sometimes unavoidable (e.g. when a downstream package drops support for a Node.js major version.) in the Node.js ecosystem.
