### ISSUE TITLE
Error node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/ ?

### ISSUE THREAD

**Issue by oshalygin** [GoogleCloudPlatform/google-cloud-node#2830]
This seems to occur with Node V10+ 

This issue is identical but it involves every single @google/* package:
https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2826

#### Environment details

  - OS: OSX
  - Node.js version: v10.2.0
  - npm version: 5.6.0
  - google-cloud-node version: 
```
    "@google-cloud/logging": "1.2.0",
    "@google-cloud/storage": "1.7.0",
    "@google-cloud/trace-agent": "2.10.1",
```
#### Steps to reproduce

npm install any of these:

```
    "@google-cloud/logging": "1.2.0",
    "@google-cloud/storage": "1.7.0",
    "@google-cloud/trace-agent": "2.10.1",
```

Thanks!

**Comment by crwilcox** [comment]
I can't reproduce your failures for any package. I can make this fail installing `google-cloud` as is stated in #2826. 

The root of the issue seems to be `npm install grpc@1.7.3` (which occurs as a dependency of `npm install @google-cloud/firestore@^0.8.0` which is a dependency of `npm install google-cloud@0.57.0`. That version of grpc, which is a bit old, doesn't have a binary prebuilt. The current version, `grpc@1.13.0-pre1` installs without issue.

@oshalygin, Can you confirm that with a blank directory you are unable to install of `@google-cloud/logging`? If not, I am going to scope this back to just installation issues with `google-cloud` as it seems its install of firestore

## Output of installing GRPC v1.7.3
```
crwilcox@crwilcox:~/test-gyp-firestore$ npm install grpc@1.7.3

> grpc@1.7.3 install /usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.2.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v64-linux-x64-glibc.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@10.2.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
make: Entering directory '/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/build'
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
make: Entering directory '/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/build'
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/surface/init.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_args.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/channel_stack_builder.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker.o
sed: can't read ./Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o.d.raw': No such file or directory
grpc.target.mk:399: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/channel/connected_channel.o] Error 1
make: Leaving directory '/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/bin/node" "/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/bin/node /usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
node-pre-gyp ERR! System Linux 4.9.0-6-amd64
node-pre-gyp ERR! command "/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/bin/node" "/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc
node-pre-gyp ERR! node -v v10.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/bin/node /usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --library=static_library --module=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc' (1)
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_factory.ol script
  CC(target) Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o script
In file included from ../deps/grpc/src/core/lib/iomgr/closure.h:26:0,
                 from ../deps/grpc/src/core/lib/channel/handshaker.h:24,
                 from ../deps/grpc/src/core/lib/channel/handshaker_factory.h:24,
                 from ../deps/grpc/src/core/lib/channel/handshaker_registry.h:24,
                 from ../deps/grpc/src/core/lib/channel/handshaker_registry.c:19:
../deps/grpc/src/core/lib/iomgr/error.h:26:10: fatal error: grpc/status.h: No such file or directory
 #include <grpc/status.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
grpc.target.mk:399: recipe for target 'Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o' failed
make: *** [Release/obj.target/grpc/deps/grpc/src/core/lib/channel/handshaker_registry.o] Error 1
make: Leaving directory '/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.9.0-6-amd64
gyp ERR! command "/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/bin/node" "/usr/local/google/home/crwilcox/.nvm/versions/node/v10.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--library=static_library" "--module=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc"
gyp ERR! cwd /usr/local/google/home/crwilcox/test-gyp-firestore/node_modules/grpc
gyp ERR! node -v v10.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/google/home/crwilcox/test-gyp-firestore/package.json'
npm WARN test-gyp-firestore No description
npm WARN test-gyp-firestore No repository field.
npm WARN test-gyp-firestore No README data
npm WARN test-gyp-firestore No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grpc@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/local/google/home/crwilcox/.npm/_logs/2018-06-21T17_36_18_091Z-debug.log
```

**Comment by oshalygin** [comment]
@crwilcox thanks for looking into this, apologies for the late reply.  I was able to solve this earlier in the day by bumping all of these package versions:

```
 "@google-cloud/logging": "1.2.0",
    "@google-cloud/storage": "1.7.0",
    "@google-cloud/trace-agent": "2.10.1",
```

Steps to fix this for anyone else reading:
1. rm -rf node_modules
2. rm yarn.lock
3. yarn

Obvs use the alternative with npm if you're going to use npm.

Make sure the package versions are fixed and they are the ones listed above.

Running this successfully with Node.js v10.2.0

**Comment by Brenndoerfer** [comment]
I can confirm that changing the versions solved it for me.
In my case:
``` 
"@google-cloud/datastore": "1.4.x",
"@google-cloud/nodejs-repo-tools": "2.3.x"
```

**Comment by edijman** [comment]
Changing node to the stable version works for me.

**Comment by jwiesmann** [comment]
i just had the same issue, adding: 
`"engines": {
    "node": "8.9.4"
  }`
to my package.json made it work. Node 10.13.0 does throw the same error as mentioned above.

**Comment by lborgman** [comment]
I think I have the same issue, though on Windows 10. The output is a little bit different (no "make" here...).  I have just checked out this again. It was built this spring, but "node_modules" is not in the GIT repository so I just ran "npm install". I have always tried to avoid Python (sorry) so I do not understand what is wrong here at the moment. Some syntax error. 


C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions>npm install

> grpc@1.9.1 install C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@10.14.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.9.1/node-v64-win32-x64-unknown.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.9.1 and node@10.14.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\lejon\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp gypERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
 gyp ERR!ERR!  configure errorstack
                                ^
gypgyp  ERR!ERR!  stack SyntaxError: invalid syntax

**Comment by lborgman** [comment]
Just by chance I tried "npm install grpc" (since I assume that versions might be wrong). I got this, which made me a bit worried:


C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions>npm install grpc

> grpc@1.16.1 install C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\getusermedia-to-text\node_modules\@google-cloud\common-grpc\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\getusermedia-to-text\node_modules\@google-cloud\common-grpc\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node" is installed via remote

> grpc@1.16.1 install C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\getusermedia-to-text\node_modules\google-gax\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\getusermedia-to-text\node_modules\google-gax\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node" is installed via remote

> grpc@1.17.0-pre1 install C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download
[grpc] Success: "C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unknown\grpc_node.node" is installed via remote

> protobufjs@6.8.6 postinstall C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions\node_modules\getusermedia-to-text\node_modules\protobufjs
> node scripts/postinstall

npm WARN firebase-functions@2.0.5 requires a peer of firebase-admin@~6.0.0 but none is installed. You must install peer dependencies yourself.

+ grpc@1.17.0-pre1
added 231 packages from 56 contributors and audited 9093 packages in 57.279s
found 149 vulnerabilities (88 moderate, 61 high)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by lborgman** [comment]
And then this. Now I guess I am into deep water here with the wrong version of "node.js". Any suggestions? Should I just delete "node_modules" and "package-lock.json"? And then try to install the supported version of "node.js" (which I rather avoid if I can since I am not going to release this software in a while)?

C:\Users\lejon\bitbucket\easycaped\firebase-caped\functions>npm audit fix
npm WARN firebase-functions@2.0.5 requires a peer of firebase-admin@~6.0.0 but none is installed. You must install peer dependencies yourself.

added 10 packages from 11 contributors, removed 8 packages and updated 9 packages in 8.939s
fixed 92 of 149 vulnerabilities in 9093 scanned packages
  2 package updates for 57 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

**Comment by lborgman** [comment]
Hm, excuse the noise. Removed package-lock.json and installed peer dependencies. I get no errors at the moment. Not deployed, running locally. (Using node --version V10.14.0 and firebase --version V6.1.1.)

**Comment by jandog8990** [comment]
what was your grpc version?

**Comment by jandog8990** [comment]
I've been working on this error all day and Still haven't got it to work:

My node versions:

node: v11.6.0
npm: 6.5.0-next.0
gprc (package.json): 1.17.0

When I run npm install for my project it randomly tries to install gprc@1.7.3 which doesn't make sense to me since I specify 1.17.0. Has anyone found a fix?

I've removed the ~/.node-gyp and ~/.nprmc files as well as downgrading to node 9.9.0 and still no go.

**Comment by jandog8990** [comment]
My stack:

> grpc@1.7.3 install /Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v67-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.7.3/node-v67-darwin-x64-unknown.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.7.3 and node@11.6.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp) 
gypgyp ERR!  configure errorERR! 
 configure error 
gypgyp  ERR!ERR!  stackstack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
 Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gypgyp  ERR!ERR!  stackstack   File "<string>", line 1
   File "<string>", line 1
gypgyp  ERR!ERR!  stackstack     import sys; print "%s.%s.%s" % sys.version_info[:3];
     import sys; print "%s.%s.%s" % sys.version_info[:3];
gypgyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! ERR!  stackstack 
gyp                                ^
 ERR!gyp  ERR!stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp  stackERR! SyntaxError: invalid syntax
 stackgyp     at ChildProcess.emit (events.js:188:13)
 gyp ERR!ERR!  stackstack 
     at maybeClose (internal/child_process.js:978:16)
gypgyp  ERR! stackERR!     at ChildProcess.exithandler (child_process.js:294:12)
 gyp stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
gyp ERR! gypstack      at Socket.stream.socket.on (internal/child_process.js:395:11)
ERR!gyp  System Darwin 15.4.0
ERR! stackgyp     at Socket.emit (events.js:188:13)
 gypERR!  ERR!command  "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown"
stack     at Pipe._handle.close (net.js:610:12)
gyp ERR! cwd /Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v11.6.0
gypgyp  ERR!ERR!  node-gyp -v v3.8.0
System Darwin 15.4.0
gyp ERR! gypnot ok  
ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node" "--module_name=grpc_node" "--module_path=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown"
gyp ERR! cwd /Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:978:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
node-pre-gyp ERR! System Darwin 15.4.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"
node-pre-gyp ERR! cwd /Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc
node-pre-gyp ERR! node -v v11.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown/grpc_node.node --module_name=grpc_node --module_path=/Users/alejandrogonzales/Development/MyProjects/Abantu/site/abantu-audio-nodejs/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v67-darwin-x64-unknown' (1)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.7.3 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.7.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alejandrogonzales/.npm/_logs/2018-12-28T05_45_15_364Z-debug.log

**Comment by jandog8990** [comment]
Nevermind I got it, thx

**Comment by thebly86** [comment]
@jandog8990 how did you fix it?

**Comment by jandog8990** [comment]
@thebly86 go through your package.json and eliminate all that you don't use first, then remove your node_modules/ and package-lock.json and finally run npm update in your project directory. I tried everything mentioned above but it turned out it was just a matter of updating my modules

**Comment by MelisseCabral** [comment]
I had this problem after config CORS for storage on firebase, in my case was solved with:

npm install gutils

**Comment by arcadia168** [comment]
Simply [reinstalling the Google Cloud SDK](https://cloud.google.com/sdk/docs/) seemed to resolve my issues.

**Comment by AleksandarSavic95** [comment]
Downgrading node to version 9 (9.11.2), removing `package-lock.json` and running `npm install` did the trick for me.

**Comment by yingdi1** [comment]
@AleksandarSavic95  downgrading is not a long term solution

**Comment by JustinBeckwith** [comment]
Folks, if you are having problems here, please file a new issue with as many details as possible, and we'd be happy to take a look :)
