### ISSUE TITLE
Wrong project id is being used in runtime

### ISSUE THREAD

**Issue by RonItelman** [GoogleCloudPlatform/google-cloud-node#2834]
Despite running `gcloud auth application-default login` and `gcloud config set core/project CORRECT_PROJECT_ID` the project keeps defaulting to a different project id.

if I run `gcloud config list`
```
[core]
account = CORRECT_EMAIL_ADDRESS
disable_usage_reporting = True
project = CORRECT_PROJECT_ID
Your active configuration is: [default]
```

If I run 
```
gcloud projects list
PROJECT_ID           NAME          PROJECT_NUMBER
CORRECT  CORRECT  CORRECT
```

I can successfully run the sample code from the tutorial (below) if I run in the terminal
export `GOOGLE_APPLICATION_CREDENTIALS="[PATH]"`

However, I didn't want to have to do this every time, so I ran the command:
`gcloud auth application-default login`

This opened a browser with a list of my gmail accounts, and even though I selected the correct account, the success window went to a different gmail account. So then I tried it in an incognito window, and it worked. 

However, running npm start resulted in the following error:

`ERROR: { Error: 7 PERMISSION_DENIED: Cloud Natural Language API has not been used in project WRONG_PROJECT_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/language.googleapis.com/overview?project=WRONG_PROJECT_ID then retry.`

Then I ran `gcloud config set core/project CORRECT_PROJECT_ID` and got the message `Updated property [core/project].`

When I run npm start I get the same message:

`ERROR: { Error: 7 PERMISSION_DENIED: Cloud Natural Language API has not been used in project WRONG_PROJECT_ID before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/language.googleapis.com/overview?project=WRONG_PROJECT_ID then retry.`

I tried `gcloud auth login` and got the following message (after I authenticated in an incognito window):
```
WARNING: `gcloud auth login` no longer writes application default credentials.
If you need to use ADC, see:
  gcloud auth application-default --help

You are now logged in as [CORRECT EMAIL ADDRESS].
Your current project is [CORRECT_PROJECT_ID].  You can change this setting by running:
  $ gcloud config set project PROJECT_ID

```
I tried to delete the other project, but I get this:
```
gcloud projects delete INCORRECT_PROJECT_ID
Your project will be deleted.

Do you want to continue (Y/n)?  Y

ERROR: (gcloud.projects.delete) User [MY_EMAIL] does not have permission to access project [INCORRECT_PROJECT_ID] (or it may not exist): User is not authorized.
```
I don't see that project id anywhere in my dashboard

**Comment by mikila85** [comment]
Hi @RonItelman, please can you share what you did? i keep getting Project x has been deleted where its not even an existing one.. i bet its an environment var or something hardcoded in one of their file but i dont know how to remove it.

**Comment by mikila85** [comment]
FIX: 
gcloud auth application-default login
