### ISSUE TITLE
Configure greenkeeper to run on sample package.json

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-node#2835]
We are suffering from woefully out of date dependencies in our samples:
https://github.com/googleapis/nodejs-dlp/pull/66/files

This is causing build breaks in seemingly random places, especially when pulling in old versions of native modules that are no longer supported. 

TL;DR - we need to enable greenkeeper (or renovate) to keep dependencies in our samples folders up to date.  We also need to make sure we're using `^` or otherwise sane semver range specifiers, as I've noticed a few that are hard coded (no range specifier).

**Comment by JustinBeckwith** [comment]
cc @GoogleCloudPlatform/yoshi-nodejs @GoogleCloudPlatform/node-team as FYI

**Comment by kinwa91** [comment]
Need a `greenkeeper.json` config

https://greenkeeper.io/docs.html#monorepo

**Comment by JustinBeckwith** [comment]
Just to keep us all on the same page - @alexander-fenster has a setup with renovate working here:
https://github.com/googleapis/nodejs-cloud-container/pull/33

We want to use renovate because it will submit `package-lock.json` files, and is generally more configurable. If we're all happy with renovate, the next task is to update all of the `Enable renovate` PRs with the right config, and hammer approve/merge them.  

@alexander-fenster you have the ball here, right?

**Comment by JustinBeckwith** [comment]
We got this up and running with renovate 😸
