### ISSUE TITLE
Dropping support for node.js 4.x and 9.x 

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-node#2838]
I'd like to submit a blanket PR to drop support for node.js 4x and 9.x . This would be a semver major across the board.  Given that we're no longer worried about the constructor pattern issue with TypeScript, does anyone have an objection to dropping these across the board?

@GoogleCloudPlatform/node-team @GoogleCloudPlatform/yoshi-nodejs

**Comment by crwilcox** [comment]
As we are looking at rev-ing some of the libs anyway with recent changes I think this is a solid idea. Are you planning on tackling this work? It should mostly be updating package.json and test configs right?

**Comment by JustinBeckwith** [comment]
We should be able to use the [@google/repo](https://github.com/googleapis/github-repo-automation) to do it - @alexander-fenster has a bunch of good examples in there 😄

**Comment by JustinBeckwith** [comment]
We are waiting for a final conversation with legal on this one.  As soon as that's cleaned up, we can use repo to blanket drop it.

**Comment by JustinBeckwith** [comment]
This is fixed now!
