### ISSUE TITLE
Libraries should avoid unhandled rejections

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#2839]
Unhandled rejections are typically a bad code smell, and many times hide real bugs. It is the logical equivalent of swallowing a sync error in a catch block (this analogy is not perfect though).

Looking at our tests, I see lots of unhandled rejections being thrown around. This could be due to a bug in the library, or a bug in how the tests are setup. The latter would be okay, if we were guaranteed that the former doesn't exist. That is, if we are confident that a user may never see an unhandled rejection caused by our libraries. We have no means of asserting that today.

At a future date Node.js core may make unhandled rejections fatal. That is – the process may crash on an unhandled rejection.

I would like our libraries to run tests in a setup where unhandled rejections are considered fatal. This can be achieved by using the [`hard-rejection`](https://npm.im/hard-rejection) module and passing it as a preload to mocha: `
mocha --require hard-rejection/register`.

Can we get this rolled out across all our libraries?

**Comment by ofrobots** [comment]
Is there a 'code-health' label?

**Comment by JustinBeckwith** [comment]
> Is there a 'code-health' label?

I've been using `type: cleanup` for that purpose.  Happy to have a discussion on what it should be called :)

I absolutely love this idea.  Let's see how it plays out with the google-auth-library PR, and if we like it, replicate across all the repos 👍

**Comment by JustinBeckwith** [comment]
Now that we are using --throw-deprecation in all (well, working on it) of our tests, I think this is good to go :)
