### ISSUE TITLE
Run tests with --throw-deprecations

### ISSUE THREAD

**Issue by ofrobots** [GoogleCloudPlatform/google-cloud-node#2844]
Similar to https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2839, it would be good for Google Cloud libraries to not use deprecated Node.js APIs. Deprecation messages printed to the console, however, can be easy to miss.

We should run tests with `--throw-deprecations` to ensure that use of deprecated APIs is caught by tests.

The same deprecation mechanism would work for our own deprecations, e.g. https://github.com/google/google-auth-library-nodejs/pull/402.

**Comment by JustinBeckwith** [comment]
Should we run all of our tests with this turned on, or just the system-tests and samples tests?  I ask because we have unit tests that verify the warning behavior for deprecated APIs :)

**Comment by ofrobots** [comment]
We have unit tests that verify the warning behavior of all deprecations, including Node.js? Can you point me to how this is done?

**Comment by JustinBeckwith** [comment]
I was referring to this:
https://github.com/google/google-auth-library-nodejs/pull/402/files#diff-86629eb1fa03b5146081c8eed046735bR1407

When you run that unit test, it will emit the deprecation warning to the console.

**Comment by ofrobots** [comment]
Oh gotcha! In that test could you install a mock on `process.emitWarning` instead of installing a listener and expecting it to be called?

**Comment by JustinBeckwith** [comment]
All of the PRs for this have been submitted.  Just waiting on fix in gax-nodejs to land the stragglers :)
