### ISSUE TITLE
Renovate: add group:linters to renovate's config

### ISSUE THREAD

**Issue by kinwa91** [GoogleCloudPlatform/google-cloud-node#2849]
https://github.com/dialogflow/dialogflow-nodejs-client-v2/pull/112#issuecomment-405838674

> You might also want to consider adding the preset "group:linters" to Renovate's config. It groups together all lint packages (eslint, tslint, etc) into a single PR, which is usually preferable than upgrading them individually and having to think about peerDependencies.

**Comment by JustinBeckwith** [comment]
Fixed!
