### ISSUE TITLE
discussion: warning users on node.js 6

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/google-cloud-node#2850]
One of the things we've been talking about a lot lately is how we communicate dropping support for old versions of node.js.  Ultimately, if a user isn't using the latest LTS release, what they're at risk for running on an unsupported version of nodejs within the next `n` months.  Given the fact that we only want to support versions of node.js supported by the foundation, it may make sense to let users know they're potentially playing a dangerous game. 

My proposal is this - when our modules run on an older non-LTS version of node.js, we provide a warning that says something to the effect of:

```
WARNING: You are currently using version 6.x of node.js.  This version of node.js is in 
maintenance mode, and will stop receiving security patches on zzzz-yy-xx.   Google 
recommends that you upgrade to the latest LTS version of node.js, 8.x.
```

This may be a broad overreach, but I think it merits discussion.  

cc @mylesborins @GoogleCloudPlatform/node-team @GoogleCloudPlatform/yoshi-nodejs

**Comment by alexander-fenster** [comment]
I'm OK if we can print this warning during `npm install` but I don't think it's a good idea to `console.log` it in runtime (especially given that we don't allow `console.log` in our library code).

**Comment by JustinBeckwith** [comment]
We would use [`process.emitWarning`](https://medium.com/@jasnell/introducing-process-warnings-in-node-v6-3096700537ee) which can be silenced.

**Comment by crwilcox** [comment]
I am with Alex. If node or npm itself wants to warn of impending non-support that seems fine, but that seems a bit much for a library to be letting you know at runtime?

**Comment by ofrobots** [comment]
I don't think we should be nannying our users. Before Node 6 goes EOL upstream, we should not be showing them warnings at install time and definitely not at runtime.

It is not the job for a library to make users aware of the Node.js release roadmap.

**Comment by JustinBeckwith** [comment]
Got it :)
