### ISSUE TITLE
How to retrieve a list of Indexed properties

### ISSUE THREAD

**Issue by hadiosbourne** [GoogleCloudPlatform/google-cloud-node#2855]
Currently I have a few properties on my datastore that are indexed and are taking too much space,
I'm planning to run through all the records and remove those properties from the index list,(to save space)

Is there a way to query the the attributes of properties or just to get list of the properties that are indexed?

Then i can run a query on all the records and update that property to be excludeFromIndexes and upsert them again.

Thanks!

**Comment by hadiosbourne** [comment]
Any suggestions guys?

**Comment by stephenplusplus** [comment]
This issue was moved to https://github.com/googleapis/nodejs-datastore/issues/183.
