### ISSUE TITLE
Google speech api IsFinal Response is too slow

### ISSUE THREAD

**Issue by wassizafar786** [GoogleCloudPlatform/google-cloud-node#2860]
Hi This is me Wassi 

I am facing a issue like i am using websocket to send stream to node server and receive result but google cloud speech api send me back isFinal result is very slow 
Below is my client side code

  this.speechServerClient = new BinaryClient(environment.speechServerUrl)
            .on('error', this.onerror.bind(this))
            .on('open', () =>
            {
                // pass the sampleRate as a parameter to the server and get a reference to the communication stream.
                this.speechServerStream = this.speechServerClient.createStream({
                    type: 'speech',
                    sampleRate: this.audioContext.sampleRate
                });
            })
            .on('stream', (serverStream) =>
            {
                serverStream
                    .on('data', this.onresult.bind(this))
                    .on('error', this.onerror.bind(this))
                    .on('close', this.onerror.bind(this))
            });
 

and this is my server side code

var options = {
    config: {
        encoding: 'LINEAR16',
        languageCode: 'en-IN',
        sampleRateHertz: 16000,
    },
    singleUtterance: false,
    interimResults: true,
    verbose: true,
};
var speechClient = new Speech.SpeechClient({
    projectId: environment_1.environment.gCloudProjectId,
    keyFilename: 'myfile.json'
});

 var server = new binaryjs.BinaryServer({
        server: httpsServer,
    });
    server
        .on('error', function (error) { console.log('Server error:' + error); })
        .on('close', function () { console.log('Server closed'); })
        .on('connection', function (client) {
        client
            .on('error', function (error) { console.log('Client error: ' + error); })
            .on('close', function () {
            console.log('Client closed.');
        })
            .on('stream', function (clientStream, meta) {
            console.log('New Client: ' + JSON.stringify(meta));
            if (meta.type === 'speech') {
                handleSpeechRequest(client, clientStream, meta);
            }
            else {
                handleRandomUtteranceRequest(client);
            }
        });
    });
}
function handleSpeechRequest(client, clientStream, meta) {
    return __awaiter(this, void 0, void 0, function () {
        var speechStream;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    options.config.sampleRateHertz = meta.sampleRate;
                    return [4 /*yield*/, speechClient.streamingRecognize(options)
                            .on('error', function (data) { handleGCSMessage(data, client, speechStream); })
                            .on('data', function (data) {
                            try {
                                handleGCSMessage(data, client, speechStream);
                                console.log("Transcription: " + data.results[0].alternatives[0].transcript);
                            }
                            catch (ex) {
                                console.log(ex);
                            }
                        })
                            .on('close', function () { client.close(); })];
                case 1:
                    speechStream = _a.sent();
                    clientStream.pipe(speechStream);
                    return [2 /*return*/];
            }
        });
    });
}

Please please tell me the solution

**Comment by JustinBeckwith** [comment]
This issue was moved to googleapis/nodejs-speech#163

**Comment by cosmobiosis** [comment]
Google Efficiency lmao
