### ISSUE TITLE
Question: will gcloud-node support (push) task queues

### ISSUE THREAD

**Issue by janesconference** [GoogleCloudPlatform/google-cloud-node#366]
Like https://cloud.google.com/appengine/docs/python/taskqueue/ ?

**Comment by ryanseys** [comment]
I don't see why we couldn't support it. Is there some example of how you would like it to work?

**Comment by janesconference** [comment]
I have a plan to decouple some accessory workers (cpu heavy, with a couple of spawned childrens) from the main nodejs REST server to another dedicated one - removing my `async` queue and taking advantage of Google's task queues.

I asked specifically about push queues because the main server should push tasks on the queue and the dedicated server should listen to the queue and take care of the task spawing a worker.
I don't think I have specifical examples or requests, as it's the first time I use task queues :)

I use gcloud-node for pretty much every interaction with the google cloud service, so it would be nice to have them supported here, instead of me rewriting square wheels :)

**Comment by gkorland** [comment]
+1

**Comment by leibale** [comment]
+1

**Comment by leibale** [comment]
what about this? you start work on this?
i can help if you need..

**Comment by ryanseys** [comment]
We haven't heard anything about this library supporting task queues. Are they only available within App Engine?

**Comment by leibale** [comment]
https://cloud.google.com/appengine/docs/python/taskqueue/
"**Push queues function only within the App Engine environment.** These queues are the best choice for applications whose tasks work only with App Engine tools and services. With push queues, you simply configure a queue and add tasks to it. App Engine handles the rest. Push queues are easier to implement, but are restricted to use within App Engine. For more information about push queues and examples of how to use them, see Using Push Queues."

so.. yes

**Comment by leibale** [comment]
and..

**Comment by stephenplusplus** [comment]
*tagging #917, as this issue relates to that discussion regarding having support for GCE/GAE-specific things in our library*

@jgeewax thoughts on this?

**Comment by dhermes** [comment]
Why would you? Pub/Sub is already supported and isn't tied to GAE / doesn't require firing up a GAE instance just to read / write a task.

**Comment by paulshapiro** [comment]
+1 This would be very for a project that's coming up very soon.

**Comment by stephenplusplus** [comment]
I've added this to our API Implementation Tracker @ #1338 -- this doesn't necessarily mean that we will be supporting this, but we've noted the request and it will be considered amongst the others.
