### ISSUE TITLE
gcloud playground

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/google-cloud-node#643]
Crazy idea, but I think it'd be great if we had a "gcloud playground" where users could basically hit our docs in their browser, select a method, give it arguments, and see the results. Like a gcloud version of the API Explorer sections of the gcloud docs: https://developers.google.com/apis-explorer/#p/storage/v1/storage.objects.list

This would be a bit tricky to implement, mostly around having a server somewhere that would process these requests, as well as the user/project authentication process. Though, if we can ship a browser version of gcloud, this should become a lot easier.

Just wanted to log the idea if we ever choose to explore it further.

**Comment by jgeewax** [comment]
It's a cool idea. We could use 3LO to make this work... See the "enable OAuth2 switch" thing in Google-hosted docs.

It might be worth kicking around, but I think way lower in priority than getting Cloud Search and others out the door.

**Comment by stephenplusplus** [comment]
:+1: :mag:

**Comment by stephenplusplus** [comment]
I think this is a bit too optimistic of a goal. We've been linking from our docs to the official docs, which has its own "playground" for a user to experiment with the raw API response.
