### ISSUE TITLE
Remove dependency on google-auto-auth and use google-auth-library

### ISSUE THREAD

**Issue by anthmgoogle** [GoogleCloudPlatform/google-cloud-node#832]
google-auth-library is where auth-related functionality should go. Add whatever features are required from google-auto-auth to it, and switch the dependency back to google-auth-library-nodejs.

**Comment by stephenplusplus** [comment]
`google-auto-auth` uses `google-auth-library-nodejs` -- auto-auth doesn't do anything other than make auth-library easier to use and adds convenience methods (like `getCredentials` and `getToken`).

I only made it into its own module to restrict gcloud from taking on more responsibility than it needs. I also needed to use it from another module: https://github.com/stephenplusplus/gce-images (that is in turn used by gcloud).

I would like to switch back to auth-library and deprecate auto-auth, but is it possible to wait to see if https://github.com/google/google-auth-library-nodejs/issues/54, https://github.com/google/google-auth-library-nodejs/issues/55, and https://github.com/google/google-auth-library-nodejs/issues/56 re-shape the library to make it easier for us to consume first?

**Comment by stephenplusplus** [comment]
Sorry, I missed the second part saying just what I was asking for in my reply. Hard to believe I couldn't read two sentences properly... I'll make an issue to get me a pair of glasses.

**Comment by stephenplusplus** [comment]
I think this issue can be tracked on google-auth-library (https://github.com/google/google-auth-library-nodejs/issues/54, https://github.com/google/google-auth-library-nodejs/issues/55, https://github.com/google/google-auth-library-nodejs/issues/56). We'll be aware if and when changes are made there and happily use google-auth-library as our dependency here.
