### ISSUE TITLE
sample ORM

### ISSUE THREAD

**Issue by beriberikix** [GoogleCloudPlatform/google-cloud-node#87]
Not pressing but it would be great to have simple samples showing ORM integration. By far my favorite is [waterline](https://github.com/balderdashy/waterline) from [sails.js](http://sailsjs.org/). It can be used with Sails or standalone. There's also an [adapter boilerplate](https://github.com/balderdashy/sails-adapter-boilerplate).

**Comment by jgeewax** [comment]
To chime in here re ORMs, I agree with Burcu. We have a special situation with Python (via NDB) but even with that we plan to put it in a separate repository, and then make it "importable" from gcloud-python (ie, `from gcloud.datastore import ndb`). It's big enough to merit it's own issue tracker, etc.

Unless there is a clear and obvious "blessed ORM" (like NDB for Python), I'm fully on board with putting any adapters for others into their own repository.

**Comment by Solido** [comment]
+1 for an example with Waterline

**Comment by jmdobry** [comment]
I created a Cloud Datastore adapter for the JSData Node.js ORM:

* [js-data-cloud-datastore GitHub repo](https://github.com/GoogleCloudPlatform/js-data-cloud-datastore)
* [js-data-cloud-datastore guide/docs](http://www.js-data.io/v3.0/docs/js-data-cloud-datastore)
* [Main JSData site](http://www.js-data.io/v3.0/)

**Comment by landrito** [comment]
@jmdobry can we close this issue?

**Comment by jmdobry** [comment]
I suppose. Do we need to link to [js-data-cloud-datastore](https://github.com/GoogleCloudPlatform/js-data-cloud-datastore) from google-cloud-node's Datastore docs?

**Comment by landrito** [comment]
I don't think a link to the js-data-cloud-datastore is needed but I do think it would be helpful.
